// advokati.mjs — демо „Lex Aurea": адвокатска кантора. Слонова кост + тъмносиньо + злато, класика.
export default {
  id: "advokati",
  slug: { bg: "advokatska-kantora", en: "law-firm", it: "studio-legale" },
  icon: "scales",
  schemaType: "LegalService",
  theme: {
    mode: "light", heroStyle: "split", pattern: "stripes", radius: "2px",
    fonts: ["Playfair+Display:wght@500;600", "Source+Sans+3:wght@400;500;600"],
    display: "'Playfair Display', Georgia, serif", body: "'Source Sans 3', system-ui, sans-serif",
    bg: "#f9f6ef", surface: "#ffffff", surface2: "#f1ece0", text: "#141b2d", muted: "#5a6070",
    accent: "#0f2a5a", accent2: "#b08d3c", onAccent: "#f9f6ef", line: "rgba(20,27,45,.13)",
    word: "LEX",
  },
  keywords: {
    bg: ["сайт за адвокатска кантора", "адвокат демо сайт", "уеб сайт адвокатска кантора", "правни услуги сайт", "изработка на сайт за адвокат"],
    en: ["law firm website", "lawyer website demo", "attorney website design", "legal services website", "law office website"],
    it: ["sito studio legale", "sito avvocato demo", "sito web avvocato", "servizi legali sito", "realizzazione sito studio legale"],
  },
  t: {
    bg: {
      name: "Lex Aurea", category: "Адвокатска кантора", city: "София",
      metaTitle: "Lex Aurea · Адвокатска кантора София · Демо сайт",
      metaDesc: "Демо сайт за адвокатска кантора: области на практика, екип, първа консултация, отзиви, FAQ. От Carbon Stealth.",
      address: "ул. Алабин 34, ет. 3, 1000 София", phone: "+359 2 000 0004", email: "office@lexaurea.example",
      hours: ["Пон – Пет: 09:00 – 18:00", "Събота: по предварителна уговорка", "Неделя: почивен ден"],
      hero: {
        eyebrow: "Адвокатска кантора · търговско, трудово и семейно право",
        title: "Ясен съвет <em>преди трудното решение.</em>",
        lede: "Кантора от седем адвокати с 20 години практика пред български и европейски съдилища. Първата консултация е 30 минути и в нея ви казваме честно какви са шансовете ви.",
        cta: "Заявете консултация", cta2: "Области на практика",
        widget: { kind: "consult", title: "Първа консултация · 30 минути", rows: ["Преглед на документите ви предварително", "Оценка на риска и възможните пътища", "Прогноза за срок и разходи", "Писмено резюме до 24 часа", "Без задължение да продължите"], cta: "Запазете час — 60 €" },
      },
      badges: ["7 адвокати", "20 години практика", "Отговор до 24 часа", "Работим на BG · EN · IT"],
      servicesTitle: "Области <em>на практика</em>",
      servicesLede: "Специализирани екипи, а не един адвокат за всичко. Хонорарът се уговаря писмено преди първото действие.",
      services: [
        { t: "Търговско и дружествено право", d: "Учредяване, преобразуване, договори, спорове между съдружници, due diligence." },
        { t: "Трудово право", d: "Трудови договори, уволнения, обезщетения — за работодатели и служители." },
        { t: "Семейно и наследствено право", d: "Развод, издръжка, родителски права, делба на наследство, завещания." },
        { t: "Недвижими имоти", d: "Проверка на имота, предварителни договори, нотариални сделки, строителни спорове." },
        { t: "Процесуално представителство", d: "Граждански и търговски дела пред всички инстанции, арбитраж, изпълнение." },
        { t: "GDPR и дигитален бизнес", d: "Политики, договори с обработващи, проверки на КЗЛД, онлайн търговия." },
      ],
      about: {
        eyebrow: "За кантората", title: "Малък екип. <em>Пълно внимание.</em>",
        p: ["Lex Aurea е основана през 2005 г. и умишлено остана малка: седем адвокати, всеки с ясна специалност. По вашия казус работи адвокатът, с когото сте говорили — не стажант.", "Говорим и пишем на български, английски и италиански; представляваме чуждестранни дружества в България и български граждани в Италия."],
        facts: [{ n: "20", l: "години практика" }, { n: "7", l: "адвокати" }, { n: "1 400+", l: "приключени казуса" }, { n: "3", l: "работни езика" }],
      },
      steps: { title: "Как <em>работим с вас</em>", items: [{ t: "Консултация", d: "30 минути, след като сме прегледали документите. Честна оценка на шансовете." }, { t: "Писмена оферта", d: "Хонорар — фиксиран или почасов — и план на действията. Нищо не започва без подпис." }, { t: "Работа по казуса", d: "Достъп до защитен клиентски портал с всички документи и срокове." }, { t: "Резултат и отчет", d: "Отчет за свършеното и препоръка какво да правите занапред." }] },
      reviews: [
        { name: "Управител, IT дружество", text: "Спор между съдружници, който можеше да съсипе фирмата. Приключи с извънсъдебно споразумение за 6 седмици.", stars: 5 },
        { name: "Р. Николова", text: "Развод с деца и имущество. Спокойствие, яснота и нито едно скрито плащане.", stars: 5 },
        { name: "Италиански инвеститор", text: "Покупка на имот в България изцяло на италиански — проверка, договор, нотариус. Безупречно.", stars: 5 },
      ],
      faq: [
        { q: "Колко струва първата консултация?", a: "60 € за 30 минути, включително предварителен преглед на документите. При ангажиране на кантората сумата се приспада от хонорара." },
        { q: "Как се определя хонорарът?", a: "Писмено, преди първото действие — фиксирана сума за ясно очертани услуги или почасова ставка за спорове. Няма скрити разходи." },
        { q: "Работите ли с чуждестранни клиенти?", a: "Да, на английски и италиански, включително дистанционно и с електронен подпис." },
        { q: "Поверителна ли е информацията, която споделям?", a: "Да — адвокатската тайна е законово задължение, а документите се съхраняват в криптиран портал в ЕС." },
        { q: "Колко бързо мога да получа час?", a: "Обикновено до 3 работни дни; спешни случаи — същия ден." },
      ],
      contact: { eyebrow: "Контакт", title: "Опишете <em>накратко казуса</em>", lede: "Ще ви отговорим до 24 часа с предложение за час и какви документи да подготвите." },
    },
    en: {
      name: "Lex Aurea", category: "Law firm", city: "Sofia",
      metaTitle: "Lex Aurea · Law Firm Sofia · Demo website",
      metaDesc: "Demo website for a law firm: practice areas, team, first consultation, reviews, FAQ. By Carbon Stealth.",
      address: "34 Alabin St, 3rd floor, 1000 Sofia", phone: "+359 2 000 0004", email: "office@lexaurea.example",
      hours: ["Mon – Fri: 09:00 – 18:00", "Saturday: by appointment", "Sunday: closed"],
      hero: {
        eyebrow: "Law firm · commercial, employment and family law",
        title: "Clear advice <em>before the hard decision.</em>",
        lede: "A firm of seven lawyers with 20 years of practice before Bulgarian and European courts. The first consultation is 30 minutes and in it we tell you honestly what your chances are.",
        cta: "Request a consultation", cta2: "Practice areas",
        widget: { kind: "consult", title: "First consultation · 30 minutes", rows: ["We review your documents beforehand", "Risk assessment and possible routes", "Estimate of time and costs", "Written summary within 24 hours", "No obligation to continue"], cta: "Book — €60" },
      },
      badges: ["7 lawyers", "20 years of practice", "Reply within 24 hours", "We work in BG · EN · IT"],
      servicesTitle: "Practice <em>areas</em>",
      servicesLede: "Specialised teams, not one lawyer for everything. Fees are agreed in writing before the first step.",
      services: [
        { t: "Commercial and corporate law", d: "Incorporation, restructuring, contracts, shareholder disputes, due diligence." },
        { t: "Employment law", d: "Employment contracts, dismissals, compensation — for employers and employees." },
        { t: "Family and inheritance law", d: "Divorce, maintenance, custody, division of estates, wills." },
        { t: "Real estate", d: "Title checks, preliminary contracts, notarial deals, construction disputes." },
        { t: "Litigation", d: "Civil and commercial cases before all instances, arbitration, enforcement." },
        { t: "GDPR and digital business", d: "Policies, processor agreements, regulator inspections, online commerce." },
      ],
      about: {
        eyebrow: "About the firm", title: "A small team. <em>Full attention.</em>",
        p: ["Lex Aurea was founded in 2005 and deliberately stayed small: seven lawyers, each with a clear speciality. The lawyer you spoke with works on your case — not a trainee.", "We speak and write Bulgarian, English and Italian; we represent foreign companies in Bulgaria and Bulgarian citizens in Italy."],
        facts: [{ n: "20", l: "years of practice" }, { n: "7", l: "lawyers" }, { n: "1,400+", l: "cases closed" }, { n: "3", l: "working languages" }],
      },
      steps: { title: "How <em>we work with you</em>", items: [{ t: "Consultation", d: "30 minutes, after we have reviewed your documents. An honest assessment of your chances." }, { t: "Written offer", d: "Fee — fixed or hourly — and an action plan. Nothing starts without a signature." }, { t: "Working the case", d: "Access to a secure client portal with all documents and deadlines." }, { t: "Result and report", d: "A report of what was done and a recommendation on what to do next." }] },
      reviews: [
        { name: "Managing director, IT company", text: "A shareholder dispute that could have ruined the company. Settled out of court in 6 weeks.", stars: 5 },
        { name: "R. Nikolova", text: "Divorce with children and property. Calm, clarity and not a single hidden payment.", stars: 5 },
        { name: "Italian investor", text: "Buying property in Bulgaria entirely in Italian — checks, contract, notary. Flawless.", stars: 5 },
      ],
      faq: [
        { q: "How much is the first consultation?", a: "€60 for 30 minutes, including a preliminary review of your documents. If you engage the firm, it is credited against the fee." },
        { q: "How are fees set?", a: "In writing, before the first step — a fixed sum for clearly defined services or an hourly rate for disputes. No hidden costs." },
        { q: "Do you work with foreign clients?", a: "Yes, in English and Italian, including remotely and with electronic signatures." },
        { q: "Is what I share confidential?", a: "Yes — legal privilege is a statutory duty, and documents are stored in an encrypted portal in the EU." },
        { q: "How soon can I get an appointment?", a: "Usually within 3 working days; urgent matters — the same day." },
      ],
      contact: { eyebrow: "Contact", title: "Describe <em>your matter briefly</em>", lede: "We reply within 24 hours with a proposed time and the documents to prepare." },
    },
    it: {
      name: "Lex Aurea", category: "Studio legale", city: "Milano",
      metaTitle: "Lex Aurea · Studio legale Milano · Sito demo",
      metaDesc: "Sito demo per studio legale: aree di attività, team, prima consulenza, recensioni, FAQ. Di Carbon Stealth.",
      address: "Via Manzoni 34, 3° piano, 20121 Milano", phone: "+39 02 000 0004", email: "studio@lexaurea.example",
      hours: ["Lun – Ven: 09:00 – 18:00", "Sabato: su appuntamento", "Domenica: chiuso"],
      hero: {
        eyebrow: "Studio legale · diritto commerciale, del lavoro e di famiglia",
        title: "Un consiglio chiaro <em>prima della decisione difficile.</em>",
        lede: "Uno studio di sette avvocati con 20 anni di pratica davanti ai tribunali italiani ed europei. La prima consulenza dura 30 minuti e ti diciamo onestamente quali sono le tue possibilità.",
        cta: "Richiedi una consulenza", cta2: "Aree di attività",
        widget: { kind: "consult", title: "Prima consulenza · 30 minuti", rows: ["Esaminiamo i tuoi documenti in anticipo", "Valutazione del rischio e delle strade possibili", "Stima di tempi e costi", "Sintesi scritta entro 24 ore", "Nessun obbligo di proseguire"], cta: "Prenota — 60 €" },
      },
      badges: ["7 avvocati", "20 anni di pratica", "Risposta entro 24 ore", "Lavoriamo in IT · EN · BG"],
      servicesTitle: "Aree <em>di attività</em>",
      servicesLede: "Team specializzati, non un avvocato per tutto. L'onorario è concordato per iscritto prima del primo atto.",
      services: [
        { t: "Diritto commerciale e societario", d: "Costituzione, trasformazioni, contratti, controversie tra soci, due diligence." },
        { t: "Diritto del lavoro", d: "Contratti, licenziamenti, indennità — per aziende e lavoratori." },
        { t: "Diritto di famiglia e successioni", d: "Separazione, divorzio, mantenimento, affidamento, divisioni ereditarie, testamenti." },
        { t: "Immobiliare", d: "Verifiche sull'immobile, preliminari, atti notarili, controversie edilizie." },
        { t: "Contenzioso", d: "Cause civili e commerciali in ogni grado, arbitrato, esecuzioni." },
        { t: "GDPR e business digitale", d: "Informative, contratti con responsabili, ispezioni del Garante, e-commerce." },
      ],
      about: {
        eyebrow: "Lo studio", title: "Un team piccolo. <em>Attenzione totale.</em>",
        p: ["Lex Aurea è nata nel 2005 ed è rimasta volutamente piccola: sette avvocati, ognuno con una specialità chiara. Sul tuo caso lavora l'avvocato con cui hai parlato — non un praticante.", "Parliamo e scriviamo italiano, inglese e bulgaro; assistiamo società straniere in Italia e cittadini italiani in Bulgaria."],
        facts: [{ n: "20", l: "anni di pratica" }, { n: "7", l: "avvocati" }, { n: "1.400+", l: "casi conclusi" }, { n: "3", l: "lingue di lavoro" }],
      },
      steps: { title: "Come <em>lavoriamo con te</em>", items: [{ t: "Consulenza", d: "30 minuti, dopo aver esaminato i documenti. Una valutazione onesta delle possibilità." }, { t: "Offerta scritta", d: "Onorario — fisso o orario — e piano d'azione. Nulla parte senza firma." }, { t: "Lavoro sul caso", d: "Accesso a un portale clienti protetto con tutti i documenti e le scadenze." }, { t: "Risultato e relazione", d: "Relazione su quanto fatto e consiglio su come procedere." }] },
      reviews: [
        { name: "Amministratore, società IT", text: "Una lite tra soci che poteva rovinare l'azienda. Chiusa con un accordo stragiudiziale in 6 settimane.", stars: 5 },
        { name: "R. Nicolini", text: "Separazione con figli e patrimonio. Calma, chiarezza e nessun pagamento nascosto.", stars: 5 },
        { name: "Investitore bulgaro", text: "Acquisto di un immobile in Italia interamente in bulgaro — verifiche, contratto, notaio. Impeccabile.", stars: 5 },
      ],
      faq: [
        { q: "Quanto costa la prima consulenza?", a: "60 € per 30 minuti, compreso l'esame preliminare dei documenti. Se affidi l'incarico allo studio, la somma viene scalata dall'onorario." },
        { q: "Come si determina l'onorario?", a: "Per iscritto, prima del primo atto — importo fisso per servizi ben definiti o tariffa oraria per il contenzioso. Nessun costo nascosto." },
        { q: "Lavorate con clienti stranieri?", a: "Sì, in inglese e bulgaro, anche a distanza e con firma elettronica." },
        { q: "Le informazioni che condivido sono riservate?", a: "Sì — il segreto professionale è un obbligo di legge e i documenti sono conservati in un portale cifrato in UE." },
        { q: "Quanto presto posso avere un appuntamento?", a: "Di norma entro 3 giorni lavorativi; urgenze — in giornata." },
      ],
      contact: { eyebrow: "Contatti", title: "Descrivi <em>brevemente il caso</em>", lede: "Ti rispondiamo entro 24 ore con una proposta di appuntamento e i documenti da preparare." },
    },
  },
};
