// avtoservis.mjs — демо „Motor Lab": автосервиз. Тъмна индустриална тема, оранжев акцент.
export default {
  id: "avtoservis",
  slug: { bg: "avtoservis", en: "car-service", it: "autofficina" },
  icon: "wrench",
  schemaType: "AutoRepair",
  theme: {
    mode: "dark", heroStyle: "split", pattern: "grid", radius: "6px",
    fonts: ["Barlow+Condensed:wght@600;700", "Barlow:wght@400;500;600"],
    display: "'Barlow Condensed', 'Arial Narrow', sans-serif", body: "'Barlow', Arial, sans-serif",
    bg: "#0f1113", surface: "#181c1f", surface2: "#20252a", text: "#f3f2ee", muted: "#a2a8ae",
    accent: "#ff6a13", accent2: "#ffb27a", onAccent: "#101214", line: "rgba(255,255,255,.09)",
    word: "SERVICE",
  },
  keywords: {
    bg: ["сайт за автосервиз", "автосервиз демо сайт", "уеб сайт сервиз", "онлайн записване автосервиз", "изработка на сайт за сервиз"],
    en: ["car service website", "auto repair website demo", "garage website design", "online booking for garage", "mechanic website"],
    it: ["sito web officina", "sito autofficina demo", "sito per meccanico", "prenotazione online officina", "realizzazione sito officina"],
  },
  t: {
    bg: {
      name: "Motor Lab", category: "Автосервиз", city: "Пловдив",
      metaTitle: "Motor Lab · Автосервиз Пловдив · Демо сайт",
      metaDesc: "Демо сайт за автосервиз: онлайн записване, услуги с цени, диагностика, гуми, отзиви. От Carbon Stealth.",
      address: "бул. Кукленско шосе 12, 4004 Пловдив", phone: "+359 88 000 0001", email: "service@motorlab.example",
      hours: ["Пон – Пет: 08:00 – 18:00", "Събота: 09:00 – 14:00", "Неделя: почивен ден"],
      hero: {
        eyebrow: "Автосервиз · Пловдив · от 2009",
        title: "Колата ви — <em>обратно на пътя</em> още днес.",
        lede: "Диагностика за 30 минути, честна цена преди да пипнем и снимка на всяка сменена част. Записвате онлайн, идвате в уречения час, без чакане.",
        cta: "Запази час", cta2: "Виж услугите",
        proof: "★ 4,9 в Google · 380+ отзива · Отговор на запитване до 15 мин в работно време",
        widget: { kind: "booking", title: "Запази час онлайн", rows: [["Услуга", "Смяна на масло и филтри"], ["Автомобил", "VW Golf VII · 2.0 TDI"], ["Дата", "Четвъртък, 09:30"], ["Цена", "от 89 €"]], cta: "Потвърди записването" },
      },
      badges: ["Гаранция 24 месеца", "Оригинални и OEM части", "Заместващ автомобил", "Плащане с карта"],
      offer: { tag: "Оферта на месеца", title: "Безплатна компютърна диагностика при смяна на масло", text: "Запишете се онлайн до края на месеца и диагностиката (25 €) е за наша сметка. Получавате доклад по имейл и снимка на всяка сменена част.", cta: "Запази часа си", note: "Важи за онлайн записвания. Без скрити условия." },
      servicesTitle: "Услуги и <em>цени без изненади</em>",
      servicesLede: "Всяка цена е крайна, с включен труд. Ако намерим нещо допълнително — първо се обаждаме, после ремонтираме.",
      services: [
        { t: "Компютърна диагностика", d: "Пълно четене на грешки за всички марки, доклад на хартия и по имейл.", p: "от 25 €" },
        { t: "Смяна на масло и филтри", d: "Масло по спецификация на производителя, филтри Mann/Bosch, нулиране на сервизния интервал.", p: "от 89 €" },
        { t: "Спирачна система", d: "Дискове, накладки, спирачна течност. Тест на стенд след монтажа.", p: "от 120 €" },
        { t: "Ходова част и реглаж", d: "3D реглаж на геометрията, амортисьори, носачи, тампони. Разпечатка преди/след.", p: "от 45 €" },
        { t: "Климатик", d: "Зареждане, откриване на течове, дезинфекция с озон. R134a и R1234yf.", p: "от 55 €" },
        { t: "Гуми и джанти", d: "Сезонна смяна, баланс, хотел за гуми, ремонт на пробиви.", p: "от 30 €" },
      ],
      about: {
        eyebrow: "За сервиза", title: "Четирима майстори. <em>Нула съмнения.</em>",
        p: ["Motor Lab е сервиз, в който ви показваме какво сменяме и защо. Всяка изведена част остава в кутия до колата, а снимката ѝ пристига на телефона ви заедно с фактурата.", "Работим с дилърско диагностично оборудване за VAG, BMW, Mercedes, Toyota и Renault-Nissan, а за останалите — с Autel и Bosch KTS."],
        facts: [{ n: "15", l: "години опит" }, { n: "4 800+", l: "обслужени автомобила" }, { n: "24", l: "месеца гаранция" }, { n: "4,9", l: "средна оценка в Google" }],
      },
      steps: { title: "Как минава <em>едно посещение</em>", items: [{ t: "Записвате час", d: "Онлайн или по телефона. Получавате потвърждение с SMS." }, { t: "Приемаме колата", d: "Оглед заедно с вас, протокол със снимки, оферта на място." }, { t: "Ремонтираме", d: "Пращаме съобщение при всяка стъпка. Никакви „допълнителни“ без ваше ОК." }, { t: "Тест и предаване", d: "Пробно шофиране, измити стъкла, фактура по имейл." }] },
      reviews: [
        { name: "Георги Д.", text: "Единственият сервиз, в който съм получавал снимка на старите накладки. Цена — точно каквато казаха по телефона.", stars: 5 },
        { name: "Мария К.", text: "Записах се онлайн в неделя вечер, в понеделник в 9 колата беше приета. Заместващ автомобил без въпроси.", stars: 5 },
        { name: "Иван П.", text: "Реглаж и амортисьори — разпечатка преди и след. Колата е като нова по магистралата.", stars: 5 },
      ],
      faq: [
        { q: "Трябва ли да запазя час предварително?", a: "Да, работим само с предварително записване, за да няма чакане. Спешни случаи (спирачки, теч) приемаме същия ден." },
        { q: "Давате ли гаранция за ремонта?", a: "24 месеца за труда и частите, монтирани от нас. При гаранционен случай ремонтираме безплатно." },
        { q: "Мога ли да донеса свои части?", a: "Да, но без гаранция за самата част. Трудът е на същата цена." },
        { q: "Има ли заместващ автомобил?", a: "Да, за ремонти над един ден — безплатно, срещу депозит за гориво." },
        { q: "Как плащам?", a: "В брой, с карта или по банков път. Фактура получавате по имейл веднага." },
      ],
      contact: { eyebrow: "Контакт", title: "Запазете час или <em>просто попитайте</em>", lede: "Отговаряме до 15 минути в работно време." },
    },
    en: {
      name: "Motor Lab", category: "Car service", city: "Plovdiv",
      metaTitle: "Motor Lab · Car Service Plovdiv · Demo website",
      metaDesc: "Demo website for a car service: online booking, priced services, diagnostics, tyres, reviews. By Carbon Stealth.",
      address: "12 Kuklensko Shose Blvd, 4004 Plovdiv", phone: "+359 88 000 0001", email: "service@motorlab.example",
      hours: ["Mon – Fri: 08:00 – 18:00", "Saturday: 09:00 – 14:00", "Sunday: closed"],
      hero: {
        eyebrow: "Car service · Plovdiv · since 2009",
        title: "Your car — <em>back on the road</em> today.",
        lede: "Diagnostics in 30 minutes, an honest price before we touch anything and a photo of every replaced part. Book online, arrive at your slot, no waiting.",
        cta: "Book a slot", cta2: "See services",
        proof: "★ 4.9 on Google · 380+ reviews · Enquiries answered within 15 min in working hours",
        widget: { kind: "booking", title: "Book online", rows: [["Service", "Oil and filter change"], ["Vehicle", "VW Golf VII · 2.0 TDI"], ["Date", "Thursday, 09:30"], ["Price", "from €89"]], cta: "Confirm booking" },
      },
      badges: ["24-month warranty", "Genuine and OEM parts", "Courtesy car", "Card payments"],
      offer: { tag: "Offer of the month", title: "Free computer diagnostics with every oil change", text: "Book online before the end of the month and the diagnostics (€25) is on us. You get an emailed report and a photo of every replaced part.", cta: "Book your slot", note: "Valid for online bookings. No small print." },
      servicesTitle: "Services and <em>prices without surprises</em>",
      servicesLede: "Every price is final, labour included. If we find something extra, we call first and repair second.",
      services: [
        { t: "Computer diagnostics", d: "Full fault reading for all makes, report on paper and by email.", p: "from €25" },
        { t: "Oil and filter change", d: "Oil to manufacturer spec, Mann/Bosch filters, service interval reset.", p: "from €89" },
        { t: "Brake system", d: "Discs, pads, brake fluid. Bench test after fitting.", p: "from €120" },
        { t: "Suspension and alignment", d: "3D wheel alignment, shock absorbers, arms, bushes. Before/after printout.", p: "from €45" },
        { t: "Air conditioning", d: "Recharge, leak detection, ozone disinfection. R134a and R1234yf.", p: "from €55" },
        { t: "Tyres and wheels", d: "Seasonal change, balancing, tyre hotel, puncture repair.", p: "from €30" },
      ],
      about: {
        eyebrow: "About the garage", title: "Four mechanics. <em>Zero doubts.</em>",
        p: ["Motor Lab is a garage where we show you what we replace and why. Every removed part stays in a box next to the car, and its photo reaches your phone together with the invoice.", "We use dealer-level diagnostic equipment for VAG, BMW, Mercedes, Toyota and Renault-Nissan, and Autel and Bosch KTS for everything else."],
        facts: [{ n: "15", l: "years of experience" }, { n: "4,800+", l: "cars serviced" }, { n: "24", l: "months warranty" }, { n: "4.9", l: "Google rating" }],
      },
      steps: { title: "How <em>a visit</em> goes", items: [{ t: "You book a slot", d: "Online or by phone. You get an SMS confirmation." }, { t: "We take the car in", d: "Inspection together with you, photo report, quote on the spot." }, { t: "We repair", d: "A message at every step. No “extras” without your OK." }, { t: "Test and handover", d: "Test drive, washed windows, invoice by email." }] },
      reviews: [
        { name: "George D.", text: "The only garage that ever sent me a photo of the old brake pads. Price — exactly what they said on the phone.", stars: 5 },
        { name: "Maria K.", text: "Booked online on Sunday night, car taken in Monday at 9. Courtesy car, no questions asked.", stars: 5 },
        { name: "Ivan P.", text: "Alignment and shocks — printout before and after. The car feels new on the motorway.", stars: 5 },
      ],
      faq: [
        { q: "Do I need to book in advance?", a: "Yes, we work by appointment only so nobody waits. Emergencies (brakes, leaks) are taken the same day." },
        { q: "Do you give a warranty?", a: "24 months on labour and parts fitted by us. Warranty repairs are free." },
        { q: "Can I bring my own parts?", a: "Yes, but without warranty on the part itself. Labour costs the same." },
        { q: "Is there a courtesy car?", a: "Yes, for repairs longer than a day — free, against a fuel deposit." },
        { q: "How do I pay?", a: "Cash, card or bank transfer. The invoice arrives by email immediately." },
      ],
      contact: { eyebrow: "Contact", title: "Book a slot or <em>just ask</em>", lede: "We reply within 15 minutes during opening hours." },
    },
    it: {
      name: "Motor Lab", category: "Autofficina", city: "Bologna",
      metaTitle: "Motor Lab · Autofficina Bologna · Sito demo",
      metaDesc: "Sito demo per autofficina: prenotazione online, servizi con prezzi, diagnosi, gomme, recensioni. Di Carbon Stealth.",
      address: "Via Stalingrado 12, 40128 Bologna", phone: "+39 051 000 0001", email: "officina@motorlab.example",
      hours: ["Lun – Ven: 08:00 – 18:00", "Sabato: 09:00 – 13:00", "Domenica: chiuso"],
      hero: {
        eyebrow: "Autofficina · Bologna · dal 2009",
        title: "La tua auto — <em>di nuovo in strada</em> oggi.",
        lede: "Diagnosi in 30 minuti, prezzo onesto prima di toccare qualsiasi cosa e foto di ogni pezzo sostituito. Prenoti online, arrivi all'orario fissato, senza attese.",
        cta: "Prenota", cta2: "Vedi i servizi",
        proof: "★ 4,9 su Google · 380+ recensioni · Risposta entro 15 min in orario di lavoro",
        widget: { kind: "booking", title: "Prenota online", rows: [["Servizio", "Cambio olio e filtri"], ["Veicolo", "VW Golf VII · 2.0 TDI"], ["Data", "Giovedì, 09:30"], ["Prezzo", "da 89 €"]], cta: "Conferma la prenotazione" },
      },
      badges: ["Garanzia 24 mesi", "Ricambi originali e OEM", "Auto di cortesia", "Pagamento con carta"],
      offer: { tag: "Offerta del mese", title: "Diagnosi computerizzata gratuita con ogni cambio olio", text: "Prenota online entro fine mese e la diagnosi (25 €) la offriamo noi. Ricevi il rapporto via email e la foto di ogni ricambio sostituito.", cta: "Prenota il tuo orario", note: "Valida per le prenotazioni online. Nessuna clausola nascosta." },
      servicesTitle: "Servizi e <em>prezzi senza sorprese</em>",
      servicesLede: "Ogni prezzo è definitivo, manodopera inclusa. Se troviamo qualcosa in più, prima chiamiamo, poi ripariamo.",
      services: [
        { t: "Diagnosi computerizzata", d: "Lettura completa degli errori per tutte le marche, report cartaceo e via email.", p: "da 25 €" },
        { t: "Cambio olio e filtri", d: "Olio secondo specifica del costruttore, filtri Mann/Bosch, azzeramento intervallo di servizio.", p: "da 89 €" },
        { t: "Impianto frenante", d: "Dischi, pastiglie, liquido freni. Prova al banco dopo il montaggio.", p: "da 120 €" },
        { t: "Sospensioni e assetto", d: "Assetto 3D, ammortizzatori, bracci, silent block. Stampa prima/dopo.", p: "da 45 €" },
        { t: "Climatizzatore", d: "Ricarica, ricerca perdite, sanificazione all'ozono. R134a e R1234yf.", p: "da 55 €" },
        { t: "Gomme e cerchi", d: "Cambio stagionale, equilibratura, deposito gomme, riparazione forature.", p: "da 30 €" },
      ],
      about: {
        eyebrow: "L'officina", title: "Quattro meccanici. <em>Zero dubbi.</em>",
        p: ["Motor Lab è un'officina dove ti mostriamo cosa sostituiamo e perché. Ogni pezzo rimosso resta in una scatola accanto all'auto e la sua foto arriva sul tuo telefono insieme alla fattura.", "Usiamo strumenti di diagnosi di livello concessionaria per VAG, BMW, Mercedes, Toyota e Renault-Nissan, e Autel e Bosch KTS per tutto il resto."],
        facts: [{ n: "15", l: "anni di esperienza" }, { n: "4.800+", l: "auto servite" }, { n: "24", l: "mesi di garanzia" }, { n: "4,9", l: "valutazione Google" }],
      },
      steps: { title: "Come si svolge <em>una visita</em>", items: [{ t: "Prenoti", d: "Online o per telefono. Ricevi conferma via SMS." }, { t: "Accettiamo l'auto", d: "Controllo insieme a te, verbale con foto, preventivo sul posto." }, { t: "Ripariamo", d: "Un messaggio a ogni passo. Nessun «extra» senza il tuo OK." }, { t: "Prova e consegna", d: "Giro di prova, vetri puliti, fattura via email." }] },
      reviews: [
        { name: "Giorgio D.", text: "L'unica officina che mi abbia mai mandato la foto delle vecchie pastiglie. Prezzo — esattamente quello detto al telefono.", stars: 5 },
        { name: "Maria C.", text: "Prenotato online domenica sera, auto accettata lunedì alle 9. Auto di cortesia senza domande.", stars: 5 },
        { name: "Ivan P.", text: "Assetto e ammortizzatori — stampa prima e dopo. L'auto sembra nuova in autostrada.", stars: 5 },
      ],
      faq: [
        { q: "Devo prenotare in anticipo?", a: "Sì, lavoriamo solo su appuntamento perché nessuno aspetti. Le urgenze (freni, perdite) le accettiamo in giornata." },
        { q: "Date garanzia sulla riparazione?", a: "24 mesi su manodopera e ricambi montati da noi. Gli interventi in garanzia sono gratuiti." },
        { q: "Posso portare i miei ricambi?", a: "Sì, ma senza garanzia sul pezzo. La manodopera costa uguale." },
        { q: "C'è un'auto di cortesia?", a: "Sì, per riparazioni oltre un giorno — gratuita, con cauzione carburante." },
        { q: "Come pago?", a: "Contanti, carta o bonifico. La fattura arriva subito via email." },
      ],
      contact: { eyebrow: "Contatti", title: "Prenota o <em>chiedi pure</em>", lede: "Rispondiamo entro 15 minuti in orario di apertura." },
    },
  },
};
