// avtokashta.mjs — демо „Drive Line": автокъща. Черно + сребро + червен акцент, обяви като плочки.
export default {
  id: "avtokashta",
  slug: { bg: "avtokashta", en: "car-dealership", it: "concessionaria" },
  icon: "car",
  schemaType: "AutoDealer",
  theme: {
    mode: "dark", heroStyle: "center", pattern: "stripes", radius: "3px",
    fonts: ["Oswald:wght@500;600", "Roboto:wght@400;500;700"],
    display: "Oswald, 'Arial Narrow', sans-serif", body: "Roboto, system-ui, sans-serif",
    bg: "#0b0b0c", surface: "#151517", surface2: "#1f1f22", text: "#f4f4f5", muted: "#9a9aa0",
    accent: "#e11d2e", accent2: "#ff5a66", onAccent: "#ffffff", line: "rgba(255,255,255,.1)",
    word: "DRIVE",
  },
  keywords: {
    bg: ["сайт за автокъща", "автокъща демо сайт", "обяви за автомобили сайт", "уеб сайт автокъща", "изработка на сайт за автокъща"],
    en: ["car dealership website", "used car dealer website demo", "car listings website", "auto dealer website design", "car sales website"],
    it: ["sito concessionaria", "sito autosalone demo", "annunci auto sito", "sito web concessionaria auto", "realizzazione sito concessionaria"],
  },
  t: {
    bg: {
      name: "Drive Line", category: "Автокъща", city: "София",
      calc: { price: "Цена на автомобила", deposit: "Самоучастие", months: "Месеци", monthly: "Месечна вноска", mo: "мес.", note: "Ориентировъчно при 7% ГПР — точната оферта е от лизинговата компания." },
      metaTitle: "Drive Line · Автокъща София · Демо сайт",
      metaDesc: "Демо сайт за автокъща: налични автомобили с цени, проверена история, лизинг, изкупуване, гаранция, отзиви. От Carbon Stealth.",
      address: "бул. Ботевградско шосе 220, 1517 София", phone: "+359 88 000 0008", email: "sales@driveline.example",
      hours: ["Пон – Пет: 09:00 – 19:00", "Събота: 10:00 – 16:00", "Неделя: по уговорка"],
      hero: {
        eyebrow: "Автокъща · внос от Германия и Италия · София",
        title: "Всяка кола с история. <em>Никоя със скрита.</em>",
        lede: "80 автомобила на склад, всеки с проверен пробег, сервизна книжка и 12 месеца гаранция. Тест драйв още днес, лизинг за 48 часа, изкупуване на вашата кола на място.",
        cta: "Запиши тест драйв", cta2: "Налични автомобили",
        proof: "★ 4,8 в Google · 1 900+ продадени автомобила · 12 месеца гаранция на всеки",
        widget: { kind: "tiles", title: "Нови постъпления", rows: [["BMW 320d", "2021 · 68 000 км · автомат", "27 900 €"], ["VW Tiguan 2.0 TDI", "2020 · 91 000 км · 4Motion", "24 500 €"], ["Toyota Corolla Hybrid", "2022 · 41 000 км · гаранция", "22 900 €"]] },
      },
      badges: ["Проверен пробег", "12 месеца гаранция", "Лизинг за 48 часа", "Изкупуване на вашия автомобил"],
      offer: { tag: "Тази седмица", title: "Лизинг с 0% самоучастие и одобрение за 48 часа", text: "Изберете автомобил от склада, запишете тест драйв и до 48 часа имате одобрение от лизингова компания. Стария ви автомобил изкупуваме на място по пазарна цена.", cta: "Запиши тест драйв", note: "Ориентировъчна вноска — от калкулатора. Точната оферта е от лизинговата компания." },
      servicesTitle: "Какво <em>получавате</em>",
      servicesLede: "Купуването на кола не трябва да е стрес. Затова всичко е написано, проверено и с гаранция.",
      services: [
        { t: "Проверена история", d: "Доклад от Carfax/AutoDNA, сервизна книжка, снимки от вноса. Нищо не се крие." },
        { t: "Гаранция 12 месеца", d: "Двигател, трансмисия, електроника. Ремонт в партньорски сервиз или възстановяване на сумата." },
        { t: "Лизинг и кредит", d: "Одобрение за 48 часа при 5 банки и лизингови компании. Вноска от 190 € / мес.", p: "от 10% самоучастие" },
        { t: "Тест драйв", d: "30 минути по вашия маршрут, с наш консултант или без." },
        { t: "Изкупуване и бартер", d: "Оценка на място за 20 минути, плащане същия ден по банков път." },
        { t: "Внос по поръчка", d: "Намираме конкретен модел в Германия или Италия, проверяваме го и го докарваме.", p: "такса 490 €" },
      ],
      about: {
        eyebrow: "За автокъщата", title: "18 години. <em>4 200 доволни клиента.</em>",
        p: ["Drive Line е семейна автокъща, основана през 2007 г. Внасяме от проверени дилъри в Германия и Италия и всеки автомобил минава през 120-точков преглед преди да излезе на площадката.", "Ако намерите скрит дефект в първите 14 дни — връщаме парите. Просто правило, което ни спестява спорове."],
        facts: [{ n: "80+", l: "автомобила на склад" }, { n: "18", l: "години опит" }, { n: "4 200+", l: "продадени автомобила" }, { n: "14", l: "дни право на връщане" }],
      },
      steps: { title: "От обява <em>до ключове</em>", items: [{ t: "Избирате онлайн", d: "Пълни снимки, история и цена без скрити такси. Запазвате колата с 200 € депозит." }, { t: "Тест драйв", d: "Идвате, карате, задавате въпроси. Ако не ви хареса — депозитът се връща." }, { t: "Финансиране", d: "Лизинг или кредит за 48 часа; ние подготвяме документите." }, { t: "Регистрация и ключове", d: "Регистрираме автомобила в КАТ вместо вас. Излизате с номера." }] },
      reviews: [
        { name: "Христо Б.", text: "Взех Tiguan с пълна история и снимки от Германия. След 8 месеца — нито един проблем.", stars: 5 },
        { name: "Ралица Д.", text: "Лизингът стана за ден и половина. Регистрацията я направиха те. Най-лесната покупка в живота ми.", stars: 5 },
        { name: "Емил К.", text: "Изкупиха старата ми кола на място на реална цена, а не „ще ви се обадим“.", stars: 5 },
      ],
      faq: [
        { q: "Как проверявате пробега?", a: "Чрез доклад от AutoDNA/Carfax, сервизната история и OBD четене на модулите. Докладът е в обявата." },
        { q: "Какво покрива гаранцията?", a: "Двигател, скоростна кутия, турбо, инжекцион, електроника — 12 месеца или 20 000 км." },
        { q: "Мога ли да върна колата?", a: "Да, до 14 дни или 1 000 км, ако откриете скрит дефект, който не е описан." },
        { q: "Правите ли лизинг за фирми?", a: "Да — оперативен и финансов, с ДДС кредит, одобрение за 48 часа." },
        { q: "Има ли скрити такси?", a: "Не. Цената в обявата включва вноса, прегледа и подготовката. Регистрацията в КАТ е 60 € отделно." },
      ],
      contact: { eyebrow: "Контакт", title: "Запишете <em>тест драйв</em>", lede: "Кажете кой автомобил и кога — ще го подготвим и зареден." },
    },
    en: {
      name: "Drive Line", category: "Car dealership", city: "Sofia",
      calc: { price: "Car price", deposit: "Deposit", months: "Months", monthly: "Monthly instalment", mo: "mo", note: "Indicative at 7% APR — the exact offer comes from the leasing company." },
      metaTitle: "Drive Line · Car Dealership Sofia · Demo website",
      metaDesc: "Demo website for a car dealership: cars in stock with prices, verified history, leasing, trade-in, warranty, reviews. By Carbon Stealth.",
      address: "220 Botevgradsko Shose Blvd, 1517 Sofia", phone: "+359 88 000 0008", email: "sales@driveline.example",
      hours: ["Mon – Fri: 09:00 – 19:00", "Saturday: 10:00 – 16:00", "Sunday: by appointment"],
      hero: {
        eyebrow: "Car dealership · imports from Germany and Italy · Sofia",
        title: "Every car with a history. <em>None with a hidden one.</em>",
        lede: "80 cars in stock, each with verified mileage, service book and a 12-month warranty. Test drive today, leasing in 48 hours, trade-in on the spot.",
        cta: "Book a test drive", cta2: "Cars in stock",
        proof: "★ 4.8 on Google · 1,900+ cars sold · 12-month warranty on every car",
        widget: { kind: "tiles", title: "New arrivals", rows: [["BMW 320d", "2021 · 68,000 km · automatic", "€27,900"], ["VW Tiguan 2.0 TDI", "2020 · 91,000 km · 4Motion", "€24,500"], ["Toyota Corolla Hybrid", "2022 · 41,000 km · warranty", "€22,900"]] },
      },
      badges: ["Verified mileage", "12-month warranty", "Leasing in 48 hours", "We buy your car"],
      offer: { tag: "This week", title: "Leasing with 0% deposit and approval in 48 hours", text: "Pick a car from stock, book a test drive and within 48 hours you have leasing approval. We buy your old car on the spot at market price.", cta: "Book a test drive", note: "Indicative instalment from the calculator. The exact offer comes from the leasing company." },
      servicesTitle: "What <em>you get</em>",
      servicesLede: "Buying a car should not be stressful. So everything is written down, checked and guaranteed.",
      services: [
        { t: "Verified history", d: "Carfax/AutoDNA report, service book, import photos. Nothing is hidden." },
        { t: "12-month warranty", d: "Engine, transmission, electronics. Repair at a partner garage or your money back." },
        { t: "Leasing and credit", d: "Approval within 48 hours from 5 banks and leasing companies. Instalments from €190 / month.", p: "from 10% deposit" },
        { t: "Test drive", d: "30 minutes on your route, with our consultant or without." },
        { t: "Trade-in", d: "Valuation on the spot in 20 minutes, bank payment the same day." },
        { t: "Import to order", d: "We find a specific model in Germany or Italy, check it and bring it.", p: "€490 fee" },
      ],
      about: {
        eyebrow: "About the dealership", title: "18 years. <em>4,200 happy customers.</em>",
        p: ["Drive Line is a family dealership founded in 2007. We import from verified dealers in Germany and Italy and every car passes a 120-point inspection before it reaches the lot.", "If you find a hidden defect in the first 14 days — we refund you. A simple rule that saves us arguments."],
        facts: [{ n: "80+", l: "cars in stock" }, { n: "18", l: "years of experience" }, { n: "4,200+", l: "cars sold" }, { n: "14", l: "days right of return" }],
      },
      steps: { title: "From listing <em>to keys</em>", items: [{ t: "Choose online", d: "Full photos, history and a price with no hidden fees. Reserve the car with a €200 deposit." }, { t: "Test drive", d: "Come, drive, ask questions. If you do not like it — the deposit is refunded." }, { t: "Financing", d: "Leasing or credit within 48 hours; we prepare the paperwork." }, { t: "Registration and keys", d: "We register the car for you. You leave with plates." }] },
      reviews: [
        { name: "Hristo B.", text: "Bought a Tiguan with full history and photos from Germany. Eight months on — not a single problem.", stars: 5 },
        { name: "Ralitsa D.", text: "Leasing took a day and a half. They did the registration. The easiest purchase of my life.", stars: 5 },
        { name: "Emil K.", text: "They bought my old car on the spot at a real price, not “we'll call you”.", stars: 5 },
      ],
      faq: [
        { q: "How do you verify mileage?", a: "Through an AutoDNA/Carfax report, the service history and OBD readings of the modules. The report is in the listing." },
        { q: "What does the warranty cover?", a: "Engine, gearbox, turbo, injection, electronics — 12 months or 20,000 km." },
        { q: "Can I return the car?", a: "Yes, within 14 days or 1,000 km if you find a hidden defect that was not described." },
        { q: "Do you offer business leasing?", a: "Yes — operating and financial, with VAT credit, approval in 48 hours." },
        { q: "Are there hidden fees?", a: "No. The listed price includes import, inspection and preparation. Registration is €60 extra." },
      ],
      contact: { eyebrow: "Contact", title: "Book a <em>test drive</em>", lede: "Tell us which car and when — we will have it ready and fuelled." },
    },
    it: {
      name: "Drive Line", category: "Concessionaria", city: "Verona",
      calc: { price: "Prezzo dell'auto", deposit: "Anticipo", months: "Mesi", monthly: "Rata mensile", mo: "mese", note: "Indicativo al 7% TAEG — l'offerta esatta arriva dalla società di leasing." },
      metaTitle: "Drive Line · Concessionaria auto Verona · Sito demo",
      metaDesc: "Sito demo per concessionaria: auto disponibili con prezzi, storia verificata, leasing, permuta, garanzia, recensioni. Di Carbon Stealth.",
      address: "Via Torricelli 220, 37136 Verona", phone: "+39 045 000 0008", email: "vendite@driveline.example",
      hours: ["Lun – Ven: 09:00 – 19:00", "Sabato: 10:00 – 16:00", "Domenica: su appuntamento"],
      hero: {
        eyebrow: "Concessionaria · usato garantito e km 0 · Verona",
        title: "Ogni auto con una storia. <em>Nessuna con una nascosta.</em>",
        lede: "80 auto in pronta consegna, ognuna con chilometraggio verificato, libretto tagliandi e 12 mesi di garanzia. Prova su strada oggi, finanziamento in 48 ore, permuta sul posto.",
        cta: "Prenota una prova", cta2: "Auto disponibili",
        proof: "★ 4,8 su Google · 1.900+ auto vendute · 12 mesi di garanzia su ogni auto",
        widget: { kind: "tiles", title: "Nuovi arrivi", rows: [["BMW 320d", "2021 · 68.000 km · automatico", "27.900 €"], ["VW Tiguan 2.0 TDI", "2020 · 91.000 km · 4Motion", "24.500 €"], ["Toyota Corolla Hybrid", "2022 · 41.000 km · garanzia", "22.900 €"]] },
      },
      badges: ["Chilometraggio verificato", "Garanzia 12 mesi", "Finanziamento in 48 ore", "Ritiriamo la tua auto"],
      offer: { tag: "Questa settimana", title: "Finanziamento con 0% di anticipo e approvazione in 48 ore", text: "Scegli un'auto in stock, prenota un test drive ed entro 48 ore hai l'approvazione della società di leasing. Ritiriamo la tua vecchia auto sul posto al prezzo di mercato.", cta: "Prenota un test drive", note: "Rata indicativa dal calcolatore. L'offerta esatta arriva dalla società di leasing." },
      servicesTitle: "Cosa <em>ricevi</em>",
      servicesLede: "Comprare un'auto non deve essere uno stress. Per questo tutto è scritto, controllato e garantito.",
      services: [
        { t: "Storia verificata", d: "Report Carfax/AutoDNA, libretto tagliandi, foto d'importazione. Niente di nascosto." },
        { t: "Garanzia 12 mesi", d: "Motore, cambio, elettronica. Riparazione in officina partner o rimborso." },
        { t: "Finanziamento e leasing", d: "Approvazione in 48 ore con 5 banche e società di leasing. Rata da 190 € / mese.", p: "da 10% di anticipo" },
        { t: "Prova su strada", d: "30 minuti sul tuo percorso, con o senza il nostro consulente." },
        { t: "Permuta", d: "Valutazione sul posto in 20 minuti, bonifico in giornata." },
        { t: "Ricerca su ordinazione", d: "Troviamo il modello che vuoi in Germania o Italia, lo controlliamo e lo portiamo.", p: "commissione 490 €" },
      ],
      about: {
        eyebrow: "La concessionaria", title: "18 anni. <em>4.200 clienti soddisfatti.</em>",
        p: ["Drive Line è una concessionaria di famiglia fondata nel 2007. Importiamo da rivenditori verificati e ogni auto passa un controllo in 120 punti prima di arrivare in piazzale.", "Se trovi un difetto nascosto nei primi 14 giorni — ti rimborsiamo. Una regola semplice che ci evita discussioni."],
        facts: [{ n: "80+", l: "auto in pronta consegna" }, { n: "18", l: "anni di esperienza" }, { n: "4.200+", l: "auto vendute" }, { n: "14", l: "giorni per il reso" }],
      },
      steps: { title: "Dall'annuncio <em>alle chiavi</em>", items: [{ t: "Scegli online", d: "Foto complete, storia e prezzo senza costi nascosti. Blocchi l'auto con 200 € di caparra." }, { t: "Prova su strada", d: "Vieni, guidi, fai domande. Se non ti piace — la caparra torna indietro." }, { t: "Finanziamento", d: "Leasing o prestito in 48 ore; prepariamo noi i documenti." }, { t: "Immatricolazione e chiavi", d: "Facciamo noi il passaggio di proprietà. Esci con la targa." }] },
      reviews: [
        { name: "Cristiano B.", text: "Ho preso una Tiguan con storia completa e foto dalla Germania. Dopo 8 mesi — nemmeno un problema.", stars: 5 },
        { name: "Raffaella D.", text: "Il finanziamento è stato approvato in un giorno e mezzo. Il passaggio l'hanno fatto loro. L'acquisto più facile della mia vita.", stars: 5 },
        { name: "Emilio C.", text: "Hanno ritirato la mia vecchia auto sul posto a un prezzo vero, non «la richiamiamo».", stars: 5 },
      ],
      faq: [
        { q: "Come verificate il chilometraggio?", a: "Con report AutoDNA/Carfax, storico tagliandi e lettura OBD delle centraline. Il report è nell'annuncio." },
        { q: "Cosa copre la garanzia?", a: "Motore, cambio, turbo, iniezione, elettronica — 12 mesi o 20.000 km." },
        { q: "Posso restituire l'auto?", a: "Sì, entro 14 giorni o 1.000 km se trovi un difetto nascosto non descritto." },
        { q: "Fate leasing per aziende?", a: "Sì — operativo e finanziario, con IVA detraibile, approvazione in 48 ore." },
        { q: "Ci sono costi nascosti?", a: "No. Il prezzo in annuncio include importazione, controllo e preparazione. Il passaggio di proprietà è a parte." },
      ],
      contact: { eyebrow: "Contatti", title: "Prenota <em>una prova su strada</em>", lede: "Dicci quale auto e quando — la prepariamo con il pieno." },
    },
  },
};
