// burger.mjs — демо „Crunch Corner": бързо хранене. Крем + червено + жълто, център, меню като плочки + пълно меню.
export default {
  id: "burger",
  slug: { bg: "barzo-hranene", en: "fast-food", it: "fast-food" },
  icon: "burger",
  schemaType: "FastFoodRestaurant",
  theme: {
    mode: "light", heroStyle: "center", pattern: "dots", radius: "18px",
    fonts: ["Rubik:wght@700;900", "Nunito:wght@400;600;700"],
    display: "Rubik, system-ui, sans-serif", body: "Nunito, system-ui, sans-serif",
    bg: "#fff7e8", surface: "#ffffff", surface2: "#ffedc7", text: "#2a1a0e", muted: "#7a6552",
    accent: "#e0301e", accent2: "#ffb703", onAccent: "#ffffff", line: "rgba(42,26,14,.13)",
    word: "YUM",
  },
  keywords: {
    bg: ["сайт за бързо хранене", "бургер ресторант демо сайт", "онлайн поръчка храна сайт", "сайт за заведение", "изработка на сайт за ресторант"],
    en: ["fast food website", "burger restaurant website demo", "online food ordering website", "restaurant website design", "takeaway website"],
    it: ["sito fast food", "sito hamburgeria demo", "ordini online ristorante sito", "sito web ristorante", "realizzazione sito fast food"],
  },
  t: {
    bg: {
      name: "Crunch Corner", category: "Бързо хранене", city: "Варна",
      metaTitle: "Crunch Corner · Бургери и пържени картофи Варна · Демо сайт",
      metaDesc: "Демо сайт за заведение за бързо хранене: меню с цени, онлайн поръчка, доставка за 30 минути, отзиви, FAQ. От Carbon Stealth.",
      address: "ул. Сливница 10, 9000 Варна", phone: "+359 88 000 0010", email: "order@crunchcorner.example",
      hours: ["Пон – Чет: 11:00 – 23:00", "Пет – Съб: 11:00 – 02:00", "Неделя: 12:00 – 22:00"],
      hero: {
        eyebrow: "Смаш бургери · пържени картофи · шейкове · Варна",
        title: "Хрупкаво отвън. <em>Сочно отвътре.</em> За 30 минути у вас.",
        lede: "Телешко от Добруджа, смачкано на плоча в момента на поръчката, ръчно рязани картофи и питки от нашата фурна. Поръчвате онлайн, плащате с карта, доставка за 30 минути или е безплатно.",
        cta: "Поръчай онлайн", cta2: "Виж менюто",
        proof: "★ 4,8 в Google · 48 000+ доставени поръчки · 30 мин или безплатно",
        widget: { kind: "tiles", title: "Най-поръчвани", rows: [["Двоен смаш", "2× телешко · чедър · сос", "8,90 €"], ["Хрупкаво пиле", "буттермилк · туршия", "7,90 €"], ["Картофи с трюфел", "пармезан · трюфелово олио", "4,50 €"]] },
      },
      badges: ["Доставка за 30 мин или безплатно", "Плащане с карта онлайн", "Отворено до 02:00 в петък и събота", "Вегетарианско меню"],
      offer: { tag: "Само онлайн", title: "Двоен смаш + картофи + напитка за 12,90 €", text: "Комбото на седмицата при поръчка от сайта: спестявате 4,50 € спрямо менюто, а доставката в рамките на Варна е безплатна над 15 €.", cta: "Поръчай комбото", note: "Всеки ден от 11:00 до 23:00. Вегетарианска версия — същата цена." },
      servicesTitle: "Защо <em>идват отново</em>",
      servicesLede: "Не сме верига. Всяка питка е от нашата фурна, всеки сос — от нашата кухня.",
      services: [
        { t: "Смаш бургери", d: "Телешко от Добруджа, 2 × 70 г, смачкано на 300 °C. Хрупкава коричка, розова среда." },
        { t: "Хрупкаво пиле", d: "24 часа в буттермилк, двойна панировка, туршия от нашата кухня." },
        { t: "Картофи и странични", d: "Ръчно рязани, двойно пържени. С трюфел, с чедър и бекон или класически." },
        { t: "Шейкове и лимонади", d: "Истински сладолед, домашни сиропи. Без прах, без концентрат." },
        { t: "Вегетарианско", d: "Бургер с пачка от нахут и халуми, картофи и салата — не „по подразбиране“, а вкусно." },
        { t: "Кетъринг", d: "Бургер бар за партита и офиси — от 20 души, с наш грил на място.", p: "от 12 € / човек" },
      ],
      about: {
        eyebrow: "За нас", title: "Двама готвачи, <em>една плоча</em> и опашка от 2021",
        p: ["Crunch Corner започна като фургон на плажа и за три години стана заведението с най-дълга опашка в петък вечер във Варна. Останахме малки — 24 места и кухня, която се вижда.", "Месото е от Добруджа, питките се пекат на всеки два часа, а картофите се режат сутрин. Ако нещо ви е студено — сменяме го, без въпроси."],
        facts: [{ n: "2021", l: "от фургон на плажа" }, { n: "30", l: "минути доставка" }, { n: "4,8", l: "оценка · 2 400 отзива" }, { n: "24", l: "места + двор" }],
      },
      list: { title: "Менюто", lede: "Всичко се приготвя при поръчка. Алергените — в онлайн менюто.", groups: [
        { t: "Бургери", items: [["Класически смаш", "6,90 €"], ["Двоен смаш", "8,90 €"], ["Бекон и лук карамел", "9,50 €"], ["Хрупкаво пиле", "7,90 €"], ["Веги халуми", "7,50 €"]] },
        { t: "Странични и напитки", items: [["Картофи класик", "3,20 €"], ["Картофи с трюфел", "4,50 €"], ["Лучени кръгчета", "3,90 €"], ["Шейк (ванилия · шоколад · ягода)", "4,20 €"], ["Домашна лимонада", "2,90 €"]] },
      ] },
      reviews: [
        { name: "Даниел Р.", text: "Двойният смаш е най-добрият бургер във Варна, точка. Доставката дойде за 22 минути, още топъл.", stars: 5 },
        { name: "Ива М.", text: "Веги бургерът с халуми не е „опция за вегетарианци“, а причина да идвам. И лимонадата!", stars: 5 },
        { name: "Офис екип, Варна", text: "Кетъринг за 40 души, грил на място, всичко навреме. Хората още говорят за картофите с трюфел.", stars: 5 },
      ],
      faq: [
        { q: "Как да поръчам?", a: "Онлайн от сайта — избирате, плащате с карта или в брой при доставка, следите поръчката в реално време." },
        { q: "Колко струва доставката?", a: "2 € в града, безплатна над 15 €. Ако закъснеем с повече от 30 минути — поръчката е безплатна." },
        { q: "Имате ли вегетарианско и без глутен?", a: "Да — веги бургер с халуми и питка без глутен по заявка (+1 €)." },
        { q: "Може ли да резервирам маса?", a: "Не приемаме резервации — 24 места, който дойде. В петък и събота опашката се движи бързо." },
        { q: "Правите ли кетъринг?", a: "Да, за партита и офиси от 20 души — с наш грил и готвач на място." },
      ],
      contact: { eyebrow: "Контакт", title: "Гладни? <em>Пишете или звънете</em>", lede: "За кетъринг и групови поръчки — пишете предварително." },
    },
    en: {
      name: "Crunch Corner", category: "Fast food", city: "Varna",
      metaTitle: "Crunch Corner · Burgers and Fries Varna · Demo website",
      metaDesc: "Demo website for a fast food restaurant: menu with prices, online ordering, 30-minute delivery, reviews, FAQ. By Carbon Stealth.",
      address: "10 Slivnitsa St, 9000 Varna", phone: "+359 88 000 0010", email: "order@crunchcorner.example",
      hours: ["Mon – Thu: 11:00 – 23:00", "Fri – Sat: 11:00 – 02:00", "Sunday: 12:00 – 22:00"],
      hero: {
        eyebrow: "Smash burgers · fries · shakes · Varna",
        title: "Crispy outside. <em>Juicy inside.</em> At your door in 30 minutes.",
        lede: "Dobrudzha beef smashed on the griddle the moment you order, hand-cut fries and buns from our own oven. Order online, pay by card, delivery in 30 minutes or it is free.",
        cta: "Order online", cta2: "See the menu",
        proof: "★ 4.8 on Google · 48,000+ orders delivered · 30 minutes or it's free",
        widget: { kind: "tiles", title: "Most ordered", rows: [["Double smash", "2× beef · cheddar · sauce", "€8.90"], ["Crispy chicken", "buttermilk · pickles", "€7.90"], ["Truffle fries", "parmesan · truffle oil", "€4.50"]] },
      },
      badges: ["Delivery in 30 min or free", "Card payment online", "Open until 02:00 Fri and Sat", "Vegetarian menu"],
      offer: { tag: "Online only", title: "Double smash + fries + drink for €12.90", text: "The combo of the week when you order on the site: you save €4.50 versus the menu, and delivery within the city is free over €15.", cta: "Order the combo", note: "Every day 11:00–23:00. Vegetarian version — same price." },
      servicesTitle: "Why <em>they come back</em>",
      servicesLede: "We are not a chain. Every bun is from our oven, every sauce from our kitchen.",
      services: [
        { t: "Smash burgers", d: "Dobrudzha beef, 2 × 70 g, smashed at 300 °C. Crispy crust, pink centre." },
        { t: "Crispy chicken", d: "24 hours in buttermilk, double breading, pickles from our kitchen." },
        { t: "Fries and sides", d: "Hand-cut, double-fried. With truffle, with cheddar and bacon, or classic." },
        { t: "Shakes and lemonades", d: "Real ice cream, home-made syrups. No powder, no concentrate." },
        { t: "Vegetarian", d: "Chickpea and halloumi burger, fries and salad — not “by default”, but delicious." },
        { t: "Catering", d: "A burger bar for parties and offices — from 20 people, with our grill on site.", p: "from €12 / person" },
      ],
      about: {
        eyebrow: "About us", title: "Two cooks, <em>one griddle</em> and a queue since 2021",
        p: ["Crunch Corner started as a truck on the beach and in three years became the place with the longest Friday-night queue in Varna. We stayed small — 24 seats and a kitchen you can see.", "The beef is from Dobrudzha, buns are baked every two hours and fries are cut in the morning. If anything arrives cold — we replace it, no questions."],
        facts: [{ n: "2021", l: "from a truck on the beach" }, { n: "30", l: "minutes delivery" }, { n: "4.8", l: "rating · 2,400 reviews" }, { n: "24", l: "seats + garden" }],
      },
      list: { title: "The menu", lede: "Everything is made to order. Allergens are in the online menu.", groups: [
        { t: "Burgers", items: [["Classic smash", "€6.90"], ["Double smash", "€8.90"], ["Bacon and caramelised onion", "€9.50"], ["Crispy chicken", "€7.90"], ["Veggie halloumi", "€7.50"]] },
        { t: "Sides and drinks", items: [["Classic fries", "€3.20"], ["Truffle fries", "€4.50"], ["Onion rings", "€3.90"], ["Shake (vanilla · chocolate · strawberry)", "€4.20"], ["Home-made lemonade", "€2.90"]] },
      ] },
      reviews: [
        { name: "Daniel R.", text: "The double smash is the best burger in Varna, full stop. Delivery came in 22 minutes, still hot.", stars: 5 },
        { name: "Iva M.", text: "The veggie halloumi burger is not “an option for vegetarians”, it is a reason to come. And the lemonade!", stars: 5 },
        { name: "Office team, Varna", text: "Catering for 40 people, grill on site, everything on time. People still talk about the truffle fries.", stars: 5 },
      ],
      faq: [
        { q: "How do I order?", a: "Online from the website — choose, pay by card or cash on delivery, track your order in real time." },
        { q: "How much is delivery?", a: "€2 in the city, free over €15. If we are more than 30 minutes late — the order is free." },
        { q: "Do you have vegetarian and gluten-free?", a: "Yes — a veggie halloumi burger and a gluten-free bun on request (+€1)." },
        { q: "Can I book a table?", a: "We do not take reservations — 24 seats, first come first served. On Friday and Saturday the queue moves fast." },
        { q: "Do you do catering?", a: "Yes, for parties and offices from 20 people — with our grill and a cook on site." },
      ],
      contact: { eyebrow: "Contact", title: "Hungry? <em>Message or call</em>", lede: "For catering and group orders — write in advance." },
    },
    it: {
      name: "Crunch Corner", category: "Fast food", city: "Rimini",
      metaTitle: "Crunch Corner · Hamburger e patatine Rimini · Sito demo",
      metaDesc: "Sito demo per fast food: menu con prezzi, ordini online, consegna in 30 minuti, recensioni, FAQ. Di Carbon Stealth.",
      address: "Viale Vespucci 10, 47921 Rimini", phone: "+39 0541 000 010", email: "ordini@crunchcorner.example",
      hours: ["Lun – Gio: 11:00 – 23:00", "Ven – Sab: 11:00 – 02:00", "Domenica: 12:00 – 22:00"],
      hero: {
        eyebrow: "Smash burger · patatine · frappè · Rimini",
        title: "Croccante fuori. <em>Succoso dentro.</em> A casa tua in 30 minuti.",
        lede: "Manzo romagnolo schiacciato sulla piastra al momento dell'ordine, patatine tagliate a mano e pane del nostro forno. Ordini online, paghi con carta, consegna in 30 minuti o è gratis.",
        cta: "Ordina online", cta2: "Vedi il menu",
        proof: "★ 4,8 su Google · 48.000+ ordini consegnati · 30 minuti o è gratis",
        widget: { kind: "tiles", title: "I più ordinati", rows: [["Doppio smash", "2× manzo · cheddar · salsa", "8,90 €"], ["Pollo croccante", "buttermilk · cetriolini", "7,90 €"], ["Patatine al tartufo", "parmigiano · olio al tartufo", "4,50 €"]] },
      },
      badges: ["Consegna in 30 min o gratis", "Pagamento con carta online", "Aperto fino alle 02:00 ven e sab", "Menu vegetariano"],
      offer: { tag: "Solo online", title: "Doppio smash + patatine + bibita a 12,90 €", text: "Il combo della settimana ordinando dal sito: risparmi 4,50 € rispetto al menu e la consegna in città è gratuita sopra i 15 €.", cta: "Ordina il combo", note: "Tutti i giorni 11:00–23:00. Versione vegetariana allo stesso prezzo." },
      servicesTitle: "Perché <em>tornano</em>",
      servicesLede: "Non siamo una catena. Ogni pane è del nostro forno, ogni salsa della nostra cucina.",
      services: [
        { t: "Smash burger", d: "Manzo romagnolo, 2 × 70 g, schiacciato a 300 °C. Crosta croccante, cuore rosa." },
        { t: "Pollo croccante", d: "24 ore nel buttermilk, doppia panatura, cetriolini della nostra cucina." },
        { t: "Patatine e contorni", d: "Tagliate a mano, doppia frittura. Al tartufo, con cheddar e bacon, o classiche." },
        { t: "Frappè e limonate", d: "Gelato vero, sciroppi fatti in casa. Niente polveri, niente concentrati." },
        { t: "Vegetariano", d: "Burger di ceci e halloumi, patatine e insalata — non «di default», ma buono." },
        { t: "Catering", d: "Un burger bar per feste e uffici — da 20 persone, con la nostra griglia sul posto.", p: "da 12 € / persona" },
      ],
      about: {
        eyebrow: "Chi siamo", title: "Due cuochi, <em>una piastra</em> e una fila dal 2021",
        p: ["Crunch Corner è nato come furgone in spiaggia e in tre anni è diventato il locale con la fila più lunga del venerdì sera a Rimini. Siamo rimasti piccoli — 24 posti e una cucina a vista.", "La carne è romagnola, il pane si sforna ogni due ore e le patate si tagliano al mattino. Se qualcosa arriva freddo — lo sostituiamo, senza domande."],
        facts: [{ n: "2021", l: "da un furgone in spiaggia" }, { n: "30", l: "minuti di consegna" }, { n: "4,8", l: "voto · 2.400 recensioni" }, { n: "24", l: "posti + giardino" }],
      },
      list: { title: "Il menu", lede: "Tutto è preparato al momento. Gli allergeni sono nel menu online.", groups: [
        { t: "Burger", items: [["Smash classico", "6,90 €"], ["Doppio smash", "8,90 €"], ["Bacon e cipolla caramellata", "9,50 €"], ["Pollo croccante", "7,90 €"], ["Veggie halloumi", "7,50 €"]] },
        { t: "Contorni e bevande", items: [["Patatine classiche", "3,20 €"], ["Patatine al tartufo", "4,50 €"], ["Anelli di cipolla", "3,90 €"], ["Frappè (vaniglia · cioccolato · fragola)", "4,20 €"], ["Limonata fatta in casa", "2,90 €"]] },
      ] },
      reviews: [
        { name: "Daniele R.", text: "Il doppio smash è il miglior burger di Rimini, punto. Consegna in 22 minuti, ancora caldo.", stars: 5 },
        { name: "Iva M.", text: "Il veggie burger con halloumi non è «un'opzione per vegetariani», è un motivo per venire. E la limonata!", stars: 5 },
        { name: "Team ufficio, Rimini", text: "Catering per 40 persone, griglia sul posto, tutto puntuale. Si parla ancora delle patatine al tartufo.", stars: 5 },
      ],
      faq: [
        { q: "Come ordino?", a: "Online dal sito — scegli, paghi con carta o in contanti alla consegna, segui l'ordine in tempo reale." },
        { q: "Quanto costa la consegna?", a: "2 € in città, gratuita sopra 15 €. Se ritardiamo più di 30 minuti — l'ordine è gratis." },
        { q: "Avete opzioni vegetariane e senza glutine?", a: "Sì — veggie burger con halloumi e pane senza glutine su richiesta (+1 €)." },
        { q: "Posso prenotare un tavolo?", a: "Non prendiamo prenotazioni — 24 posti, chi arriva si siede. Venerdì e sabato la fila scorre veloce." },
        { q: "Fate catering?", a: "Sì, per feste e uffici da 20 persone — con la nostra griglia e un cuoco sul posto." },
      ],
      contact: { eyebrow: "Contatti", title: "Fame? <em>Scrivi o chiama</em>", lede: "Per catering e ordini di gruppo — scrivi in anticipo." },
    },
  },
};
