// drehi.mjs — демо „NORD Studio": магазин за дрехи. Гипс + черно + теракота, модно editorial hero.
export default {
  id: "drehi",
  slug: { bg: "magazin-za-drehi", en: "clothing-store", it: "negozio-abbigliamento" },
  icon: "hanger",
  schemaType: "ClothingStore",
  theme: {
    mode: "light", heroStyle: "editorial", pattern: "grid", radius: "0px",
    fonts: ["Syne:wght@600;800", "Space+Grotesk:wght@400;500;600"],
    display: "Syne, system-ui, sans-serif", body: "'Space Grotesk', system-ui, sans-serif",
    bg: "#f3f0ea", surface: "#ffffff", surface2: "#e9e4da", text: "#161412", muted: "#6b665e",
    accent: "#c2492b", accent2: "#e2734f", onAccent: "#fff7f3", line: "rgba(22,20,18,.13)",
    word: "NORD",
  },
  keywords: {
    bg: ["сайт за магазин за дрехи", "моден бутик демо сайт", "онлайн магазин дрехи", "уеб сайт бутик", "изработка на сайт за дрехи"],
    en: ["clothing store website", "fashion boutique website demo", "clothing shop online", "fashion brand website", "boutique website design"],
    it: ["sito negozio abbigliamento", "sito boutique demo", "shop online abbigliamento", "sito brand moda", "realizzazione sito boutique"],
  },
  t: {
    bg: {
      name: "NORD Studio", category: "Магазин за дрехи", city: "София",
      metaTitle: "NORD Studio · Магазин за дрехи София · Демо сайт",
      metaDesc: "Демо сайт за магазин за дрехи: колекции с цени, размери, доставка и връщане, лоялна програма, отзиви. От Carbon Stealth.",
      address: "ул. Граф Игнатиев 14, 1000 София", phone: "+359 88 000 0009", email: "hi@nordstudio.example",
      hours: ["Пон – Съб: 10:00 – 20:00", "Неделя: 11:00 – 18:00", "Онлайн: 24/7"],
      hero: {
        eyebrow: "Дрехи · есен/зима 2026 · София и онлайн",
        title: "Малко неща. <em>Носени дълго.</em>",
        lede: "Вълна, лен и органичен памук, ушити в Европа в ограничени серии. Пробвате в магазина на Графа или поръчвате онлайн с безплатна доставка и 30 дни за връщане.",
        cta: "Разгледай колекцията", cta2: "Намери размера си",
        proof: "★ 4,9 в Google · 11 500+ клиенти · Доставка за 1–2 работни дни",
        widget: { kind: "tiles", title: "Нова колекция", rows: [["Палто „Север“", "вълна · камел · XS–XL", "290 €"], ["Риза „Лен 02“", "лен · бяло · S–XXL", "89 €"], ["Панталон „Ателие“", "памук · черно · 34–44", "119 €"]] },
      },
      badges: ["Безплатна доставка над 80 €", "30 дни за връщане", "Ушито в Европа", "Ограничени серии"],
      offer: { tag: "Есен/зима 2026", title: "−15% на първата поръчка + безплатни корекции в ателието", text: "Абонирайте се за новините и получавате код за 15% на първата си поръчка. Ако нещо не стои идеално — скъсяваме и стесняваме безплатно, за 3 дни.", cta: "Вземи кода", note: "Безплатна доставка над 80 € и 30 дни за връщане — винаги." },
      servicesTitle: "Какво <em>ще намерите</em>",
      servicesLede: "Три колекции годишно, всяка от 20 до 30 модела. Когато свършат — свършват.",
      services: [
        { t: "Палта и якета", d: "Вълна от Италия, подплата от вискоза, копчета от рог. Пет модела на сезон.", p: "от 190 €" },
        { t: "Ризи и блузи", d: "Лен и поплин, кройки за всяко тяло — класика, оувърсайз, cropped.", p: "от 69 €" },
        { t: "Панталони и поли", d: "Високи талии, широки крачоли, костюмни материи, които не се мачкат.", p: "от 89 €" },
        { t: "Плетива", d: "Мериносова вълна и кашмир от рециклирани влакна. Без пилинг след прането.", p: "от 99 €" },
        { t: "Аксесоари", d: "Колани, шалове и чанти от малки работилници в България и Италия.", p: "от 35 €" },
        { t: "Ателие за корекции", d: "Скъсяване и стесняване на всяка покупка — безплатно, за 3 дни." },
      ],
      about: {
        eyebrow: "За NORD", title: "Магазин за хора, <em>които не купуват всеки месец</em>",
        p: ["NORD Studio отвори през 2019 г. с идеята за малък гардероб от добри неща. Работим с четири шивашки цеха в България и Италия и знаем името на всяка шивачка.", "Не правим разпродажби на 70% — цените са честни от първия ден. Вместо това имаме лоялна програма: всяка десета покупка е подарък."],
        facts: [{ n: "3", l: "колекции годишно" }, { n: "4", l: "цеха в БГ и Италия" }, { n: "30", l: "дни за връщане" }, { n: "18 000+", l: "клиенти" }],
      },
      steps: { title: "Поръчка <em>без притеснения</em>", items: [{ t: "Изберете размер", d: "Таблица с реални мерки на всяка дреха и чат с продавач, ако се колебаете." }, { t: "Доставка", d: "Еконт или Speedy до 2 работни дни, безплатно над 80 €. Преглед преди плащане." }, { t: "Пробвайте вкъщи", d: "30 дни да решите. Върнете безплатно, ако не пасне." }, { t: "Грижа", d: "Всяка дреха идва с етикет как да я перете, за да живее дълго." }] },
      reviews: [
        { name: "Милена А.", text: "Палтото „Север“ е третата ми зима. Изглежда като ново — и ме питат откъде е всяка седмица.", stars: 5 },
        { name: "Теодора В.", text: "Поръчах два размера, върнах единия безплатно, без въпроси. Така трябва да работи онлайн магазин.", stars: 5 },
        { name: "Николай С.", text: "Ризите от лен са единствените, които нося през лятото. Корекцията на ръкавите — безплатна, за 2 дни.", stars: 5 },
      ],
      faq: [
        { q: "Как да избера размер?", a: "Всяка дреха има таблица с реални мерки (гръдна обиколка, дължина, ръкав). Ако сте между два размера — пишете ни в чата, отговаряме за минути." },
        { q: "Колко струва доставката?", a: "Безплатна над 80 €, иначе 4 €. С преглед и тест преди плащане." },
        { q: "Мога ли да върна?", a: "Да, до 30 дни, неносено, с етикет. Връщането е безплатно с наш куриерски етикет." },
        { q: "Правите ли корекции?", a: "Да, в ателието на магазина — скъсяване и стесняване безплатно за всяка покупка." },
        { q: "Има ли лоялна програма?", a: "Да. Всяка десета покупка е подарък, а членовете виждат новите колекции 3 дни по-рано." },
      ],
      contact: { eyebrow: "Контакт", title: "Питайте за <em>размер или наличност</em>", lede: "Отговаряме в работно време за минути." },
    },
    en: {
      name: "NORD Studio", category: "Clothing store", city: "Sofia",
      metaTitle: "NORD Studio · Clothing Store Sofia · Demo website",
      metaDesc: "Demo website for a clothing store: collections with prices, sizing, shipping and returns, loyalty programme, reviews. By Carbon Stealth.",
      address: "14 Graf Ignatiev St, 1000 Sofia", phone: "+359 88 000 0009", email: "hi@nordstudio.example",
      hours: ["Mon – Sat: 10:00 – 20:00", "Sunday: 11:00 – 18:00", "Online: 24/7"],
      hero: {
        eyebrow: "Clothing · autumn/winter 2026 · Sofia and online",
        title: "Few things. <em>Worn for long.</em>",
        lede: "Wool, linen and organic cotton, sewn in Europe in limited runs. Try on in our Sofia store or order online with free shipping and 30 days to return.",
        cta: "Browse the collection", cta2: "Find your size",
        proof: "★ 4.9 on Google · 11,500+ customers · Delivery in 1–2 working days",
        widget: { kind: "tiles", title: "New collection", rows: [["“North” coat", "wool · camel · XS–XL", "€290"], ["“Linen 02” shirt", "linen · white · S–XXL", "€89"], ["“Atelier” trousers", "cotton · black · 34–44", "€119"]] },
      },
      badges: ["Free shipping over €80", "30-day returns", "Sewn in Europe", "Limited runs"],
      offer: { tag: "Autumn/winter 2026", title: "15% off your first order + free alterations in our atelier", text: "Subscribe to our news and get a 15% code for your first order. If something doesn't fit perfectly, we shorten and take in for free within 3 days.", cta: "Get the code", note: "Free shipping over €80 and 30-day returns — always." },
      servicesTitle: "What <em>you will find</em>",
      servicesLede: "Three collections a year, each of 20 to 30 pieces. When they are gone — they are gone.",
      services: [
        { t: "Coats and jackets", d: "Italian wool, viscose lining, horn buttons. Five styles a season.", p: "from €190" },
        { t: "Shirts and blouses", d: "Linen and poplin, cuts for every body — classic, oversized, cropped.", p: "from €69" },
        { t: "Trousers and skirts", d: "High waists, wide legs, suiting fabrics that do not crease.", p: "from €89" },
        { t: "Knitwear", d: "Merino wool and cashmere from recycled fibres. No pilling after washing.", p: "from €99" },
        { t: "Accessories", d: "Belts, scarves and bags from small workshops in Bulgaria and Italy.", p: "from €35" },
        { t: "Alterations atelier", d: "Shortening and taking in on every purchase — free, within 3 days." },
      ],
      about: {
        eyebrow: "About NORD", title: "A store for people <em>who do not shop every month</em>",
        p: ["NORD Studio opened in 2019 with the idea of a small wardrobe of good things. We work with four sewing workshops in Bulgaria and Italy and know every seamstress by name.", "We do not run 70% sales — prices are honest from day one. Instead we have a loyalty programme: every tenth purchase is a gift."],
        facts: [{ n: "3", l: "collections a year" }, { n: "4", l: "workshops in BG and Italy" }, { n: "30", l: "days to return" }, { n: "18,000+", l: "customers" }],
      },
      steps: { title: "Ordering <em>without worry</em>", items: [{ t: "Pick a size", d: "A table of real measurements for every garment and a chat with a sales assistant if you hesitate." }, { t: "Delivery", d: "Courier within 2 working days, free over €80. Inspect before paying." }, { t: "Try at home", d: "30 days to decide. Return free if it does not fit." }, { t: "Care", d: "Every garment comes with a label on how to wash it so it lives long." }] },
      reviews: [
        { name: "Milena A.", text: "The “North” coat is on its third winter. Looks new — and people ask where it is from every week.", stars: 5 },
        { name: "Teodora V.", text: "Ordered two sizes, returned one for free, no questions. That is how an online shop should work.", stars: 5 },
        { name: "Nikolay S.", text: "The linen shirts are the only ones I wear in summer. Sleeve alteration — free, in 2 days.", stars: 5 },
      ],
      faq: [
        { q: "How do I choose a size?", a: "Every garment has a table of real measurements (chest, length, sleeve). If you are between sizes — message us in the chat, we reply within minutes." },
        { q: "How much is shipping?", a: "Free over €80, otherwise €4. With inspection before payment." },
        { q: "Can I return?", a: "Yes, within 30 days, unworn, with tags. Returns are free with our courier label." },
        { q: "Do you do alterations?", a: "Yes, in the store atelier — shortening and taking in are free on every purchase." },
        { q: "Is there a loyalty programme?", a: "Yes. Every tenth purchase is a gift, and members see new collections 3 days early." },
      ],
      contact: { eyebrow: "Contact", title: "Ask about <em>size or availability</em>", lede: "We reply within minutes during opening hours." },
    },
    it: {
      name: "NORD Studio", category: "Negozio di abbigliamento", city: "Milano",
      metaTitle: "NORD Studio · Negozio di abbigliamento Milano · Sito demo",
      metaDesc: "Sito demo per negozio di abbigliamento: collezioni con prezzi, taglie, spedizione e resi, programma fedeltà, recensioni. Di Carbon Stealth.",
      address: "Corso Como 14, 20154 Milano", phone: "+39 02 000 0009", email: "ciao@nordstudio.example",
      hours: ["Lun – Sab: 10:00 – 20:00", "Domenica: 11:00 – 18:00", "Online: 24/7"],
      hero: {
        eyebrow: "Abbigliamento · autunno/inverno 2026 · Milano e online",
        title: "Poche cose. <em>Portate a lungo.</em>",
        lede: "Lana, lino e cotone organico, cuciti in Europa in serie limitate. Provi in negozio a Milano o ordini online con spedizione gratuita e 30 giorni per il reso.",
        cta: "Sfoglia la collezione", cta2: "Trova la tua taglia",
        proof: "★ 4,9 su Google · 11.500+ clienti · Consegna in 1–2 giorni lavorativi",
        widget: { kind: "tiles", title: "Nuova collezione", rows: [["Cappotto «Nord»", "lana · cammello · XS–XL", "290 €"], ["Camicia «Lino 02»", "lino · bianco · S–XXL", "89 €"], ["Pantalone «Atelier»", "cotone · nero · 34–44", "119 €"]] },
      },
      badges: ["Spedizione gratuita sopra 80 €", "Reso in 30 giorni", "Cucito in Europa", "Serie limitate"],
      offer: { tag: "Autunno/inverno 2026", title: "−15% sul primo ordine + modifiche gratuite in atelier", text: "Iscriviti alle novità e ricevi un codice del 15% sul primo ordine. Se qualcosa non veste alla perfezione, accorciamo e stringiamo gratis in 3 giorni.", cta: "Ottieni il codice", note: "Spedizione gratuita sopra 80 € e reso in 30 giorni — sempre." },
      servicesTitle: "Cosa <em>troverai</em>",
      servicesLede: "Tre collezioni all'anno, ognuna da 20 a 30 capi. Quando finiscono — finiscono.",
      services: [
        { t: "Cappotti e giacche", d: "Lana italiana, fodera in viscosa, bottoni in corno. Cinque modelli a stagione.", p: "da 190 €" },
        { t: "Camicie e bluse", d: "Lino e popeline, vestibilità per ogni corpo — classica, oversize, cropped.", p: "da 69 €" },
        { t: "Pantaloni e gonne", d: "Vita alta, gamba ampia, tessuti da abito che non si stropicciano.", p: "da 89 €" },
        { t: "Maglieria", d: "Lana merino e cashmere da fibre riciclate. Niente pilling dopo il lavaggio.", p: "da 99 €" },
        { t: "Accessori", d: "Cinture, sciarpe e borse da piccoli laboratori in Italia e Bulgaria.", p: "da 35 €" },
        { t: "Atelier riparazioni", d: "Accorciare e stringere ogni acquisto — gratis, in 3 giorni." },
      ],
      about: {
        eyebrow: "NORD", title: "Un negozio per chi <em>non compra ogni mese</em>",
        p: ["NORD Studio ha aperto nel 2019 con l'idea di un guardaroba piccolo di cose buone. Lavoriamo con quattro laboratori di cucito in Italia e Bulgaria e conosciamo ogni sarta per nome.", "Non facciamo saldi al 70% — i prezzi sono onesti dal primo giorno. In cambio abbiamo un programma fedeltà: ogni decimo acquisto è un regalo."],
        facts: [{ n: "3", l: "collezioni all'anno" }, { n: "4", l: "laboratori in IT e BG" }, { n: "30", l: "giorni per il reso" }, { n: "18.000+", l: "clienti" }],
      },
      steps: { title: "Ordinare <em>senza pensieri</em>", items: [{ t: "Scegli la taglia", d: "Tabella con misure reali per ogni capo e chat con una commessa se hai dubbi." }, { t: "Consegna", d: "Corriere entro 2 giorni lavorativi, gratis sopra 80 €." }, { t: "Prova a casa", d: "30 giorni per decidere. Reso gratuito se non va bene." }, { t: "Cura", d: "Ogni capo arriva con un'etichetta su come lavarlo perché duri a lungo." }] },
      reviews: [
        { name: "Milena A.", text: "Il cappotto «Nord» è al terzo inverno. Sembra nuovo — e mi chiedono da dove viene ogni settimana.", stars: 5 },
        { name: "Teodora V.", text: "Ho ordinato due taglie, resa una gratis, senza domande. Così deve funzionare uno shop online.", stars: 5 },
        { name: "Nicola S.", text: "Le camicie di lino sono le uniche che porto d'estate. Accorciare le maniche — gratis, in 2 giorni.", stars: 5 },
      ],
      faq: [
        { q: "Come scelgo la taglia?", a: "Ogni capo ha una tabella con misure reali (torace, lunghezza, manica). Se sei tra due taglie — scrivici in chat, rispondiamo in pochi minuti." },
        { q: "Quanto costa la spedizione?", a: "Gratuita sopra 80 €, altrimenti 4 €." },
        { q: "Posso fare il reso?", a: "Sì, entro 30 giorni, non indossato, con etichetta. Il reso è gratuito con la nostra etichetta corriere." },
        { q: "Fate riparazioni?", a: "Sì, nell'atelier del negozio — accorciare e stringere sono gratuiti per ogni acquisto." },
        { q: "C'è un programma fedeltà?", a: "Sì. Ogni decimo acquisto è un regalo e i membri vedono le nuove collezioni 3 giorni prima." },
      ],
      contact: { eyebrow: "Contatti", title: "Chiedi <em>taglia o disponibilità</em>", lede: "Rispondiamo in pochi minuti in orario di apertura." },
    },
  },
};
