// fitnes.mjs — демо „FORMA": фитнес. Черно + електриково лайм, центриран hero, седмичен график.
export default {
  id: "fitnes",
  slug: { bg: "fitnes", en: "gym", it: "palestra" },
  icon: "dumbbell",
  schemaType: "ExerciseGym",
  theme: {
    mode: "dark", heroStyle: "center", pattern: "glow", radius: "4px",
    fonts: ["Bebas+Neue", "Inter:wght@400;500;700"],
    display: "'Bebas Neue', Impact, sans-serif", body: "Inter, system-ui, sans-serif",
    bg: "#0a0a0a", surface: "#141414", surface2: "#1d1d1d", text: "#fafafa", muted: "#9c9c9c",
    accent: "#c6ff3d", accent2: "#e2ff8a", onAccent: "#0a0a0a", line: "rgba(255,255,255,.1)",
    word: "STRONG",
  },
  keywords: {
    bg: ["сайт за фитнес", "фитнес зала демо сайт", "уеб сайт за спортен клуб", "онлайн записване фитнес", "изработка на сайт за фитнес"],
    en: ["gym website", "fitness studio website demo", "personal trainer website", "class schedule website", "fitness website design"],
    it: ["sito web palestra", "sito palestra demo", "sito personal trainer", "orario corsi online", "realizzazione sito palestra"],
  },
  t: {
    bg: {
      name: "FORMA", category: "Фитнес", city: "София",
      metaTitle: "FORMA · Фитнес и групови тренировки София · Демо сайт",
      metaDesc: "Демо сайт за фитнес зала: седмичен график, абонаменти с цени, треньори, отзиви, FAQ. От Carbon Stealth.",
      address: "ул. Позитано 20, 1000 София", phone: "+359 88 000 0002", email: "hello@forma.example",
      hours: ["Пон – Пет: 06:00 – 23:00", "Събота: 08:00 – 21:00", "Неделя: 09:00 – 20:00"],
      hero: {
        eyebrow: "Фитнес · групови тренировки · София център",
        title: "Не зала. <em>Резултат.</em>",
        lede: "Силови зони, функционални тренировки, HIIT и мобилност — 60 групови занятия седмично и треньори, които знаят името ти. Първата тренировка е безплатна.",
        cta: "Безплатна тренировка", cta2: "Виж графика",
        proof: "★ 4,8 в Google · 1 200+ членове · Първата тренировка е безплатна",
        widget: { kind: "schedule", title: "Тази седмица", rows: [["Пон", "07:00", "HIIT 45"], ["Вт", "18:30", "Силова · крака"], ["Ср", "19:00", "Мобилност и core"], ["Чет", "07:00", "Кросфит основи"], ["Пет", "18:00", "Бокс кондиция"], ["Съб", "10:00", "Open gym + треньор"]], cta: "Запази място" },
      },
      badges: ["Първа тренировка безплатно", "Без обвързване", "Отворено 06:00 – 23:00", "Душове и шкафчета"],
      offer: { tag: "Само този месец", title: "3 месеца на цената на 2 + безплатен старт с треньор", text: "Запишете се онлайн и получавате 30-минутна встъпителна тренировка с личен треньор, план за първите 4 седмици и третия месец подарък.", cta: "Вземи офертата", note: "Без обвързване. Спирате, когато решите." },
      servicesTitle: "Тренирай <em>както ти харесва</em>",
      servicesLede: "Всички зони и класове са включени във всеки абонамент. Без доплащане, без изненади.",
      services: [
        { t: "Силова зона", d: "Пет рака за клек, платформи за мъртва тяга, дъмбели до 50 кг, машини Technogym." },
        { t: "Групови класове", d: "60 занятия седмично: HIIT, силова, мобилност, бокс, кросфит основи. До 14 души в група." },
        { t: "Персонален треньор", d: "Индивидуална програма, хранене, измервания на всеки 4 седмици.", p: "от 35 € / час" },
        { t: "Кардио и възстановяване", d: "Бягащи пътеки, гребни ергометри, SkiErg, сауна и зона за разтягане." },
        { t: "Хранителен план", d: "Изготвен от диетолог, съобразен с тренировките ти. Ревизия на всеки месец.", p: "от 60 €" },
        { t: "Корпоративни карти", d: "Отстъпка за екипи от 5+ души и фактура за фирмата." },
      ],
      about: {
        eyebrow: "Залата", title: "1200 м² <em>и нула опашки</em> за уредите",
        p: ["FORMA е построена за хора, които тренират сериозно, но нямат време да чакат. Пет силови рака, отделна зала за класове и кардио зона с изглед към града.", "Треньорите ни са сертифицирани (NASM, EREPS 4) и всеки нов член получава безплатен уводен час — техника, програма, цели."],
        facts: [{ n: "1 200", l: "м² тренировъчна площ" }, { n: "60", l: "групови класа седмично" }, { n: "8", l: "сертифицирани треньори" }, { n: "17", l: "часа отворено на ден" }],
      },
      list: { title: "Абонаменти <em>без дребен шрифт</em>", lede: "Всеки план включва всички зони и класове. Спираш когато поискаш.", groups: [
        { t: "Месечни", items: [["Месечен — всичко включено", "49 €"], ["Месечен — само сутрин (до 12:00)", "35 €"], ["Студентски", "39 €"]] },
        { t: "Дългосрочни", items: [["6 месеца", "249 €"], ["12 месеца", "449 €"], ["Еднократно посещение", "8 €"]] },
      ] },
      reviews: [
        { name: "Никол В.", text: "Записах се за безплатната тренировка и останах година. Треньорите наистина следят техниката.", stars: 5 },
        { name: "Стефан М.", text: "Отворено от 6 сутринта, никога не чакам за рак. Това е всичко, което искам от зала.", stars: 5 },
        { name: "Деси П.", text: "HIIT класовете в 7 сутринта ми смениха деня. И душовете са чисти — важно е.", stars: 5 },
      ],
      faq: [
        { q: "Наистина ли първата тренировка е безплатна?", a: "Да. Идваш, треньор те развежда, тренираш 60 минути. Без карта, без ангажимент." },
        { q: "Има ли обвързване с договор?", a: "Не. Месечният абонамент се спира с едно съобщение. Дългосрочните са с отстъпка, но също без глоби." },
        { q: "Трябва ли да резервирам място за клас?", a: "Да, в приложението или на рецепция — групите са до 14 души. Отказ е възможен до 2 часа преди." },
        { q: "Има ли паркинг?", a: "Подземен паркинг с 40 места, безплатен за членове до 2 часа." },
        { q: "Мога ли да замразя абонамента?", a: "Да, до 30 дни в годината — при отпуск или болест, без документи." },
      ],
      contact: { eyebrow: "Контакт", title: "Ела на <em>безплатна тренировка</em>", lede: "Кажи ни кога ти е удобно и ще ти запазим час с треньор." },
    },
    en: {
      name: "FORMA", category: "Gym", city: "Sofia",
      metaTitle: "FORMA · Gym and Group Training Sofia · Demo website",
      metaDesc: "Demo website for a gym: weekly schedule, membership prices, trainers, reviews, FAQ. By Carbon Stealth.",
      address: "20 Pozitano St, 1000 Sofia", phone: "+359 88 000 0002", email: "hello@forma.example",
      hours: ["Mon – Fri: 06:00 – 23:00", "Saturday: 08:00 – 21:00", "Sunday: 09:00 – 20:00"],
      hero: {
        eyebrow: "Gym · group training · Sofia centre",
        title: "Not a gym. <em>A result.</em>",
        lede: "Strength zones, functional training, HIIT and mobility — 60 group classes a week and coaches who know your name. Your first session is free.",
        cta: "Free session", cta2: "See the schedule",
        proof: "★ 4.8 on Google · 1,200+ members · Your first session is free",
        widget: { kind: "schedule", title: "This week", rows: [["Mon", "07:00", "HIIT 45"], ["Tue", "18:30", "Strength · legs"], ["Wed", "19:00", "Mobility and core"], ["Thu", "07:00", "CrossFit basics"], ["Fri", "18:00", "Boxing conditioning"], ["Sat", "10:00", "Open gym + coach"]], cta: "Reserve a spot" },
      },
      badges: ["First session free", "No contract", "Open 06:00 – 23:00", "Showers and lockers"],
      offer: { tag: "This month only", title: "3 months for the price of 2 + a free coach onboarding", text: "Sign up online and get a 30-minute onboarding session with a personal trainer, a plan for your first 4 weeks and the third month free.", cta: "Claim the offer", note: "No contract. Stop whenever you want." },
      servicesTitle: "Train <em>the way you like</em>",
      servicesLede: "All zones and classes are included in every membership. No surcharges, no surprises.",
      services: [
        { t: "Strength zone", d: "Five squat racks, deadlift platforms, dumbbells up to 50 kg, Technogym machines." },
        { t: "Group classes", d: "60 sessions a week: HIIT, strength, mobility, boxing, CrossFit basics. Max 14 per class." },
        { t: "Personal trainer", d: "Individual programme, nutrition, measurements every 4 weeks.", p: "from €35 / hour" },
        { t: "Cardio and recovery", d: "Treadmills, rowers, SkiErg, sauna and stretching zone." },
        { t: "Nutrition plan", d: "Made by a dietitian, matched to your training. Revised monthly.", p: "from €60" },
        { t: "Corporate cards", d: "Discount for teams of 5+ and an invoice for the company." },
      ],
      about: {
        eyebrow: "The gym", title: "1,200 m² <em>and zero queues</em> for equipment",
        p: ["FORMA is built for people who train seriously but have no time to wait. Five racks, a separate studio for classes and a cardio zone overlooking the city.", "Our coaches are certified (NASM, EREPS 4) and every new member gets a free onboarding hour — technique, programme, goals."],
        facts: [{ n: "1,200", l: "m² of training space" }, { n: "60", l: "group classes a week" }, { n: "8", l: "certified coaches" }, { n: "17", l: "hours open a day" }],
      },
      list: { title: "Memberships <em>without small print</em>", lede: "Every plan includes all zones and classes. Stop whenever you want.", groups: [
        { t: "Monthly", items: [["Monthly — all inclusive", "€49"], ["Monthly — mornings only (until 12:00)", "€35"], ["Student", "€39"]] },
        { t: "Long-term", items: [["6 months", "€249"], ["12 months", "€449"], ["Single visit", "€8"]] },
      ] },
      reviews: [
        { name: "Nicole V.", text: "Came for the free session and stayed a year. The coaches really watch your form.", stars: 5 },
        { name: "Stefan M.", text: "Open from 6 am, never waiting for a rack. That is all I want from a gym.", stars: 5 },
        { name: "Desi P.", text: "The 7 am HIIT classes changed my day. And the showers are clean — that matters.", stars: 5 },
      ],
      faq: [
        { q: "Is the first session really free?", a: "Yes. You come, a coach shows you around, you train for 60 minutes. No card, no commitment." },
        { q: "Is there a contract?", a: "No. Monthly membership stops with a single message. Long-term plans are discounted but also penalty-free." },
        { q: "Do I need to book a class?", a: "Yes, in the app or at reception — classes are capped at 14. You can cancel up to 2 hours before." },
        { q: "Is there parking?", a: "Underground parking with 40 spaces, free for members for up to 2 hours." },
        { q: "Can I freeze my membership?", a: "Yes, up to 30 days a year — for holidays or illness, no paperwork." },
      ],
      contact: { eyebrow: "Contact", title: "Come for a <em>free session</em>", lede: "Tell us when suits you and we will book a coach." },
    },
    it: {
      name: "FORMA", category: "Palestra", city: "Milano",
      metaTitle: "FORMA · Palestra e corsi di gruppo Milano · Sito demo",
      metaDesc: "Sito demo per palestra: orario settimanale, abbonamenti con prezzi, trainer, recensioni, FAQ. Di Carbon Stealth.",
      address: "Via Torino 20, 20123 Milano", phone: "+39 02 000 0002", email: "ciao@forma.example",
      hours: ["Lun – Ven: 06:00 – 23:00", "Sabato: 08:00 – 21:00", "Domenica: 09:00 – 20:00"],
      hero: {
        eyebrow: "Palestra · corsi di gruppo · Milano centro",
        title: "Non una palestra. <em>Un risultato.</em>",
        lede: "Zone forza, allenamento funzionale, HIIT e mobilità — 60 corsi di gruppo a settimana e coach che sanno il tuo nome. La prima seduta è gratis.",
        cta: "Prova gratuita", cta2: "Vedi l'orario",
        proof: "★ 4,8 su Google · 1.200+ iscritti · La prima seduta è gratis",
        widget: { kind: "schedule", title: "Questa settimana", rows: [["Lun", "07:00", "HIIT 45"], ["Mar", "18:30", "Forza · gambe"], ["Mer", "19:00", "Mobilità e core"], ["Gio", "07:00", "CrossFit base"], ["Ven", "18:00", "Boxe conditioning"], ["Sab", "10:00", "Open gym + coach"]], cta: "Prenota un posto" },
      },
      badges: ["Prima seduta gratis", "Nessun vincolo", "Aperto 06:00 – 23:00", "Docce e armadietti"],
      offer: { tag: "Solo questo mese", title: "3 mesi al prezzo di 2 + avvio gratuito con un trainer", text: "Iscriviti online e ricevi una seduta introduttiva di 30 minuti con un personal trainer, un piano per le prime 4 settimane e il terzo mese in regalo.", cta: "Approfitta dell'offerta", note: "Nessun vincolo. Smetti quando vuoi." },
      servicesTitle: "Allenati <em>come piace a te</em>",
      servicesLede: "Tutte le zone e i corsi sono inclusi in ogni abbonamento. Niente supplementi, niente sorprese.",
      services: [
        { t: "Zona forza", d: "Cinque rack per squat, pedane per stacco, manubri fino a 50 kg, macchine Technogym." },
        { t: "Corsi di gruppo", d: "60 sessioni a settimana: HIIT, forza, mobilità, boxe, CrossFit base. Max 14 per corso." },
        { t: "Personal trainer", d: "Programma individuale, alimentazione, misurazioni ogni 4 settimane.", p: "da 35 € / ora" },
        { t: "Cardio e recupero", d: "Tapis roulant, vogatori, SkiErg, sauna e zona stretching." },
        { t: "Piano alimentare", d: "Preparato da un dietista, in linea con i tuoi allenamenti. Revisione mensile.", p: "da 60 €" },
        { t: "Card aziendali", d: "Sconto per team da 5+ persone e fattura per l'azienda." },
      ],
      about: {
        eyebrow: "La palestra", title: "1.200 m² <em>e zero code</em> agli attrezzi",
        p: ["FORMA è fatta per chi si allena sul serio ma non ha tempo di aspettare. Cinque rack, una sala separata per i corsi e una zona cardio con vista sulla città.", "I nostri coach sono certificati (NASM, EREPS 4) e ogni nuovo iscritto riceve un'ora introduttiva gratuita — tecnica, programma, obiettivi."],
        facts: [{ n: "1.200", l: "m² di area allenamento" }, { n: "60", l: "corsi di gruppo a settimana" }, { n: "8", l: "coach certificati" }, { n: "17", l: "ore di apertura al giorno" }],
      },
      list: { title: "Abbonamenti <em>senza asterischi</em>", lede: "Ogni piano include tutte le zone e i corsi. Smetti quando vuoi.", groups: [
        { t: "Mensili", items: [["Mensile — tutto incluso", "49 €"], ["Mensile — solo mattina (fino alle 12:00)", "35 €"], ["Studenti", "39 €"]] },
        { t: "Lungo periodo", items: [["6 mesi", "249 €"], ["12 mesi", "449 €"], ["Ingresso singolo", "8 €"]] },
      ] },
      reviews: [
        { name: "Nicole V.", text: "Sono venuta per la prova gratuita e sono rimasta un anno. I coach guardano davvero la tecnica.", stars: 5 },
        { name: "Stefano M.", text: "Aperto dalle 6, non aspetto mai per un rack. È tutto ciò che voglio da una palestra.", stars: 5 },
        { name: "Desi P.", text: "I corsi HIIT delle 7 mi hanno cambiato la giornata. E le docce sono pulite — conta.", stars: 5 },
      ],
      faq: [
        { q: "La prima seduta è davvero gratis?", a: "Sì. Vieni, un coach ti accompagna, ti alleni 60 minuti. Senza tessera, senza impegno." },
        { q: "C'è un contratto vincolante?", a: "No. L'abbonamento mensile si interrompe con un messaggio. Quelli lunghi sono scontati ma senza penali." },
        { q: "Devo prenotare i corsi?", a: "Sì, nell'app o alla reception — i corsi sono a massimo 14 persone. Disdetta fino a 2 ore prima." },
        { q: "C'è parcheggio?", a: "Parcheggio sotterraneo con 40 posti, gratuito per gli iscritti fino a 2 ore." },
        { q: "Posso congelare l'abbonamento?", a: "Sì, fino a 30 giorni all'anno — per ferie o malattia, senza documenti." },
      ],
      contact: { eyebrow: "Contatti", title: "Vieni a fare <em>una prova gratuita</em>", lede: "Dicci quando ti è comodo e ti prenotiamo un coach." },
    },
  },
};
