// hotel.mjs — демо „Silver Fir": хотел / къща за гости. Дълбоко зелено + пясък, резервационна карта.
export default {
  id: "hotel",
  slug: { bg: "hotel-kashta-za-gosti", en: "hotel-guest-house", it: "hotel-casa-vacanze" },
  icon: "bell",
  schemaType: "LodgingBusiness",
  theme: {
    mode: "dark", heroStyle: "split", pattern: "glow", radius: "14px",
    fonts: ["DM+Serif+Display", "DM+Sans:wght@400;500;600"],
    display: "'DM Serif Display', Georgia, serif", body: "'DM Sans', system-ui, sans-serif",
    bg: "#0f1a16", surface: "#16241f", surface2: "#1f3129", text: "#f3efe6", muted: "#a9b3aa",
    accent: "#d8b47a", accent2: "#eacc9a", onAccent: "#0f1a16", line: "rgba(243,239,230,.1)",
    word: "STAY",
  },
  keywords: {
    bg: ["сайт за хотел", "къща за гости демо сайт", "сайт за семеен хотел", "онлайн резервации хотел", "изработка на сайт за хотел"],
    en: ["hotel website", "guest house website demo", "boutique hotel website", "direct booking website", "hotel website design"],
    it: ["sito hotel", "sito casa vacanze demo", "sito b&b", "prenotazione diretta hotel", "realizzazione sito hotel"],
  },
  t: {
    bg: {
      name: "Silver Fir", category: "Хотел / къща за гости", city: "Банско",
      metaTitle: "Silver Fir · Къща за гости Банско · Демо сайт",
      metaDesc: "Демо сайт за хотел и къща за гости: стаи с цени, директни резервации без комисиона, закуска, спа, отзиви. От Carbon Stealth.",
      address: "ул. Пирин 112, 2770 Банско", phone: "+359 88 000 0006", email: "stay@silverfir.example",
      hours: ["Рецепция: 07:00 – 23:00", "Настаняване от 15:00", "Освобождаване до 11:00"],
      hero: {
        eyebrow: "Къща за гости · Банско · 400 м от лифта",
        title: "Планината <em>през прозореца.</em> Тишината — включена.",
        lede: "Осем стаи с изглед към Пирин, домашна закуска, сауна и джакузи на терасата. Резервирате директно — без комисиони за платформи, с най-ниската цена и безплатна отмяна до 7 дни.",
        cta: "Провери свободни дати", cta2: "Виж стаите",
        widget: { kind: "booking", title: "Директна резервация", rows: [["Настаняване", "Пет, 20 дек"], ["Освобождаване", "Нед, 22 дек"], ["Гости", "2 възрастни"], ["Стая „Пирин“", "2 нощувки · 190 €"]], cta: "Резервирай — най-ниска цена" },
      },
      badges: ["Най-ниска цена при директна резервация", "Безплатна отмяна до 7 дни", "Домашна закуска включена", "Безплатен паркинг и ски гардероб"],
      servicesTitle: "Стаи <em>и удобства</em>",
      servicesLede: "Всяка стая е с дърво, вълна и изглед към планината. Цените са на нощувка за двама, със закуска.",
      services: [
        { t: "Стая „Пирин“", d: "24 м², спалня 180 см, балкон на юг към върховете. Най-търсената.", p: "95 € / нощ" },
        { t: "Стая „Ела“", d: "20 м², спалня 160 см, тих двор. Идеална за двама след ски.", p: "80 € / нощ" },
        { t: "Апартамент „Вихрен“", d: "42 м², две стаи, кухненски бокс, камина. До 4 души.", p: "160 € / нощ" },
        { t: "Спа терасата", d: "Сауна, джакузи на открито и зона за отдих с чай — за гости, безплатно." },
        { t: "Закуска", d: "Домашна, от 07:30 до 10:30: баница, мед от Пирин, яйца от съседа, кафе от Банско." },
        { t: "Ски и планина", d: "Гардероб за ски, сушилня за обувки, водач за преходи през лятото." },
      ],
      about: {
        eyebrow: "За къщата", title: "Семейна къща, <em>не верига</em>",
        p: ["Silver Fir е домът на Мария и Стоян от 2012 г. — осем стаи, обзаведени с местно дърво и вълна, и правило: не повече от 20 гости наведнъж, за да е тихо.", "Резервирате директно и плащате най-ниската цена: не даваме на платформите 15%, а ги връщаме на вас — по-евтина стая и безплатна отмяна."],
        facts: [{ n: "8", l: "стаи" }, { n: "400", l: "м до лифта" }, { n: "9,6", l: "оценка от гости" }, { n: "0%", l: "комисиона при директна резервация" }],
      },
      list: { title: "Цени <em>по сезони</em>", lede: "На нощувка за двама, със закуска и ДДС. Деца до 6 г. — безплатно.", groups: [
        { t: "Зима (дек – мар)", items: [["Стая „Ела“", "80 €"], ["Стая „Пирин“", "95 €"], ["Апартамент „Вихрен“", "160 €"], ["Ски пакет 3 нощи + лифт карта", "от 420 €"]] },
        { t: "Лято (юни – сеп)", items: [["Стая „Ела“", "60 €"], ["Стая „Пирин“", "72 €"], ["Апартамент „Вихрен“", "120 €"], ["Планински уикенд с водач", "от 190 €"]] },
      ] },
      reviews: [
        { name: "Анна и Петър, София", text: "Изглед, закуска, джакузи под снега. Резервирахме директно и излезе по-евтино от сайтовете.", stars: 5 },
        { name: "Familie Weber, München", text: "Stille, Holz, Berge. Genau das, was wir gesucht haben. Wir kommen wieder.", stars: 5 },
        { name: "Марко, Милано", text: "Ски гардеробът и сушилнята за обувки са дребни неща, които правят разликата. Домакините — злато.", stars: 5 },
      ],
      faq: [
        { q: "Защо да резервирам директно?", a: "Защото получавате най-ниската цена, безплатна отмяна до 7 дни преди и приоритет при избор на стая — без комисионата на платформите." },
        { q: "Има ли паркинг?", a: "Да, безплатен, охраняем, до къщата. През зимата почистваме снега сутрин." },
        { q: "Допускат ли се домашни любимци?", a: "Да, в стая „Ела“ и апартамент „Вихрен“ — 10 € на нощ." },
        { q: "Как се плаща?", a: "30% депозит с карта при резервация, остатъкът на място. Фактура за фирми." },
        { q: "Колко е далече лифтът?", a: "400 метра — 5 минути пеша, или безплатен трансфер с нашия бус в 08:30 и 09:15." },
      ],
      contact: { eyebrow: "Контакт", title: "Питайте за <em>свободни дати</em>", lede: "Отговаряме до час в работно време на рецепцията." },
    },
    en: {
      name: "Silver Fir", category: "Hotel / guest house", city: "Bansko",
      metaTitle: "Silver Fir · Guest House Bansko · Demo website",
      metaDesc: "Demo website for a hotel and guest house: rooms with prices, direct commission-free booking, breakfast, spa, reviews. By Carbon Stealth.",
      address: "112 Pirin St, 2770 Bansko", phone: "+359 88 000 0006", email: "stay@silverfir.example",
      hours: ["Reception: 07:00 – 23:00", "Check-in from 15:00", "Check-out by 11:00"],
      hero: {
        eyebrow: "Guest house · Bansko · 400 m from the gondola",
        title: "The mountain <em>through your window.</em> Silence included.",
        lede: "Eight rooms facing Pirin, home-made breakfast, sauna and a hot tub on the terrace. Book direct — no platform commission, the lowest price and free cancellation up to 7 days.",
        cta: "Check availability", cta2: "See the rooms",
        widget: { kind: "booking", title: "Direct booking", rows: [["Check-in", "Fri, 20 Dec"], ["Check-out", "Sun, 22 Dec"], ["Guests", "2 adults"], ["“Pirin” room", "2 nights · €190"]], cta: "Book — lowest price" },
      },
      badges: ["Lowest price when booking direct", "Free cancellation up to 7 days", "Home-made breakfast included", "Free parking and ski room"],
      servicesTitle: "Rooms <em>and comforts</em>",
      servicesLede: "Every room is wood, wool and a mountain view. Prices are per night for two, breakfast included.",
      services: [
        { t: "“Pirin” room", d: "24 m², 180 cm bed, south balcony facing the peaks. The most requested.", p: "€95 / night" },
        { t: "“Fir” room", d: "20 m², 160 cm bed, quiet courtyard. Perfect for two after skiing.", p: "€80 / night" },
        { t: "“Vihren” apartment", d: "42 m², two rooms, kitchenette, fireplace. Up to 4 people.", p: "€160 / night" },
        { t: "Spa terrace", d: "Sauna, outdoor hot tub and a tea lounge — free for guests." },
        { t: "Breakfast", d: "Home-made, 07:30 to 10:30: banitsa, Pirin honey, eggs from the neighbour, local coffee." },
        { t: "Ski and mountain", d: "Ski room, boot dryer, hiking guide in summer." },
      ],
      about: {
        eyebrow: "About the house", title: "A family house, <em>not a chain</em>",
        p: ["Silver Fir has been Maria and Stoyan's home since 2012 — eight rooms furnished with local wood and wool, and one rule: no more than 20 guests at once, so it stays quiet.", "Book direct and pay the lowest price: we do not give platforms 15%, we give it back to you — a cheaper room and free cancellation."],
        facts: [{ n: "8", l: "rooms" }, { n: "400", l: "m to the gondola" }, { n: "9.6", l: "guest rating" }, { n: "0%", l: "commission when booking direct" }],
      },
      list: { title: "Prices <em>by season</em>", lede: "Per night for two, breakfast and VAT included. Children under 6 stay free.", groups: [
        { t: "Winter (Dec – Mar)", items: [["“Fir” room", "€80"], ["“Pirin” room", "€95"], ["“Vihren” apartment", "€160"], ["Ski package 3 nights + lift pass", "from €420"]] },
        { t: "Summer (Jun – Sep)", items: [["“Fir” room", "€60"], ["“Pirin” room", "€72"], ["“Vihren” apartment", "€120"], ["Guided mountain weekend", "from €190"]] },
      ] },
      reviews: [
        { name: "Anna and Peter, Sofia", text: "The view, the breakfast, the hot tub under the snow. We booked direct and it was cheaper than the booking sites.", stars: 5 },
        { name: "Familie Weber, München", text: "Stille, Holz, Berge. Genau das, was wir gesucht haben. Wir kommen wieder.", stars: 5 },
        { name: "Marco, Milan", text: "The ski room and boot dryer are small things that make the difference. The hosts are gold.", stars: 5 },
      ],
      faq: [
        { q: "Why book direct?", a: "Because you get the lowest price, free cancellation up to 7 days before and first pick of rooms — without the platform commission." },
        { q: "Is there parking?", a: "Yes, free, guarded, next to the house. In winter we clear the snow every morning." },
        { q: "Are pets allowed?", a: "Yes, in the “Fir” room and the “Vihren” apartment — €10 per night." },
        { q: "How do I pay?", a: "30% deposit by card at booking, the rest on site. Invoices for companies." },
        { q: "How far is the gondola?", a: "400 metres — a 5-minute walk, or our free shuttle at 08:30 and 09:15." },
      ],
      contact: { eyebrow: "Contact", title: "Ask about <em>available dates</em>", lede: "We reply within the hour during reception hours." },
    },
    it: {
      name: "Silver Fir", category: "Hotel / casa vacanze", city: "Cortina d'Ampezzo",
      metaTitle: "Silver Fir · Casa vacanze Cortina · Sito demo",
      metaDesc: "Sito demo per hotel e casa vacanze: camere con prezzi, prenotazione diretta senza commissioni, colazione, spa, recensioni. Di Carbon Stealth.",
      address: "Via Roma 112, 32043 Cortina d'Ampezzo", phone: "+39 0436 000 006", email: "stay@silverfir.example",
      hours: ["Reception: 07:00 – 23:00", "Check-in dalle 15:00", "Check-out entro le 11:00"],
      hero: {
        eyebrow: "Casa vacanze · Cortina · 400 m dagli impianti",
        title: "La montagna <em>dalla finestra.</em> Il silenzio — incluso.",
        lede: "Otto camere con vista sulle Dolomiti, colazione fatta in casa, sauna e vasca idromassaggio in terrazza. Prenoti direttamente — senza commissioni ai portali, al prezzo più basso e con cancellazione gratuita fino a 7 giorni.",
        cta: "Verifica disponibilità", cta2: "Vedi le camere",
        widget: { kind: "booking", title: "Prenotazione diretta", rows: [["Arrivo", "Ven, 20 dic"], ["Partenza", "Dom, 22 dic"], ["Ospiti", "2 adulti"], ["Camera «Tofane»", "2 notti · 190 €"]], cta: "Prenota — prezzo più basso" },
      },
      badges: ["Prezzo più basso prenotando direttamente", "Cancellazione gratuita fino a 7 giorni", "Colazione fatta in casa inclusa", "Parcheggio e deposito sci gratuiti"],
      servicesTitle: "Camere <em>e comfort</em>",
      servicesLede: "Ogni camera è legno, lana e vista sulle montagne. Prezzi a notte per due, colazione inclusa.",
      services: [
        { t: "Camera «Tofane»", d: "24 m², letto 180 cm, balcone a sud verso le cime. La più richiesta.", p: "95 € / notte" },
        { t: "Camera «Abete»", d: "20 m², letto 160 cm, cortile silenzioso. Perfetta per due dopo lo sci.", p: "80 € / notte" },
        { t: "Appartamento «Cristallo»", d: "42 m², due stanze, angolo cottura, camino. Fino a 4 persone.", p: "160 € / notte" },
        { t: "Terrazza spa", d: "Sauna, vasca idromassaggio all'aperto e angolo tè — gratuiti per gli ospiti." },
        { t: "Colazione", d: "Fatta in casa, dalle 07:30 alle 10:30: strudel, miele di montagna, uova del vicino, caffè locale." },
        { t: "Sci e montagna", d: "Deposito sci, asciugascarponi, guida per le escursioni in estate." },
      ],
      about: {
        eyebrow: "La casa", title: "Una casa di famiglia, <em>non una catena</em>",
        p: ["Silver Fir è la casa di Maria e Stefano dal 2012 — otto camere arredate con legno e lana locali, e una regola: mai più di 20 ospiti alla volta, perché resti silenziosa.", "Prenoti direttamente e paghi il prezzo più basso: il 15% che non diamo ai portali lo restituiamo a te — camera più economica e cancellazione gratuita."],
        facts: [{ n: "8", l: "camere" }, { n: "400", l: "m dagli impianti" }, { n: "9,6", l: "voto degli ospiti" }, { n: "0%", l: "commissioni prenotando direttamente" }],
      },
      list: { title: "Prezzi <em>per stagione</em>", lede: "A notte per due, colazione e IVA incluse. Bambini fino a 6 anni gratis.", groups: [
        { t: "Inverno (dic – mar)", items: [["Camera «Abete»", "80 €"], ["Camera «Tofane»", "95 €"], ["Appartamento «Cristallo»", "160 €"], ["Pacchetto sci 3 notti + skipass", "da 420 €"]] },
        { t: "Estate (giu – set)", items: [["Camera «Abete»", "60 €"], ["Camera «Tofane»", "72 €"], ["Appartamento «Cristallo»", "120 €"], ["Weekend in montagna con guida", "da 190 €"]] },
      ] },
      reviews: [
        { name: "Anna e Pietro, Milano", text: "Vista, colazione, idromassaggio sotto la neve. Abbiamo prenotato direttamente ed è costato meno dei portali.", stars: 5 },
        { name: "Familie Weber, München", text: "Stille, Holz, Berge. Genau das, was wir gesucht haben. Wir kommen wieder.", stars: 5 },
        { name: "Marco, Bologna", text: "Il deposito sci e l'asciugascarponi sono piccole cose che fanno la differenza. I padroni di casa — oro.", stars: 5 },
      ],
      faq: [
        { q: "Perché prenotare direttamente?", a: "Perché ottieni il prezzo più basso, cancellazione gratuita fino a 7 giorni prima e priorità nella scelta della camera — senza la commissione dei portali." },
        { q: "C'è parcheggio?", a: "Sì, gratuito, custodito, accanto alla casa. In inverno spaliamo la neve ogni mattina." },
        { q: "Gli animali sono ammessi?", a: "Sì, nella camera «Abete» e nell'appartamento «Cristallo» — 10 € a notte." },
        { q: "Come si paga?", a: "Acconto del 30% con carta alla prenotazione, saldo in loco. Fattura per le aziende." },
        { q: "Quanto distano gli impianti?", a: "400 metri — 5 minuti a piedi, oppure la nostra navetta gratuita alle 08:30 e 09:15." },
      ],
      contact: { eyebrow: "Contatti", title: "Chiedi <em>le date disponibili</em>", lede: "Rispondiamo entro un'ora negli orari della reception." },
    },
  },
};
