// imoti.mjs — демо „Casa Nova": агенция за недвижими имоти. Светла тема в бежово и тъмнозелено, серифен дисплей,
// hero с фасада, заявка за безплатна оценка (consult), избрани имоти като „услуги" с цени, стъпки при покупка.
export default {
  id: "imoti",
  slug: { bg: "agencia-za-imoti", en: "real-estate-agency", it: "agenzia-immobiliare" },
  icon: "key",
  schemaType: "RealEstateAgent",
  theme: {
    mode: "light", heroStyle: "editorial", pattern: "grid", radius: "4px",
    fonts: ["DM+Serif+Display", "Inter:wght@400;500;600"],
    display: "'DM Serif Display', Georgia, serif", body: "Inter, system-ui, sans-serif",
    bg: "#f7f4ee", surface: "#ffffff", surface2: "#ede7dc", text: "#1f2a24", muted: "#66716a",
    accent: "#1f5c47", accent2: "#3b8a6d", onAccent: "#ffffff", line: "rgba(31,42,36,.13)",
    word: "CASA",
  },
  keywords: {
    bg: ["сайт за агенция за имоти", "сайт за недвижими имоти демо", "обяви за имоти онлайн", "оценка на имот онлайн", "изработка на сайт за брокер"],
    en: ["real estate agency website", "real estate website demo", "property listings website", "free property valuation", "estate agent web design"],
    it: ["sito agenzia immobiliare", "sito immobiliare demo", "annunci immobili online", "valutazione immobile gratuita", "realizzazione sito agenzia"],
  },
  t: {
    bg: {
      name: "Casa Nova", category: "Агенция за имоти", city: "Варна",
      metaTitle: "Casa Nova · Агенция за имоти Варна · Демо сайт",
      metaDesc: "Демо сайт за агенция за недвижими имоти: избрани имоти с цени, безплатна оценка, стъпки при покупка, отзиви, FAQ. От Carbon Stealth.",
      address: "ул. Сливница 8, 9000 Варна", phone: "+359 52 000 0014", email: "office@casanova.example",
      hours: ["Пон – Пет: 09:00 – 18:30", "Събота: 10:00 – 14:00", "Огледи: и в неделя по уговорка"],
      hero: {
        eyebrow: "Продажби · наеми · управление · Варна и морето",
        title: "Имотът, който <em>наистина ще ви хареса.</em>",
        lede: "Шестима брокери, 340 имота в портфолиото и правило, което ни струва сделки, но пести нерви: показваме само това, което сами сме огледали. Оценката на вашия имот е безплатна и е готова за 48 часа.",
        cta: "Безплатна оценка", cta2: "Избрани имоти",
        proof: "★ 4,9 в Google · 1 100+ сделки · Средно 34 дни до продажба",
        widget: { kind: "consult", title: "Безплатна оценка за 48 часа", rows: ["Оглед на място от брокер, не от таблица", "Сравнение с реални сделки в квартала", "Писмена оценка с препоръчана цена", "Без ангажимент да продавате с нас"], cta: "Заяви оценка" },
      },
      badges: ["Само огледани имоти", "Правна проверка включена", "Виртуални огледи", "Комисион 2,5% при продажба"],
      offer: { tag: "За продавачи", title: "Без комисион, ако не продадем за 90 дни", text: "Подписвате ексклузивен договор за 90 дни. Ако имотът не е продаден на договорената цена в срока, не дължите нищо — нито за снимките, нито за рекламата.", cta: "Заяви оценка", note: "Условията са примерни за демото." },
      servicesTitle: "Избрани <em>имоти</em>",
      servicesLede: "В реалния сайт тук са обявите с филтри, карта и виртуален оглед. Шест примера със снимки от галерията.",
      services: [
        { t: "Къща с двор · Виница", d: "180 м², 4 стаи, 600 м² двор, реновирана 2023. Морето на 10 минути.", p: "289 000 €" },
        { t: "Тристаен · Гръцка махала", d: "96 м², ет. 3, тухла, южно изложение, гараж. Готов за нанасяне.", p: "168 000 €" },
        { t: "Двустаен · Бриз", d: "68 м², ново строителство, акт 16, паркомясто, морска панорама.", p: "129 000 €" },
        { t: "Вила с басейн · Кранево", d: "240 м², 3 спални, басейн 8×4, 1 200 м² двор. Идеална за отдаване.", p: "395 000 €" },
        { t: "Мезонет · Център", d: "142 м², две нива, камина, тераса 30 м². Сграда от 1930 г., санирана.", p: "245 000 €" },
        { t: "Офис · Бизнес парк", d: "85 м², отворен план, 2 паркоместа, наем с включена поддръжка.", p: "1 100 € / мес." },
      ],
      about: {
        eyebrow: "За агенцията", title: "Шест брокери, <em>един квартал всеки</em>",
        p: ["Casa Nova работи от 2012 г. Всеки брокер отговаря за един район на Варна и го познава по улици — знае кой блок е с нов покрив и в кой двор има съседи, които свирят на барабани.", "Правната проверка на имота е включена в комисиона, а не „допълнителна услуга“. Затова сделките ни минават средно за 34 дни и нито една не е върната от нотариус."],
        facts: [{ n: "6", l: "брокери" }, { n: "340", l: "имота" }, { n: "1 100+", l: "сделки" }, { n: "34", l: "дни средно до продажба" }],
      },
      steps: { title: "Как <em>купувате с нас</em>", items: [
        { t: "Разговор", d: "20 минути: бюджет, район, срок. Казваме честно какво може да се купи с парите ви." },
        { t: "Подбор и огледи", d: "Не 30 обяви, а 5 огледани имота. Огледите са за един ден, по маршрут." },
        { t: "Проверка и оферта", d: "Правна проверка на имота, преговори за цената, предварителен договор." },
        { t: "Нотариус и ключове", d: "Организираме нотариуса, банката и прехвърлянето на партидите. Вие носите само лична карта." },
      ] },
      reviews: [
        { name: "Семейство Иванови", text: "Търсехме къща 8 месеца с други агенции. Casa Nova ни показа 4 имота за един ден — купихме третия.", stars: 5 },
        { name: "Марио Р. (Италия)", text: "Купих апартамент във Варна дистанционно: виртуален оглед, правна проверка на италиански, пълномощно. Безупречно.", stars: 5 },
        { name: "Ел. С.", text: "Продадоха апартамента ми за 27 дни на цената от оценката. Снимките бяха толкова хубави, че почти се отказах.", stars: 5 },
      ],
      faq: [
        { q: "Колко е комисионът?", a: "2,5% от цената при продажба, плаща се при нотариуса. За купувачи — 2,5%. При наем — половин месечен наем." },
        { q: "Безплатна ли е оценката?", a: "Да, и не ви задължава да продавате с нас. Брокер идва на място и до 48 часа получавате писмена оценка." },
        { q: "Правите ли правна проверка?", a: "Да, за всеки имот, който предлагаме — тежести, собственост, строителни книжа. Включена е в комисиона." },
        { q: "Мога ли да купя дистанционно?", a: "Да. Виртуален оглед на живо, документи на английски или италиански, сделка с пълномощно. Правили сме го над 60 пъти." },
        { q: "Управлявате ли имоти под наем?", a: "Да — намиране на наематели, договори, събиране на наема, ремонти. 8% от наема месечно." },
      ],
      contact: { eyebrow: "Контакт", title: "Кажете какво търсите <em>или какво продавате</em>", lede: "Отговаряме до 2 часа в работно време, огледи и в неделя." },
    },
    en: {
      name: "Casa Nova", category: "Real estate agency", city: "Varna",
      metaTitle: "Casa Nova · Real Estate Agency Varna · Demo website",
      metaDesc: "Demo website for a real estate agency: selected properties with prices, free valuation, buying steps, reviews, FAQ. By Carbon Stealth.",
      address: "8 Slivnitsa St, 9000 Varna", phone: "+359 52 000 0014", email: "office@casanova.example",
      hours: ["Mon – Fri: 09:00 – 18:30", "Saturday: 10:00 – 14:00", "Viewings: Sundays by arrangement"],
      hero: {
        eyebrow: "Sales · rentals · management · Varna and the coast",
        title: "The property you will <em>actually like.</em>",
        lede: "Six agents, 340 properties and a rule that costs us deals but saves nerves: we only show what we have viewed ourselves. Your property valuation is free and ready in 48 hours.",
        cta: "Free valuation", cta2: "Selected properties",
        proof: "★ 4.9 on Google · 1,100+ deals · 34 days on average to sell",
        widget: { kind: "consult", title: "Free valuation in 48 hours", rows: ["On-site visit by an agent, not a spreadsheet", "Comparison with real deals in the area", "Written valuation with a recommended price", "No obligation to sell with us"], cta: "Request a valuation" },
      },
      badges: ["Only viewed properties", "Legal check included", "Virtual viewings", "2.5% commission on sale"],
      offer: { tag: "For sellers", title: "No commission if we don't sell in 90 days", text: "You sign a 90-day exclusive agreement. If the property is not sold at the agreed price within the term, you owe nothing — not for the photos, not for the advertising.", cta: "Request a valuation", note: "Terms are examples for the demo." },
      servicesTitle: "Selected <em>properties</em>",
      servicesLede: "On the real site this is the listings page with filters, a map and virtual tours. Six examples with photos from the gallery.",
      services: [
        { t: "House with garden · Vinitsa", d: "180 m², 4 rooms, 600 m² garden, renovated 2023. The sea 10 minutes away.", p: "€289,000" },
        { t: "3-room flat · Greek quarter", d: "96 m², 3rd floor, brick, south-facing, garage. Move-in ready.", p: "€168,000" },
        { t: "2-room flat · Briz", d: "68 m², new build, occupancy permit, parking space, sea view.", p: "€129,000" },
        { t: "Villa with pool · Kranevo", d: "240 m², 3 bedrooms, 8×4 pool, 1,200 m² garden. Ideal for letting.", p: "€395,000" },
        { t: "Maisonette · Centre", d: "142 m², two levels, fireplace, 30 m² terrace. 1930 building, renovated.", p: "€245,000" },
        { t: "Office · Business park", d: "85 m², open plan, 2 parking spaces, rent with maintenance included.", p: "€1,100 / month" },
      ],
      about: {
        eyebrow: "About the agency", title: "Six agents, <em>one district each</em>",
        p: ["Casa Nova has been working since 2012. Each agent is responsible for one district of Varna and knows it street by street — which block has a new roof and which yard has neighbours who play the drums.", "The legal check is included in the commission, not an “extra service”. That is why our deals close in 34 days on average and not one has been returned by a notary."],
        facts: [{ n: "6", l: "agents" }, { n: "340", l: "properties" }, { n: "1,100+", l: "deals" }, { n: "34", l: "days on average to sell" }],
      },
      steps: { title: "How <em>you buy with us</em>", items: [
        { t: "A conversation", d: "20 minutes: budget, area, timeline. We tell you honestly what your money can buy." },
        { t: "Shortlist and viewings", d: "Not 30 listings but 5 viewed properties. Viewings in one day, by route." },
        { t: "Check and offer", d: "Legal check of the property, price negotiation, preliminary contract." },
        { t: "Notary and keys", d: "We organise the notary, the bank and the utility transfers. You bring only your ID." },
      ] },
      reviews: [
        { name: "The Ivanov family", text: "We looked for a house for 8 months with other agencies. Casa Nova showed us 4 properties in one day — we bought the third.", stars: 5 },
        { name: "Mario R. (Italy)", text: "Bought a flat in Varna remotely: live virtual viewing, legal check in Italian, power of attorney. Flawless.", stars: 5 },
        { name: "E. S.", text: "They sold my flat in 27 days at the valuation price. The photos were so good I almost changed my mind.", stars: 5 },
      ],
      faq: [
        { q: "What is the commission?", a: "2.5% of the price on sale, paid at the notary. For buyers — 2.5%. For rentals — half a month's rent." },
        { q: "Is the valuation free?", a: "Yes, and it does not oblige you to sell with us. An agent visits and within 48 hours you get a written valuation." },
        { q: "Do you do a legal check?", a: "Yes, for every property we offer — encumbrances, ownership, building documents. It is included in the commission." },
        { q: "Can I buy remotely?", a: "Yes. Live virtual viewing, documents in English or Italian, a deal by power of attorney. We have done it over 60 times." },
        { q: "Do you manage rental properties?", a: "Yes — finding tenants, contracts, rent collection, repairs. 8% of the monthly rent." },
      ],
      contact: { eyebrow: "Contact", title: "Tell us what you are looking for <em>or what you are selling</em>", lede: "We reply within 2 hours during business hours, viewings on Sundays too." },
    },
    it: {
      name: "Casa Nova", category: "Agenzia immobiliare", city: "Rimini",
      metaTitle: "Casa Nova · Agenzia immobiliare Rimini · Sito demo",
      metaDesc: "Sito demo per agenzia immobiliare: immobili selezionati con prezzi, valutazione gratuita, passi per l'acquisto, recensioni, FAQ. Di Carbon Stealth.",
      address: "Via Slivnitsa 8, 47921 Rimini", phone: "+39 0541 000 0014", email: "office@casanova.example",
      hours: ["Lun – Ven: 09:00 – 18:30", "Sabato: 10:00 – 14:00", "Visite: anche la domenica su appuntamento"],
      hero: {
        eyebrow: "Vendite · affitti · gestione · Rimini e la riviera",
        title: "L'immobile che <em>ti piacerà davvero.</em>",
        lede: "Sei agenti, 340 immobili in portafoglio e una regola che ci costa affari ma risparmia nervi: mostriamo solo ciò che abbiamo visitato noi. La valutazione del tuo immobile è gratuita e pronta in 48 ore.",
        cta: "Valutazione gratuita", cta2: "Immobili selezionati",
        proof: "★ 4,9 su Google · 1.100+ compravendite · 34 giorni in media per vendere",
        widget: { kind: "consult", title: "Valutazione gratuita in 48 ore", rows: ["Sopralluogo di un agente, non un foglio di calcolo", "Confronto con compravendite reali della zona", "Valutazione scritta con prezzo consigliato", "Nessun obbligo di vendere con noi"], cta: "Richiedi la valutazione" },
      },
      badges: ["Solo immobili visitati", "Verifica legale inclusa", "Visite virtuali", "Provvigione 2,5% sulla vendita"],
      offer: { tag: "Per chi vende", title: "Nessuna provvigione se non vendiamo in 90 giorni", text: "Firmi un incarico in esclusiva di 90 giorni. Se l'immobile non è venduto al prezzo concordato entro il termine, non devi nulla — né per le foto, né per la pubblicità.", cta: "Richiedi la valutazione", note: "Le condizioni sono esempi per la demo." },
      servicesTitle: "Immobili <em>selezionati</em>",
      servicesLede: "Nel sito reale qui ci sono gli annunci con filtri, mappa e tour virtuale. Sei esempi con le foto della galleria.",
      services: [
        { t: "Villetta con giardino · Viserba", d: "180 m², 4 stanze, 600 m² di giardino, ristrutturata nel 2023. Il mare a 10 minuti.", p: "289.000 €" },
        { t: "Trilocale · Centro storico", d: "96 m², 3° piano, mattoni, esposizione sud, garage. Pronto da abitare.", p: "168.000 €" },
        { t: "Bilocale · Marina Centro", d: "68 m², nuova costruzione, agibilità, posto auto, vista mare.", p: "129.000 €" },
        { t: "Villa con piscina · Riccione", d: "240 m², 3 camere, piscina 8×4, 1.200 m² di giardino. Ideale da affittare.", p: "395.000 €" },
        { t: "Attico su due livelli · Centro", d: "142 m², due livelli, camino, terrazza 30 m². Palazzo del 1930, restaurato.", p: "245.000 €" },
        { t: "Ufficio · Business park", d: "85 m², open space, 2 posti auto, affitto con manutenzione inclusa.", p: "1.100 € / mese" },
      ],
      about: {
        eyebrow: "L'agenzia", title: "Sei agenti, <em>un quartiere ciascuno</em>",
        p: ["Casa Nova lavora dal 2012. Ogni agente segue un quartiere di Rimini e lo conosce via per via — quale palazzo ha il tetto nuovo e in quale cortile ci sono vicini che suonano la batteria.", "La verifica legale dell'immobile è inclusa nella provvigione, non è un «servizio extra». Per questo le nostre compravendite si chiudono in 34 giorni in media e nessuna è mai stata respinta dal notaio."],
        facts: [{ n: "6", l: "agenti" }, { n: "340", l: "immobili" }, { n: "1.100+", l: "compravendite" }, { n: "34", l: "giorni in media per vendere" }],
      },
      steps: { title: "Come <em>si compra con noi</em>", items: [
        { t: "Un colloquio", d: "20 minuti: budget, zona, tempi. Ti diciamo onestamente cosa si può comprare con i tuoi soldi." },
        { t: "Selezione e visite", d: "Non 30 annunci ma 5 immobili visitati. Le visite in un giorno, per itinerario." },
        { t: "Verifica e proposta", d: "Verifica legale dell'immobile, trattativa sul prezzo, compromesso." },
        { t: "Notaio e chiavi", d: "Organizziamo notaio, banca e volture delle utenze. Tu porti solo la carta d'identità." },
      ] },
      reviews: [
        { name: "Famiglia Rossi", text: "Cercavamo casa da 8 mesi con altre agenzie. Casa Nova ci ha mostrato 4 immobili in un giorno — abbiamo comprato il terzo.", stars: 5 },
        { name: "Mario R.", text: "Ho comprato un appartamento a distanza: visita virtuale dal vivo, verifica legale, procura. Impeccabile.", stars: 5 },
        { name: "E. S.", text: "Hanno venduto il mio appartamento in 27 giorni al prezzo della valutazione. Le foto erano così belle che quasi ci ripensavo.", stars: 5 },
      ],
      faq: [
        { q: "Quanto è la provvigione?", a: "2,5% del prezzo sulla vendita, pagata dal notaio. Per chi compra — 2,5%. Per gli affitti — mezza mensilità." },
        { q: "La valutazione è gratuita?", a: "Sì, e non ti obbliga a vendere con noi. Un agente viene sul posto ed entro 48 ore ricevi una valutazione scritta." },
        { q: "Fate la verifica legale?", a: "Sì, per ogni immobile che proponiamo — ipoteche, proprietà, conformità urbanistica. È inclusa nella provvigione." },
        { q: "Posso comprare a distanza?", a: "Sì. Visita virtuale dal vivo, documenti in inglese o bulgaro, compravendita per procura. L'abbiamo fatto oltre 60 volte." },
        { q: "Gestite immobili in affitto?", a: "Sì — ricerca inquilini, contratti, incasso del canone, riparazioni. 8% del canone mensile." },
      ],
      contact: { eyebrow: "Contatti", title: "Dicci cosa cerchi <em>o cosa vendi</em>", lede: "Rispondiamo entro 2 ore in orario di lavoro, visite anche la domenica." },
    },
  },
};
