// klinika.mjs — демо „Clinica Vita": медицински и дентален център. Светла тема в тил и бяло, hero със снимка на
// приемната, онлайн записване (booking), ценоразпис, лекари-без-имена (специалности), FAQ за здравна каса.
export default {
  id: "klinika",
  slug: { bg: "medicinski-centar", en: "medical-clinic", it: "poliambulatorio" },
  icon: "tooth",
  schemaType: "MedicalClinic",
  theme: {
    mode: "light", heroStyle: "split", pattern: "dots", radius: "14px",
    fonts: ["Manrope:wght@500;700;800", "DM+Sans:wght@400;500;600"],
    display: "Manrope, system-ui, sans-serif", body: "'DM Sans', system-ui, sans-serif",
    bg: "#f6fbfa", surface: "#ffffff", surface2: "#e6f3f0", text: "#10302b", muted: "#5f7a75",
    accent: "#0f8f80", accent2: "#3fb8a8", onAccent: "#ffffff", line: "rgba(16,48,43,.12)",
    word: "VITA",
  },
  keywords: {
    bg: ["сайт за медицински център", "сайт за дентална клиника", "онлайн записване при лекар", "сайт за клиника демо", "изработка на сайт за лекар"],
    en: ["medical clinic website", "dental clinic website demo", "online doctor booking", "clinic website design", "healthcare website"],
    it: ["sito poliambulatorio", "sito studio dentistico demo", "prenotazione online medico", "sito clinica", "realizzazione sito medico"],
  },
  t: {
    bg: {
      name: "Clinica Vita", category: "Медицински център", city: "Пловдив",
      metaTitle: "Clinica Vita · Медицински център Пловдив · Демо сайт",
      metaDesc: "Демо сайт за медицински и дентален център: специалности, онлайн записване, ценоразпис, здравна каса, отзиви, FAQ. От Carbon Stealth.",
      address: "бул. Васил Априлов 12, 4000 Пловдив", phone: "+359 32 000 0012", email: "info@clinicavita.example",
      hours: ["Пон – Пет: 08:00 – 20:00", "Събота: 09:00 – 14:00", "Спешен дентален кабинет: 24/7"],
      hero: {
        eyebrow: "Медицински и дентален център · Пловдив · от 2011",
        title: "Лекар за 48 часа, <em>не за три седмици.</em>",
        lede: "Дванадесет специалности, собствена лаборатория и дентално отделение под един покрив. Записвате се онлайн, получавате SMS потвърждение и резултатите ви са в телефона на следващия ден.",
        cta: "Запази час", cta2: "Ценоразпис",
        proof: "★ 4,8 в Google · 38 000 пациенти · Час до 48 часа при 9 от 10 специалности",
        widget: { kind: "booking", title: "Запази час онлайн", rows: [["Специалност", "Кардиология"], ["Лекар", "Първи свободен"], ["Дата", "Сряда, 10:30"], ["Продължителност", "30 мин · 45 €"]], cta: "Потвърди часа", done: "Демо: в реалния сайт получавате SMS и имейл с потвърждение." },
      },
      badges: ["Договор със здравната каса", "Собствена лаборатория", "Резултати онлайн", "Паркинг за пациенти"],
      offer: { tag: "Профилактика", title: "Годишен профилактичен пакет за 89 € — 6 изследвания + преглед", text: "Кръвна картина, липиден профил, кръвна захар, щитовидна жлеза, ЕКГ и преглед при интернист. Резултати до 24 часа, безплатно повторно посещение за разчитане.", cta: "Запиши пакета", note: "Цените са примерни за демото." },
      servicesTitle: "Специалности <em>и услуги</em>",
      servicesLede: "Лекарите са на щат, не на консултация веднъж месечно. Затова часът е до 48 часа.",
      services: [
        { t: "Обща и вътрешна медицина", d: "Профилактични прегледи, хронични заболявания, направления по здравна каса.", p: "от 35 €" },
        { t: "Кардиология", d: "ЕКГ, ехокардиография, холтер, консултация за кръвно налягане.", p: "от 45 €" },
        { t: "Дентална медицина", d: "Профилактика, лечение, естетика, импланти. Спешен кабинет 24/7.", p: "от 25 €" },
        { t: "Педиатрия", d: "Детски прегледи, имунизации, консултации за родители — отделна чакалня.", p: "от 35 €" },
        { t: "Образна диагностика", d: "Ехография, рентген, мамография — резултат на място.", p: "от 30 €" },
        { t: "Лаборатория", d: "Над 300 изследвания, резултати до 24 часа в профила ви.", p: "от 5 €" },
      ],
      about: {
        eyebrow: "За центъра", title: "Един адрес, <em>цялата грижа</em>",
        p: ["Clinica Vita отвори през 2011 г. с три кабинета. Днес сме 24 лекари в 12 специалности, лаборатория и дентално отделение на 1 400 м² — но пациентът все още говори с човек, не с гласово меню.", "Работим със здравната каса и с всички основни застрахователи. Резултатите и епикризите са в личния ви профил, достъпни и за лекуващия ви лекар, ако решите."],
        facts: [{ n: "24", l: "лекари" }, { n: "12", l: "специалности" }, { n: "38 000", l: "пациенти" }, { n: "48 ч", l: "до първи час" }],
      },
      list: { title: "Ценоразпис", lede: "Крайни цени. По здравна каса — само потребителската такса.", groups: [
        { t: "Прегледи", items: [["Първичен преглед при специалист", "45 €"], ["Вторичен преглед", "25 €"], ["Преглед по здравна каза (такса)", "1,50 €"], ["Домашно посещение", "от 60 €"]] },
        { t: "Дентална медицина", items: [["Профилактичен преглед", "25 €"], ["Почистване на зъбен камък", "40 €"], ["Фотополимерна пломба", "от 45 €"], ["Имплант (без корона)", "от 550 €"]] },
      ] },
      reviews: [
        { name: "Десислава К.", text: "Записах се в понеделник вечер, във вторник в 10:30 бях при кардиолога. Резултатите от кръвта — в телефона на другия ден.", stars: 5 },
        { name: "Георги М.", text: "Детето със зъбобол в събота вечер. Спешният кабинет отвори за 20 минути и никой не ни гледаше накриво.", stars: 5 },
        { name: "Мария Т.", text: "Профилактичният пакет хвана проблем с щитовидната жлеза, за който нямах представа. Лекарката ми обясни всичко без да бърза.", stars: 5 },
      ],
      faq: [
        { q: "Работите ли със здравната каса?", a: "Да. За преглед по направление плащате само потребителската такса. Носете направлението или кажете номера му при записване." },
        { q: "Как получавам резултатите?", a: "В личния ви профил и по имейл до 24 часа за повечето изследвания. На хартия — на рецепция по всяко време." },
        { q: "Мога ли да избера конкретен лекар?", a: "Да, при записването. Ако искате най-бързия час, изберете „първи свободен“." },
        { q: "Имате ли спешен дентален кабинет?", a: "Да, 24/7, включително празници. Обадете се преди да дойдете, за да ви очаква лекар." },
        { q: "Има ли паркинг?", a: "Да, 40 места за пациенти зад сградата, безплатно за времето на прегледа." },
      ],
      contact: { eyebrow: "Контакт", title: "Запазете час <em>или попитайте</em>", lede: "Рецепцията отговаря на телефона до 20:00, на имейл — до 2 часа." },
    },
    en: {
      name: "Clinica Vita", category: "Medical clinic", city: "Plovdiv",
      metaTitle: "Clinica Vita · Medical Clinic Plovdiv · Demo website",
      metaDesc: "Demo website for a medical and dental clinic: specialties, online booking, price list, insurance, reviews, FAQ. By Carbon Stealth.",
      address: "12 Vasil Aprilov Blvd, 4000 Plovdiv", phone: "+359 32 000 0012", email: "info@clinicavita.example",
      hours: ["Mon – Fri: 08:00 – 20:00", "Saturday: 09:00 – 14:00", "Emergency dental: 24/7"],
      hero: {
        eyebrow: "Medical and dental centre · Plovdiv · since 2011",
        title: "A doctor in 48 hours, <em>not three weeks.</em>",
        lede: "Twelve specialties, an in-house laboratory and a dental department under one roof. Book online, get an SMS confirmation and have your results on your phone the next day.",
        cta: "Book an appointment", cta2: "Price list",
        proof: "★ 4.8 on Google · 38,000 patients · Appointment within 48 h in 9 of 10 specialties",
        widget: { kind: "booking", title: "Book online", rows: [["Specialty", "Cardiology"], ["Doctor", "First available"], ["Date", "Wednesday, 10:30"], ["Duration", "30 min · €45"]], cta: "Confirm appointment", done: "Demo: on the real site you get an SMS and an email confirmation." },
      },
      badges: ["National health fund contract", "In-house laboratory", "Results online", "Patient parking"],
      offer: { tag: "Prevention", title: "Annual check-up package for €89 — 6 tests + consultation", text: "Blood count, lipid profile, blood sugar, thyroid, ECG and an internist consultation. Results within 24 hours, free follow-up visit to discuss them.", cta: "Book the package", note: "Prices are examples for the demo." },
      servicesTitle: "Specialties <em>and services</em>",
      servicesLede: "Our doctors are on staff, not visiting once a month. That is why the appointment is within 48 hours.",
      services: [
        { t: "General and internal medicine", d: "Check-ups, chronic conditions, referrals under the health fund.", p: "from €35" },
        { t: "Cardiology", d: "ECG, echocardiography, Holter monitoring, blood pressure consultation.", p: "from €45" },
        { t: "Dentistry", d: "Prevention, treatment, aesthetics, implants. Emergency room 24/7.", p: "from €25" },
        { t: "Paediatrics", d: "Children's check-ups, vaccinations, parent consultations — separate waiting room.", p: "from €35" },
        { t: "Imaging", d: "Ultrasound, X-ray, mammography — results on the spot.", p: "from €30" },
        { t: "Laboratory", d: "Over 300 tests, results within 24 hours in your profile.", p: "from €5" },
      ],
      about: {
        eyebrow: "About the clinic", title: "One address, <em>all the care</em>",
        p: ["Clinica Vita opened in 2011 with three consulting rooms. Today we are 24 doctors in 12 specialties, a laboratory and a dental department on 1,400 m² — but a patient still talks to a person, not a voice menu.", "We work with the national health fund and all major insurers. Results and discharge summaries live in your personal profile, shared with your GP if you choose."],
        facts: [{ n: "24", l: "doctors" }, { n: "12", l: "specialties" }, { n: "38,000", l: "patients" }, { n: "48 h", l: "to first appointment" }],
      },
      list: { title: "Price list", lede: "Final prices. Under the health fund — only the user fee.", groups: [
        { t: "Consultations", items: [["First specialist consultation", "€45"], ["Follow-up", "€25"], ["Health fund visit (fee)", "€1.50"], ["Home visit", "from €60"]] },
        { t: "Dentistry", items: [["Check-up", "€25"], ["Scale and polish", "€40"], ["Composite filling", "from €45"], ["Implant (without crown)", "from €550"]] },
      ] },
      reviews: [
        { name: "Desislava K.", text: "Booked on Monday evening, saw the cardiologist on Tuesday at 10:30. Blood results were on my phone the next day.", stars: 5 },
        { name: "Georgi M.", text: "Child with toothache on Saturday night. The emergency room opened within 20 minutes and nobody made us feel like a burden.", stars: 5 },
        { name: "Maria T.", text: "The check-up package caught a thyroid issue I had no idea about. The doctor explained everything without rushing.", stars: 5 },
      ],
      faq: [
        { q: "Do you work with the national health fund?", a: "Yes. For a referral visit you pay only the user fee. Bring the referral or give its number when booking." },
        { q: "How do I get my results?", a: "In your personal profile and by email within 24 hours for most tests. On paper — at reception any time." },
        { q: "Can I choose a specific doctor?", a: "Yes, when booking. If you want the earliest slot, choose “first available”." },
        { q: "Do you have emergency dental care?", a: "Yes, 24/7 including holidays. Call before you come so a dentist is waiting for you." },
        { q: "Is there parking?", a: "Yes, 40 patient spaces behind the building, free for the duration of your visit." },
      ],
      contact: { eyebrow: "Contact", title: "Book an appointment <em>or ask</em>", lede: "Reception answers the phone until 20:00, email within 2 hours." },
    },
    it: {
      name: "Clinica Vita", category: "Poliambulatorio", city: "Padova",
      metaTitle: "Clinica Vita · Poliambulatorio Padova · Sito demo",
      metaDesc: "Sito demo per poliambulatorio e studio dentistico: specialità, prenotazione online, listino, convenzioni, recensioni, FAQ. Di Carbon Stealth.",
      address: "Via Vasil Aprilov 12, 35100 Padova", phone: "+39 049 000 0012", email: "info@clinicavita.example",
      hours: ["Lun – Ven: 08:00 – 20:00", "Sabato: 09:00 – 14:00", "Pronto soccorso dentistico: 24/7"],
      hero: {
        eyebrow: "Poliambulatorio e studio dentistico · Padova · dal 2011",
        title: "Un medico in 48 ore, <em>non in tre settimane.</em>",
        lede: "Dodici specialità, laboratorio interno e reparto odontoiatrico sotto lo stesso tetto. Prenoti online, ricevi la conferma via SMS e i referti sono sul tuo telefono il giorno dopo.",
        cta: "Prenota una visita", cta2: "Listino",
        proof: "★ 4,8 su Google · 38.000 pazienti · Visita entro 48 h in 9 specialità su 10",
        widget: { kind: "booking", title: "Prenota online", rows: [["Specialità", "Cardiologia"], ["Medico", "Primo disponibile"], ["Data", "Mercoledì, 10:30"], ["Durata", "30 min · 45 €"]], cta: "Conferma la visita", done: "Demo: sul sito reale ricevi SMS ed email di conferma." },
      },
      badges: ["Convenzionato SSN", "Laboratorio interno", "Referti online", "Parcheggio per i pazienti"],
      offer: { tag: "Prevenzione", title: "Check-up annuale a 89 € — 6 esami + visita", text: "Emocromo, profilo lipidico, glicemia, tiroide, ECG e visita internistica. Referti entro 24 ore, controllo gratuito per discuterli.", cta: "Prenota il pacchetto", note: "I prezzi sono esempi per la demo." },
      servicesTitle: "Specialità <em>e servizi</em>",
      servicesLede: "I nostri medici sono in organico, non in visita una volta al mese. Per questo la visita è entro 48 ore.",
      services: [
        { t: "Medicina generale e interna", d: "Visite di controllo, patologie croniche, impegnative SSN.", p: "da 35 €" },
        { t: "Cardiologia", d: "ECG, ecocardiografia, Holter, consulenza per la pressione.", p: "da 45 €" },
        { t: "Odontoiatria", d: "Prevenzione, cure, estetica, impianti. Pronto soccorso 24/7.", p: "da 25 €" },
        { t: "Pediatria", d: "Visite pediatriche, vaccinazioni, consulenze per i genitori — sala d'attesa separata.", p: "da 35 €" },
        { t: "Diagnostica per immagini", d: "Ecografia, radiografia, mammografia — referto immediato.", p: "da 30 €" },
        { t: "Laboratorio", d: "Oltre 300 esami, referti entro 24 ore nel tuo profilo.", p: "da 5 €" },
      ],
      about: {
        eyebrow: "La clinica", title: "Un indirizzo, <em>tutta la cura</em>",
        p: ["Clinica Vita ha aperto nel 2011 con tre ambulatori. Oggi siamo 24 medici in 12 specialità, un laboratorio e un reparto odontoiatrico su 1.400 m² — ma il paziente parla ancora con una persona, non con un menu vocale.", "Lavoriamo con il SSN e con le principali assicurazioni. Referti e lettere di dimissione sono nel tuo profilo personale, condivisibili con il tuo medico di base se lo desideri."],
        facts: [{ n: "24", l: "medici" }, { n: "12", l: "specialità" }, { n: "38.000", l: "pazienti" }, { n: "48 h", l: "alla prima visita" }],
      },
      list: { title: "Listino", lede: "Prezzi definitivi. In convenzione — solo il ticket.", groups: [
        { t: "Visite", items: [["Prima visita specialistica", "45 €"], ["Visita di controllo", "25 €"], ["Visita in convenzione (ticket)", "1,50 €"], ["Visita a domicilio", "da 60 €"]] },
        { t: "Odontoiatria", items: [["Visita di controllo", "25 €"], ["Igiene e detartrasi", "40 €"], ["Otturazione in composito", "da 45 €"], ["Impianto (senza corona)", "da 550 €"]] },
      ] },
      reviews: [
        { name: "Desislava K.", text: "Ho prenotato lunedì sera, martedì alle 10:30 ero dal cardiologo. Gli esami del sangue sul telefono il giorno dopo.", stars: 5 },
        { name: "Giorgio M.", text: "Bambino con mal di denti sabato sera. Il pronto soccorso ha aperto in 20 minuti e nessuno ci ha guardato storto.", stars: 5 },
        { name: "Maria T.", text: "Il check-up ha trovato un problema alla tiroide di cui non sapevo nulla. La dottoressa mi ha spiegato tutto senza fretta.", stars: 5 },
      ],
      faq: [
        { q: "Siete convenzionati con il SSN?", a: "Sì. Per una visita con impegnativa paghi solo il ticket. Porta l'impegnativa o comunica il numero alla prenotazione." },
        { q: "Come ricevo i referti?", a: "Nel tuo profilo personale e via email entro 24 ore per la maggior parte degli esami. Su carta — in reception in qualsiasi momento." },
        { q: "Posso scegliere un medico specifico?", a: "Sì, al momento della prenotazione. Se vuoi il primo orario disponibile, scegli «primo disponibile»." },
        { q: "Avete un pronto soccorso dentistico?", a: "Sì, 24/7 festivi compresi. Chiama prima di venire, così un dentista ti aspetta." },
        { q: "C'è parcheggio?", a: "Sì, 40 posti per i pazienti dietro l'edificio, gratuiti per la durata della visita." },
      ],
      contact: { eyebrow: "Contatti", title: "Prenota una visita <em>o chiedi</em>", lede: "La reception risponde al telefono fino alle 20:00, alle email entro 2 ore." },
    },
  },
};
