// magazin.mjs — демо „Orbit Store": онлайн магазин за аксесоари и техника (пакетът „Магазин"). Тъмна тема с
// електриково синьо, продуктова решетка с ИСТИНСКА кошница и поръчка (fx/shop.js), доставка/връщане, отзиви.
export default {
  id: "magazin",
  slug: { bg: "onlain-magazin", en: "online-shop", it: "negozio-online" },
  icon: "bag",
  schemaType: "OnlineStore",
  theme: {
    mode: "dark", heroStyle: "split", pattern: "grid", radius: "10px",
    fonts: ["Sora:wght@400;600;700;800", "Inter:wght@400;500;600"],
    display: "Sora, system-ui, sans-serif", body: "Inter, system-ui, sans-serif",
    bg: "#0b0d12", surface: "#12151d", surface2: "#1a1e29", text: "#eef0f5", muted: "#9aa3b5",
    accent: "#3b82f6", accent2: "#60a5fa", onAccent: "#ffffff", line: "rgba(238,240,245,.1)",
    word: "ORBIT",
  },
  keywords: {
    bg: ["онлайн магазин демо сайт", "изработка на онлайн магазин", "електронен магазин с кошница", "магазин за аксесоари онлайн", "e-commerce сайт цена"],
    en: ["online shop demo website", "e-commerce website design", "online store with cart", "accessories online store", "e-commerce website cost"],
    it: ["sito e-commerce demo", "realizzazione negozio online", "shop online con carrello", "negozio accessori online", "costo sito e-commerce"],
  },
  t: {
    bg: {
      name: "Orbit Store", category: "Онлайн магазин", city: "Варна",
      metaTitle: "Orbit Store · Онлайн магазин за аксесоари · Демо сайт",
      metaDesc: "Демо онлайн магазин: каталог с кошница, поръчка с доставка и плащане, връщане до 14 дни, отзиви. Аксесоари и техника. От Carbon Stealth.",
      address: "бул. Княз Борис I 45, 9000 Варна", phone: "+359 88 000 0011", email: "hello@orbitstore.example",
      hours: ["Онлайн: 24/7", "Магазин: Пон – Съб 10:00 – 19:00", "Доставка: 1–2 работни дни"],
      hero: {
        eyebrow: "Аксесоари · аудио · часовници · фото · Варна и онлайн",
        title: "Нещата, които носите <em>всеки ден.</em>",
        lede: "Подбрани аксесоари и техника от 40 марки, с реални наличности и цени с ДДС. Поръчвате за две минути, доставяме до 1–2 работни дни в цяла България, връщате до 14 дни без въпроси.",
        cta: "Разгледай каталога", cta2: "Доставка и връщане",
        proof: "★ 4,8 в Google · 23 000+ поръчки · Безплатна доставка над 80 €",
        widget: { kind: "tiles", title: "Топ тази седмица", rows: [["Слушалки Aero One", "безжични · 30 ч батерия", "129 €"], ["Часовник Meridian", "сапфир · 5 ATM", "249 €"], ["Чанта Field 12", "кожа · 12 л", "159 €"]] },
      },
      badges: ["Безплатна доставка над 80 €", "14 дни връщане", "2 години гаранция", "Плащане с карта или при доставка"],
      catalog: {
        title: "Каталог <em>· 6 избрани</em>",
        lede: "В реалния магазин каталогът е с категории, филтри, размери и наличности. Тук — шест продукта, за да пробвате кошницата и поръчката.",
        freeFrom: 80, shipping: 4.9, shipNote: "Доставка 4,90 € · безплатна над 80 €",
        ship: ["Куриер до адрес · 1–2 работни дни · 4,90 €", "Вземане от магазина във Варна · безплатно"],
        pay: ["Карта онлайн (Visa · Mastercard · Apple Pay)", "Наложен платеж при доставка"],
        items: [
          { cat: "Аудио", n: "Слушалки Aero One", d: "Безжични, активно шумопотискане, 30 часа батерия, USB-C.", price: "129 €", num: 129, img: "g1" },
          { cat: "Часовници", n: "Часовник Meridian 40", d: "Автоматичен механизъм, сапфирено стъкло, водоустойчив 5 ATM.", price: "249 €", num: 249, img: "g2" },
          { cat: "Чанти", n: "Чанта Field 12", d: "Естествена кожа, 12 литра, отделение за лаптоп 13″.", price: "159 €", num: 159, img: "g3" },
          { cat: "Обувки", n: "Сандали Lilac", d: "Кожа, ръчно шити, размери 36–41.", price: "89 €", num: 89, img: "g4" },
          { cat: "Очила", n: "Очила Solar", d: "Поляризирани, UV400, ацетатна рамка, калъф в комплекта.", price: "69 €", num: 69, img: "g5" },
          { cat: "Фото", n: "Обектив Wide 14", d: "14 mm f/2.8 за безогледални камери, метален корпус.", price: "319 €", num: 319, img: "g6" },
        ],
      },
      servicesTitle: "Защо да поръчате <em>от нас</em>",
      servicesLede: "Магазинът е малък, но всичко в него е избрано и пробвано от нас.",
      services: [
        { t: "Реални наличности", d: "Каквото виждате, е на склад във Варна. Без „ще проверим“ и без поръчки от чужбина." },
        { t: "Доставка за 1–2 дни", d: "Куриер до адрес в цяла България, проследяване по SMS, безплатно над 80 €." },
        { t: "14 дни връщане", d: "Не ви харесва — връщате без въпроси. Парите са обратно до 5 дни." },
        { t: "2 години гаранция", d: "Сервиз за всяка марка. Докато поправяме, получавате заместващ продукт." },
        { t: "Плащане както искате", d: "Карта, Apple Pay, Google Pay или наложен платеж. Фактура за фирми." },
        { t: "Подаръчна опаковка", d: "Безплатна кутия и картичка с ваш текст. Директно до получателя." },
      ],
      offer: { tag: "Само онлайн", title: "−10% на първата поръчка с код ORBIT10", text: "Въведете кода при поръчка. Важи за всички продукти до края на месеца, комбинира се с безплатната доставка.", cta: "Пазарувай", note: "Кодът е демо — в реалния магазин се прилага автоматично." },
      about: {
        eyebrow: "За магазина", title: "Малък магазин, <em>подбрано всичко</em>",
        p: ["Orbit Store отвори през 2018 г. като щанд за слушалки на 8 м². Днес сме магазин във Варна и онлайн магазин с 40 марки, но правилото е същото: продаваме само неща, които сами бихме купили.", "Всеки продукт минава през нас — пробваме го седмица, преди да го качим. Затова каталогът е кратък, а върнатите поръчки са под 2%."],
        facts: [{ n: "40", l: "марки" }, { n: "23 000+", l: "поръчки" }, { n: "1–2", l: "дни доставка" }, { n: "4,8", l: "оценка в Google" }],
      },
      steps: { title: "Как се <em>поръчва</em>", items: [
        { t: "Избирате", d: "Добавяте в кошницата, виждате сумата и доставката веднага." },
        { t: "Поръчвате", d: "Име, адрес, доставка и плащане — без регистрация." },
        { t: "Получавате", d: "SMS с проследяване; куриерът идва до 1–2 работни дни." },
        { t: "Връщате, ако трябва", d: "До 14 дни, безплатно, парите обратно до 5 дни." },
      ] },
      list: { title: "Доставка и връщане", lede: "Крайни условия, без дребен шрифт.", groups: [
        { t: "Доставка", items: [["Куриер до адрес (1–2 дни)", "4,90 €"], ["Куриер над 80 €", "безплатно"], ["Вземане от магазина", "безплатно"], ["Експресна доставка Варна (същия ден)", "9,90 €"]] },
        { t: "Връщане и гаранция", items: [["Срок за връщане", "14 дни"], ["Възстановяване на сумата", "до 5 дни"], ["Гаранция", "2 години"], ["Замяна на размер", "безплатно"]] },
      ] },
      reviews: [
        { name: "Калоян П.", text: "Поръчах слушалките в неделя вечер, във вторник бяха при мен. Кутията беше по-хубава от тази в мола.", stars: 5 },
        { name: "Милена Р.", text: "Върнах чанта, защото исках друг цвят — новата дойде преди да са взели старата. Нула драма.", stars: 5 },
        { name: "Стефан Д.", text: "Часовникът е точно като на снимките. Фактура за фирмата дойде на имейла същия ден.", stars: 5 },
      ],
      faq: [
        { q: "Колко струва доставката?", a: "4,90 € с куриер до адрес; безплатна при поръчка над 80 €. Вземането от магазина във Варна е винаги безплатно." },
        { q: "Как мога да платя?", a: "С карта онлайн (Visa, Mastercard, Apple Pay, Google Pay) или с наложен платеж при доставка." },
        { q: "Мога ли да върна продукт?", a: "Да, до 14 дни от получаването, без да обяснявате защо. Куриерът го взема от вас безплатно." },
        { q: "Издавате ли фактура?", a: "Да — въведете данните на фирмата при поръчка и фактурата пристига по имейл веднага." },
        { q: "Доставяте ли извън България?", a: "Да, в ЕС за 3–5 работни дни. Цената се показва при поръчка според държавата." },
      ],
      contact: { eyebrow: "Контакт", title: "Въпрос за продукт <em>или поръчка?</em>", lede: "Отговаряме до 2 часа в работно време." },
    },
    en: {
      name: "Orbit Store", category: "Online shop", city: "Varna",
      metaTitle: "Orbit Store · Accessories Online Shop · Demo website",
      metaDesc: "Demo online shop: catalogue with cart, checkout with delivery and payment, 14-day returns, reviews. Accessories and tech. By Carbon Stealth.",
      address: "45 Knyaz Boris I Blvd, 9000 Varna", phone: "+359 88 000 0011", email: "hello@orbitstore.example",
      hours: ["Online: 24/7", "Store: Mon – Sat 10:00 – 19:00", "Delivery: 1–2 working days"],
      hero: {
        eyebrow: "Accessories · audio · watches · photo · Varna and online",
        title: "The things you carry <em>every day.</em>",
        lede: "Curated accessories and tech from 40 brands, with real stock and prices incl. VAT. Order in two minutes, delivered in 1–2 working days across Bulgaria, returns within 14 days, no questions asked.",
        cta: "Browse the catalogue", cta2: "Delivery and returns",
        proof: "★ 4.8 on Google · 23,000+ orders · Free delivery over €80",
        widget: { kind: "tiles", title: "Top this week", rows: [["Aero One headphones", "wireless · 30 h battery", "€129"], ["Meridian watch", "sapphire · 5 ATM", "€249"], ["Field 12 bag", "leather · 12 l", "€159"]] },
      },
      badges: ["Free delivery over €80", "14-day returns", "2-year warranty", "Card or cash on delivery"],
      catalog: {
        title: "Catalogue <em>· 6 picks</em>",
        lede: "In the real shop the catalogue has categories, filters, sizes and stock. Here — six products so you can try the cart and the checkout.",
        freeFrom: 80, shipping: 4.9, shipNote: "Delivery €4.90 · free over €80",
        ship: ["Courier to your address · 1–2 working days · €4.90", "Pick up in the Varna store · free"],
        pay: ["Card online (Visa · Mastercard · Apple Pay)", "Cash on delivery"],
        items: [
          { cat: "Audio", n: "Aero One headphones", d: "Wireless, active noise cancelling, 30-hour battery, USB-C.", price: "€129", num: 129, img: "g1" },
          { cat: "Watches", n: "Meridian 40 watch", d: "Automatic movement, sapphire glass, water resistant 5 ATM.", price: "€249", num: 249, img: "g2" },
          { cat: "Bags", n: "Field 12 bag", d: "Full-grain leather, 12 litres, 13″ laptop sleeve.", price: "€159", num: 159, img: "g3" },
          { cat: "Shoes", n: "Lilac sandals", d: "Leather, hand-stitched, sizes 36–41.", price: "€89", num: 89, img: "g4" },
          { cat: "Eyewear", n: "Solar sunglasses", d: "Polarised, UV400, acetate frame, case included.", price: "€69", num: 69, img: "g5" },
          { cat: "Photo", n: "Wide 14 lens", d: "14 mm f/2.8 for mirrorless cameras, metal body.", price: "€319", num: 319, img: "g6" },
        ],
      },
      servicesTitle: "Why order <em>from us</em>",
      servicesLede: "The shop is small, but everything in it was picked and tested by us.",
      services: [
        { t: "Real stock", d: "What you see is in our Varna warehouse. No “we'll check” and no drop-shipping from abroad." },
        { t: "Delivery in 1–2 days", d: "Courier to any address in Bulgaria, SMS tracking, free over €80." },
        { t: "14-day returns", d: "Don't like it — return it, no questions asked. Refund within 5 days." },
        { t: "2-year warranty", d: "Service for every brand. While we repair, you get a replacement." },
        { t: "Pay how you like", d: "Card, Apple Pay, Google Pay or cash on delivery. Invoices for companies." },
        { t: "Gift wrapping", d: "Free box and a card with your message. Shipped straight to the recipient." },
      ],
      offer: { tag: "Online only", title: "10% off your first order with code ORBIT10", text: "Enter the code at checkout. Valid for all products until the end of the month, combines with free delivery.", cta: "Shop now", note: "The code is a demo — the real shop applies it automatically." },
      about: {
        eyebrow: "About the shop", title: "A small shop, <em>everything curated</em>",
        p: ["Orbit Store opened in 2018 as an 8 m² headphone stand. Today we are a store in Varna and an online shop with 40 brands, but the rule is the same: we only sell things we would buy ourselves.", "Every product passes through our hands — we use it for a week before listing it. That is why the catalogue is short and returns are under 2%."],
        facts: [{ n: "40", l: "brands" }, { n: "23,000+", l: "orders" }, { n: "1–2", l: "days delivery" }, { n: "4.8", l: "Google rating" }],
      },
      steps: { title: "How to <em>order</em>", items: [
        { t: "Pick", d: "Add to cart and see the total and delivery right away." },
        { t: "Order", d: "Name, address, delivery and payment — no account needed." },
        { t: "Receive", d: "SMS tracking; the courier arrives within 1–2 working days." },
        { t: "Return if needed", d: "Within 14 days, free, refund within 5 days." },
      ] },
      list: { title: "Delivery and returns", lede: "Final terms, no small print.", groups: [
        { t: "Delivery", items: [["Courier to address (1–2 days)", "€4.90"], ["Courier over €80", "free"], ["Store pickup", "free"], ["Same-day express in Varna", "€9.90"]] },
        { t: "Returns and warranty", items: [["Return period", "14 days"], ["Refund", "within 5 days"], ["Warranty", "2 years"], ["Size exchange", "free"]] },
      ] },
      reviews: [
        { name: "Kaloyan P.", text: "Ordered the headphones on Sunday night, had them on Tuesday. The box was nicer than the one in the mall.", stars: 5 },
        { name: "Milena R.", text: "Returned a bag because I wanted another colour — the new one arrived before they picked up the old one. Zero drama.", stars: 5 },
        { name: "Stefan D.", text: "The watch is exactly like the photos. The company invoice landed in my inbox the same day.", stars: 5 },
      ],
      faq: [
        { q: "How much is delivery?", a: "€4.90 by courier to your address; free for orders over €80. Pickup from the Varna store is always free." },
        { q: "How can I pay?", a: "By card online (Visa, Mastercard, Apple Pay, Google Pay) or cash on delivery." },
        { q: "Can I return a product?", a: "Yes, within 14 days of receiving it, no explanation needed. The courier collects it from you for free." },
        { q: "Do you issue invoices?", a: "Yes — enter your company details at checkout and the invoice arrives by email immediately." },
        { q: "Do you ship outside Bulgaria?", a: "Yes, within the EU in 3–5 working days. The price is shown at checkout by country." },
      ],
      contact: { eyebrow: "Contact", title: "A question about a product <em>or an order?</em>", lede: "We reply within 2 hours during business hours." },
    },
    it: {
      name: "Orbit Store", category: "Negozio online", city: "Bologna",
      metaTitle: "Orbit Store · Negozio online di accessori · Sito demo",
      metaDesc: "Sito demo e-commerce: catalogo con carrello, ordine con consegna e pagamento, reso entro 14 giorni, recensioni. Accessori e tech. Di Carbon Stealth.",
      address: "Via dell'Indipendenza 45, 40121 Bologna", phone: "+39 051 000 0011", email: "ciao@orbitstore.example",
      hours: ["Online: 24/7", "Negozio: Lun – Sab 10:00 – 19:00", "Consegna: 1–2 giorni lavorativi"],
      hero: {
        eyebrow: "Accessori · audio · orologi · foto · Bologna e online",
        title: "Le cose che porti con te <em>ogni giorno.</em>",
        lede: "Accessori e tech selezionati da 40 marchi, con disponibilità reale e prezzi IVA inclusa. Ordini in due minuti, consegna in 1–2 giorni lavorativi in tutta Italia, reso entro 14 giorni senza domande.",
        cta: "Sfoglia il catalogo", cta2: "Consegna e resi",
        proof: "★ 4,8 su Google · 23.000+ ordini · Consegna gratuita sopra 80 €",
        widget: { kind: "tiles", title: "Top della settimana", rows: [["Cuffie Aero One", "wireless · 30 h batteria", "129 €"], ["Orologio Meridian", "zaffiro · 5 ATM", "249 €"], ["Borsa Field 12", "pelle · 12 l", "159 €"]] },
      },
      badges: ["Consegna gratuita sopra 80 €", "Reso entro 14 giorni", "Garanzia 2 anni", "Carta o contrassegno"],
      catalog: {
        title: "Catalogo <em>· 6 selezionati</em>",
        lede: "Nel negozio reale il catalogo ha categorie, filtri, taglie e disponibilità. Qui — sei prodotti per provare carrello e ordine.",
        freeFrom: 80, shipping: 4.9, shipNote: "Consegna 4,90 € · gratuita sopra 80 €",
        ship: ["Corriere a domicilio · 1–2 giorni lavorativi · 4,90 €", "Ritiro in negozio a Bologna · gratuito"],
        pay: ["Carta online (Visa · Mastercard · Apple Pay)", "Contrassegno alla consegna"],
        items: [
          { cat: "Audio", n: "Cuffie Aero One", d: "Wireless, cancellazione attiva del rumore, 30 ore di batteria, USB-C.", price: "129 €", num: 129, img: "g1" },
          { cat: "Orologi", n: "Orologio Meridian 40", d: "Movimento automatico, vetro zaffiro, impermeabile 5 ATM.", price: "249 €", num: 249, img: "g2" },
          { cat: "Borse", n: "Borsa Field 12", d: "Pelle pieno fiore, 12 litri, tasca per laptop 13″.", price: "159 €", num: 159, img: "g3" },
          { cat: "Scarpe", n: "Sandali Lilac", d: "Pelle, cuciti a mano, taglie 36–41.", price: "89 €", num: 89, img: "g4" },
          { cat: "Occhiali", n: "Occhiali Solar", d: "Polarizzati, UV400, montatura in acetato, custodia inclusa.", price: "69 €", num: 69, img: "g5" },
          { cat: "Foto", n: "Obiettivo Wide 14", d: "14 mm f/2.8 per mirrorless, corpo in metallo.", price: "319 €", num: 319, img: "g6" },
        ],
      },
      servicesTitle: "Perché ordinare <em>da noi</em>",
      servicesLede: "Il negozio è piccolo, ma tutto ciò che contiene è scelto e provato da noi.",
      services: [
        { t: "Disponibilità reale", d: "Ciò che vedi è nel nostro magazzino di Bologna. Niente «verifichiamo» e niente dropshipping dall'estero." },
        { t: "Consegna in 1–2 giorni", d: "Corriere a qualsiasi indirizzo in Italia, tracking via SMS, gratuita sopra 80 €." },
        { t: "Reso entro 14 giorni", d: "Non ti piace — lo rendi senza domande. Rimborso entro 5 giorni." },
        { t: "Garanzia 2 anni", d: "Assistenza per ogni marchio. Mentre ripariamo, ricevi un prodotto sostitutivo." },
        { t: "Paghi come vuoi", d: "Carta, Apple Pay, Google Pay o contrassegno. Fattura per le aziende." },
        { t: "Confezione regalo", d: "Scatola e biglietto con il tuo messaggio, gratis. Spedito direttamente al destinatario." },
      ],
      offer: { tag: "Solo online", title: "−10% sul primo ordine con il codice ORBIT10", text: "Inserisci il codice all'ordine. Valido su tutti i prodotti fino a fine mese, cumulabile con la consegna gratuita.", cta: "Acquista", note: "Il codice è dimostrativo — nel negozio reale si applica in automatico." },
      about: {
        eyebrow: "Il negozio", title: "Un negozio piccolo, <em>tutto selezionato</em>",
        p: ["Orbit Store ha aperto nel 2018 come banco di cuffie da 8 m². Oggi siamo un negozio a Bologna e uno shop online con 40 marchi, ma la regola è la stessa: vendiamo solo cose che compreremmo noi.", "Ogni prodotto passa dalle nostre mani — lo usiamo una settimana prima di metterlo online. Per questo il catalogo è corto e i resi sono sotto il 2%."],
        facts: [{ n: "40", l: "marchi" }, { n: "23.000+", l: "ordini" }, { n: "1–2", l: "giorni di consegna" }, { n: "4,8", l: "valutazione Google" }],
      },
      steps: { title: "Come si <em>ordina</em>", items: [
        { t: "Scegli", d: "Aggiungi al carrello e vedi subito totale e consegna." },
        { t: "Ordina", d: "Nome, indirizzo, consegna e pagamento — senza registrazione." },
        { t: "Ricevi", d: "SMS con tracking; il corriere arriva in 1–2 giorni lavorativi." },
        { t: "Rendi, se serve", d: "Entro 14 giorni, gratis, rimborso entro 5 giorni." },
      ] },
      list: { title: "Consegna e resi", lede: "Condizioni definitive, senza caratteri piccoli.", groups: [
        { t: "Consegna", items: [["Corriere a domicilio (1–2 giorni)", "4,90 €"], ["Corriere sopra 80 €", "gratuita"], ["Ritiro in negozio", "gratuito"], ["Espresso in giornata a Bologna", "9,90 €"]] },
        { t: "Resi e garanzia", items: [["Termine per il reso", "14 giorni"], ["Rimborso", "entro 5 giorni"], ["Garanzia", "2 anni"], ["Cambio taglia", "gratuito"]] },
      ] },
      reviews: [
        { name: "Carlo P.", text: "Ho ordinato le cuffie domenica sera, martedì erano da me. La scatola era più bella di quella del centro commerciale.", stars: 5 },
        { name: "Milena R.", text: "Ho reso una borsa perché volevo un altro colore — la nuova è arrivata prima che ritirassero la vecchia. Zero drammi.", stars: 5 },
        { name: "Stefano D.", text: "L'orologio è esattamente come nelle foto. La fattura per l'azienda è arrivata via email lo stesso giorno.", stars: 5 },
      ],
      faq: [
        { q: "Quanto costa la consegna?", a: "4,90 € con corriere a domicilio; gratuita per ordini sopra 80 €. Il ritiro in negozio a Bologna è sempre gratuito." },
        { q: "Come posso pagare?", a: "Con carta online (Visa, Mastercard, Apple Pay, Google Pay) o in contrassegno alla consegna." },
        { q: "Posso rendere un prodotto?", a: "Sì, entro 14 giorni dal ricevimento, senza spiegare il motivo. Il corriere lo ritira gratuitamente." },
        { q: "Emettete fattura?", a: "Sì — inserisci i dati dell'azienda all'ordine e la fattura arriva subito via email." },
        { q: "Spedite fuori dall'Italia?", a: "Sì, in UE in 3–5 giorni lavorativi. Il prezzo è mostrato all'ordine in base al paese." },
      ],
      contact: { eyebrow: "Contatti", title: "Una domanda su un prodotto <em>o un ordine?</em>", lede: "Rispondiamo entro 2 ore in orario di lavoro." },
    },
  },
};
