// mebeli.mjs — демо „Oak & Linen": мебелен магазин. Светла топла тема (крем + орех + салвия), editorial hero.
export default {
  id: "mebeli",
  slug: { bg: "mebelen-magazin", en: "furniture-store", it: "negozio-arredamento" },
  icon: "chair",
  schemaType: "FurnitureStore",
  theme: {
    mode: "light", heroStyle: "editorial", pattern: "dots", radius: "10px",
    fonts: ["Fraunces:opsz,wght@9..144,500;9..144,600", "Manrope:wght@400;500;700"],
    display: "Fraunces, Georgia, serif", body: "Manrope, system-ui, sans-serif",
    bg: "#f6f1ea", surface: "#ffffff", surface2: "#efe7dc", text: "#2b241d", muted: "#6f6559",
    accent: "#7a4b2a", accent2: "#a8714a", onAccent: "#fbf7f2", line: "rgba(43,36,29,.12)",
    word: "HOME",
  },
  keywords: {
    bg: ["сайт за мебелен магазин", "мебели демо сайт", "онлайн каталог мебели", "уеб сайт мебели по поръчка", "изработка на сайт за мебели"],
    en: ["furniture store website", "furniture shop website demo", "custom furniture website", "furniture catalogue online", "interior brand website"],
    it: ["sito negozio arredamento", "sito mobili demo", "sito arredamento su misura", "catalogo mobili online", "realizzazione sito arredamento"],
  },
  t: {
    bg: {
      name: "Oak & Linen", category: "Мебелен магазин", city: "Варна",
      metaTitle: "Oak & Linen · Мебели от масив Варна · Демо сайт",
      metaDesc: "Демо сайт за мебелен магазин: каталог с цени, мебели по поръчка, доставка и монтаж, отзиви. От Carbon Stealth.",
      address: "бул. Владислав Варненчик 186, 9000 Варна", phone: "+359 88 000 0003", email: "hello@oaklinen.example",
      hours: ["Пон – Пет: 10:00 – 19:00", "Събота: 10:00 – 17:00", "Неделя: почивен ден"],
      hero: {
        eyebrow: "Мебели от масив · шоурум Варна · собствено производство",
        title: "Мебели, които <em>остават в семейството.</em>",
        lede: "Дъб, орех и лен от собствената ни работилница. Всяка маса, легло и гардероб се прави по вашите размери и се доставя с монтаж в цяла България.",
        cta: "Запитване за оферта", cta2: "Разгледай каталога",
        widget: { kind: "tiles", title: "Най-търсени този сезон", rows: [["Маса „Рила“", "дъб · 200 × 90 см", "1 190 €"], ["Легло „Лен“", "орех · 160 × 200", "890 €"], ["Скрин „Нива“", "дъб · 4 чекмеджета", "640 €"]] },
      },
      badges: ["Собствена работилница", "Гаранция 10 години", "Доставка и монтаж в цяла България", "Плащане на 3 вноски"],
      servicesTitle: "Какво <em>правим</em>",
      servicesLede: "Всичко се изработва в цеха ни край Варна — виждате дървото преди да го отрежем.",
      services: [
        { t: "Маси и столове", d: "Трапезни и работни маси от масивен дъб и орех, столове с ленена тапицерия.", p: "от 490 €" },
        { t: "Спални", d: "Легла, нощни шкафчета и гардероби по размер, с меки затварящи механизми.", p: "от 690 €" },
        { t: "Кухни по поръчка", d: "Проект в 3D, фронтове от масив или фурнир, уреди по избор.", p: "от 3 900 €" },
        { t: "Дневни", d: "Секции, библиотеки, ТВ шкафове — с кабелен мениджмънт и скрит монтаж.", p: "от 590 €" },
        { t: "Интериорен проект", d: "Архитект идва на място, мери и предлага решение с визуализация.", p: "120 €, приспада се" },
        { t: "Реставрация", d: "Връщаме живота на старите ви мебели от масив — шлайф, масло, нов обков." },
      ],
      about: {
        eyebrow: "За нас", title: "Две поколения <em>и една работилница</em>",
        p: ["Oak & Linen започна през 1998 г. като дърводелски цех на Петър и днес работи с 14 майстори. Не ползваме ПДЧ и не крием фугите — дървото трябва да се вижда.", "Всяко изделие идва с паспорт: от кой ствол е, с какво масло е обработено и как да го поддържате."],
        facts: [{ n: "26", l: "години опит" }, { n: "14", l: "майстори" }, { n: "10", l: "години гаранция" }, { n: "3 200+", l: "доставени домове" }],
      },
      steps: { title: "От идея <em>до дома ви</em>", items: [{ t: "Разговор и мерки", d: "Идвате в шоурума или ние идваме при вас. Мерим и уточняваме дървесина и покритие." }, { t: "3D проект", d: "Виждате мебела в стаята си преди да е направен. Промени — колкото трябват." }, { t: "Изработка", d: "4 до 6 седмици в цеха. Пращаме снимки от всяка фаза." }, { t: "Доставка и монтаж", d: "Наш екип, наш камион, ден и час по ваш избор. Опаковката си взимаме." }] },
      reviews: [
        { name: "Елена и Мартин", text: "Масата за 8 души е центърът на къщата ни. След три години изглежда като в деня на доставката.", stars: 5 },
        { name: "Калин Р.", text: "Кухнята дойде точно за 5 седмици, монтажът — за един ден. Хората знаят какво правят.", stars: 5 },
        { name: "Ивана Т.", text: "Поръчах легло по нестандартен размер. Направиха го без нито един въпрос „защо“.", stars: 5 },
      ],
      faq: [
        { q: "Колко време отнема една поръчка?", a: "Стандартни модели — 2 до 3 седмици; по поръчка — 4 до 6. Кухни — 6 до 8 седмици." },
        { q: "Доставяте ли извън Варна?", a: "Да, в цяла България с наш екип за монтаж. Цената на доставката се вижда в офертата." },
        { q: "Може ли разсрочено плащане?", a: "Да — 3 вноски без оскъпяване, или лизинг до 24 месеца през партньор." },
        { q: "Какво покрива гаранцията?", a: "10 години за конструкцията и съединенията, 2 години за обкова и тапицерията." },
        { q: "Мога ли да видя дървото преди да поръчам?", a: "Да. В шоурума има мостри от всяка партида, а в цеха — самите дъски." },
      ],
      contact: { eyebrow: "Контакт", title: "Разкажете ни <em>за стаята си</em>", lede: "Пратете размери и снимка — връщаме идея и цена до 2 работни дни." },
    },
    en: {
      name: "Oak & Linen", category: "Furniture store", city: "Varna",
      metaTitle: "Oak & Linen · Solid Wood Furniture Varna · Demo website",
      metaDesc: "Demo website for a furniture store: priced catalogue, made-to-measure furniture, delivery and assembly, reviews. By Carbon Stealth.",
      address: "186 Vladislav Varnenchik Blvd, 9000 Varna", phone: "+359 88 000 0003", email: "hello@oaklinen.example",
      hours: ["Mon – Fri: 10:00 – 19:00", "Saturday: 10:00 – 17:00", "Sunday: closed"],
      hero: {
        eyebrow: "Solid wood furniture · Varna showroom · own workshop",
        title: "Furniture that <em>stays in the family.</em>",
        lede: "Oak, walnut and linen from our own workshop. Every table, bed and wardrobe is made to your measurements and delivered with assembly across Bulgaria.",
        cta: "Request a quote", cta2: "Browse the catalogue",
        widget: { kind: "tiles", title: "Most wanted this season", rows: [["“Rila” table", "oak · 200 × 90 cm", "€1,190"], ["“Linen” bed", "walnut · 160 × 200", "€890"], ["“Niva” chest", "oak · 4 drawers", "€640"]] },
      },
      badges: ["Own workshop", "10-year warranty", "Delivery and assembly across Bulgaria", "Pay in 3 instalments"],
      servicesTitle: "What <em>we make</em>",
      servicesLede: "Everything is made in our workshop near Varna — you see the wood before we cut it.",
      services: [
        { t: "Tables and chairs", d: "Dining and work tables in solid oak and walnut, chairs with linen upholstery.", p: "from €490" },
        { t: "Bedrooms", d: "Beds, bedside tables and wardrobes to size, with soft-close mechanisms.", p: "from €690" },
        { t: "Custom kitchens", d: "3D design, solid or veneered fronts, appliances of your choice.", p: "from €3,900" },
        { t: "Living rooms", d: "Wall units, bookcases, TV cabinets — with cable management and hidden fixings.", p: "from €590" },
        { t: "Interior design", d: "An architect visits, measures and proposes a solution with a visualisation.", p: "€120, credited" },
        { t: "Restoration", d: "We bring your old solid wood furniture back to life — sanding, oil, new hardware." },
      ],
      about: {
        eyebrow: "About us", title: "Two generations <em>and one workshop</em>",
        p: ["Oak & Linen started in 1998 as Petar's joinery and today works with 14 craftsmen. We use no chipboard and hide no joints — the wood should be seen.", "Every piece comes with a passport: which log it came from, which oil it was finished with and how to care for it."],
        facts: [{ n: "26", l: "years of experience" }, { n: "14", l: "craftsmen" }, { n: "10", l: "years warranty" }, { n: "3,200+", l: "homes furnished" }],
      },
      steps: { title: "From idea <em>to your home</em>", items: [{ t: "Talk and measure", d: "You visit the showroom or we visit you. We measure and agree on wood and finish." }, { t: "3D design", d: "See the piece in your room before it exists. Changes — as many as needed." }, { t: "Making", d: "4 to 6 weeks in the workshop. We send photos from every stage." }, { t: "Delivery and assembly", d: "Our team, our truck, a day and time of your choice. We take the packaging away." }] },
      reviews: [
        { name: "Elena and Martin", text: "The table for 8 is the centre of our house. Three years on it looks like the day it arrived.", stars: 5 },
        { name: "Kalin R.", text: "The kitchen came in exactly 5 weeks, assembly took a day. These people know what they are doing.", stars: 5 },
        { name: "Ivana T.", text: "I ordered a bed in a non-standard size. They made it without a single “why”.", stars: 5 },
      ],
      faq: [
        { q: "How long does an order take?", a: "Standard models — 2 to 3 weeks; made to measure — 4 to 6. Kitchens — 6 to 8 weeks." },
        { q: "Do you deliver outside Varna?", a: "Yes, across Bulgaria with our own assembly team. Delivery cost is shown in the quote." },
        { q: "Can I pay in instalments?", a: "Yes — 3 instalments at no extra cost, or leasing up to 24 months through a partner." },
        { q: "What does the warranty cover?", a: "10 years on structure and joints, 2 years on hardware and upholstery." },
        { q: "Can I see the wood before ordering?", a: "Yes. The showroom has samples from every batch, and the workshop has the boards themselves." },
      ],
      contact: { eyebrow: "Contact", title: "Tell us <em>about your room</em>", lede: "Send measurements and a photo — we return an idea and a price within 2 working days." },
    },
    it: {
      name: "Oak & Linen", category: "Negozio di arredamento", city: "Torino",
      metaTitle: "Oak & Linen · Mobili in legno massello Torino · Sito demo",
      metaDesc: "Sito demo per negozio di arredamento: catalogo con prezzi, mobili su misura, consegna e montaggio, recensioni. Di Carbon Stealth.",
      address: "Corso Francia 186, 10138 Torino", phone: "+39 011 000 0003", email: "ciao@oaklinen.example",
      hours: ["Lun – Ven: 10:00 – 19:00", "Sabato: 10:00 – 17:00", "Domenica: chiuso"],
      hero: {
        eyebrow: "Mobili in massello · showroom Torino · produzione propria",
        title: "Mobili che <em>restano in famiglia.</em>",
        lede: "Rovere, noce e lino dal nostro laboratorio. Ogni tavolo, letto e armadio è fatto sulle tue misure e consegnato con montaggio in tutta Italia.",
        cta: "Richiedi un preventivo", cta2: "Sfoglia il catalogo",
        widget: { kind: "tiles", title: "I più richiesti della stagione", rows: [["Tavolo «Rila»", "rovere · 200 × 90 cm", "1.190 €"], ["Letto «Lino»", "noce · 160 × 200", "890 €"], ["Cassettiera «Niva»", "rovere · 4 cassetti", "640 €"]] },
      },
      badges: ["Laboratorio proprio", "Garanzia 10 anni", "Consegna e montaggio in tutta Italia", "Pagamento in 3 rate"],
      servicesTitle: "Cosa <em>realizziamo</em>",
      servicesLede: "Tutto nasce nel nostro laboratorio alle porte di Torino — vedi il legno prima che lo tagliamo.",
      services: [
        { t: "Tavoli e sedie", d: "Tavoli da pranzo e da lavoro in rovere e noce massello, sedie con rivestimento in lino.", p: "da 490 €" },
        { t: "Camere da letto", d: "Letti, comodini e armadi su misura, con chiusure ammortizzate.", p: "da 690 €" },
        { t: "Cucine su misura", d: "Progetto 3D, ante in massello o impiallacciate, elettrodomestici a scelta.", p: "da 3.900 €" },
        { t: "Soggiorni", d: "Pareti attrezzate, librerie, mobili TV — con gestione cavi e fissaggi nascosti.", p: "da 590 €" },
        { t: "Progetto d'interni", d: "Un architetto viene da te, misura e propone una soluzione con rendering.", p: "120 €, scalati" },
        { t: "Restauro", d: "Ridiamo vita ai tuoi vecchi mobili in massello — levigatura, olio, ferramenta nuova." },
      ],
      about: {
        eyebrow: "Chi siamo", title: "Due generazioni <em>e un laboratorio</em>",
        p: ["Oak & Linen è nata nel 1998 come falegnameria di Pietro e oggi lavora con 14 artigiani. Non usiamo truciolare e non nascondiamo le giunzioni — il legno si deve vedere.", "Ogni pezzo arriva con un passaporto: da quale tronco viene, con quale olio è finito e come prendersene cura."],
        facts: [{ n: "26", l: "anni di esperienza" }, { n: "14", l: "artigiani" }, { n: "10", l: "anni di garanzia" }, { n: "3.200+", l: "case arredate" }],
      },
      steps: { title: "Dall'idea <em>a casa tua</em>", items: [{ t: "Colloquio e misure", d: "Vieni in showroom o veniamo noi. Misuriamo e definiamo legno e finitura." }, { t: "Progetto 3D", d: "Vedi il mobile nella tua stanza prima che esista. Modifiche — quante servono." }, { t: "Realizzazione", d: "Da 4 a 6 settimane in laboratorio. Ti mandiamo foto di ogni fase." }, { t: "Consegna e montaggio", d: "Il nostro team, il nostro camion, giorno e ora a tua scelta. L'imballo lo portiamo via noi." }] },
      reviews: [
        { name: "Elena e Martino", text: "Il tavolo da 8 è il centro della nostra casa. Dopo tre anni sembra quello del giorno della consegna.", stars: 5 },
        { name: "Carlo R.", text: "La cucina è arrivata in 5 settimane esatte, montaggio in un giorno. Sanno quello che fanno.", stars: 5 },
        { name: "Ivana T.", text: "Ho ordinato un letto fuori misura. L'hanno fatto senza un solo «perché».", stars: 5 },
      ],
      faq: [
        { q: "Quanto tempo richiede un ordine?", a: "Modelli standard — da 2 a 3 settimane; su misura — da 4 a 6. Cucine — da 6 a 8 settimane." },
        { q: "Consegnate fuori Torino?", a: "Sì, in tutta Italia con il nostro team di montaggio. Il costo della consegna è indicato nel preventivo." },
        { q: "Posso pagare a rate?", a: "Sì — 3 rate senza interessi, oppure finanziamento fino a 24 mesi tramite partner." },
        { q: "Cosa copre la garanzia?", a: "10 anni su struttura e giunzioni, 2 anni su ferramenta e rivestimenti." },
        { q: "Posso vedere il legno prima di ordinare?", a: "Sì. In showroom ci sono campioni di ogni lotto, e in laboratorio le tavole stesse." },
      ],
      contact: { eyebrow: "Contatti", title: "Raccontaci <em>la tua stanza</em>", lede: "Mandaci misure e una foto — rispondiamo con un'idea e un prezzo entro 2 giorni lavorativi." },
    },
  },
};
