// restorant.mjs — демо „Trattoria Sole": ресторант. Тъмна тема в бордо и крем, серифен дисплей, hero със снимка
// на масата, поръчка за вкъщи (tiles с брояч и сума), меню с цени, резервации, отзиви.
export default {
  id: "restorant",
  slug: { bg: "restorant", en: "restaurant", it: "ristorante" },
  icon: "fork",
  schemaType: "Restaurant",
  theme: {
    mode: "dark", heroStyle: "center", pattern: "glow", radius: "6px",
    fonts: ["Playfair+Display:wght@500;600", "Source+Sans+3:wght@400;500;600"],
    display: "'Playfair Display', Georgia, serif", body: "'Source Sans 3', system-ui, sans-serif",
    bg: "#1a1113", surface: "#241719", surface2: "#2f1e21", text: "#f4ebe4", muted: "#b8a49b",
    accent: "#d9a441", accent2: "#e8bd6a", onAccent: "#1a1113", line: "rgba(244,235,228,.12)",
    word: "SOLE",
  },
  keywords: {
    bg: ["сайт за ресторант", "сайт за ресторант демо", "онлайн меню ресторант", "резервация на маса онлайн", "изработка на сайт за заведение"],
    en: ["restaurant website", "restaurant website demo", "online restaurant menu", "table reservation online", "restaurant web design"],
    it: ["sito ristorante", "sito ristorante demo", "menu online ristorante", "prenotazione tavolo online", "realizzazione sito ristorante"],
  },
  t: {
    bg: {
      name: "Trattoria Sole", category: "Ресторант", city: "София",
      metaTitle: "Trattoria Sole · Италиански ресторант София · Демо сайт",
      metaDesc: "Демо сайт за ресторант: меню с цени, поръчка за вкъщи, резервация на маса, събития, отзиви, FAQ. От Carbon Stealth.",
      address: "ул. Шишман 22, 1000 София", phone: "+359 2 000 0013", email: "ciao@trattoriasole.example",
      hours: ["Пон – Чет: 12:00 – 23:00", "Пет – Съб: 12:00 – 00:30", "Неделя: 12:00 – 22:00"],
      hero: {
        eyebrow: "Италианска кухня · прясна паста всеки ден · София център",
        title: "Пастата се точи <em>в 11 сутринта.</em>",
        lede: "Четири вида прясна паста всяка сутрин, пица от пещ на дърва и вино от 40 малки изби. Резервирате маса за минута, поръчвате за вкъщи и е при вас за 35 минути.",
        cta: "Резервирай маса", cta2: "Виж менюто",
        proof: "★ 4,9 в Google · 1 800+ отзива · Прясна паста от 2014",
        widget: { kind: "tiles", title: "Поръчай за вкъщи", rows: [["Талятеле рагу", "телешко · 6 часа", "14,90 €"], ["Пица Маргерита", "пещ на дърва · фиор ди лате", "10,50 €"], ["Тирамису", "домашно · маскарпоне", "6,50 €"]] },
      },
      badges: ["Прясна паста всеки ден", "Пещ на дърва", "40 изби · вино на чаша", "Доставка за 35 мин"],
      offer: { tag: "Обедно меню", title: "Обяд за 12,90 € — паста + салата + вода, до 15:00 в делник", text: "Две пасти на ден по избор на готвача, сезонна салата и минерална вода. Сервира се до 20 минути, за да се върнете навреме на работа.", cta: "Резервирай за обяд", note: "Валидно от понеделник до петък." },
      servicesTitle: "Какво <em>предлагаме</em>",
      servicesLede: "Кратко меню, което се сменя със сезона. По-добре десет ястия, които са перфектни, отколкото четиридесет.",
      services: [
        { t: "Прясна паста", d: "Талятеле, тортелини, папарделе, ньоки — точени сутринта от нашия пастайо.", p: "от 12 €" },
        { t: "Пица от пещ на дърва", d: "72 часа ферментация, брашно от Неапол, 90 секунди при 450 °C.", p: "от 9 €" },
        { t: "Вино на чаша", d: "40 малки изби от Италия и България, 12 вина на чаша, сомелиер в петък и събота.", p: "от 4 €" },
        { t: "Поръчка за вкъщи", d: "Цялото меню, опаковано така, че пастата да пристигне ал денте. 35 минути в центъра.", p: "доставка 2,90 €" },
        { t: "Частни събития", d: "Залата за 40 души за рождени дни и фирмени вечери, с меню по договаряне.", p: "от 35 € / човек" },
        { t: "Кулинарни уроци", d: "Събота сутрин: прясна паста от нулата с готвача, после обяд с това, което сте направили.", p: "45 €" },
      ],
      about: {
        eyebrow: "За ресторанта", title: "Малка трапезария, <em>големи тенджери</em>",
        p: ["Trattoria Sole отвори през 2014 г. с осем маси и една пещ. Днес масите са 22, но пастата все още се точи на ръка всяка сутрин, а менюто се пише на дъската според това, което е дошло от пазара.", "Готвачът е от Болоня, пастайото — от Пловдив. Половината вина са от малки български изби, защото са добри, не защото са модерни."],
        facts: [{ n: "22", l: "маси" }, { n: "4", l: "вида прясна паста дневно" }, { n: "40", l: "изби" }, { n: "4,9", l: "оценка в Google" }],
      },
      list: { title: "Меню <em>· избрано</em>", lede: "Цени с ДДС. Пълното меню се сменя всеки сезон.", groups: [
        { t: "Паста и пица", items: [["Талятеле с телешко рагу", "14,90 €"], ["Тортелини в бульон", "13,50 €"], ["Ньоки с горгонзола", "12,90 €"], ["Пица Маргерита", "10,50 €"], ["Пица Дяволa", "12,90 €"]] },
        { t: "Десерти и вино", items: [["Тирамису", "6,50 €"], ["Панакота с горски плодове", "6 €"], ["Вино на чаша", "от 4 €"], ["Бутилка от избата", "от 22 €"]] },
      ] },
      reviews: [
        { name: "Йоана В.", text: "Талятелето е като в Болоня, не преувеличавам. Резервирах онлайн за събота и масата ни чакаше точно в 20:00.", stars: 5 },
        { name: "Николай Д.", text: "Поръчахме за вкъщи в дъжда — 28 минути, пастата още беше ал денте. Опаковката е измислена от някой, който яде паста.", stars: 5 },
        { name: "Фирмено събитие", text: "Вечеря за 35 души с меню по договаряне. Нито едно закъснение, нито едно объркано ястие.", stars: 5 },
      ],
      faq: [
        { q: "Как да резервирам маса?", a: "Онлайн от сайта за минута — избирате ден, час и брой хора и получавате SMS потвърждение. За над 8 души ни се обадете." },
        { q: "Доставяте ли?", a: "Да, в центъра на София за 35 минути, доставка 2,90 €, безплатна над 30 €. Поръчвате от сайта, плащате с карта или при доставка." },
        { q: "Имате ли ястия без глутен и вегански?", a: "Да — безглутенова паста и пица всеки ден, три вегански ястия в менюто. Кажете за алергии при резервацията." },
        { q: "Мога ли да доведа деца?", a: "Разбира се. Имаме детски столчета, детско меню и пастата за деца се сервира първа." },
        { q: "Правите ли частни събития?", a: "Да, залата за 40 души е за рождени дни, фирмени вечери и сватбени репетиции. Меню и цена се договарят индивидуално." },
      ],
      contact: { eyebrow: "Контакт", title: "Резервирайте маса <em>или ни пишете</em>", lede: "Отговаряме на телефона в работно време, на имейл — до 2 часа." },
    },
    en: {
      name: "Trattoria Sole", category: "Restaurant", city: "Sofia",
      metaTitle: "Trattoria Sole · Italian Restaurant Sofia · Demo website",
      metaDesc: "Demo website for a restaurant: menu with prices, takeaway ordering, table reservation, events, reviews, FAQ. By Carbon Stealth.",
      address: "22 Shishman St, 1000 Sofia", phone: "+359 2 000 0013", email: "ciao@trattoriasole.example",
      hours: ["Mon – Thu: 12:00 – 23:00", "Fri – Sat: 12:00 – 00:30", "Sunday: 12:00 – 22:00"],
      hero: {
        eyebrow: "Italian kitchen · fresh pasta daily · Sofia centre",
        title: "The pasta is rolled <em>at 11 in the morning.</em>",
        lede: "Four kinds of fresh pasta every morning, wood-fired pizza and wine from 40 small cellars. Book a table in a minute, order takeaway and it is with you in 35 minutes.",
        cta: "Book a table", cta2: "See the menu",
        proof: "★ 4.9 on Google · 1,800+ reviews · Fresh pasta since 2014",
        widget: { kind: "tiles", title: "Order takeaway", rows: [["Tagliatelle ragù", "beef · 6 hours", "€14.90"], ["Pizza Margherita", "wood-fired · fior di latte", "€10.50"], ["Tiramisù", "homemade · mascarpone", "€6.50"]] },
      },
      badges: ["Fresh pasta daily", "Wood-fired oven", "40 cellars · wine by the glass", "Delivery in 35 min"],
      offer: { tag: "Lunch menu", title: "Lunch for €12.90 — pasta + salad + water, weekdays until 15:00", text: "Two pastas a day chosen by the chef, a seasonal salad and mineral water. Served within 20 minutes so you get back to work on time.", cta: "Book for lunch", note: "Valid Monday to Friday." },
      servicesTitle: "What <em>we offer</em>",
      servicesLede: "A short menu that changes with the season. Better ten dishes that are perfect than forty.",
      services: [
        { t: "Fresh pasta", d: "Tagliatelle, tortellini, pappardelle, gnocchi — rolled in the morning by our pastaio.", p: "from €12" },
        { t: "Wood-fired pizza", d: "72-hour fermentation, Neapolitan flour, 90 seconds at 450 °C.", p: "from €9" },
        { t: "Wine by the glass", d: "40 small cellars from Italy and Bulgaria, 12 wines by the glass, sommelier on Fridays and Saturdays.", p: "from €4" },
        { t: "Takeaway", d: "The whole menu, packed so the pasta arrives al dente. 35 minutes in the centre.", p: "delivery €2.90" },
        { t: "Private events", d: "The 40-seat room for birthdays and company dinners, with a menu by arrangement.", p: "from €35 / person" },
        { t: "Cooking classes", d: "Saturday morning: fresh pasta from scratch with the chef, then lunch with what you made.", p: "€45" },
      ],
      about: {
        eyebrow: "About the restaurant", title: "A small dining room, <em>big pots</em>",
        p: ["Trattoria Sole opened in 2014 with eight tables and one oven. Today there are 22 tables, but the pasta is still rolled by hand every morning and the menu is written on the board according to what came from the market.", "The chef is from Bologna, the pastaio from Plovdiv. Half the wines are from small Bulgarian cellars because they are good, not because they are fashionable."],
        facts: [{ n: "22", l: "tables" }, { n: "4", l: "fresh pastas a day" }, { n: "40", l: "cellars" }, { n: "4.9", l: "Google rating" }],
      },
      list: { title: "Menu <em>· selection</em>", lede: "Prices incl. VAT. The full menu changes every season.", groups: [
        { t: "Pasta and pizza", items: [["Tagliatelle with beef ragù", "€14.90"], ["Tortellini in broth", "€13.50"], ["Gnocchi with gorgonzola", "€12.90"], ["Pizza Margherita", "€10.50"], ["Pizza Diavola", "€12.90"]] },
        { t: "Desserts and wine", items: [["Tiramisù", "€6.50"], ["Panna cotta with berries", "€6"], ["Wine by the glass", "from €4"], ["Bottle from the cellar", "from €22"]] },
      ] },
      reviews: [
        { name: "Joanna V.", text: "The tagliatelle is like in Bologna, no exaggeration. Booked online for Saturday and our table was waiting at exactly 20:00.", stars: 5 },
        { name: "Nikolay D.", text: "Ordered takeaway in the rain — 28 minutes, the pasta was still al dente. The packaging was designed by someone who eats pasta.", stars: 5 },
        { name: "Company event", text: "Dinner for 35 with a menu by arrangement. Not one delay, not one mixed-up dish.", stars: 5 },
      ],
      faq: [
        { q: "How do I book a table?", a: "Online from the website in a minute — pick the day, time and number of guests and get an SMS confirmation. For more than 8 people, call us." },
        { q: "Do you deliver?", a: "Yes, in central Sofia within 35 minutes, delivery €2.90, free over €30. Order from the website, pay by card or on delivery." },
        { q: "Do you have gluten-free and vegan dishes?", a: "Yes — gluten-free pasta and pizza every day, three vegan dishes on the menu. Tell us about allergies when booking." },
        { q: "Can I bring children?", a: "Of course. We have high chairs, a children's menu and the kids' pasta is served first." },
        { q: "Do you host private events?", a: "Yes, the 40-seat room is for birthdays, company dinners and rehearsal dinners. Menu and price are arranged individually." },
      ],
      contact: { eyebrow: "Contact", title: "Book a table <em>or write to us</em>", lede: "We answer the phone during opening hours, email within 2 hours." },
    },
    it: {
      name: "Trattoria Sole", category: "Ristorante", city: "Bologna",
      metaTitle: "Trattoria Sole · Ristorante Bologna · Sito demo",
      metaDesc: "Sito demo per ristorante: menu con prezzi, ordine da asporto, prenotazione tavolo, eventi, recensioni, FAQ. Di Carbon Stealth.",
      address: "Via Santo Stefano 22, 40125 Bologna", phone: "+39 051 000 0013", email: "ciao@trattoriasole.example",
      hours: ["Lun – Gio: 12:00 – 23:00", "Ven – Sab: 12:00 – 00:30", "Domenica: 12:00 – 22:00"],
      hero: {
        eyebrow: "Cucina di casa · pasta fresca ogni giorno · Bologna centro",
        title: "La sfoglia si tira <em>alle 11 del mattino.</em>",
        lede: "Quattro tipi di pasta fresca ogni mattina, pizza dal forno a legna e vino di 40 piccole cantine. Prenoti il tavolo in un minuto, ordini da asporto e arriva in 35 minuti.",
        cta: "Prenota un tavolo", cta2: "Vedi il menu",
        proof: "★ 4,9 su Google · 1.800+ recensioni · Pasta fresca dal 2014",
        widget: { kind: "tiles", title: "Ordina da asporto", rows: [["Tagliatelle al ragù", "manzo · 6 ore", "14,90 €"], ["Pizza Margherita", "forno a legna · fior di latte", "10,50 €"], ["Tiramisù", "fatto in casa · mascarpone", "6,50 €"]] },
      },
      badges: ["Pasta fresca ogni giorno", "Forno a legna", "40 cantine · vino al calice", "Consegna in 35 min"],
      offer: { tag: "Menu pranzo", title: "Pranzo a 12,90 € — pasta + insalata + acqua, nei feriali fino alle 15:00", text: "Due paste al giorno a scelta dello chef, insalata di stagione e acqua minerale. Servito entro 20 minuti, per tornare al lavoro in orario.", cta: "Prenota per pranzo", note: "Valido dal lunedì al venerdì." },
      servicesTitle: "Cosa <em>offriamo</em>",
      servicesLede: "Un menu corto che cambia con la stagione. Meglio dieci piatti perfetti che quaranta.",
      services: [
        { t: "Pasta fresca", d: "Tagliatelle, tortellini, pappardelle, gnocchi — tirati al mattino dalla nostra sfoglina.", p: "da 12 €" },
        { t: "Pizza dal forno a legna", d: "72 ore di lievitazione, farina napoletana, 90 secondi a 450 °C.", p: "da 9 €" },
        { t: "Vino al calice", d: "40 piccole cantine italiane e bulgare, 12 vini al calice, sommelier venerdì e sabato.", p: "da 4 €" },
        { t: "Asporto", d: "Tutto il menu, confezionato perché la pasta arrivi al dente. 35 minuti in centro.", p: "consegna 2,90 €" },
        { t: "Eventi privati", d: "La sala da 40 posti per compleanni e cene aziendali, con menu concordato.", p: "da 35 € / persona" },
        { t: "Corsi di cucina", d: "Sabato mattina: pasta fresca da zero con lo chef, poi pranzo con quello che avete fatto.", p: "45 €" },
      ],
      about: {
        eyebrow: "Il ristorante", title: "Una sala piccola, <em>pentole grandi</em>",
        p: ["Trattoria Sole ha aperto nel 2014 con otto tavoli e un forno. Oggi i tavoli sono 22, ma la sfoglia si tira ancora a mano ogni mattina e il menu si scrive sulla lavagna in base a ciò che arriva dal mercato.", "Lo chef è di Bologna, la sfoglina di Plovdiv. Metà dei vini sono di piccole cantine bulgare perché sono buoni, non perché sono di moda."],
        facts: [{ n: "22", l: "tavoli" }, { n: "4", l: "paste fresche al giorno" }, { n: "40", l: "cantine" }, { n: "4,9", l: "valutazione Google" }],
      },
      list: { title: "Menu <em>· selezione</em>", lede: "Prezzi IVA inclusa. Il menu completo cambia ogni stagione.", groups: [
        { t: "Pasta e pizza", items: [["Tagliatelle al ragù di manzo", "14,90 €"], ["Tortellini in brodo", "13,50 €"], ["Gnocchi al gorgonzola", "12,90 €"], ["Pizza Margherita", "10,50 €"], ["Pizza Diavola", "12,90 €"]] },
        { t: "Dolci e vino", items: [["Tiramisù", "6,50 €"], ["Panna cotta ai frutti di bosco", "6 €"], ["Vino al calice", "da 4 €"], ["Bottiglia dalla cantina", "da 22 €"]] },
      ] },
      reviews: [
        { name: "Giovanna V.", text: "Le tagliatelle sono quelle vere, non esagero. Ho prenotato online per sabato e il tavolo ci aspettava alle 20:00 in punto.", stars: 5 },
        { name: "Nicola D.", text: "Asporto sotto la pioggia — 28 minuti, la pasta ancora al dente. La confezione l'ha pensata qualcuno che la pasta la mangia.", stars: 5 },
        { name: "Evento aziendale", text: "Cena per 35 persone con menu concordato. Nessun ritardo, nessun piatto sbagliato.", stars: 5 },
      ],
      faq: [
        { q: "Come prenoto un tavolo?", a: "Online dal sito in un minuto — scegli giorno, ora e numero di persone e ricevi la conferma via SMS. Oltre 8 persone, chiamaci." },
        { q: "Consegnate a domicilio?", a: "Sì, nel centro di Bologna in 35 minuti, consegna 2,90 €, gratuita sopra 30 €. Ordini dal sito, paghi con carta o alla consegna." },
        { q: "Avete piatti senza glutine e vegani?", a: "Sì — pasta e pizza senza glutine ogni giorno, tre piatti vegani nel menu. Segnala le allergie alla prenotazione." },
        { q: "Posso portare i bambini?", a: "Certo. Abbiamo seggioloni, menu bambini e la pasta dei bambini arriva per prima." },
        { q: "Organizzate eventi privati?", a: "Sì, la sala da 40 posti è per compleanni, cene aziendali e prove di matrimonio. Menu e prezzo si concordano." },
      ],
      contact: { eyebrow: "Contatti", title: "Prenota un tavolo <em>o scrivici</em>", lede: "Rispondiamo al telefono in orario di apertura, alle email entro 2 ore." },
    },
  },
};
