// salon.mjs — демо „Atelier Luna": салон за красота / нокти / фризьор. Пудра + графит, центриран hero, ценоразпис.
export default {
  id: "salon",
  slug: { bg: "salon-za-krasota", en: "beauty-salon", it: "salone-bellezza" },
  icon: "scissors",
  schemaType: "BeautySalon",
  theme: {
    mode: "light", heroStyle: "center", pattern: "dots", radius: "16px",
    fonts: ["Cormorant+Garamond:ital,wght@0,500;0,600;1,500", "Jost:wght@400;500;600"],
    display: "'Cormorant Garamond', Georgia, serif", body: "Jost, system-ui, sans-serif",
    bg: "#fbf3f0", surface: "#ffffff", surface2: "#f6e6e1", text: "#2a2224", muted: "#6f6265",
    accent: "#b4585f", accent2: "#d58a8f", onAccent: "#fff8f6", line: "rgba(42,34,36,.12)",
    word: "BEAUTY",
  },
  keywords: {
    bg: ["сайт за салон за красота", "фризьорски салон демо сайт", "сайт за маникюр", "онлайн записване салон", "изработка на сайт за салон"],
    en: ["beauty salon website", "hair salon website demo", "nail salon website", "salon online booking", "salon website design"],
    it: ["sito salone di bellezza", "sito parrucchiere demo", "sito nail salon", "prenotazione online salone", "realizzazione sito salone"],
  },
  t: {
    bg: {
      name: "Atelier Luna", category: "Салон за красота", city: "Бургас",
      metaTitle: "Atelier Luna · Салон за красота Бургас · Демо сайт",
      metaDesc: "Демо сайт за салон за красота: фризьор, маникюр, козметика, ценоразпис, онлайн записване, отзиви. От Carbon Stealth.",
      address: "ул. Александровска 58, 8000 Бургас", phone: "+359 88 000 0005", email: "hello@atelierluna.example",
      hours: ["Пон – Пет: 09:00 – 20:00", "Събота: 09:00 – 18:00", "Неделя: почивен ден"],
      hero: {
        eyebrow: "Коса · нокти · козметика · Бургас център",
        title: "Излизате <em>по-добрата си версия.</em>",
        lede: "Шест майстори, продукти Kérastase и OPI, кафе на влизане и час, който наистина започва навреме. Записвате се онлайн за две минути.",
        cta: "Запази час", cta2: "Ценоразпис",
        widget: { kind: "booking", title: "Запази час", rows: [["Услуга", "Подстригване + стилизиране"], ["Майстор", "Без предпочитание"], ["Дата", "Петък, 17:30"], ["Продължителност", "60 мин · 35 €"]], cta: "Потвърди" },
      },
      badges: ["Онлайн записване 24/7", "Kérastase · OPI · Dermalogica", "SMS напомняне", "Подарък-ваучери"],
      servicesTitle: "Какво <em>правим за вас</em>",
      servicesLede: "Всяка услуга включва консултация — казвате какво искате, ние казваме какво ще стои най-добре.",
      services: [
        { t: "Фризьорски салон", d: "Подстригване, боядисване, балеаж, кератинова терапия, официални прически.", p: "от 20 €" },
        { t: "Маникюр и педикюр", d: "Класически, гел лак, изграждане, японски маникюр, спа педикюр.", p: "от 18 €" },
        { t: "Козметика", d: "Почистване, хидратация, микронидлинг, химически пилинг с Dermalogica.", p: "от 35 €" },
        { t: "Вежди и мигли", d: "Ламиниране, оформяне, боядисване, удължаване косъм по косъм.", p: "от 15 €" },
        { t: "Грим", d: "Дневен, вечерен, сватбен — с проба. Идваме и на място.", p: "от 40 €" },
        { t: "Абонамент „Луна“", d: "Месечен пакет: 1 подстригване + 2 маникюра + 1 процедура за лице.", p: "89 € / мес." },
      ],
      about: {
        eyebrow: "За салона", title: "Шест майстори, <em>едно правило:</em> часът започва навреме",
        p: ["Atelier Luna отвори през 2016 г. с две кресла и обещание — никой не чака. Днес сме шест майстори на 140 м², но правилото е същото: ако се забавим с повече от 10 минути, услугата е с 20% отстъпка.", "Продуктите, които ползваме, можете да купите на място — казваме ви точно кой и защо."],
        facts: [{ n: "6", l: "майстори" }, { n: "9", l: "години" }, { n: "12 000+", l: "записани часа" }, { n: "4,9", l: "оценка в Google" }],
      },
      list: { title: "Ценоразпис", lede: "Крайни цени. Дългата коса не е „допълнителна услуга“.", groups: [
        { t: "Коса", items: [["Дамско подстригване + стилизиране", "35 €"], ["Мъжко подстригване", "20 €"], ["Боядисване корени", "45 €"], ["Балеаж", "от 120 €"], ["Кератинова терапия", "от 150 €"]] },
        { t: "Нокти и лице", items: [["Маникюр с гел лак", "28 €"], ["Изграждане", "от 45 €"], ["Спа педикюр", "40 €"], ["Почистване на лице", "50 €"], ["Ламиниране на вежди", "30 €"]] },
      ] },
      reviews: [
        { name: "Виктория С.", text: "Балеажът излезе точно като снимката, която показах. И наистина започнаха в 17:30, не в 17:50.", stars: 5 },
        { name: "Йоана М.", text: "Абонаментът „Луна“ ми спестява и пари, и мислене. Записвам се от телефона за 1 минута.", stars: 5 },
        { name: "Петя Г.", text: "Сватбен грим с проба две седмици преди. Държа 14 часа, включително сълзите.", stars: 5 },
      ],
      faq: [
        { q: "Как да запазя час?", a: "Онлайн от сайта — избирате услуга, майстор и час; получавате SMS потвърждение и напомняне ден преди." },
        { q: "Мога ли да отменя?", a: "Да, безплатно до 24 часа преди. При по-късна отмяна се дължи 30% от услугата." },
        { q: "Имате ли ваучери за подарък?", a: "Да, за всяка сума или конкретна услуга — електронни или в красива кутия." },
        { q: "Правите ли официални прически на място?", a: "Да — за сватби и събития идваме на адрес в Бургас и региона." },
        { q: "Какви продукти ползвате?", a: "Kérastase и L'Oréal Professionnel за коса, OPI и CND за нокти, Dermalogica за лице." },
      ],
      contact: { eyebrow: "Контакт", title: "Запазете час <em>или попитайте</em>", lede: "Отговаряме бързо и в събота." },
    },
    en: {
      name: "Atelier Luna", category: "Beauty salon", city: "Burgas",
      metaTitle: "Atelier Luna · Beauty Salon Burgas · Demo website",
      metaDesc: "Demo website for a beauty salon: hair, nails, skincare, price list, online booking, reviews. By Carbon Stealth.",
      address: "58 Aleksandrovska St, 8000 Burgas", phone: "+359 88 000 0005", email: "hello@atelierluna.example",
      hours: ["Mon – Fri: 09:00 – 20:00", "Saturday: 09:00 – 18:00", "Sunday: closed"],
      hero: {
        eyebrow: "Hair · nails · skincare · Burgas centre",
        title: "Leave as <em>your better self.</em>",
        lede: "Six stylists, Kérastase and OPI products, coffee on arrival and an appointment that actually starts on time. Book online in two minutes.",
        cta: "Book now", cta2: "Price list",
        widget: { kind: "booking", title: "Book an appointment", rows: [["Service", "Cut + styling"], ["Stylist", "No preference"], ["Date", "Friday, 17:30"], ["Duration", "60 min · €35"]], cta: "Confirm" },
      },
      badges: ["Online booking 24/7", "Kérastase · OPI · Dermalogica", "SMS reminders", "Gift vouchers"],
      servicesTitle: "What <em>we do for you</em>",
      servicesLede: "Every service includes a consultation — you say what you want, we say what will suit you best.",
      services: [
        { t: "Hair", d: "Cuts, colour, balayage, keratin treatment, event styling.", p: "from €20" },
        { t: "Manicure and pedicure", d: "Classic, gel polish, extensions, Japanese manicure, spa pedicure.", p: "from €18" },
        { t: "Skincare", d: "Cleansing, hydration, microneedling, chemical peel with Dermalogica.", p: "from €35" },
        { t: "Brows and lashes", d: "Lamination, shaping, tinting, lash extensions.", p: "from €15" },
        { t: "Make-up", d: "Day, evening, bridal — with a trial. We also come to you.", p: "from €40" },
        { t: "“Luna” membership", d: "Monthly package: 1 cut + 2 manicures + 1 facial.", p: "€89 / month" },
      ],
      about: {
        eyebrow: "About the salon", title: "Six stylists, <em>one rule:</em> appointments start on time",
        p: ["Atelier Luna opened in 2016 with two chairs and a promise — nobody waits. Today we are six stylists on 140 m², but the rule is the same: if we run more than 10 minutes late, the service is 20% off.", "The products we use can be bought on site — we tell you exactly which and why."],
        facts: [{ n: "6", l: "stylists" }, { n: "9", l: "years" }, { n: "12,000+", l: "appointments" }, { n: "4.9", l: "Google rating" }],
      },
      list: { title: "Price list", lede: "Final prices. Long hair is not an “extra”.", groups: [
        { t: "Hair", items: [["Women's cut + styling", "€35"], ["Men's cut", "€20"], ["Root colour", "€45"], ["Balayage", "from €120"], ["Keratin treatment", "from €150"]] },
        { t: "Nails and face", items: [["Gel polish manicure", "€28"], ["Extensions", "from €45"], ["Spa pedicure", "€40"], ["Facial cleansing", "€50"], ["Brow lamination", "€30"]] },
      ] },
      reviews: [
        { name: "Victoria S.", text: "The balayage came out exactly like the photo I showed. And they really started at 17:30, not 17:50.", stars: 5 },
        { name: "Joanna M.", text: "The “Luna” membership saves me money and thinking. I book from my phone in 1 minute.", stars: 5 },
        { name: "Petya G.", text: "Bridal make-up with a trial two weeks before. It lasted 14 hours, tears included.", stars: 5 },
      ],
      faq: [
        { q: "How do I book?", a: "Online from the website — pick a service, stylist and time; you get an SMS confirmation and a reminder the day before." },
        { q: "Can I cancel?", a: "Yes, free of charge up to 24 hours before. Later cancellations are charged 30% of the service." },
        { q: "Do you have gift vouchers?", a: "Yes, for any amount or a specific service — digital or in a lovely box." },
        { q: "Do you do event styling on location?", a: "Yes — for weddings and events we come to your address in Burgas and the region." },
        { q: "Which products do you use?", a: "Kérastase and L'Oréal Professionnel for hair, OPI and CND for nails, Dermalogica for skin." },
      ],
      contact: { eyebrow: "Contact", title: "Book an appointment <em>or ask</em>", lede: "We reply quickly, Saturdays included." },
    },
    it: {
      name: "Atelier Luna", category: "Salone di bellezza", city: "Firenze",
      metaTitle: "Atelier Luna · Salone di bellezza Firenze · Sito demo",
      metaDesc: "Sito demo per salone di bellezza: parrucchiere, unghie, estetica, listino, prenotazione online, recensioni. Di Carbon Stealth.",
      address: "Via de' Tornabuoni 58, 50123 Firenze", phone: "+39 055 000 0005", email: "ciao@atelierluna.example",
      hours: ["Lun – Ven: 09:00 – 20:00", "Sabato: 09:00 – 18:00", "Domenica: chiuso"],
      hero: {
        eyebrow: "Capelli · unghie · estetica · Firenze centro",
        title: "Esci <em>nella tua versione migliore.</em>",
        lede: "Sei professionisti, prodotti Kérastase e OPI, caffè all'arrivo e un appuntamento che inizia davvero in orario. Prenoti online in due minuti.",
        cta: "Prenota", cta2: "Listino",
        widget: { kind: "booking", title: "Prenota un appuntamento", rows: [["Servizio", "Taglio + piega"], ["Professionista", "Nessuna preferenza"], ["Data", "Venerdì, 17:30"], ["Durata", "60 min · 35 €"]], cta: "Conferma" },
      },
      badges: ["Prenotazione online 24/7", "Kérastase · OPI · Dermalogica", "Promemoria SMS", "Buoni regalo"],
      servicesTitle: "Cosa <em>facciamo per te</em>",
      servicesLede: "Ogni servizio include una consulenza — tu dici cosa vuoi, noi diciamo cosa ti starà meglio.",
      services: [
        { t: "Parrucchiere", d: "Taglio, colore, balayage, trattamento alla cheratina, acconciature per eventi.", p: "da 20 €" },
        { t: "Manicure e pedicure", d: "Classica, semipermanente, ricostruzione, manicure giapponese, pedicure spa.", p: "da 18 €" },
        { t: "Estetica viso", d: "Pulizia, idratazione, microneedling, peeling chimico con Dermalogica.", p: "da 35 €" },
        { t: "Sopracciglia e ciglia", d: "Laminazione, definizione, tinta, extension ciglia una a una.", p: "da 15 €" },
        { t: "Trucco", d: "Giorno, sera, sposa — con prova. Veniamo anche a domicilio.", p: "da 40 €" },
        { t: "Abbonamento «Luna»", d: "Pacchetto mensile: 1 taglio + 2 manicure + 1 trattamento viso.", p: "89 € / mese" },
      ],
      about: {
        eyebrow: "Il salone", title: "Sei professionisti, <em>una regola:</em> si inizia in orario",
        p: ["Atelier Luna ha aperto nel 2016 con due poltrone e una promessa — nessuno aspetta. Oggi siamo sei professionisti su 140 m², ma la regola è la stessa: se ritardiamo più di 10 minuti, il servizio è scontato del 20%.", "I prodotti che usiamo si possono comprare in salone — ti diciamo esattamente quale e perché."],
        facts: [{ n: "6", l: "professionisti" }, { n: "9", l: "anni" }, { n: "12.000+", l: "appuntamenti" }, { n: "4,9", l: "valutazione Google" }],
      },
      list: { title: "Listino", lede: "Prezzi definitivi. I capelli lunghi non sono un «extra».", groups: [
        { t: "Capelli", items: [["Taglio donna + piega", "35 €"], ["Taglio uomo", "20 €"], ["Colore ricrescita", "45 €"], ["Balayage", "da 120 €"], ["Trattamento cheratina", "da 150 €"]] },
        { t: "Unghie e viso", items: [["Manicure semipermanente", "28 €"], ["Ricostruzione", "da 45 €"], ["Pedicure spa", "40 €"], ["Pulizia viso", "50 €"], ["Laminazione sopracciglia", "30 €"]] },
      ] },
      reviews: [
        { name: "Vittoria S.", text: "Il balayage è venuto esattamente come la foto che ho mostrato. E hanno iniziato davvero alle 17:30, non alle 17:50.", stars: 5 },
        { name: "Giovanna M.", text: "L'abbonamento «Luna» mi fa risparmiare soldi e pensieri. Prenoto dal telefono in 1 minuto.", stars: 5 },
        { name: "Petra G.", text: "Trucco sposa con prova due settimane prima. Ha retto 14 ore, lacrime comprese.", stars: 5 },
      ],
      faq: [
        { q: "Come prenoto?", a: "Online dal sito — scegli servizio, professionista e orario; ricevi conferma via SMS e un promemoria il giorno prima." },
        { q: "Posso disdire?", a: "Sì, gratuitamente fino a 24 ore prima. Disdette successive: 30% del servizio." },
        { q: "Avete buoni regalo?", a: "Sì, per qualsiasi importo o servizio specifico — digitali o in una bella scatola." },
        { q: "Fate acconciature a domicilio?", a: "Sì — per matrimoni ed eventi veniamo al tuo indirizzo a Firenze e provincia." },
        { q: "Quali prodotti usate?", a: "Kérastase e L'Oréal Professionnel per i capelli, OPI e CND per le unghie, Dermalogica per il viso." },
      ],
      contact: { eyebrow: "Contatti", title: "Prenota <em>o chiedi</em>", lede: "Rispondiamo in fretta, anche il sabato." },
    },
  },
};
