// schetovodstvo.mjs — демо „Balance Pro": счетоводна къща. Бяло + кралско синьо, editorial hero, KPI карта.
export default {
  id: "schetovodstvo",
  slug: { bg: "schetovodna-kashta", en: "accounting-firm", it: "studio-commercialista" },
  icon: "calc",
  schemaType: "AccountingService",
  theme: {
    mode: "light", heroStyle: "editorial", pattern: "grid", radius: "10px",
    fonts: ["Sora:wght@600;700", "IBM+Plex+Sans:wght@400;500;600"],
    display: "Sora, system-ui, sans-serif", body: "'IBM Plex Sans', system-ui, sans-serif",
    bg: "#f7f9fc", surface: "#ffffff", surface2: "#eaf0fa", text: "#0f1b33", muted: "#586378",
    accent: "#1d4ed8", accent2: "#3b82f6", onAccent: "#ffffff", line: "rgba(15,27,51,.11)",
    word: "BALANCE",
  },
  keywords: {
    bg: ["сайт за счетоводна къща", "счетоводител демо сайт", "счетоводни услуги сайт", "уеб сайт счетоводство", "изработка на сайт за счетоводител"],
    en: ["accounting firm website", "accountant website demo", "bookkeeping website", "tax advisor website", "accounting website design"],
    it: ["sito studio commercialista", "sito commercialista demo", "sito contabilità", "consulente fiscale sito", "realizzazione sito commercialista"],
  },
  t: {
    bg: {
      name: "Balance Pro", category: "Счетоводна къща", city: "Пловдив",
      metaTitle: "Balance Pro · Счетоводна къща Пловдив · Демо сайт",
      metaDesc: "Демо сайт за счетоводна къща: месечни пакети с цени, ДДС, ТРЗ, годишно приключване, онлайн портал, отзиви. От Carbon Stealth.",
      address: "ул. Иван Вазов 25, 4000 Пловдив", phone: "+359 32 000 0007", email: "office@balancepro.example",
      hours: ["Пон – Пет: 09:00 – 17:30", "Събота – Неделя: почивни дни", "Онлайн портал: 24/7"],
      hero: {
        eyebrow: "Счетоводство · ТРЗ · данъчни консултации · Пловдив",
        title: "Числата ви — <em>в ред, навреме, без изненади.</em>",
        lede: "Счетоводна къща за малки и средни фирми: фиксирана месечна цена, портал с всички документи и счетоводител, който отговаря същия ден. Работим и с фирми с чуждестранни собственици.",
        cta: "Безплатна консултация", cta2: "Виж пакетите",
        widget: { kind: "stats", title: "Вашият портал — в реално време", rows: [["14 250 €", "приходи този месец"], ["2 850 €", "ДДС за внасяне до 14-ти"], ["6", "служители · ТРЗ готово"], ["0", "просрочени срокове", "wide"]], cta: "Вход в портала" },
      },
      badges: ["Фиксирана месечна цена", "Отговор същия работен ден", "Онлайн портал 24/7", "Застраховка професионална отговорност"],
      servicesTitle: "Услуги <em>с ясна цена</em>",
      servicesLede: "Всичко, от което една фирма има нужда, в един договор. Без такси „на документ“.",
      services: [
        { t: "Месечно счетоводство", d: "Осчетоводяване, ДДС декларации, Интрастат, отчети към НАП и НСИ.", p: "от 90 € / мес." },
        { t: "ТРЗ и личен състав", d: "Трудови договори, ведомости, болнични, декларации 1 и 6, служебни бележки.", p: "от 12 € / служител" },
        { t: "Годишно приключване", d: "ГФО, ГДД, публикуване в Търговския регистър. Включено в месечните пакети." },
        { t: "Данъчни консултации", d: "ДДС в ЕС, дивиденти, трансферни цени, данъчни проверки и ревизии.", p: "60 € / час" },
        { t: "Регистрация на фирма", d: "ЕООД/ООД за 3 дни, ДДС регистрация, откриване на сметка, всичко онлайн.", p: "150 €" },
        { t: "Чуждестранни собственици", d: "Комуникация на английски и италиански, отчети по международни стандарти." },
      ],
      about: {
        eyebrow: "За кантората", title: "Дванадесет счетоводители, <em>една отговорност</em>",
        p: ["Balance Pro обслужва 230 фирми от 2011 г. — от фрийлансъри до производители със 120 служители. Всеки клиент има конкретен счетоводител и заместник, който познава фирмата.", "Работим изцяло дигитално: качвате фактурите в портала или ги снимате с телефона, ние правим останалото. Хартия не е нужна."],
        facts: [{ n: "230", l: "обслужвани фирми" }, { n: "14", l: "години" }, { n: "12", l: "счетоводители" }, { n: "0", l: "пропуснати срока през 2025" }],
      },
      steps: { title: "Как започваме <em>заедно</em>", items: [{ t: "Разговор", d: "30 минути за дейността, обема и това, което не ви харесва в момента." }, { t: "Оферта", d: "Фиксирана месечна цена по обем документи и служители. Писмено, без дребен шрифт." }, { t: "Прехвърляне", d: "Взимаме документите от стария счетоводител и настройваме портала. Вие не правите нищо." }, { t: "Първи месец", d: "Отчет и среща — виждате къде сте и какво може да се оптимизира." }] },
      reviews: [
        { name: "Управител, онлайн магазин", text: "ДДС по OSS в 6 държави и никога проблем. Отговарят за минути в чата на портала.", stars: 5 },
        { name: "Собственик, ресторант", text: "Смених трима счетоводители за 5 години. Тук за първи път знам какво плащам и защо.", stars: 5 },
        { name: "Italian founder, Plovdiv", text: "Всичко на английски, отчетите в срок, а данъчната ревизия мина без нито една забележка.", stars: 5 },
      ],
      faq: [
        { q: "Как се определя месечната цена?", a: "По брой документи и служители, фиксирана за 12 месеца. Ако обемът се промени значително, преговаряме — не ви изненадваме с фактура." },
        { q: "Мога ли да сменя счетоводителя си без прекъсване?", a: "Да. Взимаме документите и базата от предишния счетоводител и поемаме от следващия месец." },
        { q: "Работите ли с чуждестранни собственици?", a: "Да — на английски и италиански, с отчети и обяснения, подходящи за чуждестранен управител." },
        { q: "Какво става при данъчна проверка?", a: "Ние отговаряме на НАП и присъстваме на проверката. Включено е в пакета." },
        { q: "Има ли договор с обвързване?", a: "Не. Договорът е безсрочен с едномесечно предизвестие." },
      ],
      contact: { eyebrow: "Контакт", title: "Кажете ни <em>за фирмата си</em>", lede: "Оферта за месечна цена до 24 часа." },
    },
    en: {
      name: "Balance Pro", category: "Accounting firm", city: "Plovdiv",
      metaTitle: "Balance Pro · Accounting Firm Plovdiv · Demo website",
      metaDesc: "Demo website for an accounting firm: monthly packages with prices, VAT, payroll, year-end closing, online portal, reviews. By Carbon Stealth.",
      address: "25 Ivan Vazov St, 4000 Plovdiv", phone: "+359 32 000 0007", email: "office@balancepro.example",
      hours: ["Mon – Fri: 09:00 – 17:30", "Saturday – Sunday: closed", "Online portal: 24/7"],
      hero: {
        eyebrow: "Accounting · payroll · tax advice · Plovdiv",
        title: "Your numbers — <em>in order, on time, no surprises.</em>",
        lede: "An accounting firm for small and medium businesses: a fixed monthly price, a portal with all your documents and an accountant who replies the same day. We also work with foreign-owned companies.",
        cta: "Free consultation", cta2: "See packages",
        widget: { kind: "stats", title: "Your portal — in real time", rows: [["€14,250", "revenue this month"], ["€2,850", "VAT due by the 14th"], ["6", "employees · payroll ready"], ["0", "overdue deadlines", "wide"]], cta: "Log in to the portal" },
      },
      badges: ["Fixed monthly price", "Same-day reply", "Online portal 24/7", "Professional liability insurance"],
      servicesTitle: "Services <em>with a clear price</em>",
      servicesLede: "Everything a company needs in one contract. No “per document” fees.",
      services: [
        { t: "Monthly bookkeeping", d: "Bookkeeping, VAT returns, Intrastat, reports to the tax and statistics offices.", p: "from €90 / month" },
        { t: "Payroll and HR", d: "Employment contracts, payslips, sick leave, declarations, employee certificates.", p: "from €12 / employee" },
        { t: "Year-end closing", d: "Annual financial statements, tax return, filing with the Commercial Register. Included in monthly packages." },
        { t: "Tax advice", d: "EU VAT, dividends, transfer pricing, tax audits and inspections.", p: "€60 / hour" },
        { t: "Company registration", d: "Ltd in 3 days, VAT registration, bank account, all online.", p: "€150" },
        { t: "Foreign owners", d: "Communication in English and Italian, reports under international standards." },
      ],
      about: {
        eyebrow: "About the firm", title: "Twelve accountants, <em>one responsibility</em>",
        p: ["Balance Pro has served 230 companies since 2011 — from freelancers to manufacturers with 120 employees. Every client has a named accountant and a deputy who knows the company.", "We work fully digitally: upload invoices to the portal or photograph them with your phone, we do the rest. No paper needed."],
        facts: [{ n: "230", l: "companies served" }, { n: "14", l: "years" }, { n: "12", l: "accountants" }, { n: "0", l: "missed deadlines in 2025" }],
      },
      steps: { title: "How we <em>start together</em>", items: [{ t: "Conversation", d: "30 minutes about your business, volume and what you dislike right now." }, { t: "Quote", d: "A fixed monthly price by document volume and employees. In writing, no small print." }, { t: "Handover", d: "We collect documents from your previous accountant and set up the portal. You do nothing." }, { t: "First month", d: "Report and meeting — you see where you stand and what can be optimised." }] },
      reviews: [
        { name: "Manager, online shop", text: "OSS VAT in 6 countries and never a problem. They answer within minutes in the portal chat.", stars: 5 },
        { name: "Owner, restaurant", text: "I changed three accountants in 5 years. Here, for the first time, I know what I pay and why.", stars: 5 },
        { name: "Italian founder, Plovdiv", text: "Everything in English, reports on time, and the tax audit passed without a single remark.", stars: 5 },
      ],
      faq: [
        { q: "How is the monthly price set?", a: "By number of documents and employees, fixed for 12 months. If volume changes significantly, we renegotiate — we never surprise you with an invoice." },
        { q: "Can I switch accountants without interruption?", a: "Yes. We collect documents and data from your previous accountant and take over from the next month." },
        { q: "Do you work with foreign owners?", a: "Yes — in English and Italian, with reports and explanations suited to a foreign manager." },
        { q: "What happens during a tax audit?", a: "We respond to the tax office and attend the audit. It is included in the package." },
        { q: "Is there a lock-in contract?", a: "No. The contract is open-ended with one month's notice." },
      ],
      contact: { eyebrow: "Contact", title: "Tell us <em>about your company</em>", lede: "A monthly price quote within 24 hours." },
    },
    it: {
      name: "Balance Pro", category: "Studio commercialista", city: "Bologna",
      metaTitle: "Balance Pro · Studio commercialista Bologna · Sito demo",
      metaDesc: "Sito demo per studio commercialista: pacchetti mensili con prezzi, IVA, paghe, bilancio, portale online, recensioni. Di Carbon Stealth.",
      address: "Via Indipendenza 25, 40121 Bologna", phone: "+39 051 000 0007", email: "studio@balancepro.example",
      hours: ["Lun – Ven: 09:00 – 17:30", "Sabato – Domenica: chiuso", "Portale online: 24/7"],
      hero: {
        eyebrow: "Contabilità · paghe · consulenza fiscale · Bologna",
        title: "I tuoi numeri — <em>in ordine, puntuali, senza sorprese.</em>",
        lede: "Uno studio per piccole e medie imprese: canone mensile fisso, un portale con tutti i documenti e un commercialista che risponde in giornata. Lavoriamo anche con società a proprietà estera.",
        cta: "Consulenza gratuita", cta2: "Vedi i pacchetti",
        widget: { kind: "stats", title: "Il tuo portale — in tempo reale", rows: [["14.250 €", "ricavi questo mese"], ["2.850 €", "IVA da versare entro il 16"], ["6", "dipendenti · paghe pronte"], ["0", "scadenze in ritardo", "wide"]], cta: "Accedi al portale" },
      },
      badges: ["Canone mensile fisso", "Risposta in giornata", "Portale online 24/7", "Assicurazione responsabilità professionale"],
      servicesTitle: "Servizi <em>con prezzo chiaro</em>",
      servicesLede: "Tutto ciò che serve a un'azienda in un solo contratto. Nessun costo «a documento».",
      services: [
        { t: "Contabilità mensile", d: "Registrazioni, liquidazioni IVA, Intrastat, comunicazioni ad Agenzia delle Entrate e ISTAT.", p: "da 90 € / mese" },
        { t: "Paghe e personale", d: "Contratti, cedolini, malattie, UniEmens, CU e certificazioni.", p: "da 12 € / dipendente" },
        { t: "Bilancio annuale", d: "Bilancio, dichiarazione dei redditi, deposito al Registro Imprese. Incluso nei pacchetti mensili." },
        { t: "Consulenza fiscale", d: "IVA UE, dividendi, transfer pricing, verifiche e accertamenti.", p: "60 € / ora" },
        { t: "Apertura società", d: "SRL in 3 giorni, partita IVA, conto corrente, tutto online.", p: "150 €" },
        { t: "Titolari esteri", d: "Comunicazione in inglese e bulgaro, report secondo standard internazionali." },
      ],
      about: {
        eyebrow: "Lo studio", title: "Dodici professionisti, <em>una responsabilità</em>",
        p: ["Balance Pro segue 230 aziende dal 2011 — da freelance a produttori con 120 dipendenti. Ogni cliente ha un commercialista di riferimento e un sostituto che conosce l'azienda.", "Lavoriamo in modo completamente digitale: carichi le fatture nel portale o le fotografi col telefono, al resto pensiamo noi. Niente carta."],
        facts: [{ n: "230", l: "aziende seguite" }, { n: "14", l: "anni" }, { n: "12", l: "professionisti" }, { n: "0", l: "scadenze mancate nel 2025" }],
      },
      steps: { title: "Come <em>iniziamo insieme</em>", items: [{ t: "Colloquio", d: "30 minuti su attività, volumi e ciò che non ti piace oggi." }, { t: "Preventivo", d: "Canone mensile fisso in base a documenti e dipendenti. Per iscritto, senza asterischi." }, { t: "Passaggio", d: "Ritiriamo i documenti dal vecchio commercialista e configuriamo il portale. Tu non fai nulla." }, { t: "Primo mese", d: "Report e incontro — vedi dove sei e cosa si può ottimizzare." }] },
      reviews: [
        { name: "Titolare, e-commerce", text: "IVA OSS in 6 Paesi e mai un problema. Rispondono in pochi minuti nella chat del portale.", stars: 5 },
        { name: "Titolare, ristorante", text: "Ho cambiato tre commercialisti in 5 anni. Qui per la prima volta so cosa pago e perché.", stars: 5 },
        { name: "Fondatore bulgaro, Bologna", text: "Tutto in bulgaro, report puntuali, e la verifica fiscale è passata senza un rilievo.", stars: 5 },
      ],
      faq: [
        { q: "Come si determina il canone mensile?", a: "In base a numero di documenti e dipendenti, fisso per 12 mesi. Se il volume cambia molto, rinegoziamo — non ti sorprendiamo con una fattura." },
        { q: "Posso cambiare commercialista senza interruzioni?", a: "Sì. Ritiriamo documenti e dati dal precedente e subentriamo dal mese successivo." },
        { q: "Lavorate con titolari esteri?", a: "Sì — in inglese e bulgaro, con report e spiegazioni adatte a un amministratore straniero." },
        { q: "Cosa succede in caso di verifica fiscale?", a: "Rispondiamo noi all'Agenzia e siamo presenti alla verifica. È incluso nel pacchetto." },
        { q: "C'è un contratto vincolante?", a: "No. Il contratto è a tempo indeterminato con un mese di preavviso." },
      ],
      contact: { eyebrow: "Contatti", title: "Parlaci <em>della tua azienda</em>", lede: "Preventivo del canone mensile entro 24 ore." },
    },
  },
};
