// stroitelstvo.mjs — демо „Bauhaus Build": строителство и ремонти. Тъмна индустриална тема с оранжев акцент,
// кондензиран дисплей, hero с обект в ремонт, безплатен оглед и оферта за 48 часа (consult), стъпки, ценоразпис.
export default {
  id: "stroitelstvo",
  slug: { bg: "stroitelstvo-i-remonti", en: "construction-company", it: "impresa-edile" },
  icon: "hardhat",
  schemaType: "GeneralContractor",
  theme: {
    mode: "dark", heroStyle: "split", pattern: "stripes", radius: "2px",
    fonts: ["Barlow+Condensed:wght@600;700", "Barlow:wght@400;500;600"],
    display: "'Barlow Condensed', 'Inter Tight', sans-serif", body: "Barlow, system-ui, sans-serif",
    bg: "#131416", surface: "#1b1d20", surface2: "#25282c", text: "#f2f2ef", muted: "#a2a6ab",
    accent: "#f28c28", accent2: "#f7a94f", onAccent: "#131416", line: "rgba(242,242,239,.12)",
    word: "BUILD",
  },
  keywords: {
    bg: ["сайт за строителна фирма", "сайт за ремонти демо", "строителство и ремонти цени", "оферта за ремонт онлайн", "изработка на сайт за строител"],
    en: ["construction company website", "renovation company website demo", "building and renovation prices", "online renovation quote", "contractor web design"],
    it: ["sito impresa edile", "sito ristrutturazioni demo", "prezzi ristrutturazione", "preventivo ristrutturazione online", "realizzazione sito impresa"],
  },
  t: {
    bg: {
      name: "Bauhaus Build", category: "Строителство и ремонти", city: "София",
      metaTitle: "Bauhaus Build · Строителство и ремонти София · Демо сайт",
      metaDesc: "Демо сайт за строителна фирма: ремонти до ключ, груб строеж, цени на м², безплатен оглед и оферта за 48 часа, отзиви, FAQ. От Carbon Stealth.",
      address: "бул. Черни връх 100, 1407 София", phone: "+359 2 000 0015", email: "office@bauhausbuild.example",
      hours: ["Пон – Пет: 08:00 – 18:00", "Събота: 09:00 – 13:00", "Огледи: по уговорка, включително вечер"],
      hero: {
        eyebrow: "Ремонти до ключ · груб строеж · покриви · София и региона",
        title: "Ремонт с фиксирана цена <em>и дата на ключа.</em>",
        lede: "Двадесет и осем работници на щат, собствен склад и инженер на всеки обект. Офертата е с фиксирана цена и краен срок, за всеки ден закъснение плащаме ние.",
        cta: "Безплатен оглед", cta2: "Цени на м²",
        proof: "★ 4,8 в Google · 620 завършени обекта · 0,5% закъснения за 2025",
        widget: { kind: "consult", title: "Безплатен оглед и оферта за 48 часа", rows: ["Инженер на място, замерване и снимки", "Оферта по позиции с материали и труд", "Фиксирана цена и дата на предаване", "Неустойка 100 € на ден закъснение"], cta: "Заяви оглед" },
      },
      badges: ["Фиксирана цена", "Неустойка при закъснение", "5 години гаранция", "Собствени екипи, не подизпълнители"],
      offer: { tag: "Есен 2026", title: "Баня до ключ за 14 дни — от 4 900 €", text: "Демонтаж, ВиК и ел. инсталация, хидроизолация, плочки до 60 €/м², окачен таван, санитария Grohe/Ideal Standard. Цената включва материалите и извозването.", cta: "Заяви оглед", note: "Цените са примерни за демото." },
      servicesTitle: "Какво <em>строим и ремонтираме</em>",
      servicesLede: "Ценоразписът е публичен, защото и без това ще го научите от съседа.",
      services: [
        { t: "Ремонт до ключ", d: "Апартаменти и къщи: от проект до последния ключ. Един договор, един отговорник.", p: "от 420 €/м²" },
        { t: "Бани и кухни", d: "Демонтаж, инсталации, хидроизолация, плочки, мебели по поръчка.", p: "от 4 900 €" },
        { t: "Груб строеж", d: "Къщи и малки сгради: изкоп, фундамент, конструкция, покрив. Собствен кран.", p: "от 380 €/м²" },
        { t: "Покриви и изолации", d: "Ремонт и нови покриви, хидро- и топлоизолация, водосточни системи.", p: "от 45 €/м²" },
        { t: "Електро и ВиК", d: "Нови инсталации, табла, слаботокови системи, соларни системи до 10 kW.", p: "от 35 €/точка" },
        { t: "Довършителни работи", d: "Шпакловка, боя, паркет, гипсокартон, декоративни мазилки.", p: "от 18 €/м²" },
      ],
      about: {
        eyebrow: "За фирмата", title: "Фиксирана цена. <em>Фиксирана дата.</em>",
        p: ["Bauhaus Build е основана през 2009 г. от двама строителни инженери, които се умориха да гледат как ремонтите се точат по два пъти по-дълго от обещаното. Затова договорът ни има две числа, които не мърдат: цена и дата.", "Двадесет и осемте работници са на щат, с осигуровки и обучение. Не работим с подизпълнители, защото не можем да гарантираме тяхната работа — а вие получавате 5 години гаранция за нашата."],
        facts: [{ n: "28", l: "работници на щат" }, { n: "620", l: "завършени обекта" }, { n: "5", l: "години гаранция" }, { n: "0,5%", l: "закъснения 2025" }],
      },
      steps: { title: "Как <em>протича ремонтът</em>", items: [
        { t: "Оглед", d: "Инженер идва на място, замерва, снима и слуша какво искате. Безплатно, до 48 часа." },
        { t: "Оферта по позиции", d: "Материали и труд по отделно, с марки и количества. Фиксирана цена и дата." },
        { t: "Изпълнение", d: "Екип от 3–6 души на обекта всеки ден, седмичен отчет със снимки в приложението." },
        { t: "Предаване", d: "Обход заедно, протокол, гаранционна книжка. Извозваме всичко до последния чувал." },
      ] },
      list: { title: "Цени на м²", lede: "Ориентировъчни цени с ДДС, материали и труд. Точната цена е в офертата след оглед.", groups: [
        { t: "Ремонт", items: [["Ремонт до ключ · стандарт", "420 €/м²"], ["Ремонт до ключ · премиум", "680 €/м²"], ["Баня до ключ (до 6 м²)", "от 4 900 €"], ["Кухня до ключ (без мебели)", "от 3 200 €"]] },
        { t: "Строеж", items: [["Груб строеж къща", "380 €/м²"], ["Къща до ключ", "от 950 €/м²"], ["Покрив нов · керемиди", "от 85 €/м²"], ["Топлоизолация 10 см", "от 45 €/м²"]] },
      ] },
      reviews: [
        { name: "Ивайло К.", text: "Ремонт на 92 м² за 38 дни при обещани 40. Офертата беше по позиции и крайната сума беше същата до евро.", stars: 5 },
        { name: "Управител, дентална клиника", text: "Ремонт на клиника за 3 седмици, работиха и нощем, за да не затваряме. Инженерът отговаряше на телефона в 22:00.", stars: 5 },
        { name: "Р. и М. Петрови", text: "Къща от нулата за 11 месеца. Всяка седмица снимки в приложението, всеки разход — в таблицата. Нула изненади.", stars: 5 },
      ],
      faq: [
        { q: "Наистина ли цената е фиксирана?", a: "Да. Промяна има само ако вие промените проекта — тогава подписваме анекс с новата цена и дата, преди да продължим." },
        { q: "Какво става при закъснение?", a: "Плащаме неустойка 100 € на ден, приспадната от последната вноска. През 2025 г. сме закъснели на 3 от 600 обекта." },
        { q: "Кой купува материалите?", a: "Ние, на цени на едро, с фактури, които виждате. Може и вие да купите някои — приспадаме ги от офертата." },
        { q: "Как се плаща?", a: "30% при старт, 40% на средата, 30% при предаване. За обекти над 50 000 € — на 5 вноски по етапи." },
        { q: "Каква е гаранцията?", a: "5 години за конструкция, инсталации и хидроизолация, 2 години за довършителни работи. Гаранционна книжка при предаване." },
      ],
      contact: { eyebrow: "Контакт", title: "Заявете оглед <em>или пратете снимки</em>", lede: "Отговаряме до 2 часа; оглед до 48 часа в София и региона." },
    },
    en: {
      name: "Bauhaus Build", category: "Construction and renovation", city: "Sofia",
      metaTitle: "Bauhaus Build · Construction and Renovation Sofia · Demo",
      metaDesc: "Demo website for a construction company: turnkey renovation, structural work, prices per m², free site visit and 48-hour quote, reviews. By Carbon Stealth.",
      address: "100 Cherni Vrah Blvd, 1407 Sofia", phone: "+359 2 000 0015", email: "office@bauhausbuild.example",
      hours: ["Mon – Fri: 08:00 – 18:00", "Saturday: 09:00 – 13:00", "Site visits: by arrangement, evenings too"],
      hero: {
        eyebrow: "Turnkey renovation · structural work · roofs · Sofia and region",
        title: "Renovation with a fixed price <em>and a key date.</em>",
        lede: "Twenty-eight employed workers, our own warehouse and an engineer on every site. The quote has a fixed price and a deadline — for every day of delay, we pay.",
        cta: "Free site visit", cta2: "Prices per m²",
        proof: "★ 4.8 on Google · 620 completed projects · 0.5% delays in 2025",
        widget: { kind: "consult", title: "Free site visit and quote in 48 hours", rows: ["Engineer on site, measurements and photos", "Itemised quote with materials and labour", "Fixed price and handover date", "€100 penalty per day of delay"], cta: "Request a visit" },
      },
      badges: ["Fixed price", "Delay penalty", "5-year warranty", "Own crews, no subcontractors"],
      offer: { tag: "Autumn 2026", title: "Turnkey bathroom in 14 days — from €4,900", text: "Demolition, plumbing and wiring, waterproofing, tiles up to €60/m², suspended ceiling, Grohe/Ideal Standard fittings. Price includes materials and waste removal.", cta: "Request a visit", note: "Prices are examples for the demo." },
      servicesTitle: "What <em>we build and renovate</em>",
      servicesLede: "The price list is public because you would find it out from a neighbour anyway.",
      services: [
        { t: "Turnkey renovation", d: "Flats and houses: from design to the last key. One contract, one person in charge.", p: "from €420/m²" },
        { t: "Bathrooms and kitchens", d: "Demolition, installations, waterproofing, tiling, custom furniture.", p: "from €4,900" },
        { t: "Structural work", d: "Houses and small buildings: excavation, foundations, structure, roof. Own crane.", p: "from €380/m²" },
        { t: "Roofs and insulation", d: "Repairs and new roofs, waterproofing and thermal insulation, gutters.", p: "from €45/m²" },
        { t: "Electrical and plumbing", d: "New installations, panels, low-voltage systems, solar systems up to 10 kW.", p: "from €35/point" },
        { t: "Finishing works", d: "Plastering, painting, parquet, drywall, decorative renders.", p: "from €18/m²" },
      ],
      about: {
        eyebrow: "About the company", title: "Fixed price. <em>Fixed date.</em>",
        p: ["Bauhaus Build was founded in 2009 by two civil engineers who were tired of watching renovations take twice as long as promised. So our contract has two numbers that do not move: price and date.", "The twenty-eight workers are employed, insured and trained. We do not use subcontractors because we cannot guarantee their work — and you get a 5-year warranty on ours."],
        facts: [{ n: "28", l: "employed workers" }, { n: "620", l: "completed projects" }, { n: "5", l: "years warranty" }, { n: "0.5%", l: "delays in 2025" }],
      },
      steps: { title: "How <em>the renovation goes</em>", items: [
        { t: "Site visit", d: "An engineer comes, measures, photographs and listens to what you want. Free, within 48 hours." },
        { t: "Itemised quote", d: "Materials and labour separately, with brands and quantities. Fixed price and date." },
        { t: "Execution", d: "A crew of 3–6 on site every day, weekly photo report in the app." },
        { t: "Handover", d: "Walk-through together, protocol, warranty booklet. We remove everything down to the last bag." },
      ] },
      list: { title: "Prices per m²", lede: "Indicative prices incl. VAT, materials and labour. The exact price is in the quote after the visit.", groups: [
        { t: "Renovation", items: [["Turnkey renovation · standard", "€420/m²"], ["Turnkey renovation · premium", "€680/m²"], ["Turnkey bathroom (up to 6 m²)", "from €4,900"], ["Turnkey kitchen (without furniture)", "from €3,200"]] },
        { t: "Construction", items: [["Structural work, house", "€380/m²"], ["Turnkey house", "from €950/m²"], ["New tiled roof", "from €85/m²"], ["10 cm thermal insulation", "from €45/m²"]] },
      ] },
      reviews: [
        { name: "Ivaylo K.", text: "92 m² renovated in 38 days against 40 promised. The quote was itemised and the final amount was the same to the euro.", stars: 5 },
        { name: "Manager, dental clinic", text: "Clinic renovated in 3 weeks, they worked nights so we did not close. The engineer answered the phone at 22:00.", stars: 5 },
        { name: "R. and M. Petrov", text: "A house from scratch in 11 months. Photos in the app every week, every cost in the spreadsheet. Zero surprises.", stars: 5 },
      ],
      faq: [
        { q: "Is the price really fixed?", a: "Yes. It changes only if you change the design — then we sign an annex with the new price and date before continuing." },
        { q: "What happens if you are late?", a: "We pay a €100 penalty per day, deducted from the last instalment. In 2025 we were late on 3 of 600 projects." },
        { q: "Who buys the materials?", a: "We do, at wholesale prices, with invoices you can see. You can buy some yourself — we deduct them from the quote." },
        { q: "How do I pay?", a: "30% at the start, 40% halfway, 30% at handover. For projects over €50,000 — 5 instalments by stage." },
        { q: "What is the warranty?", a: "5 years on structure, installations and waterproofing, 2 years on finishing works. Warranty booklet at handover." },
      ],
      contact: { eyebrow: "Contact", title: "Request a visit <em>or send photos</em>", lede: "We reply within 2 hours; site visit within 48 hours in Sofia and the region." },
    },
    it: {
      name: "Bauhaus Build", category: "Impresa edile", city: "Torino",
      metaTitle: "Bauhaus Build · Impresa edile Torino · Sito demo",
      metaDesc: "Sito demo per impresa edile: ristrutturazioni chiavi in mano, strutture, prezzi al m², sopralluogo gratuito, preventivo in 48 ore. Di Carbon Stealth.",
      address: "Corso Vittorio Emanuele II 100, 10121 Torino", phone: "+39 011 000 0015", email: "office@bauhausbuild.example",
      hours: ["Lun – Ven: 08:00 – 18:00", "Sabato: 09:00 – 13:00", "Sopralluoghi: su appuntamento, anche di sera"],
      hero: {
        eyebrow: "Ristrutturazioni chiavi in mano · strutture · tetti · Torino e provincia",
        title: "Ristrutturazione a prezzo fisso <em>e data di consegna.</em>",
        lede: "Ventotto operai assunti, magazzino proprio e un ingegnere su ogni cantiere. Il preventivo ha un prezzo fisso e una scadenza — per ogni giorno di ritardo, paghiamo noi.",
        cta: "Sopralluogo gratuito", cta2: "Prezzi al m²",
        proof: "★ 4,8 su Google · 620 cantieri completati · 0,5% di ritardi nel 2025",
        widget: { kind: "consult", title: "Sopralluogo gratuito e preventivo in 48 ore", rows: ["Ingegnere sul posto, misure e foto", "Preventivo a voci con materiali e manodopera", "Prezzo fisso e data di consegna", "Penale di 100 € per ogni giorno di ritardo"], cta: "Richiedi il sopralluogo" },
      },
      badges: ["Prezzo fisso", "Penale per ritardo", "Garanzia 5 anni", "Squadre proprie, niente subappalti"],
      offer: { tag: "Autunno 2026", title: "Bagno chiavi in mano in 14 giorni — da 4.900 €", text: "Demolizione, idraulica ed elettrico, impermeabilizzazione, piastrelle fino a 60 €/m², controsoffitto, sanitari Grohe/Ideal Standard. Il prezzo include materiali e smaltimento.", cta: "Richiedi il sopralluogo", note: "I prezzi sono esempi per la demo." },
      servicesTitle: "Cosa <em>costruiamo e ristrutturiamo</em>",
      servicesLede: "Il listino è pubblico perché tanto lo sapreste dal vicino.",
      services: [
        { t: "Ristrutturazione chiavi in mano", d: "Appartamenti e case: dal progetto all'ultima chiave. Un contratto, un responsabile.", p: "da 420 €/m²" },
        { t: "Bagni e cucine", d: "Demolizione, impianti, impermeabilizzazione, piastrelle, mobili su misura.", p: "da 4.900 €" },
        { t: "Opere strutturali", d: "Case e piccoli edifici: scavo, fondazioni, struttura, tetto. Gru propria.", p: "da 380 €/m²" },
        { t: "Tetti e isolamenti", d: "Riparazioni e tetti nuovi, impermeabilizzazione e cappotto, grondaie.", p: "da 45 €/m²" },
        { t: "Elettrico e idraulico", d: "Impianti nuovi, quadri, impianti a bassa tensione, fotovoltaico fino a 10 kW.", p: "da 35 €/punto" },
        { t: "Finiture", d: "Rasatura, tinteggiatura, parquet, cartongesso, intonaci decorativi.", p: "da 18 €/m²" },
      ],
      about: {
        eyebrow: "L'impresa", title: "Prezzo fisso. <em>Data fissa.</em>",
        p: ["Bauhaus Build è nata nel 2009 da due ingegneri civili stanchi di vedere ristrutturazioni durare il doppio del promesso. Per questo il nostro contratto ha due numeri che non si muovono: prezzo e data.", "I ventotto operai sono assunti, assicurati e formati. Non usiamo subappaltatori perché non possiamo garantire il loro lavoro — e voi avete 5 anni di garanzia sul nostro."],
        facts: [{ n: "28", l: "operai assunti" }, { n: "620", l: "cantieri completati" }, { n: "5", l: "anni di garanzia" }, { n: "0,5%", l: "ritardi nel 2025" }],
      },
      steps: { title: "Come <em>procede il cantiere</em>", items: [
        { t: "Sopralluogo", d: "Un ingegnere viene sul posto, misura, fotografa e ascolta cosa volete. Gratis, entro 48 ore." },
        { t: "Preventivo a voci", d: "Materiali e manodopera separati, con marche e quantità. Prezzo fisso e data." },
        { t: "Esecuzione", d: "Una squadra di 3–6 persone in cantiere ogni giorno, report fotografico settimanale nell'app." },
        { t: "Consegna", d: "Sopralluogo insieme, verbale, libretto di garanzia. Portiamo via tutto fino all'ultimo sacco." },
      ] },
      list: { title: "Prezzi al m²", lede: "Prezzi indicativi IVA inclusa, materiali e manodopera. Il prezzo esatto è nel preventivo dopo il sopralluogo.", groups: [
        { t: "Ristrutturazione", items: [["Chiavi in mano · standard", "420 €/m²"], ["Chiavi in mano · premium", "680 €/m²"], ["Bagno chiavi in mano (fino a 6 m²)", "da 4.900 €"], ["Cucina chiavi in mano (senza mobili)", "da 3.200 €"]] },
        { t: "Costruzione", items: [["Struttura casa", "380 €/m²"], ["Casa chiavi in mano", "da 950 €/m²"], ["Tetto nuovo in tegole", "da 85 €/m²"], ["Cappotto 10 cm", "da 45 €/m²"]] },
      ] },
      reviews: [
        { name: "Ivo K.", text: "92 m² ristrutturati in 38 giorni contro i 40 promessi. Il preventivo era a voci e l'importo finale era lo stesso all'euro.", stars: 5 },
        { name: "Titolare, studio dentistico", text: "Studio ristrutturato in 3 settimane, hanno lavorato di notte per non farci chiudere. L'ingegnere rispondeva al telefono alle 22:00.", stars: 5 },
        { name: "R. e M. Petrov", text: "Una casa da zero in 11 mesi. Foto nell'app ogni settimana, ogni spesa nel foglio. Zero sorprese.", stars: 5 },
      ],
      faq: [
        { q: "Il prezzo è davvero fisso?", a: "Sì. Cambia solo se cambiate voi il progetto — allora firmiamo un'integrazione con nuovo prezzo e data prima di proseguire." },
        { q: "Cosa succede in caso di ritardo?", a: "Paghiamo una penale di 100 € al giorno, detratta dall'ultima rata. Nel 2025 abbiamo ritardato su 3 cantieri su 600." },
        { q: "Chi compra i materiali?", a: "Noi, a prezzi all'ingrosso, con fatture che vedete. Potete comprarne alcuni voi — li scaliamo dal preventivo." },
        { q: "Come si paga?", a: "30% all'inizio, 40% a metà, 30% alla consegna. Per cantieri sopra 50.000 € — 5 rate per fasi." },
        { q: "Qual è la garanzia?", a: "5 anni su struttura, impianti e impermeabilizzazione, 2 anni sulle finiture. Libretto di garanzia alla consegna." },
      ],
      contact: { eyebrow: "Contatti", title: "Richiedi un sopralluogo <em>o manda le foto</em>", lede: "Rispondiamo entro 2 ore; sopralluogo entro 48 ore a Torino e provincia." },
    },
  },
};
