// Bundles src/ into two artifacts. three.js is never bundled into either: both load the exact
// pinned version through an import map (the standalone page's own <script type="importmap">,
// or — for the embed — whatever import map the host page already provides, see mascot/CLAUDE.md).
//  - dist/mascot-cinematic.html — the self-contained showcase page (src/main.js + template.html).
//  - dist/mascot-embed.js       — the bare ESM `mount()` module (src/embed.js) that other products
//                                  copy in generated form (tools/agents/mascot-theme.mjs -> the
//                                  agents-dashboard profile card). No HTML wrapper: it is a library.
import { build } from 'esbuild';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';

// Offline-bake the desk set (dist/tex/*.webp) before bundling, exactly like boy/build.mjs. Wrapped
// in try/catch on purpose: `sharp` is a native addon and a CI image without a matching prebuilt
// binary must not hard-fail the whole showcase build — the page already falls back to the runtime
// procedural textures (src/desk-textures.js) when dist/tex/manifest.json is missing (src/baked.js).
try {
  execFileSync(process.execPath, ['bake/index.mjs'], { stdio: 'inherit' });
} catch (err) {
  process.stderr.write(`bake skipped (falling back to runtime procedural textures): ${err?.message ?? err}\n`);
}

async function bundle(entryPoint) {
  const result = await build({
    entryPoints: [entryPoint],
    bundle: true,
    format: 'esm',
    write: false,
    external: ['three', 'three/addons/*'],
    target: 'es2020',
    legalComments: 'none',
  });
  return result.outputFiles[0].text;
}

const pageJs = await bundle('src/main.js');
if (pageJs.includes('</script')) throw new Error('Page bundle contains a closing script tag');
const html = readFileSync('template.html', 'utf8').replace('/*BUNDLE*/', () => pageJs);
mkdirSync('dist', { recursive: true });
writeFileSync('dist/mascot-cinematic.html', html);
process.stdout.write(`dist/mascot-cinematic.html ${(html.length / 1024).toFixed(1)} KiB\n`);

const embedJs = await bundle('src/embed.js');
const banner = '// GENERATED by mascot/cinematic/build.mjs from src/embed.js — do not edit directly.\n';
writeFileSync('dist/mascot-embed.js', banner + embedJs);
process.stdout.write(`dist/mascot-embed.js ${(embedJs.length / 1024).toFixed(1)} KiB\n`);
