#!/usr/bin/env python3
"""Промо клип: истинските визии от генератора на store екраните (store/screenshots/build.py).

Popup-ът е РЕАЛНИЯТ popup/popup.html (със същите демо числа), панелите — същите като в
магазина, така че клипът не може да се разминава с продукта. Пише tools/promo/assets.js
(window.PROMO_ASSETS), който film.html зарежда.
"""
import importlib.util, json, os

HERE = os.path.dirname(os.path.abspath(__file__))
BUILD = os.path.join(HERE, "..", "..", "store", "screenshots", "build.py")
spec = importlib.util.spec_from_file_location("store_build", BUILD)
sb = importlib.util.module_from_spec(spec)
spec.loader.exec_module(sb)  # the slide loop only runs under __main__

src = lambda tag: tag.split('src="', 1)[1].split('"', 1)[0]
assets = {
    "css": sb.CSS[sb.CSS.index("/* settings panel mock */"):],
    "popupYT": src(sb.popup(blocked="3,782", data="1.4 GB", time="52 min", host="youtube.com")),
    "popupLog": src(sb.popup(blocked="9,140", data="4.6 GB", time="2.3 h", host="news.example.com",
                             log=[["EasyPrivacy", 12], ["EasyList", 7], ["uBlock filters", 5], ["Supreme core rules", 3], ["Tracking parameters", 2]])),
    "smart": sb.smartlog_panel(),
    "lists": sb.features_panel(),
}
with open(os.path.join(HERE, "assets.js"), "w", encoding="utf-8") as f:
    f.write("// GENERATED by tools/promo/assets.py — do not edit\nwindow.PROMO_ASSETS = " + json.dumps(assets) + ";\n")
print("assets.js", sum(len(v) for v in assets.values()) // 1024, "KB")
