/**
 * Extended player pool — populates the arena leaderboard and marketplace
 * so a fresh server feels lived-in. Every entry is OBVIOUSLY a bot:
 *   - name starts with "BOT_", "AI_", "NPC_", or "DUMMY_" prefix
 *   - bio openly admits it's an auto-generated training opponent
 *   - is_npc flag is set (handled by the seed runner) so derived stats
 *     correctly skip guild-bonus lookups etc.
 *
 * No real player chat or social system mistakes these for humans.
 */

import type { CharacterClass } from '../types/domain';

export interface ExtendedDummy {
  name: string;
  class: CharacterClass;
  level: number;
  rating: number;
  bio: string;
  gear_tier: 1 | 2 | 3;        // pull starter / mid / late kit
  joined_days_ago: number;
}

const PREFIXES = ['BOT', 'AI', 'NPC', 'DUMMY', 'TRAINER', 'SANDBOX'];
const ROLE_BY_CLASS: Record<CharacterClass, string[]> = {
  warrior: ['Warrior', 'Sentinel', 'Bulwark', 'Vanguard', 'Champion', 'Bastion'],
  ranger:  ['Ranger', 'Hunter', 'Tracker', 'Marksman', 'Pathfinder', 'Scout'],
  mage:    ['Mage', 'Conjurer', 'Lorekeeper', 'Adept', 'Channeler', 'Arcanist'],
  rogue:   ['Rogue', 'Cutpurse', 'Shade', 'Stalker', 'Thief', 'Wraith'],
};

const BIOS: string[] = [
  '[AI training partner — auto-generated by the matchmaker.]',
  '[Bot account. Used for sparring practice.]',
  '[Procedurally generated NPC. No human behind this screen.]',
  '[Sandbox arena target. Beat me, take my gold.]',
  '[Server-spawned trainer. Difficulty scales with your level.]',
  '[Auto-spawned to fill the leaderboard. Polite combat only.]',
  '[I am a machine. My loot is also a machine.]',
  '[CPU opponent. Replies are not real.]',
  '[Generated dummy — no chat, no guild invites accepted.]',
  '[Procedural NPC. Rating drifts a bit; XP I drop is real.]',
];

const CLASSES: CharacterClass[] = ['warrior', 'ranger', 'mage', 'rogue'];

function seeded(rng: () => number, arr: any[]) {
  return arr[Math.floor(rng() * arr.length) % arr.length];
}

function makeRng(seed: number) {
  // Tiny deterministic PRNG (mulberry32). Keeps seed reproducible across runs.
  return function () {
    seed = (seed + 0x6d2b79f5) | 0;
    let t = seed;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function botName(rng: () => number, cls: CharacterClass): string {
  const prefix = seeded(rng, PREFIXES);
  const role = seeded(rng, ROLE_BY_CLASS[cls]);
  // 4-char hex tail keeps names unique without inflating the namespace.
  const tail = Math.floor(rng() * 0xffff).toString(16).padStart(4, '0');
  // Random separator picks between underscore and dot for variety.
  const sep = rng() > 0.5 ? '_' : '-';
  return `${prefix}${sep}${role}${sep}${tail}`;
}

export function generateExtendedDummies(): ExtendedDummy[] {
  const rng = makeRng(0xc0ffee);
  const out: ExtendedDummy[] = [];
  const usedNames = new Set<string>();
  let attempts = 0;
  while (out.length < 80 && attempts < 5000) {
    attempts++;
    const cls = seeded(rng, CLASSES) as CharacterClass;
    const name = botName(rng, cls);
    if (usedNames.has(name)) continue;
    usedNames.add(name);
    // Level distribution: weighted toward 3–18.
    const r = rng();
    let level = 1;
    if (r < 0.20) level = 1 + Math.floor(rng() * 3);          // 1–3 newer
    else if (r < 0.55) level = 4 + Math.floor(rng() * 7);     // 4–10 most common
    else if (r < 0.85) level = 11 + Math.floor(rng() * 7);    // 11–17 mid
    else level = 18 + Math.floor(rng() * 8);                  // 18–25 veterans

    // Rating loosely correlates with level + jitter.
    const rating = Math.round(950 + level * 22 + (rng() - 0.5) * 200);
    const gear_tier: 1 | 2 | 3 = (level <= 6 ? 1 : level <= 14 ? 2 : 3);
    const joined_days_ago = 1 + Math.floor(rng() * 220);
    const bio = seeded(rng, BIOS);
    out.push({ name, class: cls, level, rating, bio, gear_tier, joined_days_ago });
  }
  return out;
}
