export const ITEM_SEED = [
  // ===== STARTER WEAPONS =====
  { slug: 'iron_sword', name: 'Iron Sword', category: 'weapon', sub_type: 'sword', tier: 1, rarity: 'common', level_req: 1, class_req: '', atk_min: 4, atk_max: 8, defense: 0, hp_bonus: 0, mp_bonus: 0, str_bonus: 1, dex_bonus: 0, con_bonus: 0, int_bonus: 0, cha_bonus: 0, wis_bonus: 0, buy_price: 25, sell_price: 8, icon: 'sword', description: 'A serviceable iron blade. Common, but it cuts.' },
  { slug: 'rusty_dagger', name: 'Rusty Dagger', category: 'weapon', sub_type: 'sword', tier: 1, rarity: 'common', level_req: 1, class_req: '', atk_min: 3, atk_max: 6, defense: 0, hp_bonus: 0, mp_bonus: 0, str_bonus: 0, dex_bonus: 2, con_bonus: 0, int_bonus: 0, cha_bonus: 0, wis_bonus: 0, buy_price: 18, sell_price: 6, icon: 'dagger', description: 'A worn dagger, fast in the hand.' },
  { slug: 'short_bow', name: 'Short Bow', category: 'weapon', sub_type: 'bow', tier: 1, rarity: 'common', level_req: 1, class_req: '', atk_min: 3, atk_max: 9, defense: 0, hp_bonus: 0, mp_bonus: 0, str_bonus: 0, dex_bonus: 2, con_bonus: 0, int_bonus: 0, cha_bonus: 0, wis_bonus: 0, buy_price: 22, sell_price: 7, icon: 'bow', description: 'Light bow, ideal for woodland skirmishes.' },
  { slug: 'novice_staff', name: 'Novice Staff', category: 'weapon', sub_type: 'staff', tier: 1, rarity: 'common', level_req: 1, class_req: '', atk_min: 2, atk_max: 5, defense: 0, hp_bonus: 0, mp_bonus: 10, str_bonus: 0, dex_bonus: 0, con_bonus: 0, int_bonus: 2, cha_bonus: 0, wis_bonus: 1, buy_price: 24, sell_price: 8, icon: 'staff', description: 'A simple oak staff humming with potential.' },
  { slug: 'wooden_shield', name: 'Wooden Shield', category: 'shield', sub_type: '', tier: 1, rarity: 'common', level_req: 1, class_req: '', atk_min: 0, atk_max: 0, defense: 4, hp_bonus: 5, mp_bonus: 0, str_bonus: 0, dex_bonus: 0, con_bonus: 1, int_bonus: 0, cha_bonus: 0, wis_bonus: 0, buy_price: 20, sell_price: 6, icon: 'shield', description: 'A reinforced oak shield.' },

  // ===== TIER 2 WEAPONS =====
  { slug: 'steel_longsword', name: 'Steel Longsword', category: 'weapon', sub_type: 'sword', tier: 2, rarity: 'uncommon', level_req: 5, class_req: '', atk_min: 9, atk_max: 16, defense: 0, hp_bonus: 0, mp_bonus: 0, str_bonus: 2, dex_bonus: 1, con_bonus: 0, int_bonus: 0, cha_bonus: 0, wis_bonus: 0, buy_price: 180, sell_price: 60, icon: 'sword', description: 'Forged in the kingdom\'s great furnaces.' },
  { slug: 'warhammer', name: 'Warhammer', category: 'weapon', sub_type: 'axe', tier: 2, rarity: 'uncommon', level_req: 6, class_req: '', atk_min: 12, atk_max: 18, defense: 0, hp_bonus: 0, mp_bonus: 0, str_bonus: 3, dex_bonus: 0, con_bonus: 1, int_bonus: 0, cha_bonus: 0, wis_bonus: 0, buy_price: 220, sell_price: 70, icon: 'axe', description: 'Crushes plate as easily as bone.' },
  { slug: 'elven_bow', name: 'Elven Longbow', category: 'weapon', sub_type: 'bow', tier: 2, rarity: 'uncommon', level_req: 5, class_req: '', atk_min: 8, atk_max: 17, defense: 0, hp_bonus: 0, mp_bonus: 0, str_bonus: 0, dex_bonus: 3, con_bonus: 0, int_bonus: 0, cha_bonus: 0, wis_bonus: 1, buy_price: 200, sell_price: 65, icon: 'bow', description: 'Strung with sinew that sings.' },
  { slug: 'sapphire_staff', name: 'Sapphire Staff', category: 'weapon', sub_type: 'staff', tier: 2, rarity: 'uncommon', level_req: 5, class_req: '', atk_min: 6, atk_max: 13, defense: 0, hp_bonus: 0, mp_bonus: 20, str_bonus: 0, dex_bonus: 0, con_bonus: 0, int_bonus: 3, cha_bonus: 0, wis_bonus: 2, buy_price: 210, sell_price: 65, icon: 'staff', description: 'A gem channels arcane power.' },

  // ===== TIER 3 WEAPONS =====
  { slug: 'flameblade', name: 'Flameblade of Valor', category: 'weapon', sub_type: 'sword', tier: 3, rarity: 'rare', level_req: 12, class_req: '', atk_min: 20, atk_max: 32, defense: 0, hp_bonus: 10, mp_bonus: 0, str_bonus: 4, dex_bonus: 2, con_bonus: 1, int_bonus: 0, cha_bonus: 0, wis_bonus: 0, buy_price: 900, sell_price: 280, icon: 'sword', description: 'Glows ember-red at the touch of the wielder.' },
  { slug: 'shadowfang_bow', name: 'Shadowfang Bow', category: 'weapon', sub_type: 'bow', tier: 3, rarity: 'rare', level_req: 12, class_req: '', atk_min: 18, atk_max: 34, defense: 0, hp_bonus: 0, mp_bonus: 0, str_bonus: 0, dex_bonus: 5, con_bonus: 0, int_bonus: 1, cha_bonus: 0, wis_bonus: 1, buy_price: 880, sell_price: 270, icon: 'bow', description: 'Said to draw breath from its prey.' },
  { slug: 'archmage_staff', name: 'Archmage Staff', category: 'weapon', sub_type: 'staff', tier: 3, rarity: 'rare', level_req: 12, class_req: '', atk_min: 14, atk_max: 26, defense: 0, hp_bonus: 0, mp_bonus: 45, str_bonus: 0, dex_bonus: 0, con_bonus: 0, int_bonus: 6, cha_bonus: 0, wis_bonus: 3, buy_price: 920, sell_price: 290, icon: 'staff', description: 'Carved with runes of every school.' },

  // ===== EPIC/LEGENDARY (drops only) =====
  { slug: 'dragonbane', name: 'Dragonbane', category: 'weapon', sub_type: 'sword', tier: 5, rarity: 'legendary', level_req: 25, class_req: '', atk_min: 60, atk_max: 95, defense: 5, hp_bonus: 50, mp_bonus: 0, str_bonus: 10, dex_bonus: 5, con_bonus: 5, int_bonus: 0, cha_bonus: 0, wis_bonus: 0, buy_price: 0, sell_price: 5000, icon: 'sword', description: 'A blade whispered of in dragon kin nightmares.' },
  { slug: 'voidwhisper', name: 'Voidwhisper', category: 'weapon', sub_type: 'staff', tier: 5, rarity: 'legendary', level_req: 25, class_req: '', atk_min: 45, atk_max: 80, defense: 0, hp_bonus: 0, mp_bonus: 100, str_bonus: 0, dex_bonus: 0, con_bonus: 0, int_bonus: 15, cha_bonus: 0, wis_bonus: 10, buy_price: 0, sell_price: 5000, icon: 'staff', description: 'Speaks in tongues of the cold dark.' },

  // ===== ARMOR =====
  { slug: 'leather_helm', name: 'Leather Helm', category: 'helm', sub_type: '', tier: 1, rarity: 'common', level_req: 1, class_req: '', atk_min: 0, atk_max: 0, defense: 2, hp_bonus: 5, mp_bonus: 0, str_bonus: 0, dex_bonus: 0, con_bonus: 1, int_bonus: 0, cha_bonus: 0, wis_bonus: 0, buy_price: 15, sell_price: 5, icon: 'helm', description: 'Padded leather for the head.' },
  { slug: 'leather_armor', name: 'Leather Armor', category: 'armor', sub_type: '', tier: 1, rarity: 'common', level_req: 1, class_req: '', atk_min: 0, atk_max: 0, defense: 4, hp_bonus: 10, mp_bonus: 0, str_bonus: 0, dex_bonus: 0, con_bonus: 1, int_bonus: 0, cha_bonus: 0, wis_bonus: 0, buy_price: 30, sell_price: 10, icon: 'armor', description: 'Hardened hide, supple but tough.' },
  { slug: 'leather_gloves', name: 'Leather Gloves', category: 'gloves', sub_type: '', tier: 1, rarity: 'common', level_req: 1, class_req: '', atk_min: 0, atk_max: 0, defense: 1, hp_bonus: 3, mp_bonus: 0, str_bonus: 0, dex_bonus: 1, con_bonus: 0, int_bonus: 0, cha_bonus: 0, wis_bonus: 0, buy_price: 12, sell_price: 4, icon: 'gloves', description: 'Gripping gloves of supple leather.' },
  { slug: 'leather_boots', name: 'Leather Boots', category: 'boots', sub_type: '', tier: 1, rarity: 'common', level_req: 1, class_req: '', atk_min: 0, atk_max: 0, defense: 1, hp_bonus: 3, mp_bonus: 0, str_bonus: 0, dex_bonus: 1, con_bonus: 0, int_bonus: 0, cha_bonus: 0, wis_bonus: 0, buy_price: 12, sell_price: 4, icon: 'boots', description: 'Quiet on the forest paths.' },
  { slug: 'cloth_hood', name: 'Cloth Hood', category: 'helm', sub_type: '', tier: 1, rarity: 'common', level_req: 1, class_req: '', atk_min: 0, atk_max: 0, defense: 1, hp_bonus: 0, mp_bonus: 5, str_bonus: 0, dex_bonus: 0, con_bonus: 0, int_bonus: 1, cha_bonus: 0, wis_bonus: 0, buy_price: 12, sell_price: 4, icon: 'helm', description: 'A scholar\'s hood.' },
  { slug: 'cloth_robe', name: 'Cloth Robe', category: 'armor', sub_type: '', tier: 1, rarity: 'common', level_req: 1, class_req: '', atk_min: 0, atk_max: 0, defense: 2, hp_bonus: 0, mp_bonus: 10, str_bonus: 0, dex_bonus: 0, con_bonus: 0, int_bonus: 1, cha_bonus: 0, wis_bonus: 1, buy_price: 28, sell_price: 9, icon: 'armor', description: 'Embroidered with subtle wards.' },
  { slug: 'cloth_gloves', name: 'Cloth Gloves', category: 'gloves', sub_type: '', tier: 1, rarity: 'common', level_req: 1, class_req: '', atk_min: 0, atk_max: 0, defense: 1, hp_bonus: 0, mp_bonus: 3, str_bonus: 0, dex_bonus: 0, con_bonus: 0, int_bonus: 1, cha_bonus: 0, wis_bonus: 0, buy_price: 10, sell_price: 3, icon: 'gloves', description: 'Soft gloves for steady casting.' },
  { slug: 'cloth_shoes', name: 'Cloth Shoes', category: 'boots', sub_type: '', tier: 1, rarity: 'common', level_req: 1, class_req: '', atk_min: 0, atk_max: 0, defense: 1, hp_bonus: 0, mp_bonus: 3, str_bonus: 0, dex_bonus: 0, con_bonus: 0, int_bonus: 1, cha_bonus: 0, wis_bonus: 0, buy_price: 10, sell_price: 3, icon: 'boots', description: 'Slippered shoes for the studious.' },

  // Tier 2 armor sets
  { slug: 'chain_helm', name: 'Chainmail Coif', category: 'helm', sub_type: '', tier: 2, rarity: 'uncommon', level_req: 5, class_req: '', atk_min: 0, atk_max: 0, defense: 5, hp_bonus: 12, mp_bonus: 0, str_bonus: 0, dex_bonus: 0, con_bonus: 2, int_bonus: 0, cha_bonus: 0, wis_bonus: 0, buy_price: 80, sell_price: 28, icon: 'helm', description: 'Linked rings catch the firelight.' },
  { slug: 'chain_armor', name: 'Chainmail Armor', category: 'armor', sub_type: '', tier: 2, rarity: 'uncommon', level_req: 5, class_req: '', atk_min: 0, atk_max: 0, defense: 9, hp_bonus: 25, mp_bonus: 0, str_bonus: 0, dex_bonus: 0, con_bonus: 3, int_bonus: 0, cha_bonus: 0, wis_bonus: 0, buy_price: 140, sell_price: 48, icon: 'armor', description: 'A soldier\'s second skin.' },
  { slug: 'chain_gloves', name: 'Chainmail Gauntlets', category: 'gloves', sub_type: '', tier: 2, rarity: 'uncommon', level_req: 5, class_req: '', atk_min: 0, atk_max: 0, defense: 3, hp_bonus: 8, mp_bonus: 0, str_bonus: 1, dex_bonus: 0, con_bonus: 1, int_bonus: 0, cha_bonus: 0, wis_bonus: 0, buy_price: 60, sell_price: 20, icon: 'gloves', description: 'Linked steel guards the hands.' },
  { slug: 'chain_boots', name: 'Chainmail Boots', category: 'boots', sub_type: '', tier: 2, rarity: 'uncommon', level_req: 5, class_req: '', atk_min: 0, atk_max: 0, defense: 3, hp_bonus: 8, mp_bonus: 0, str_bonus: 0, dex_bonus: 1, con_bonus: 1, int_bonus: 0, cha_bonus: 0, wis_bonus: 0, buy_price: 60, sell_price: 20, icon: 'boots', description: 'Heavy but reassuring.' },
  { slug: 'kite_shield', name: 'Kite Shield', category: 'shield', sub_type: '', tier: 2, rarity: 'uncommon', level_req: 5, class_req: '', atk_min: 0, atk_max: 0, defense: 8, hp_bonus: 15, mp_bonus: 0, str_bonus: 1, dex_bonus: 0, con_bonus: 2, int_bonus: 0, cha_bonus: 0, wis_bonus: 0, buy_price: 110, sell_price: 38, icon: 'shield', description: 'Tall and steady.' },

  // Tier 3 armor (rare)
  { slug: 'plate_helm', name: 'Plate Greathelm', category: 'helm', sub_type: '', tier: 3, rarity: 'rare', level_req: 12, class_req: '', atk_min: 0, atk_max: 0, defense: 10, hp_bonus: 25, mp_bonus: 0, str_bonus: 1, dex_bonus: 0, con_bonus: 4, int_bonus: 0, cha_bonus: 0, wis_bonus: 0, buy_price: 380, sell_price: 130, icon: 'helm', description: 'A fortress for the skull.' },
  { slug: 'plate_armor', name: 'Plate Cuirass', category: 'armor', sub_type: '', tier: 3, rarity: 'rare', level_req: 12, class_req: '', atk_min: 0, atk_max: 0, defense: 18, hp_bonus: 55, mp_bonus: 0, str_bonus: 2, dex_bonus: 0, con_bonus: 5, int_bonus: 0, cha_bonus: 0, wis_bonus: 0, buy_price: 620, sell_price: 210, icon: 'armor', description: 'Polished bright as river ice.' },
  { slug: 'mage_robe', name: 'Mage\'s Greater Robe', category: 'armor', sub_type: '', tier: 3, rarity: 'rare', level_req: 12, class_req: '', atk_min: 0, atk_max: 0, defense: 8, hp_bonus: 20, mp_bonus: 60, str_bonus: 0, dex_bonus: 0, con_bonus: 1, int_bonus: 4, cha_bonus: 0, wis_bonus: 3, buy_price: 580, sell_price: 200, icon: 'armor', description: 'Stitched with spell-thread.' },

  // ===== ACCESSORIES =====
  { slug: 'silver_ring', name: 'Silver Ring', category: 'ring', sub_type: '', tier: 1, rarity: 'uncommon', level_req: 3, class_req: '', atk_min: 0, atk_max: 0, defense: 1, hp_bonus: 5, mp_bonus: 5, str_bonus: 1, dex_bonus: 0, con_bonus: 0, int_bonus: 0, cha_bonus: 0, wis_bonus: 0, buy_price: 60, sell_price: 20, icon: 'ring', description: 'Plain but enchanted.' },
  { slug: 'amulet_of_warding', name: 'Amulet of Warding', category: 'amulet', sub_type: '', tier: 2, rarity: 'rare', level_req: 8, class_req: '', atk_min: 0, atk_max: 0, defense: 3, hp_bonus: 20, mp_bonus: 10, str_bonus: 0, dex_bonus: 0, con_bonus: 2, int_bonus: 0, cha_bonus: 0, wis_bonus: 2, buy_price: 240, sell_price: 80, icon: 'amulet', description: 'A pulsing rune wards off harm.' },
  { slug: 'ring_of_power', name: 'Ring of Power', category: 'ring', sub_type: '', tier: 3, rarity: 'epic', level_req: 15, class_req: '', atk_min: 0, atk_max: 0, defense: 2, hp_bonus: 15, mp_bonus: 15, str_bonus: 3, dex_bonus: 3, con_bonus: 0, int_bonus: 3, cha_bonus: 0, wis_bonus: 0, buy_price: 0, sell_price: 1200, icon: 'ring', description: 'Whispers gather around the wearer.' },

  // ===== CONSUMABLES =====
  { slug: 'lesser_health_potion', name: 'Lesser Health Potion', category: 'potion', sub_type: '', tier: 1, rarity: 'common', level_req: 1, class_req: '', atk_min: 0, atk_max: 0, defense: 0, hp_bonus: 0, mp_bonus: 0, str_bonus: 0, dex_bonus: 0, con_bonus: 0, int_bonus: 0, cha_bonus: 0, wis_bonus: 0, heal_hp: 40, heal_mp: 0, buy_price: 15, sell_price: 4, icon: 'potion_red', description: 'Restores 40 HP.' },
  { slug: 'health_potion', name: 'Health Potion', category: 'potion', sub_type: '', tier: 2, rarity: 'uncommon', level_req: 5, class_req: '', atk_min: 0, atk_max: 0, defense: 0, hp_bonus: 0, mp_bonus: 0, str_bonus: 0, dex_bonus: 0, con_bonus: 0, int_bonus: 0, cha_bonus: 0, wis_bonus: 0, heal_hp: 100, heal_mp: 0, buy_price: 50, sell_price: 14, icon: 'potion_red', description: 'Restores 100 HP.' },
  { slug: 'greater_health_potion', name: 'Greater Health Potion', category: 'potion', sub_type: '', tier: 3, rarity: 'rare', level_req: 12, class_req: '', atk_min: 0, atk_max: 0, defense: 0, hp_bonus: 0, mp_bonus: 0, str_bonus: 0, dex_bonus: 0, con_bonus: 0, int_bonus: 0, cha_bonus: 0, wis_bonus: 0, heal_hp: 250, heal_mp: 0, buy_price: 150, sell_price: 40, icon: 'potion_red', description: 'Restores 250 HP.' },
  { slug: 'mana_potion', name: 'Mana Potion', category: 'potion', sub_type: '', tier: 2, rarity: 'uncommon', level_req: 5, class_req: '', atk_min: 0, atk_max: 0, defense: 0, hp_bonus: 0, mp_bonus: 0, str_bonus: 0, dex_bonus: 0, con_bonus: 0, int_bonus: 0, cha_bonus: 0, wis_bonus: 0, heal_hp: 0, heal_mp: 60, buy_price: 45, sell_price: 12, icon: 'potion_blue', description: 'Restores 60 MP.' },

  /* ===== ALCHEMIST'S ATTRIBUTE ELIXIRS =====
     Minor (+10% / 30 min) · Greater (+20% / 60 min) · Supreme (+35% / 120 min).
     sub_type encodes "buff:<stat>:<percent>:<minutes>" for the use handler. */
  { slug: 'minor_strength_elixir',    name: 'Minor Elixir of Vigour',    category: 'potion', sub_type: 'buff:strength:10:60',  tier: 1, rarity: 'common',   level_req: 3,  class_req: '', atk_min: 0, atk_max: 0, defense: 0, hp_bonus: 0, mp_bonus: 0, str_bonus: 0, dex_bonus: 0, con_bonus: 0, int_bonus: 0, cha_bonus: 0, wis_bonus: 0, heal_hp: 0, heal_mp: 0, buy_price: 80,  sell_price: 22,  icon: 'potion_red',   description: '+10% Strength for 1 hour.' },
  { slug: 'greater_strength_elixir',  name: 'Greater Elixir of Vigour',  category: 'potion', sub_type: 'buff:strength:20:480',  tier: 2, rarity: 'uncommon', level_req: 8,  class_req: '', atk_min: 0, atk_max: 0, defense: 0, hp_bonus: 0, mp_bonus: 0, str_bonus: 0, dex_bonus: 0, con_bonus: 0, int_bonus: 0, cha_bonus: 0, wis_bonus: 0, heal_hp: 0, heal_mp: 0, buy_price: 280, sell_price: 80,  icon: 'potion_red',   description: '+20% Strength for 8 hours.' },
  { slug: 'supreme_strength_elixir',  name: 'Supreme Elixir of Vigour',  category: 'potion', sub_type: 'buff:strength:35:1440', tier: 3, rarity: 'rare',     level_req: 14, class_req: '', atk_min: 0, atk_max: 0, defense: 0, hp_bonus: 0, mp_bonus: 0, str_bonus: 0, dex_bonus: 0, con_bonus: 0, int_bonus: 0, cha_bonus: 0, wis_bonus: 0, heal_hp: 0, heal_mp: 0, buy_price: 950, sell_price: 280, icon: 'potion_red',   description: '+35% Strength for 24 hours.' },
  { slug: 'minor_dexterity_elixir',   name: 'Minor Elixir of Swiftness', category: 'potion', sub_type: 'buff:dexterity:10:60', tier: 1, rarity: 'common',   level_req: 3,  class_req: '', atk_min: 0, atk_max: 0, defense: 0, hp_bonus: 0, mp_bonus: 0, str_bonus: 0, dex_bonus: 0, con_bonus: 0, int_bonus: 0, cha_bonus: 0, wis_bonus: 0, heal_hp: 0, heal_mp: 0, buy_price: 80,  sell_price: 22,  icon: 'potion_green', description: '+10% Dexterity for 1 hour.' },
  { slug: 'greater_dexterity_elixir', name: 'Greater Elixir of Swiftness', category: 'potion', sub_type: 'buff:dexterity:20:480', tier: 2, rarity: 'uncommon', level_req: 8,  class_req: '', atk_min: 0, atk_max: 0, defense: 0, hp_bonus: 0, mp_bonus: 0, str_bonus: 0, dex_bonus: 0, con_bonus: 0, int_bonus: 0, cha_bonus: 0, wis_bonus: 0, heal_hp: 0, heal_mp: 0, buy_price: 280, sell_price: 80, icon: 'potion_green', description: '+20% Dexterity for 8 hours.' },
  { slug: 'supreme_dexterity_elixir', name: 'Supreme Elixir of Swiftness', category: 'potion', sub_type: 'buff:dexterity:35:1440', tier: 3, rarity: 'rare', level_req: 14, class_req: '', atk_min: 0, atk_max: 0, defense: 0, hp_bonus: 0, mp_bonus: 0, str_bonus: 0, dex_bonus: 0, con_bonus: 0, int_bonus: 0, cha_bonus: 0, wis_bonus: 0, heal_hp: 0, heal_mp: 0, buy_price: 950, sell_price: 280, icon: 'potion_green', description: '+35% Dexterity for 24 hours.' },
  { slug: 'minor_constitution_elixir', name: 'Minor Elixir of Endurance', category: 'potion', sub_type: 'buff:constitution:10:60', tier: 1, rarity: 'common', level_req: 3, class_req: '', atk_min: 0, atk_max: 0, defense: 0, hp_bonus: 0, mp_bonus: 0, str_bonus: 0, dex_bonus: 0, con_bonus: 0, int_bonus: 0, cha_bonus: 0, wis_bonus: 0, heal_hp: 0, heal_mp: 0, buy_price: 80, sell_price: 22, icon: 'potion_red', description: '+10% Constitution for 1 hour.' },
  { slug: 'greater_constitution_elixir', name: 'Greater Elixir of Endurance', category: 'potion', sub_type: 'buff:constitution:20:480', tier: 2, rarity: 'uncommon', level_req: 8, class_req: '', atk_min: 0, atk_max: 0, defense: 0, hp_bonus: 0, mp_bonus: 0, str_bonus: 0, dex_bonus: 0, con_bonus: 0, int_bonus: 0, cha_bonus: 0, wis_bonus: 0, heal_hp: 0, heal_mp: 0, buy_price: 280, sell_price: 80, icon: 'potion_red', description: '+20% Constitution for 8 hours.' },
  { slug: 'supreme_constitution_elixir', name: 'Supreme Elixir of Endurance', category: 'potion', sub_type: 'buff:constitution:35:1440', tier: 3, rarity: 'rare', level_req: 14, class_req: '', atk_min: 0, atk_max: 0, defense: 0, hp_bonus: 0, mp_bonus: 0, str_bonus: 0, dex_bonus: 0, con_bonus: 0, int_bonus: 0, cha_bonus: 0, wis_bonus: 0, heal_hp: 0, heal_mp: 0, buy_price: 950, sell_price: 280, icon: 'potion_red', description: '+35% Constitution for 24 hours.' },
  { slug: 'minor_intelligence_elixir', name: 'Minor Elixir of Insight', category: 'potion', sub_type: 'buff:intelligence:10:60', tier: 1, rarity: 'common', level_req: 3, class_req: '', atk_min: 0, atk_max: 0, defense: 0, hp_bonus: 0, mp_bonus: 0, str_bonus: 0, dex_bonus: 0, con_bonus: 0, int_bonus: 0, cha_bonus: 0, wis_bonus: 0, heal_hp: 0, heal_mp: 0, buy_price: 80, sell_price: 22, icon: 'potion_blue', description: '+10% Intelligence for 1 hour.' },
  { slug: 'greater_intelligence_elixir', name: 'Greater Elixir of Insight', category: 'potion', sub_type: 'buff:intelligence:20:480', tier: 2, rarity: 'uncommon', level_req: 8, class_req: '', atk_min: 0, atk_max: 0, defense: 0, hp_bonus: 0, mp_bonus: 0, str_bonus: 0, dex_bonus: 0, con_bonus: 0, int_bonus: 0, cha_bonus: 0, wis_bonus: 0, heal_hp: 0, heal_mp: 0, buy_price: 280, sell_price: 80, icon: 'potion_blue', description: '+20% Intelligence for 8 hours.' },
  { slug: 'supreme_intelligence_elixir', name: 'Supreme Elixir of Insight', category: 'potion', sub_type: 'buff:intelligence:35:1440', tier: 3, rarity: 'rare', level_req: 14, class_req: '', atk_min: 0, atk_max: 0, defense: 0, hp_bonus: 0, mp_bonus: 0, str_bonus: 0, dex_bonus: 0, con_bonus: 0, int_bonus: 0, cha_bonus: 0, wis_bonus: 0, heal_hp: 0, heal_mp: 0, buy_price: 950, sell_price: 280, icon: 'potion_blue', description: '+35% Intelligence for 24 hours.' },
  { slug: 'minor_wisdom_elixir', name: 'Minor Elixir of Sagacity', category: 'potion', sub_type: 'buff:wisdom:10:60', tier: 1, rarity: 'common', level_req: 3, class_req: '', atk_min: 0, atk_max: 0, defense: 0, hp_bonus: 0, mp_bonus: 0, str_bonus: 0, dex_bonus: 0, con_bonus: 0, int_bonus: 0, cha_bonus: 0, wis_bonus: 0, heal_hp: 0, heal_mp: 0, buy_price: 80, sell_price: 22, icon: 'potion_blue', description: '+10% Wisdom for 1 hour.' },
  { slug: 'greater_wisdom_elixir', name: 'Greater Elixir of Sagacity', category: 'potion', sub_type: 'buff:wisdom:20:480', tier: 2, rarity: 'uncommon', level_req: 8, class_req: '', atk_min: 0, atk_max: 0, defense: 0, hp_bonus: 0, mp_bonus: 0, str_bonus: 0, dex_bonus: 0, con_bonus: 0, int_bonus: 0, cha_bonus: 0, wis_bonus: 0, heal_hp: 0, heal_mp: 0, buy_price: 280, sell_price: 80, icon: 'potion_blue', description: '+20% Wisdom for 8 hours.' },
  { slug: 'supreme_wisdom_elixir', name: 'Supreme Elixir of Sagacity', category: 'potion', sub_type: 'buff:wisdom:35:1440', tier: 3, rarity: 'rare', level_req: 14, class_req: '', atk_min: 0, atk_max: 0, defense: 0, hp_bonus: 0, mp_bonus: 0, str_bonus: 0, dex_bonus: 0, con_bonus: 0, int_bonus: 0, cha_bonus: 0, wis_bonus: 0, heal_hp: 0, heal_mp: 0, buy_price: 950, sell_price: 280, icon: 'potion_blue', description: '+35% Wisdom for 24 hours.' },
  { slug: 'minor_charisma_elixir', name: 'Minor Elixir of Presence', category: 'potion', sub_type: 'buff:charisma:10:60', tier: 1, rarity: 'common', level_req: 3, class_req: '', atk_min: 0, atk_max: 0, defense: 0, hp_bonus: 0, mp_bonus: 0, str_bonus: 0, dex_bonus: 0, con_bonus: 0, int_bonus: 0, cha_bonus: 0, wis_bonus: 0, heal_hp: 0, heal_mp: 0, buy_price: 80, sell_price: 22, icon: 'potion_green', description: '+10% Charisma for 1 hour.' },
  { slug: 'greater_charisma_elixir', name: 'Greater Elixir of Presence', category: 'potion', sub_type: 'buff:charisma:20:480', tier: 2, rarity: 'uncommon', level_req: 8, class_req: '', atk_min: 0, atk_max: 0, defense: 0, hp_bonus: 0, mp_bonus: 0, str_bonus: 0, dex_bonus: 0, con_bonus: 0, int_bonus: 0, cha_bonus: 0, wis_bonus: 0, heal_hp: 0, heal_mp: 0, buy_price: 280, sell_price: 80, icon: 'potion_green', description: '+20% Charisma for 8 hours.' },
  { slug: 'supreme_charisma_elixir', name: 'Supreme Elixir of Presence', category: 'potion', sub_type: 'buff:charisma:35:1440', tier: 3, rarity: 'rare', level_req: 14, class_req: '', atk_min: 0, atk_max: 0, defense: 0, hp_bonus: 0, mp_bonus: 0, str_bonus: 0, dex_bonus: 0, con_bonus: 0, int_bonus: 0, cha_bonus: 0, wis_bonus: 0, heal_hp: 0, heal_mp: 0, buy_price: 950, sell_price: 280, icon: 'potion_green', description: '+35% Charisma for 24 hours.' },
];
