export const QUEST_SEED = [
  // Whispering Woods
  {
    slug: 'whispering_woods_rats',
    title: 'Cellar Vermin',
    region: 'whispering_woods',
    level_req: 1,
    energy_cost: 4,
    duration_sec: 0,
    intro: 'The innkeeper of Oaken Hollow leans across the bar. "Rats. Big ones, in the cellar. Would you?"',
    narrative: 'You descend the wooden stairs by candlelight. The air is heavy with the scent of old ale and something else — fur. A pair of red eyes glint from behind a barrel...',
    monster_slug: 'forest_rat',
    xp_reward: 12,
    gold_reward: 6,
    item_reward: '',
    success_text: 'The rat squeaks and goes still. The innkeeper claps you on the back and presses coins into your hand.',
    failure_text: 'You stumble out of the cellar bloodied. The innkeeper sighs and waves you off.',
  },
  {
    slug: 'whispering_woods_boar',
    title: 'The Stubborn Boar',
    region: 'whispering_woods',
    level_req: 2,
    energy_cost: 5,
    duration_sec: 0,
    intro: 'A farmer\'s field has been wrecked by a wild boar. He offers a bag of coins to whoever brings him peace.',
    narrative: 'You track the boar\'s muddy footprints to a thicket. A low grunting. A flash of tusk through the brambles. It charges...',
    monster_slug: 'wild_boar',
    xp_reward: 20,
    gold_reward: 12,
    item_reward: '',
    success_text: 'The boar collapses with a final, defiant snort. The farmer thanks you with coin and a flask of cider.',
    failure_text: 'Bruised and limping, you flee back to town. The farmer is not impressed.',
  },
  {
    slug: 'whispering_woods_goblin',
    title: 'Scout in the Shadows',
    region: 'whispering_woods',
    level_req: 3,
    energy_cost: 6,
    duration_sec: 0,
    intro: 'Travelers report a goblin watching the road from the trees. The kingdom wants him gone.',
    narrative: 'You crouch low along the moss. A snicker — sharp ears twitch. The scout draws a wicked, jagged knife...',
    monster_slug: 'goblin_scout',
    xp_reward: 30,
    gold_reward: 18,
    item_reward: 'silver_ring',
    success_text: 'The goblin\'s lifeless hand drops a battered silver ring. You take it.',
    failure_text: 'The scout flees into the trees laughing. You collect yourself, ashamed.',
  },
  {
    slug: 'whispering_woods_wolf',
    title: 'Wolves at the Door',
    region: 'whispering_woods',
    level_req: 4,
    energy_cost: 7,
    duration_sec: 0,
    intro: 'A homestead has been losing sheep nightly. The husband points into the trees: "Wolves. Big ones."',
    narrative: 'Twigs crack beneath padded feet. Yellow eyes drift in the dark. With a snarl, the alpha lunges...',
    monster_slug: 'forest_wolf',
    xp_reward: 45,
    gold_reward: 25,
    item_reward: '',
    success_text: 'The wolf yields with a whimper. The family will sleep peacefully tonight.',
    failure_text: 'You crawl back to the homestead clutching your wounds. The wife mutters prayers over you.',
  },
  {
    slug: 'whispering_woods_bandit',
    title: 'The Hooded One',
    region: 'whispering_woods',
    level_req: 5,
    energy_cost: 8,
    duration_sec: 0,
    intro: 'A bounty notice in Oaken Hollow: 12 gold and a fine helm for the bandit who has been robbing pilgrims.',
    narrative: 'You wait by the road, pretending to nap. Footsteps approach. A blade flashes in the moonlight as the hooded figure pounces...',
    monster_slug: 'bandit',
    xp_reward: 60,
    gold_reward: 35,
    item_reward: 'chain_helm',
    success_text: 'You strip the bandit of his loot. The reward and a fine chainmail coif are yours.',
    failure_text: 'The bandit escapes with your purse. You curse and head back to town with empty pockets.',
  },

  // Mistmoor Hills
  {
    slug: 'mistmoor_troll',
    title: 'Troll Under the Bridge',
    region: 'mistmoor_hills',
    level_req: 6,
    energy_cost: 10,
    duration_sec: 0,
    intro: 'The merchant guild promises gold to anyone who clears the troll from the King\'s Bridge.',
    narrative: 'The bridge looms ahead. A thick stink. From beneath the stones, a great hand grips the rail and a troll heaves itself into view...',
    monster_slug: 'hill_troll',
    xp_reward: 100,
    gold_reward: 50,
    item_reward: 'steel_longsword',
    success_text: 'The troll topples into the river with a thunderous splash. The guild pays handsomely.',
    failure_text: 'You flee with bruised ribs. The troll roars from beneath the bridge.',
  },
  {
    slug: 'mistmoor_orc_raid',
    title: 'Stop the Raiders',
    region: 'mistmoor_hills',
    level_req: 7,
    energy_cost: 10,
    duration_sec: 0,
    intro: 'Orc raiders have been burning farms. A captain points to a smoking field. "Bring me his head."',
    narrative: 'You crest the hill. Smoke. An orc with a notched axe turns slowly, baring yellow tusks...',
    monster_slug: 'orc_raider',
    xp_reward: 130,
    gold_reward: 65,
    item_reward: 'kite_shield',
    success_text: 'The orc topples. The farmer collapses to his knees in gratitude.',
    failure_text: 'The raider drives you off. The fires burn brighter.',
  },
  {
    slug: 'mistmoor_witch',
    title: 'The Witch of Mistmoor',
    region: 'mistmoor_hills',
    level_req: 9,
    energy_cost: 12,
    duration_sec: 0,
    intro: 'The village priest grips a charm. "Find the witch. End her. The mists thicken when she works.”',
    narrative: 'You step into a clearing of standing stones. The air shimmers green. A figure rises from a cauldron, eyes alight...',
    monster_slug: 'mistmoor_witch',
    xp_reward: 180,
    gold_reward: 90,
    item_reward: 'amulet_of_warding',
    success_text: 'The witch dissolves into mist. From her cauldron, an amulet shines.',
    failure_text: 'Her hex sends you reeling. You crawl from the clearing, mist-blind.',
  },

  // Crystal Caverns
  {
    slug: 'crystal_spider',
    title: 'The Web in the Dark',
    region: 'crystal_caverns',
    level_req: 10,
    energy_cost: 12,
    duration_sec: 0,
    intro: 'Miners have stopped returning. The guildmaster suspects a beast in the deep tunnels.',
    narrative: 'Your torch flickers. Silk threads cling to the walls. Eight eyes gleam from the ceiling above...',
    monster_slug: 'cave_spider',
    xp_reward: 220,
    gold_reward: 110,
    item_reward: 'chain_armor',
    success_text: 'The spider falls in a curl of legs. The miners cheer.',
    failure_text: 'You barely escape the webbing. Your torch sputters out as you flee.',
  },
  {
    slug: 'crystal_golem',
    title: 'Heart of Stone',
    region: 'crystal_caverns',
    level_req: 12,
    energy_cost: 14,
    duration_sec: 0,
    intro: 'A golem has awakened from ancient dwarven runes. It guards a vein of pure crystal.',
    narrative: 'The chamber thunders with each step. Crystals scatter light across the walls. The golem raises a fist of granite...',
    monster_slug: 'rock_golem',
    xp_reward: 320,
    gold_reward: 160,
    item_reward: 'plate_armor',
    success_text: 'The golem cracks and crumbles. You pry a glittering shard from its chest.',
    failure_text: 'The golem hammers you back through the corridor. You leave the crystal vein to it.',
  },
  {
    slug: 'crystal_overlord',
    title: 'The Overlord\'s Lair',
    region: 'crystal_caverns',
    level_req: 14,
    energy_cost: 16,
    duration_sec: 0,
    intro: 'Word reaches the king of an overlord crowning himself in the depths. The realm cannot allow it.',
    narrative: 'You stride into a hall of mirrored crystal. The Overlord laughs from a glittering throne, then springs at you...',
    monster_slug: 'caverns_overlord',
    xp_reward: 500,
    gold_reward: 300,
    item_reward: 'flameblade',
    success_text: 'The Overlord falls from his throne with a final, hateful breath. His blade — Flameblade — is yours.',
    failure_text: 'You stagger from the hall, the Overlord\'s laughter echoing.',
  },

  // Ashen Wastes
  {
    slug: 'ashen_revenant',
    title: 'Whispers in Ash',
    region: 'ashen_wastes',
    level_req: 16,
    energy_cost: 18,
    duration_sec: 0,
    intro: 'A scholar pays well for proof that revenants stalk the wastes. Bring back proof — or its head.',
    narrative: 'The dust kicks up around you. A grey, hollow figure rises from a heap of ash, eyes burning blue...',
    monster_slug: 'ash_revenant',
    xp_reward: 700,
    gold_reward: 350,
    item_reward: 'mage_robe',
    success_text: 'The revenant collapses to a heap of grey dust. You retrieve a scrap of glowing rune-script.',
    failure_text: 'Its cold hand sears your soul. You stagger back, hollowed.',
  },
  {
    slug: 'ashen_drake',
    title: 'Wings of Flame',
    region: 'ashen_wastes',
    level_req: 19,
    energy_cost: 20,
    duration_sec: 0,
    intro: 'A drake has been seen near the Ember Spires. Its scales would mend a king\'s armor.',
    narrative: 'The sky darkens. Wings beat once, twice. The drake lands with a bellow of flame...',
    monster_slug: 'fire_drake',
    xp_reward: 1000,
    gold_reward: 550,
    item_reward: 'ring_of_power',
    success_text: 'The drake plummets, its tail thrashing. From its hoard, a ring of power glows.',
    failure_text: 'You retreat through a wall of flame. The drake\'s laughter follows.',
  },

  // Endgame
  {
    slug: 'shadowfell_shadowlord',
    title: 'The Shadow Lord',
    region: 'shadowfell',
    level_req: 24,
    energy_cost: 30,
    duration_sec: 0,
    intro: 'The fate of Nexus itself rests on a single confrontation. The Shadow Lord stirs.',
    narrative: 'Darkness coils around you. From the void, a crown of black iron rises atop a being of pure shadow. He raises his hand and the world holds its breath...',
    monster_slug: 'shadow_lord',
    xp_reward: 3000,
    gold_reward: 1500,
    item_reward: 'dragonbane',
    success_text: 'The Shadow Lord shatters in a thousand shards of dusk. Light returns to Nexus Dominion, and the legendary Dragonbane is yours.',
    failure_text: 'You fall. The kingdom awaits another hero.',
  },

  // Story / Skill quests (no monster)
  {
    slug: 'help_old_hermit',
    title: 'Aid the Old Hermit',
    region: 'whispering_woods',
    level_req: 1,
    energy_cost: 3,
    duration_sec: 0,
    intro: 'An old hermit asks for herbs from a perilous patch of nettles.',
    narrative: 'You weave through brambles, plucking the herbs while avoiding their thorny barbs.',
    monster_slug: '',
    xp_reward: 15,
    gold_reward: 10,
    item_reward: '',
    success_text: 'The hermit smiles, gums showing. "Here, traveler. A few coins for your trouble."',
    failure_text: 'Your hands are too clumsy. You return scratched and herb-less.',
  },
  {
    slug: 'lost_journal',
    title: 'The Lost Journal',
    region: 'mistmoor_hills',
    level_req: 6,
    energy_cost: 5,
    duration_sec: 0,
    intro: 'A traveling scribe lost his journal on the trail. It must be returned.',
    narrative: 'You follow the trail for hours, sifting through leaves and brush. At last you spot a leather cover.',
    monster_slug: '',
    xp_reward: 60,
    gold_reward: 30,
    item_reward: '',
    success_text: 'The scribe weeps and presses a coin into your hand. "My life\'s work."',
    failure_text: 'You search until dusk but find nothing.',
  },
];
