// Service worker: rule toggling, allowlist, stats and messaging.

// Single source of the scriptlet/selector policy (shared with the engine and the
// build). Classic worker → synchronous importScripts; if it ever fails the
// live-config path throws and the update is rejected (fail-closed).
importScripts("scriptlets/policy.js");

const RULESET_IDS = ["ad_rules", "youtube_rules", "easylist", "easyprivacy", "removeparam", "urlhaus", "surrogates", "headers", "privacy"];

// Rule counts per bundled ruleset, generated by tools/build_filters.mjs.
let ruleCounts = null;
async function getRuleCounts() {
  if (ruleCounts) return ruleCounts;
  try {
    const res = await fetch(chrome.runtime.getURL("rules/counts.json"));
    ruleCounts = await res.json();
  } catch {
    ruleCounts = {};
  }
  return ruleCounts;
}

// Dynamic-rule id ranges, kept clear of the static rulesets.
const YT_BYPASS_RULE_ID = 70000; // YouTube session bypass (allowAllRequests); below every sync range
const USER_BLOCK_BASE = 80000;   // user "my filters" block rules
const ALLOW_RULE_BASE = 90000;   // allowlist (allowAllRequests)
const ALLOW_RULE_MAX = 5000;     // cap: allowlist ids must stay below LIVE_RULE_BASE (same cap as import)
const LIVE_RULE_BASE = 100000;   // block domains from the live filter update

// Live filter updates: DATA only (domains + CSS selectors), never code.
// Update this JSON on the server and every install refreshes itself, no
// Web Store re-review needed. MV3 forbids remote CODE, not remote data.
const CONFIG_URL = "https://adblock.carbonstealth.eu/filters.json";
// 20k live domains fit comfortably: block rules with requestDomains are "safe"
// dynamic rules (30k cap) and are chunked 1000 per rule (see domainBlockRules),
// so the store holds 20 rules, not 20 000.
const LIVE_RULE_MAX = 20000;
const USER_RULE_MAX = 2000;
const DOMAINS_PER_RULE = 1000;
const BLOCK_TYPES = ["script", "image", "sub_frame", "xmlhttprequest", "media", "ping", "font", "stylesheet", "object"];

// One DNR block rule per ≤1000 domains (requestDomains matches the domain and its
// subdomains, exactly like ||domain^). Ids: base, base+1, … — never main_frame.
function domainBlockRules(domains, base, cap) {
  const list = domains.slice(0, cap);
  const rules = [];
  for (let i = 0; i < list.length; i += DOMAINS_PER_RULE) {
    rules.push({
      id: base + rules.length,
      priority: 1,
      action: { type: "block" },
      condition: { requestDomains: list.slice(i, i + DOMAINS_PER_RULE), resourceTypes: BLOCK_TYPES },
    });
  }
  return rules;
}

// YouTube anti-adblock bypass window. When YouTube hard-blocks playback (its
// "3 strikes" enforcement) we turn the YouTube DNR ruleset OFF for this long so
// the page is a genuinely clean client and videos play (ads return, auto-skip
// still fast-forwards them). It auto-expires so blocking retries later —
// enforcement comes in waves, so we don't give up ad blocking permanently.
const YT_BYPASS_MS = 6 * 60 * 60 * 1000; // 6h

// Ed25519 подпис на filters.json (data-only канала). Публичният ключ е вграден;
// приватният живее само на сървъра (deploy-ът подписва при качване). Ако .sig
// файлът съществува и не съвпада, ъпдейтът се отхвърля и остава последната
// добра конфигурация. Докато собственикът не качи ключ (.sig липсва, 404),
// ъпдейтите се приемат както досега; после SIG_REQUIRED става true в релийз.
const SIG_URL = CONFIG_URL + ".sig";
// Rotation without a flag day: ship a release with [current, next], switch the
// server to sign with `next`, then drop `current` in a later release. Every
// listed key is tried; the first that verifies wins.
const SIG_PUBKEYS_B64 = ["dHNcuMuLraQ8w1sse7rk6Dnzzh5wzbLc4/KofD5QWMQ="]; // raw Ed25519 публични ключове

// Политика: щом ключ е конфигуриран И платформата може да верифицира Ed25519
// (Chrome 137+), изискваме ВАЛИДЕН подпис — липсващ или невалиден .sig отхвърля
// ъпдейта (спира downgrade при компрометиран сървър). На стар браузър, който не
// поддържа Ed25519, приемаме best-effort, за да не спрем live ъпдейтите (121-136).
let ed25519Supported = null;
const rawKey = (b64) => Uint8Array.from(atob(b64), (c) => c.charCodeAt(0));
async function canVerifyEd25519() {
  if (ed25519Supported !== null) return ed25519Supported;
  if (!SIG_PUBKEYS_B64.length) { ed25519Supported = false; return false; }
  try {
    await crypto.subtle.importKey("raw", rawKey(SIG_PUBKEYS_B64[0]), { name: "Ed25519" }, false, ["verify"]);
    ed25519Supported = true;
  } catch {
    ed25519Supported = false; // Chrome < 137
  }
  return ed25519Supported;
}

async function verifySignature(bytes, sigB64) {
  let sig;
  try { sig = rawKey((sigB64 || "").trim()); } catch { return false; }
  for (const pub of SIG_PUBKEYS_B64) {
    try {
      const key = await crypto.subtle.importKey("raw", rawKey(pub), { name: "Ed25519" }, false, ["verify"]);
      if (await crypto.subtle.verify("Ed25519", key, sig, bytes)) return true;
    } catch {}
  }
  return false; // не можем да потвърдим валиден подпис → третираме като невалиден
}

// never block these from a user filter, even by mistake
const NEVER_BLOCK = SA_POLICY.NEVER_LIVE; // single source: scriptlets/policy.js
const isProtected = (d) => NEVER_BLOCK.some((p) => d === p || d.endsWith("." + p));

// avg bytes per blocked resource type. count is exact, size is approximate
// (the request never loads, so its real size is unknown)
const SIZE_BY_TYPE = {
  script: 95 * 1024,
  image: 38 * 1024,
  sub_frame: 75 * 1024,
  xmlhttprequest: 9 * 1024,
  media: 620 * 1024,
  ping: 1 * 1024,
  font: 28 * 1024,
  stylesheet: 16 * 1024,
  object: 110 * 1024,
  websocket: 2 * 1024,
  other: 20 * 1024,
};
const BLENDED_SIZE = 55 * 1024;
const BANDWIDTH = 1.6 * 1024 * 1024; // bytes/s, for the time estimate
const LATENCY_MS = 40; // per-request round-trip overhead

const DEFAULTS = {
  enabled: true,
  blockedTotal: 0,
  savedBytes: 0,
  smartBlocked: 0,
  smartLog: [],
  allowlist: [],
  features: { cookies: true, antiAdblock: true, meta: true, youtube: true, smart: true, removeparam: true, malware: false, topics: true, privacy: true },
  customHidden: {},
  userFilters: "",
  theme: "carbon",
  sync: false,
  pausedUntil: 0,
  autoUpdate: true,
  liveConfig: null,
  liveUpdated: 0,
  subscriptions: [],   // [{ url, added, fetched, count, error }] — filter lists refreshed daily (text, never code)
  noCosmetics: [],     // hosts where cosmetic (element-hiding) filtering is off; network blocking stays
};

// Settings mirrored to chrome.storage.sync when cross-device sync is on.
const SYNC_KEYS = ["enabled", "features", "theme", "allowlist", "userFilters", "subscriptions", "noCosmetics"];

chrome.runtime.onInstalled.addListener(async () => {
  const stored = await chrome.storage.local.get(Object.keys(DEFAULTS));
  const patch = {};
  for (const [k, v] of Object.entries(DEFAULTS)) {
    if (stored[k] === undefined) patch[k] = v;
  }
  if (Object.keys(patch).length) await chrome.storage.local.set(patch);
  await applyState();
  await syncAllowRules();
  await syncUserRules();
  createMenus();
  chrome.alarms.create("config-update", { periodInMinutes: 720 }); // every 12h
  chrome.alarms.create("subs-refresh", { periodInMinutes: 1440 }); // subscribed filter lists, daily
  await reconcileYtBypass(); // update clears alarms; re-arm/clear an in-flight bypass
  fetchLiveConfig();
});

chrome.runtime.onStartup.addListener(async () => {
  const { sync, pausedUntil, liveConfig } = await chrome.storage.local.get([
    "sync",
    "pausedUntil",
    "liveConfig",
  ]);
  if (sync) await pullFromSync();
  // Restore or expire a pending pause.
  if (pausedUntil && pausedUntil > Date.now()) {
    chrome.alarms.create("resume", { when: pausedUntil });
  } else if (pausedUntil) {
    await chrome.storage.local.set({ enabled: true, pausedUntil: 0 });
  }
  await applyState();
  await syncAllowRules();
  await syncUserRules();
  await syncLiveRules(liveConfig?.blockDomains || []); // re-apply + clear stale
  createMenus();
  chrome.alarms.create("config-update", { periodInMinutes: 720 });
  chrome.alarms.create("subs-refresh", { periodInMinutes: 1440 });
  await reconcileYtBypass();
});

// right-click entries: element picker (saves) + zapper (one-off)
function createMenus() {
  try {
    chrome.contextMenus.removeAll(() => {
      const contexts = ["page", "image", "video", "link", "frame"];
      chrome.contextMenus.create({ id: "tbab-pick", title: "Block an element here", contexts });
      chrome.contextMenus.create({ id: "tbab-zap", title: "Zap this element (once)", contexts });
    });
  } catch (e) {}
}

// cross-device sync via chrome.storage.sync
async function pushToSync() {
  try {
    await chrome.storage.sync.set(await chrome.storage.local.get(SYNC_KEYS));
  } catch (e) {
    console.warn("sync push failed", e);
  }
}

async function pullFromSync() {
  try {
    const data = await chrome.storage.sync.get(SYNC_KEYS);
    const patch = {};
    for (const k of SYNC_KEYS) if (data[k] !== undefined) patch[k] = data[k];
    if (Object.keys(patch).length) await chrome.storage.local.set(patch);
  } catch (e) {}
}

// Cache the sync flag so we don't hit storage on every change (the stats
// counter writes once a second).
let syncOn = false;
chrome.storage.local.get("sync", (d) => (syncOn = !!d.sync));

chrome.storage.onChanged.addListener(async (changes, area) => {
  if (area === "local" && changes.sync) syncOn = !!changes.sync.newValue;
  if (!syncOn) return;

  if (area === "local") {
    const patch = {};
    for (const k of SYNC_KEYS) if (k in changes) patch[k] = changes[k].newValue;
    if (Object.keys(patch).length) {
      try {
        await chrome.storage.sync.set(patch);
      } catch (e) {}
    }
  } else if (area === "sync") {
    const patch = {};
    for (const k of SYNC_KEYS) if (k in changes) patch[k] = changes[k].newValue;
    if (!Object.keys(patch).length) return;
    // Only write differing values, so the local<->sync mirror can't loop.
    const cur = await chrome.storage.local.get(Object.keys(patch));
    const diff = {};
    for (const k in patch) {
      if (JSON.stringify(cur[k]) !== JSON.stringify(patch[k])) diff[k] = patch[k];
    }
    if (Object.keys(diff).length) {
      await chrome.storage.local.set(diff);
      await applyState();
      await syncAllowRules();
      await syncUserRules();
    }
  }
});

// temporary pause, auto-resumes via alarm
async function pauseFor(minutes) {
  const until = Date.now() + minutes * 60000;
  await chrome.storage.local.set({ enabled: false, pausedUntil: until });
  await applyState();
  chrome.alarms.create("resume", { when: until });
}

async function resumeNow() {
  await chrome.alarms.clear("resume");
  await chrome.storage.local.set({ enabled: true, pausedUntil: 0 });
  await applyState();
}

chrome.alarms.onAlarm.addListener((a) => {
  if (a.name === "resume") resumeNow();
  if (a.name === "config-update") fetchLiveConfig();
  if (a.name === "scriptlets-retry") syncScriptlets();
  if (a.name === "subs-refresh") refreshAllSubscriptions();
  if (a.name === "yt-bypass-expire") chrome.storage.local.remove("ytBypassUntil").then(() => setYtBypassRule(false));
});

chrome.contextMenus?.onClicked.addListener((info, tab) => {
  if (!tab?.id) return;
  if (info.menuItemId === "tbab-pick") chrome.tabs.sendMessage(tab.id, { type: "activatePicker" });
  else if (info.menuItemId === "tbab-zap") chrome.tabs.sendMessage(tab.id, { type: "activateZapper" });
});

// Enable or disable the bundled static rulesets. The YouTube ruleset also
// follows the "youtube" feature toggle so it can be turned off independently.
async function applyState() {
  const { enabled, features } = await chrome.storage.local.get(["enabled", "features"]);
  const on = enabled !== false;
  const f = features || DEFAULTS.features;
  const ytOn = on && f.youtube !== false;

  const enable = [];
  const disable = [];
  (on ? enable : disable).push("ad_rules", "easylist", "easyprivacy", "surrogates");
  (ytOn ? enable : disable).push("youtube_rules");
  (on && f.removeparam !== false ? enable : disable).push("removeparam");
  (on && f.malware === true ? enable : disable).push("urlhaus");
  (on && f.topics !== false ? enable : disable).push("headers");
  (on && f.privacy !== false ? enable : disable).push("privacy");

  try {
    await chrome.declarativeNetRequest.updateEnabledRulesets({
      enableRulesetIds: enable,
      disableRulesetIds: disable,
    });
  } catch (e) {
    console.warn("ruleset toggle failed", e);
  }
  await syncScriptlets(on);
  chrome.action.setBadgeBackgroundColor({ color: on ? "#00838f" : "#5a5a5a" });
}

// ---- Scriptlet engine (##+js) ----
// Registers scriptlets/main.js as a MAIN-world, document_start content script
// (built from scriptlets/list.txt by tools/build_scriptlets.mjs). The CODE
// ships in the package; the per-site directive MAP is baked at build time —
// nothing is fetched or evaluated at runtime (MV3 compliant). We register it
// dynamically (not in the manifest) so we can honour the global on/off toggle
// and skip allowlisted sites. `world:"MAIN"` needs Chrome 111+ (min is 121).
const SCRIPTLET_SCRIPT_ID = "sa-scriptlets";

// Serialise register/unregister so a fast on/off/on burst (alarm + message
// racing through applyState) can't interleave the awaits and leave the engine
// registered while disabled, or vice versa. Same pattern as smartChain below.
let scriptletChain = Promise.resolve();
function syncScriptlets(on) {
  scriptletChain = scriptletChain.then(() => doSyncScriptlets(on)).catch(() => {});
  return scriptletChain;
}

async function doSyncScriptlets(on) {
  if (!chrome.scripting?.registerContentScripts) return;
  if (on === undefined) {
    const { enabled } = await chrome.storage.local.get("enabled");
    on = enabled !== false;
  }
  // Always clear first so a re-register can't throw "already registered".
  try {
    const existing = await chrome.scripting.getRegisteredContentScripts({ ids: [SCRIPTLET_SCRIPT_ID] });
    if (existing.length) await chrome.scripting.unregisterContentScripts({ ids: [SCRIPTLET_SCRIPT_ID] });
  } catch (e) {}
  if (!on) return;

  const { allowlist = [] } = await chrome.storage.local.get("allowlist");
  const excludeMatches = [];
  for (const d of allowlist) {
    if (typeof d !== "string" || !/^[a-z0-9.-]+\.[a-z]{2,}$/i.test(d)) continue;
    excludeMatches.push(`*://${d}/*`, `*://*.${d}/*`);
  }

  const script = {
    id: SCRIPTLET_SCRIPT_ID,
    matches: ["<all_urls>"],
    js: ["scriptlets/main.js"],
    runAt: "document_start",
    allFrames: true,
    world: "MAIN",
    // Explicit: Chrome auto-restores the registration on restart before
    // onStartup runs; onStartup then clears + re-registers to refresh
    // excludeMatches. We rely on injection without a live service worker.
    persistAcrossSessions: true,
  };
  if (excludeMatches.length) script.excludeMatches = excludeMatches;

  try {
    await chrome.scripting.registerContentScripts([script]);
    try { await chrome.storage.local.set({ scriptletsError: "" }); } catch {}
  } catch (e) {
    console.warn("scriptlet registration failed", e);
    // Surface it (health card) and retry once shortly: a transient failure here
    // means NO scriptlets on any page until the next applyState.
    try { await chrome.storage.local.set({ scriptletsError: String((e && e.message) || e) }); } catch {}
    try { chrome.alarms.create("scriptlets-retry", { delayInMinutes: 1 }); } catch {}
  }
}

// YouTube session bypass: one high-priority allowAllRequests rule scoped to
// YouTube. It overrides EVERY block ruleset (youtube_rules AND easylist/
// easyprivacy, which also block YouTube's first-party detection paths), so the
// reloaded page's network is unblocked. Paired with youtube_loader skipping the
// player-script injection and youtube_skip skipping ad manipulation during the
// bypass (see bgBypass), the client stops signalling ad blocking, so playback
// resumes. Its id sits below all sync ranges so syncAllow/User/LiveRules never
// touch it. Removed when the bypass window (YT_BYPASS_MS) expires.
async function setYtBypassRule(active) {
  const addRules = active
    ? [{
        id: YT_BYPASS_RULE_ID,
        priority: 20000, // above allowlist (10000) and every block rule
        action: { type: "allowAllRequests" },
        condition: {
          requestDomains: ["youtube.com", "youtube-nocookie.com"],
          resourceTypes: ["main_frame", "sub_frame"],
        },
      }]
    : [];
  try {
    await chrome.declarativeNetRequest.updateDynamicRules({
      removeRuleIds: [YT_BYPASS_RULE_ID],
      addRules,
    });
  } catch (e) {
    console.warn("yt bypass rule update failed", e);
  }
}

// Reconcile the persisted YouTube bypass with its expiry. Dynamic rules and
// storage survive restarts/updates but alarms do not, so both onStartup AND
// onInstalled must call this — otherwise an in-flight bypass can outlive its
// window until the next browser restart.
async function reconcileYtBypass() {
  const { ytBypassUntil } = await chrome.storage.local.get("ytBypassUntil");
  if (ytBypassUntil && ytBypassUntil > Date.now()) {
    await setYtBypassRule(true);
    chrome.alarms.create("yt-bypass-expire", { when: ytBypassUntil });
  } else {
    if (ytBypassUntil) await chrome.storage.local.remove("ytBypassUntil");
    await setYtBypassRule(false);
  }
}

// ---- Live filter update (remote DATA, never code) ----
const strArr = (x, cap) =>
  Array.isArray(x)
    ? x.filter((s) => typeof s === "string" && s.length < 400).slice(0, cap)
    : [];

// Selector policy (form controls / credential fields / whole-page selectors are
// refused) lives in scriptlets/policy.js — one rule set for live cosmetic
// filters, imported settings and live scriptlets.
const safeSelector = (s) => SA_POLICY.safeSelector(s);
const selArr = (x, cap) => strArr(x, cap).filter(safeSelector);

// Player-response fields the config must never be able to delete (would break
// playback), so ad-field pruning can only touch genuine ad fields.
const PROTECTED_YT_FIELDS = new Set([
  "videoDetails", "streamingData", "playerConfig", "playabilityStatus",
  "captions", "storyboards", "microformat", "trackingParams", "responseContext",
]);

// ---- Live scriptlets (Level 2, DATA only) ----
// filters.json may carry `scriptlets: [{ h: "host.tld" | "", n: "name", a: [args] }]`.
// We canonicalise uBO aliases and validate with rules that are a STRICT
// SUPERSET of tools/build_scriptlets.mjs (the baked list is trusted dev input;
// this channel is not): selector/attribute/tag policy, the cookie-name denylist
// and the remove-cookie refusal apply only here and in the engine. Invariant:
// live accepts ⇒ build accepts, never the reverse. The profile is ONE function in
// scriptlets/policy.js (validateDirective(name, args, live)) shared by the build,
// this worker and the engine. content.js hands the result to the MAIN-world
// engine, which re-validates on arrival. Only names the engine
// ships are accepted; NO trusted-* variants; never on core video/CDN hosts.
function validateScriptlet(rawName, args) {
  const name = SA_POLICY.canonical(rawName);
  if (!name || !Array.isArray(args)) return null;
  return SA_POLICY.validateDirective(name, args, true) ? [name, ...args] : null;
}

function sanitizeScriptlets(x) {
  if (!Array.isArray(x)) return [];
  const out = [];
  for (const it of x.slice(0, 500)) {
    if (!it || typeof it !== "object") continue;
    const h = typeof it.h === "string" ? it.h.trim().toLowerCase() : "";
    if (h !== "" && !/^[a-z0-9.-]+\.[a-z]{2,}$/.test(h)) continue;
    if (!h) continue;             // live = explicit host only (global anti-adblock is baked in MAP)
    if (isProtected(h)) continue; // YouTube & co. are handled by dedicated code
    const d = validateScriptlet(it.n, Array.isArray(it.a) ? it.a : []);
    if (d) out.push({ h, d });
  }
  return out;
}

// Reduce the fetched JSON to a strict, known shape. Everything is treated as
// inert data (domain strings, CSS selectors); nothing is ever executed.
function sanitizeConfig(cfg) {
  const yt = cfg && typeof cfg.youtube === "object" ? cfg.youtube : {};
  return {
    version: Number.isFinite(cfg?.version) ? cfg.version : 0,
    blockDomains: strArr(cfg?.blockDomains, LIVE_RULE_MAX)
      .map((d) => d.toLowerCase().replace(/^\|\|/, "").replace(/[\^/].*$/, ""))
      .filter((d) => /^[a-z0-9.-]+\.[a-z]{2,}$/.test(d) && !isProtected(d)),
    cosmetic: selArr(cfg?.cosmetic, 2000),
    scriptlets: sanitizeScriptlets(cfg?.scriptlets),      // Level 2 live directives (data)
    youtube: {
      hide: selArr(yt.hide, 300),
      skip: selArr(yt.skip, 100),
      enforcement: selArr(yt.enforcement, 50),
      adFields: strArr(yt.adFields, 50).filter(
        (f) => /^[a-zA-Z]+$/.test(f) && !PROTECTED_YT_FIELDS.has(f)
      ),
      // Дот-пътища в player ЗАЯВКАТА, чиято стойност се вдига на true (напр.
      // playbackContext.contentPlaybackContext.isInlinePlaybackNoAd). Само
      // данни: пътят е стойност, логиката (set на true) е в пакета.
      requestFlags: strArr(yt.requestFlags, 10).filter((p) =>
        /^[a-zA-Z][a-zA-Z0-9]*(\.[a-zA-Z][a-zA-Z0-9]*){0,5}$/.test(p) &&
        !p.split(".").some((seg) => PROTECTED_YT_FIELDS.has(seg))
      ),
      // Авариен стоп: ако флаговете някога счупят възпроизвеждането, това
      // ги изключва от сървъра без нов релийз.
      disableRequestFlags: yt.disableRequestFlags === true,
      // Имена на ad renderer ключове за прунинг от browse/search/next
      // отговорите (feed/search реклами), добавка към вградения списък.
      adRenderers: strArr(yt.adRenderers, 100).filter(
        (f) => /^[a-zA-Z][a-zA-Z0-9]*$/.test(f) && !PROTECTED_YT_FIELDS.has(f)
      ),
    },
  };
}

async function syncLiveRules(domains = []) {
  const existing = await chrome.declarativeNetRequest.getDynamicRules();
  const removeRuleIds = existing.filter((r) => r.id >= LIVE_RULE_BASE).map((r) => r.id);
  const addRules = domainBlockRules(domains, LIVE_RULE_BASE, LIVE_RULE_MAX);
  try {
    await chrome.declarativeNetRequest.updateDynamicRules({ removeRuleIds, addRules });
  } catch (e) {
    console.warn("live rules failed", e);
  }
}

// Wrapper: remember the last failure reason for the health card (cleared on success;
// "off" is not a failure).
async function fetchLiveConfig(force) {
  const r = await fetchLiveConfigInner(force);
  try {
    if (r.ok) await chrome.storage.local.set({ liveError: "" });
    else if (r.reason !== "off") await chrome.storage.local.set({ liveError: r.reason, liveErrorAt: Date.now() });
  } catch {}
  return r;
}
async function fetchLiveConfigInner(force) {
  const { autoUpdate } = await chrome.storage.local.get("autoUpdate");
  if (!force && autoUpdate === false) return { ok: false, reason: "off" };
  let raw;
  try {
    const res = await fetch(CONFIG_URL, { cache: "no-cache" });
    if (!res.ok) return { ok: false, reason: "http " + res.status };
    const text = await res.text();

    // Подпис: щом ключ е конфигуриран И платформата поддържа Ed25519,
    // ИЗИСКВАМЕ валиден подпис — липсващ (.sig 404 / мрежа) или невалиден
    // отхвърля ъпдейта (спира downgrade при компрометиран сървър). На стар
    // браузър без Ed25519 приемаме best-effort, за да не спрем live ъпдейтите.
    if (SIG_PUBKEYS_B64.length && (await canVerifyEd25519())) {
      let sigText = null;
      try {
        const sres = await fetch(SIG_URL, { cache: "no-cache" });
        if (sres.ok) sigText = await sres.text();
      } catch {}
      if (sigText === null) return { ok: false, reason: "no signature" };
      const ok = await verifySignature(new TextEncoder().encode(text), sigText);
      if (!ok) return { ok: false, reason: "bad signature" };
    }

    raw = JSON.parse(text);
  } catch (e) {
    return { ok: false, reason: "network" };
  }
  const cfg = sanitizeConfig(raw);
  // Anti-rollback: подписът доказва автентичност, не свежест. Отхвърляме стар
  // (валидно подписан) config — компрометиран сървър да не може да replay-не
  // остаряла версия. version-ът трябва да е монотонен.
  const { liveConfig: prev } = await chrome.storage.local.get("liveConfig");
  if (prev && Number.isFinite(prev.version) && cfg.version < prev.version) {
    return { ok: false, reason: "stale version" };
  }
  await chrome.storage.local.set({ liveConfig: cfg, liveUpdated: Date.now() });
  await syncLiveRules(cfg.blockDomains);
  return { ok: true, version: cfg.version, domains: cfg.blockDomains.length };
}

// Rebuild the allowlist rules (one allowAllRequests rule per whitelisted host).
async function syncAllowRules() {
  const { allowlist = [] } = await chrome.storage.local.get("allowlist");
  const existing = await chrome.declarativeNetRequest.getDynamicRules();
  const removeRuleIds = existing
    .filter((r) => r.id >= ALLOW_RULE_BASE && r.id < LIVE_RULE_BASE)
    .map((r) => r.id);

  const addRules = allowlist.slice(0, ALLOW_RULE_MAX).map((domain, i) => ({
    id: ALLOW_RULE_BASE + i,
    priority: 10000,
    action: { type: "allowAllRequests" },
    condition: {
      requestDomains: [domain],
      resourceTypes: ["main_frame", "sub_frame"],
    },
  }));

  try {
    await chrome.declarativeNetRequest.updateDynamicRules({ removeRuleIds, addRules });
  } catch (e) {
    console.warn("allow rules update failed", e);
  }
}

// "My filters": lines that aren't cosmetic (no "##") and look like a domain
// become block rules. uBlock-style ||domain^ and bare domains both work.
function parseUserDomains(text) {
  const set = new Set();
  for (let line of (text || "").split("\n")) {
    line = line.trim();
    if (!line || line.startsWith("!") || line.includes("##")) continue;
    const d = line
      .replace(/^\|\|/, "")
      .replace(/[\^/].*$/, "")
      .replace(/^https?:\/\//, "")
      .toLowerCase();
    if (/^[a-z0-9.-]+\.[a-z]{2,}$/.test(d) && !isProtected(d)) set.add(d);
  }
  return [...set];
}

// ---- Filter-list subscriptions (TEXT, never code) ----
// A subscription is a URL the user chose. We fetch it as text, keep only the
// lines we can apply (bare domain blocks + ##cosmetic, sanitised through the
// shared selector policy) and write them into "My filters" as a managed block
// between markers, so refreshes replace exactly that block and never touch the
// user's own lines. Refreshed daily by the subs-refresh alarm.
const SUB_MAX = 20;
const SUB_LINES_MAX = 5000;
const SUB_BYTES_MAX = 5 * 1024 * 1024;
const subStart = (url) => "! === subscription: " + url + " ===";
const SUB_END = "! === end subscription ===";
const isSubUrl = (u) => typeof u === "string" && /^https:\/\/[^\s"'<>]{4,500}$/.test(u);

function parseImportedList(text) {
  const keep = [];
  for (let line of String(text).split("\n")) {
    line = line.trim();
    if (!line || line.startsWith("!") || line.startsWith("[") || line.startsWith("#")) continue;
    if (line.includes("##")) {
      if (line.includes("#@#") || line.includes("+js(")) continue; // no exceptions, no scriptlets from imports
      const sel = line.slice(line.indexOf("##") + 2);
      if (!safeSelector(sel)) continue;
      keep.push(line);
    } else if (/^(\|\|)?[a-z0-9.-]+\.[a-z]{2,}\^?$/i.test(line)) {
      const d = line.replace(/[|^]/g, "").toLowerCase();
      if (!isProtected(d)) keep.push(d);
    }
    if (keep.length >= SUB_LINES_MAX) break;
  }
  return keep;
}

// Replace (or remove, when lines is null) the managed block for url inside text.
function setSubscriptionBlock(text, url, lines) {
  const src = String(text || "").split("\n");
  const out = [];
  let skipping = false;
  for (const l of src) {
    if (l.trim() === subStart(url)) { skipping = true; continue; }
    if (skipping) { if (l.trim() === SUB_END) skipping = false; continue; }
    out.push(l);
  }
  while (out.length && !out[out.length - 1].trim()) out.pop();
  if (lines) out.push("", subStart(url), ...lines, SUB_END);
  return out.join("\n");
}

async function fetchListText(url) {
  const res = await fetch(url, { cache: "no-cache" });
  if (!res.ok) throw new Error("http " + res.status);
  const len = Number(res.headers && res.headers.get && res.headers.get("content-length"));
  if (len && len > SUB_BYTES_MAX) throw new Error("too large");
  const text = await res.text();
  if (text.length > SUB_BYTES_MAX) throw new Error("too large");
  return text;
}

let subsChain = Promise.resolve();
function withSubs(fn) { subsChain = subsChain.then(fn).catch((e) => { console.warn("subscriptions", e); }); return subsChain; }

async function refreshSubscription(url) {
  const { subscriptions = [], userFilters = "" } = await chrome.storage.local.get(["subscriptions", "userFilters"]);
  const sub = subscriptions.find((s) => s.url === url);
  if (!sub) return { ok: false, reason: "unknown" };
  try {
    const lines = parseImportedList(await fetchListText(url));
    sub.fetched = Date.now(); sub.count = lines.length; sub.error = "";
    await chrome.storage.local.set({ userFilters: setSubscriptionBlock(userFilters, url, lines), subscriptions });
    await syncUserRules();
    return { ok: true, count: lines.length };
  } catch (e) {
    sub.error = String((e && e.message) || e); sub.fetched = sub.fetched || 0;
    await chrome.storage.local.set({ subscriptions });
    return { ok: false, reason: sub.error };
  }
}
async function refreshAllSubscriptions() {
  const { subscriptions = [] } = await chrome.storage.local.get("subscriptions");
  for (const s of subscriptions) await withSubs(() => refreshSubscription(s.url));
}
async function addSubscription(url) {
  if (!isSubUrl(url)) return { ok: false, reason: "invalid url" };
  const { subscriptions = [] } = await chrome.storage.local.get("subscriptions");
  if (subscriptions.some((s) => s.url === url)) return refreshSubscription(url);
  if (subscriptions.length >= SUB_MAX) return { ok: false, reason: "limit" };
  subscriptions.push({ url, added: Date.now(), fetched: 0, count: 0, error: "" });
  await chrome.storage.local.set({ subscriptions });
  return refreshSubscription(url);
}
async function removeSubscription(url) {
  const { subscriptions = [], userFilters = "" } = await chrome.storage.local.get(["subscriptions", "userFilters"]);
  await chrome.storage.local.set({ subscriptions: subscriptions.filter((s) => s.url !== url), userFilters: setSubscriptionBlock(userFilters, url, null) });
  await syncUserRules();
  return { ok: true };
}

async function syncUserRules() {
  const { userFilters = "" } = await chrome.storage.local.get("userFilters");
  const domains = parseUserDomains(userFilters);
  const existing = await chrome.declarativeNetRequest.getDynamicRules();
  const removeRuleIds = existing
    .filter((r) => r.id >= USER_BLOCK_BASE && r.id < ALLOW_RULE_BASE)
    .map((r) => r.id);
  const addRules = domainBlockRules(domains, USER_BLOCK_BASE, USER_RULE_MAX);
  try {
    await chrome.declarativeNetRequest.updateDynamicRules({ removeRuleIds, addRules });
  } catch (e) {
    console.warn("user rules update failed", e);
  }
}

// Домейн-специфична козметика от EasyList (bundle-ната при билда). Зарежда се
// мързеливо и живее в паметта на service worker-а; content.js я иска per host.
let cosmeticBundle = null;
async function getCosmeticBundle() {
  if (cosmeticBundle) return cosmeticBundle;
  try {
    const res = await fetch(chrome.runtime.getURL("rules/cosmetic_specific.json"));
    cosmeticBundle = await res.json();
  } catch {
    cosmeticBundle = { specific: {}, unhide: {}, genericHide: [] };
  }
  return cosmeticBundle;
}

// Всички селектори за host: точният домейн + всеки родителски суфикс
// (sub.example.com -> sub.example.com, example.com).
function domainChain(host) {
  const parts = host.split(".");
  const out = [];
  for (let i = 0; i < parts.length - 1; i++) out.push(parts.slice(i).join("."));
  return out;
}

async function cosmeticFor(host) {
  const { specific = {}, unhide = {}, genericHide = [] } = await getCosmeticBundle();
  const hide = [];
  const show = [];
  const chain = domainChain(host || "");
  for (const d of chain) {
    if (specific[d]) hide.push(...specific[d]);
    if (unhide[d]) show.push(...unhide[d]);
  }
  // $generichide за този хост (или родителски суфикс) → content.js спира
  // прилагането на глобалния генеричен CSS тук.
  const ghSet = genericHide.length ? new Set(genericHide) : null;
  const genericHideHere = ghSet ? chain.some((d) => ghSet.has(d)) : false;
  return { hide, unhide: show, genericHide: genericHideHere };
}

// blocked-request counters
const tabMatched = new Map();
let pendingCount = 0;
let pendingBytes = 0;
let flushTimer = null;

function record(count, bytes) {
  pendingCount += count;
  pendingBytes += bytes;
  if (flushTimer) return;
  flushTimer = setTimeout(async () => {
    const c = pendingCount;
    const b = pendingBytes;
    pendingCount = pendingBytes = 0;
    flushTimer = null;
    const { blockedTotal = 0, savedBytes = 0 } = await chrome.storage.local.get([
      "blockedTotal",
      "savedBytes",
    ]);
    await chrome.storage.local.set({
      blockedTotal: blockedTotal + c,
      savedBytes: savedBytes + b,
    });
  }, 1000);
}

// Smart Detection hits arrive from every frame (content.js is all_frames), so
// serialise the read-modify-write through one chain to avoid lost updates.
let smartChain = Promise.resolve();
function recordSmart(host, items) {
  smartChain = smartChain
    .then(async () => {
      const { smartBlocked = 0, smartLog = [] } = await chrome.storage.local.get([
        "smartBlocked",
        "smartLog",
      ]);
      const now = Date.now();
      const entries = items.map((it) => ({ host, w: it.w, h: it.h, reason: it.reason, time: now }));
      await chrome.storage.local.set({
        smartBlocked: smartBlocked + items.length,
        smartLog: entries.concat(smartLog).slice(0, 50),
      });
    })
    .catch(() => {});
}

const DEBUG_COUNTING = !!chrome.declarativeNetRequest.onRuleMatchedDebug;

if (DEBUG_COUNTING) {
  chrome.declarativeNetRequest.onRuleMatchedDebug.addListener((info) => {
    const id = info?.rule?.ruleId;
    // Don't count allow rules: the allowlist range and the YouTube bypass rule.
    // Live block rules (≥ LIVE_RULE_BASE) DO count.
    if ((id >= ALLOW_RULE_BASE && id < LIVE_RULE_BASE) || id === YT_BYPASS_RULE_ID) return;
    record(1, SIZE_BY_TYPE[info?.request?.type] ?? BLENDED_SIZE);
  });
}

async function refreshBadge(tabId) {
  try {
    const { enabled } = await chrome.storage.local.get("enabled");
    if (enabled === false) {
      chrome.action.setBadgeText({ text: "", tabId });
      return;
    }
    const info = await chrome.declarativeNetRequest.getMatchedRules({ tabId });
    const count = info?.rulesMatchedInfo?.length || 0;
    if (!DEBUG_COUNTING) {
      const prev = tabMatched.get(tabId) || 0;
      if (count > prev) record(count - prev, (count - prev) * BLENDED_SIZE);
    }
    tabMatched.set(tabId, count);
    chrome.action.setBadgeText({ text: count > 0 ? String(count) : "", tabId });
  } catch (e) {}
}

chrome.tabs.onUpdated.addListener((tabId, changeInfo) => {
  if (changeInfo.status === "loading" && changeInfo.url) tabMatched.set(tabId, 0);
  if (changeInfo.status === "complete") refreshBadge(tabId);
});
chrome.tabs.onActivated.addListener(({ tabId }) => refreshBadge(tabId));
chrome.tabs.onRemoved.addListener((tabId) => tabMatched.delete(tabId));

// helpers
function hostFromUrl(url) {
  try {
    return new URL(url).hostname.replace(/^www\./, "");
  } catch {
    return null;
  }
}

async function isAllowlisted(host) {
  if (!host) return false;
  const { allowlist = [] } = await chrome.storage.local.get("allowlist");
  return allowlist.some((d) => host === d || host.endsWith("." + d));
}

function savedStats(bytes, count) {
  return {
    bytes,
    mb: bytes / (1024 * 1024),
    seconds: bytes / BANDWIDTH + (count * LATENCY_MS) / 1000,
  };
}

// messages from popup / options / content
chrome.runtime.onMessage.addListener((msg, sender, sendResponse) => {
  // Приемаме съобщения само от собствените ни скриптове (defense-in-depth;
  // няма externally_connectable, така че уеб страници и без това не достигат тук).
  if (sender.id !== chrome.runtime.id) return;
  switch (msg.type) {
    case "toggle":
      // A manual toggle cancels any active timed pause.
      chrome.alarms.clear("resume");
      chrome.storage.local.set({ enabled: msg.enabled, pausedUntil: 0 }, async () => {
        await applyState();
        sendResponse({ ok: true });
      });
      return true;

    case "pause":
      pauseFor(msg.minutes || 30).then(() => sendResponse({ ok: true }));
      return true;

    case "resume":
      resumeNow().then(() => sendResponse({ ok: true }));
      return true;

    case "setSync":
      chrome.storage.local.set({ sync: !!msg.on }, async () => {
        if (msg.on) await pushToSync();
        sendResponse({ ok: true });
      });
      return true;

    case "getTabLog": {
      // "What was blocked on this page": our matched rules for the tab (local,
      // declarativeNetRequestFeedback). getMatchedRules is quota-limited by
      // Chrome, so a refusal is reported, not thrown.
      (async () => {
        try {
          const info = await chrome.declarativeNetRequest.getMatchedRules({ tabId: msg.tabId });
          const agg = new Map();
          for (const m of info.rulesMatchedInfo || []) {
            const rid = m.rule && m.rule.ruleId;
            if (rid === YT_BYPASS_RULE_ID || (rid >= ALLOW_RULE_BASE && rid < LIVE_RULE_BASE)) continue; // allow rules aren't blocks
            const h = hostFromUrl(m.request && m.request.url) || "?";
            const k = h + "|" + ((m.request && m.request.type) || "other");
            const cur = agg.get(k) || { host: h, type: (m.request && m.request.type) || "other", n: 0, t: 0 };
            cur.n++; cur.t = Math.max(cur.t, m.timeStamp || 0); agg.set(k, cur);
          }
          const items = [...agg.values()].sort((a, b) => b.t - a.t).slice(0, 40);
          sendResponse({ ok: true, total: (info.rulesMatchedInfo || []).length, items });
        } catch (e) {
          sendResponse({ ok: false, reason: /quota|MAX_GETMATCHEDRULES/i.test(String(e)) ? "quota" : "unavailable" });
        }
      })();
      return true;
    }

    case "setNoCosmetics":
      chrome.storage.local.get("noCosmetics", async (data) => {
        let list = Array.isArray(data.noCosmetics) ? data.noCosmetics : [];
        const host = typeof msg.host === "string" ? msg.host.toLowerCase() : "";
        if (!host || !/^[a-z0-9.-]+\.[a-z0-9-]{2,}$/.test(host)) return sendResponse({ ok: false });
        list = list.filter((d) => d !== host);
        if (msg.off && list.length < 5000) list.push(host);
        await chrome.storage.local.set({ noCosmetics: list });
        sendResponse({ ok: true, noCosmetics: list });
      });
      return true;

    case "addSubscription":
      withSubs(() => addSubscription(msg.url)).then((r) => sendResponse(r || { ok: false }));
      return true;
    case "removeSubscription":
      withSubs(() => removeSubscription(msg.url)).then((r) => sendResponse(r || { ok: false }));
      return true;
    case "refreshSubscriptions":
      refreshAllSubscriptions().then(async () => sendResponse({ ok: true, subscriptions: (await chrome.storage.local.get("subscriptions")).subscriptions || [] }));
      return true;
    case "getSubscriptions":
      chrome.storage.local.get("subscriptions", (d) => sendResponse({ subscriptions: d.subscriptions || [] }));
      return true;

    case "getHealth": {
      // Diagnostics for the options page: is the engine registered, which
      // rulesets are on, how many dynamic rules per range, live-config state.
      (async () => {
        const out = { engineRegistered: false, enabledRulesets: [], dynamic: { user: 0, allow: 0, live: 0, ytBypass: false }, liveVersion: 0, liveUpdated: 0, liveError: "", scriptletsError: "", ed25519: false, keys: SIG_PUBKEYS_B64.length, popupHosts: 0 };
        try { out.engineRegistered = (await chrome.scripting.getRegisteredContentScripts({ ids: [SCRIPTLET_SCRIPT_ID] })).length > 0; } catch {}
        try { out.enabledRulesets = await chrome.declarativeNetRequest.getEnabledRulesets(); } catch {}
        try {
          for (const r of await chrome.declarativeNetRequest.getDynamicRules()) {
            if (r.id === YT_BYPASS_RULE_ID) out.dynamic.ytBypass = true;
            else if (r.id >= LIVE_RULE_BASE) out.dynamic.live += (r.condition.requestDomains || []).length || 1;
            else if (r.id >= ALLOW_RULE_BASE) out.dynamic.allow++;
            else if (r.id >= USER_BLOCK_BASE) out.dynamic.user += (r.condition.requestDomains || []).length || 1;
          }
        } catch {}
        try {
          const d = await chrome.storage.local.get(["liveConfig", "liveUpdated", "liveError", "scriptletsError"]);
          out.liveVersion = (d.liveConfig && d.liveConfig.version) || 0;
          out.liveUpdated = d.liveUpdated || 0;
          out.liveError = d.liveError || "";
          out.scriptletsError = d.scriptletsError || "";
        } catch {}
        try { out.ed25519 = await canVerifyEd25519(); } catch {}
        try { out.popupHosts = (await getRuleCounts()).popupHosts || 0; } catch {}
        sendResponse(out);
      })();
      return true;
    }

    case "getStats":
      chrome.storage.local.get(
        ["enabled", "blockedTotal", "savedBytes", "smartBlocked", "allowlist", "features", "theme", "sync", "pausedUntil", "autoUpdate", "liveConfig", "liveUpdated", "noCosmetics"],
        async (data) => {
          let host = null;
          let allowed = false;
          let noCosmetics = false;
          if (msg.tabUrl) {
            host = hostFromUrl(msg.tabUrl);
            allowed = await isAllowlisted(host);
            noCosmetics = !!host && (data.noCosmetics || []).some((d) => host === d || host.endsWith("." + d));
          }
          const blockedTotal = data.blockedTotal || 0;
          const live = data.liveConfig || null;
          const rc = await getRuleCounts();
          const bundled =
            (rc.ad_rules || 0) + (rc.youtube_rules || 0) + (rc.easylist || 0) +
            (rc.easyprivacy || 0) + (rc.removeparam || 0) + (rc.urlhaus || 0) +
            (rc.cosmeticGeneric || 0) + (rc.cosmeticSpecific || 0) + (rc.privacy || 0);
          sendResponse({
            enabled: data.enabled !== false,
            blockedTotal,
            saved: savedStats(data.savedBytes || 0, blockedTotal),
            allowlist: data.allowlist || [],
            features: data.features || DEFAULTS.features,
            theme: data.theme || "carbon",
            filterCount: bundled + (live?.blockDomains?.length || 0),
            smartBlocked: data.smartBlocked || 0,
            sync: !!data.sync,
            pausedUntil: data.pausedUntil || 0,
            autoUpdate: data.autoUpdate !== false,
            liveVersion: live?.version || 0,
            liveUpdated: data.liveUpdated || 0,
            host,
            allowed,
            noCosmetics,
          });
        }
      );
      return true;

    case "updateFilters":
      fetchLiveConfig(true).then((r) => sendResponse(r));
      return true;

    case "ytBypass": {
      // YouTube hard-blocked us; a content script can't touch DNR, so it asks
      // the service worker to add the YouTube allow-all rule for the bypass
      // window BEFORE it reloads. Only then is the reload a clean client.
      // Defence in depth: only a content script running in a YouTube-origin
      // FRAME may request the bypass (sender.url is browser-set, unspoofable).
      // Frame URL, not tab URL: youtube_skip runs all_frames and the bypass
      // rule covers sub_frame, so a YouTube embed on another site must pass.
      const ytHost = hostFromUrl(sender.url || "");
      const isYt = !!ytHost && /(^|\.)youtube(-nocookie)?\.com$/.test(ytHost);
      if (!isYt) { sendResponse({ ok: false, reason: "not youtube" }); return false; }
      chrome.storage.local.set({ ytBypassUntil: Date.now() + YT_BYPASS_MS }, async () => {
        await setYtBypassRule(true);
        chrome.alarms.create("yt-bypass-expire", { when: Date.now() + YT_BYPASS_MS });
        sendResponse({ ok: true });
      });
      return true;
    }

    case "setAutoUpdate":
      chrome.storage.local.set({ autoUpdate: !!msg.on }, () => sendResponse({ ok: true }));
      return true;

    case "setAllow":
      chrome.storage.local.get("allowlist", async (data) => {
        let list = data.allowlist || [];
        if (!msg.host) return sendResponse({ ok: false });
        if (msg.allow) {
          if (!list.includes(msg.host)) {
            if (list.length >= ALLOW_RULE_MAX) return sendResponse({ ok: false, reason: "allowlist full", allowlist: list });
            list.push(msg.host);
          }
        } else {
          list = list.filter((d) => d !== msg.host);
        }
        await chrome.storage.local.set({ allowlist: list });
        await syncAllowRules();
        await syncScriptlets(); // refresh excludeMatches for the new allowlist
        sendResponse({ ok: true, allowlist: list });
      });
      return true;

    case "setFeatures":
      chrome.storage.local.set({ features: msg.features }, async () => {
        await applyState(); // youtube ruleset follows the youtube toggle
        sendResponse({ ok: true });
      });
      return true;

    case "setTheme":
      chrome.storage.local.set({ theme: msg.theme }, () => sendResponse({ ok: true }));
      return true;

    case "resetStats":
      chrome.storage.local.set(
        { blockedTotal: 0, savedBytes: 0, smartBlocked: 0, smartLog: [] },
        () => sendResponse({ ok: true })
      );
      return true;

    case "saveCustomSelector":
      chrome.storage.local.get("customHidden", async (data) => {
        const map = data.customHidden || {};
        if (!msg.host || !msg.selector) return sendResponse({ ok: false });
        map[msg.host] = map[msg.host] || [];
        if (!map[msg.host].includes(msg.selector)) map[msg.host].push(msg.selector);
        await chrome.storage.local.set({ customHidden: map });
        sendResponse({ ok: true });
      });
      return true;

    case "importSettings": {
      // Импортираме само познати ключове, с ВАЛИДАЦИЯ на тип/shape (грешен тип
      // би счупил разширението) и САНИТИЗАЦИЯ на селекторите — иначе подлъган
      // потребител може да импортира файл с :remove()/ReDoS върху форм-полета.
      // liveConfig/liveUpdated са сървърно управлявани и не се приемат от импорт.
      const SKIP_IMPORT = new Set(["liveConfig", "liveUpdated"]);
      const d = (msg.data && typeof msg.data === "object") ? msg.data : {};
      const clean = {};
      for (const k of Object.keys(DEFAULTS)) {
        if (SKIP_IMPORT.has(k) || !(k in d)) continue;
        const v = d[k];
        if (k === "allowlist" || k === "noCosmetics") {
          if (Array.isArray(v)) clean[k] = v.filter((x) => typeof x === "string" && /^[a-z0-9.-]+\.[a-z0-9-]{2,}$/i.test(x)).slice(0, 5000);
        } else if (k === "subscriptions") {
          if (Array.isArray(v)) clean[k] = v.filter((s) => s && isSubUrl(s.url)).map((s) => ({ url: s.url, added: Number(s.added) || Date.now(), fetched: 0, count: 0, error: "" })).slice(0, SUB_MAX);
        } else if (k === "userFilters") {
          if (typeof v === "string") clean[k] = v.slice(0, 100000);
        } else if (k === "features") {
          if (v && typeof v === "object" && !Array.isArray(v)) clean[k] = v;
        } else if (k === "customHidden") {
          // { host: [selector,...] } — санитизираме селекторите като live канала
          if (v && typeof v === "object" && !Array.isArray(v)) {
            const m = {};
            for (const host of Object.keys(v)) {
              if (typeof host !== "string" || !Array.isArray(v[host])) continue;
              const sels = v[host].filter((x) => typeof x === "string" && safeSelector(x)).slice(0, 500);
              if (sels.length) m[host] = sels;
            }
            clean[k] = m;
          }
        } else if (typeof v === typeof DEFAULTS[k]) {
          clean[k] = v; // прости скаларни ключове само при съвпадащ тип
        }
      }
      chrome.storage.local.set(clean, async () => {
        await applyState();
        await syncAllowRules();
        await syncUserRules();
        sendResponse({ ok: true });
      });
      return true;
    }

    case "smartHit": {
      const items = Array.isArray(msg.items) ? msg.items : [];
      if (items.length) recordSmart(msg.host || "", items);
      return false;
    }

    case "getCosmetic":
      cosmeticFor(msg.host || "").then((r) => sendResponse(r));
      return true;

    case "setUserFilters":
      chrome.storage.local.set({ userFilters: msg.text || "" }, async () => {
        await syncUserRules();
        sendResponse({ ok: true });
      });
      return true;

    case "startPicker":
      chrome.tabs.query({ active: true, currentWindow: true }, (tabs) => {
        if (tabs[0]) chrome.tabs.sendMessage(tabs[0].id, { type: "activatePicker" });
        sendResponse({ ok: true });
      });
      return true;
  }
});
