// generic_css.mjs — единственият генератор на cosmetic_generic.css (ползва го
// build_filters.mjs; тестовете го викат директно, без да пускат целия билд).
//
// Генеричен CSS, гейтнат зад html[data-tbab-on] (content.js слага атрибута само при
// включена защита). Форма = ПРОИЗВОДИТЕЛНОСТ: по-рано беше `html[data-tbab-on] :is(<500
// селектора>)` — Blink не може да индексира такова правило по id/клас, значи ВСЕКИ
// елемент при ВСЕКИ style recalc се сверяваше с ~13 600 селектора (измерено: 5–12× по-скъп
// recalc, ~9× по-бавен първи стил на голяма страница; на Speedtest това изяждаше главната
// нишка и сваляше измерената скорост). Сега е вложено правило (CSS nesting, Chrome 120+;
// manifest-ът иска 121): всеки селектор се индексира по най-десния си id/клас/таг.
// Вложеното правило пада ЦЯЛО при един невалиден селектор (за разлика от :is() не прощава), затова
// в общите списъци влизат само селектори, чиято граматика доказваме тук; всичко друго
// (псевдо-класове, escape-и, не-ASCII) е отделно правило — невалидното пада само.
const CSS_IDENT = "-?[_a-zA-Z][\\w-]*";
const CSS_ATTR = `\\[${CSS_IDENT}(?:[\\^$*|~]?=(?:"[^"\\\\\\n]*"|'[^'\\\\\\n]*'|${CSS_IDENT}))?(?:\\s+i)?\\]`;
// Непразен compound: иначе `div.promo >`, `a > > b`, `.x ~` минаваха за „доказани" и
// един такъв изпускаше цял чънк от 500 (Кодаджията, 5.0.5).
const CSS_SIMPLE = `(?:#${CSS_IDENT}|\\.${CSS_IDENT}|${CSS_ATTR})`;
const CSS_COMPOUND = `(?:(?:${CSS_IDENT}|\\*)${CSS_SIMPLE}*|${CSS_SIMPLE}+)`;
export const SAFE_CSS_SELECTOR = new RegExp(`^${CSS_COMPOUND}(?:\\s*[>+~]\\s*${CSS_COMPOUND}|\\s+${CSS_COMPOUND})*$`);
export function genericCss(selectors, chunk = 500, label = "EasyList generic cosmetic rules") {
  const HIDE = "{display:none!important}\n";
  const plain = [], odd = [];
  for (const s of selectors) {
    // Скоба извън низ в кавички би затворила правилото — такъв „селектор" не влиза.
    // Нито коментар, нито завършваща \ (тя екранира следващата скоба).
    if (!s || /[{}]/.test(s.replace(/"[^"]*"|'[^']*'/g, "")) || /\/\*|\\\s*$/.test(s)) continue;
    (SAFE_CSS_SELECTOR.test(s) ? plain : odd).push(s);
  }
  let css = `/* Generated by tools/build_filters.mjs - ${label} */\nhtml[data-tbab-on]{\n`;
  for (let i = 0; i < plain.length; i += chunk) css += plain.slice(i, i + chunk).join(",\n") + HIDE;
  for (const s of odd) css += s + HIDE;
  return css + "}\n";
}
