// Статичен HTML фрагмент, изваден буквално от boy/template.html (canvas#view +
// #hud + #loader). Никакво потребителско съдържание не влиза тук — низът е
// собствен, доверен build-time артефакт, затова dangerouslySetInnerHTML в
// BoyDuelStage.tsx е безопасен (не е untrusted/потребителски вход).
export const BOY_MARKUP = `
<canvas id="view" role="img" aria-label="Animated 3D scene: two armoured knights duel in a rain-soaked castle courtyard at night."></canvas>

<div id="hud">
  <header class="title">
    <p class="eyebrow" data-i18n="eyebrow">Ravenhold · Anno 1417</p>
    <h1 data-i18n="title">Duel at Ravenhold</h1>
    <p class="chapter" id="chapter">I · The Challenge</p>
  </header>
  <div class="slate" aria-hidden="true">
    <span class="rec" id="slate-shot">Shot 01/13</span>
    <span id="slate-lens">35 mm · f/2.8</span>
    <span id="slate-speed">1.00× · 60 fps</span>
  </div>
  <div class="caption" id="caption" aria-live="polite">
    <span class="term" id="cap-term"></span>
    <span class="rule"></span>
    <span class="gloss" id="cap-gloss"></span>
  </div>
  <div class="endcard" id="endcard">
    <div>
      <p class="eyebrow" data-i18n="eyebrow">Ravenhold · Anno 1417</p>
      <h2 data-i18n="title">Duel at Ravenhold</h2>
      <p class="fighters" data-i18n="fighters">Ser Aldric of the Azure Cross · The Black Warden</p>
      <p class="endline" data-i18n="endLine">Every plate, flame and texture is generated by code. Body motion: CMU Graphics Lab Motion Capture Database (mocap.cs.cmu.edu, NSF EIA-0196217).</p>
    </div>
  </div>
  <p class="hint" id="hint" hidden data-i18n="hintFree">Drag to orbit · scroll or pinch to zoom</p>
  <div class="stats" id="stats" hidden aria-live="off">
    <span id="st-fps">60 fps</span>
    <span id="st-res">—</span>
    <span id="st-draw">—</span>
    <span id="st-tier">—</span>
  </div>
  <nav class="controls" aria-label="Playback">
    <button class="btn play" id="play" type="button" aria-label="Pause" data-state="playing">
      <svg class="i-pause" viewBox="0 0 14 14" aria-hidden="true"><rect x="2" y="1" width="3.5" height="12"/><rect x="8.5" y="1" width="3.5" height="12"/></svg>
      <svg class="i-play" viewBox="0 0 14 14" aria-hidden="true"><path d="M3 1 L13 7 L3 13 Z"/></svg>
    </button>
    <span class="timecode" id="tc">00:00.00</span>
    <div class="scrub">
      <div class="ticks" id="ticks" aria-hidden="true"></div>
      <label class="sr-only" for="scrub" data-i18n="timeline">Timeline</label>
      <input id="scrub" type="range" min="0" max="1000" step="1" value="0">
    </div>
    <div class="group" role="group" aria-labelledby="speed-l">
      <span class="label" id="speed-l" data-i18n="speed">Speed</span>
      <button class="btn" type="button" data-speed="1" aria-pressed="true">1×</button>
      <button class="btn" type="button" data-speed="0.5" aria-pressed="false">½×</button>
      <button class="btn" type="button" data-speed="0.25" aria-pressed="false">¼×</button>
    </div>
    <button class="btn" id="cam" type="button" aria-pressed="false"><span class="label" data-i18n="camera">Camera</span><span id="cam-state">Director</span></button>
    <button class="btn" id="sound" type="button" aria-pressed="false"><span class="label" data-i18n="sound">Sound</span><span id="sound-state">Off</span></button>
    <button class="btn" id="stats-btn" type="button" aria-pressed="false"><span data-i18n="stats">Stats</span></button>
    <label class="group" for="quality"><span class="label" data-i18n="quality">Quality</span>
      <select id="quality">
        <option value="auto" data-i18n="auto">Auto</option>
        <option value="low" data-i18n="low">Low</option>
        <option value="high" data-i18n="high">High</option>
        <option value="ultra" data-i18n="ultra">Ultra</option>
      </select>
    </label>
    <div class="group" role="group" aria-labelledby="lang-l">
      <span class="label sr-only" id="lang-l" data-i18n="language">Language</span>
      <button class="btn" type="button" data-lang="en">EN</button>
      <button class="btn" type="button" data-lang="bg">BG</button>
      <button class="btn" type="button" data-lang="it">IT</button>
    </div>
    <p class="credit">Created and Designed by <a href="https://carbonstealth.eu" target="_blank" rel="noopener">Carbon Stealth VCC</a></p>
  </nav>
</div>

<div id="loader" role="status" aria-live="polite">
  <div class="loader-inner">
    <p class="eyebrow" data-i18n="eyebrow">Ravenhold · Anno 1417</p>
    <p class="loader-title" data-i18n="title">Duel at Ravenhold</p>
    <p class="tagline" data-i18n="tagline">A real-time medieval duel rendered in your browser: forged plate, fire, rain and steel.</p>
    <div class="loader-bar"><i id="load-fill"></i></div>
    <p class="load-step" id="load-step">Forging the steel</p>
  </div>
</div>
`;
