#!/usr/bin/env python3
"""Advance widths of DejaVu Sans (regular and bold) for the characters the drawings use, as a TypeScript table
(src/drawing/metrics-data.ts): the drawing kernel lays texts out with the same metrics the PDF renderer draws with.
Dev tool, run once when the character set changes:  PYTHONPATH=<fontTools> python3 scripts/font-metrics.py
"""
import os
import sys

from fontTools.ttLib import TTFont

FONT_DIR = os.environ.get("REPORT_FONT_DIR", "/usr/share/fonts/truetype/dejavu")
EXTRA = "–—‘’“”„…•·×÷±≤≥≈≠°²³¹µΩØøφΦαβγδηθλμπρστωΔΣ▲●■◆→←↑↓€‰′″⌀√∞"
CHARS = list(dict.fromkeys([chr(c) for c in range(32, 127)] + [chr(c) for c in range(160, 256)] + list(EXTRA)))


def widths(path):
    font = TTFont(path)
    upm = font["head"].unitsPerEm
    cmap = font.getBestCmap()
    hmtx = font["hmtx"]
    out = []
    for ch in CHARS:
        glyph = cmap.get(ord(ch))
        if glyph is None:
            continue
        out.append((ord(ch), round(hmtx[glyph][0] * 1000 / upm)))
    return out


def main():
    lines = [
        "// Generated by scripts/font-metrics.py from DejaVu Sans: advance widths in thousandths of the em, by code point.",
        "// Do not edit by hand.",
    ]
    for name, file in (("REGULAR", "DejaVuSans.ttf"), ("BOLD", "DejaVuSans-Bold.ttf")):
        pairs = widths(os.path.join(FONT_DIR, file))
        body = ",".join("%d:%d" % p for p in pairs)
        lines.append("export const %s: Readonly<Record<number, number>> = {%s};" % (name, body))
    target = os.path.join(os.path.dirname(__file__), "..", "src", "drawing", "metrics-data.ts")
    with open(target, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote", os.path.normpath(target), file=sys.stderr)


if __name__ == "__main__":
    main()
