# Builds the site's icons from the painted PNG library of the LiftPilot Premium pack (brand/premium/icons/*.png,
# 224x224 RGBA, listed in icon-manifest.json): each icon as WebP at 48 and 96 px in public/icons/<name>-<size>.webp,
# and the typed list of names src/components/icon-names.ts that the Icon component accepts.
# The icons are fixed-colour (cyan on dark): they are made for the dark surfaces of the site.
# Run from liftpilot/ after the library changes: python3 -I scripts/icons-build.py   (needs Pillow with WebP)
import json
import os
import re

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "brand", "premium", "icons")
OUT = os.path.join(ROOT, "public", "icons")
NAMES = os.path.join(ROOT, "src", "components", "icon-names.ts")
SIZES = (48, 96)
# the painted glyphs and their glow stay within 8..216 of the 224 canvas: the margin outside it is cut, the same for
# every icon, so that they keep one optical size and the glyph fills more of the box at small sizes
CROP = (8, 8, 216, 216)
NAME = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")

manifest = json.load(open(os.path.join(SRC, "icon-manifest.json"), encoding="utf-8"))
names = sorted({i["name"] for i in manifest["icons"]})
assert len(names) == manifest["count"], f"the manifest lists {len(names)} names, says {manifest['count']}"

os.makedirs(OUT, exist_ok=True)
for old in os.listdir(OUT):  # an icon gone from the library goes from the site too
    if old.endswith(".webp"):
        os.remove(os.path.join(OUT, old))
for name in names:
    if not NAME.match(name):
        raise SystemExit(f"icon name not in kebab-case: {name}")
    im = Image.open(os.path.join(SRC, f"{name}.png")).convert("RGBA")
    if im.size != (224, 224):
        raise SystemExit(f"{name}.png is {im.size}, the library is 224x224")
    im = im.crop(CROP)
    for s in SIZES:
        # exact=True keeps the colour under fully transparent pixels from being rewritten (no dark fringe on the glow)
        im.resize((s, s), Image.LANCZOS).save(os.path.join(OUT, f"{name}-{s}.webp"), "WEBP", quality=82, alpha_quality=85, method=6, exact=True)

lines = [
    "// Generated by scripts/icons-build.py from brand/premium/icons/icon-manifest.json: do not edit by hand.",
    "// The painted icons of the LiftPilot Premium pack, served as public/icons/<name>-48.webp and -96.webp.",
    "export const ICON_NAMES = [",
]
row = "  "
for n in names:
    item = f"'{n}', "
    if len(row) + len(item) > 120:
        lines.append(row.rstrip())
        row = "  "
    row += item
lines.append(row.rstrip())
lines += ["] as const;", "", "export type IconName = (typeof ICON_NAMES)[number];", ""]
open(NAMES, "w", encoding="utf-8").write("\n".join(lines))
print(f"{len(names)} icons x {len(SIZES)} sizes written to public/icons/, names to src/components/icon-names.ts")
