// The drawings of the landing page, as the software makes them: the plan at the main floor and section A-A of the
// sample shaft of 1600 × 1750 mm (src/lib/tavole/views.ts), written to public/img/lp-plan.svg and lp-section.svg with
// the same SVG renderer as the screens, and their sizes and scales to src/components/landing/drawings.ts. Run after a
// change of the drawings: npx tsx scripts/landing-drawings.ts
import { writeFileSync } from 'node:fs';
import * as React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import ShapesSvg from '../src/components/drawing/ShapesSvg';
import { defaultInputs, layout } from '../src/shaft';
import { previews } from '../src/lib/tavole/views';

// tsx compiles the component's JSX for the classic runtime here (the app's tsconfig preserves JSX for Next)
Object.assign(globalThis, { React });
const { plan, section } = previews(layout(defaultInputs(1600, 1750)));
const sizes: string[] = [];
const out = (name: string, v: NonNullable<typeof section>, label: string): void => {
  const w = Math.round(v.w * 4), h = Math.round(v.h * 4);
  sizes.push(`  '${name}': { w: ${w}, h: ${h}, scale: ${v.scale} },`);
  const svg = renderToStaticMarkup(React.createElement(ShapesSvg, { shapes: v.shapes, w: v.w, h: v.h, id: name, label }))
    // a file of its own: the namespace, and the paper size for the browser to keep its proportions
    .replace('<svg ', `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" `);
  writeFileSync(new URL(`../public/img/${name}.svg`, import.meta.url), `${svg}\n`);
  console.log(name, `1:${v.scale}`, `${Math.round(svg.length / 1024)} KB`);
};
out('lp-plan', plan, 'Pianta del vano generata da LiftPilot');
if (section) out('lp-section', section, 'Sezione A-A generata da LiftPilot');
writeFileSync(new URL('../src/components/landing/drawings.ts', import.meta.url), [
  '// Generated by scripts/landing-drawings.ts: the size [px] and the scale of each drawing of the landing page.',
  'export const LANDING_DRAWINGS = {', ...sizes, '} as const;', '',
].join('\n'));
