export const QUEST_SEED = [
  // Whispering Woods
  {
    slug: 'whispering_woods_rats',
    title: 'Cellar Vermin',
    region: 'whispering_woods',
    level_req: 1,
    energy_cost: 4,
    duration_sec: 0,
    intro: 'The innkeeper of Oaken Hollow leans across the bar. "Rats. Big ones, in the cellar. Would you?"',
    narrative: 'You descend the wooden stairs by candlelight. The air is heavy with the scent of old ale and something else — fur. A pair of red eyes glint from behind a barrel...',
    monster_slug: 'forest_rat',
    xp_reward: 12,
    gold_reward: 6,
    item_reward: '',
    success_text: 'The rat squeaks and goes still. The innkeeper claps you on the back and presses coins into your hand.',
    failure_text: 'You stumble out of the cellar bloodied. The innkeeper sighs and waves you off.',
  },
  {
    slug: 'whispering_woods_boar',
    title: 'The Stubborn Boar',
    region: 'whispering_woods',
    level_req: 2,
    energy_cost: 5,
    duration_sec: 0,
    intro: 'A farmer\'s field has been wrecked by a wild boar. He offers a bag of coins to whoever brings him peace.',
    narrative: 'You track the boar\'s muddy footprints to a thicket. A low grunting. A flash of tusk through the brambles. It charges...',
    monster_slug: 'wild_boar',
    xp_reward: 20,
    gold_reward: 12,
    item_reward: '',
    success_text: 'The boar collapses with a final, defiant snort. The farmer thanks you with coin and a flask of cider.',
    failure_text: 'Bruised and limping, you flee back to town. The farmer is not impressed.',
  },
  {
    slug: 'whispering_woods_goblin',
    title: 'Scout in the Shadows',
    region: 'whispering_woods',
    level_req: 3,
    energy_cost: 6,
    duration_sec: 0,
    intro: 'Travelers report a goblin watching the road from the trees. The kingdom wants him gone.',
    narrative: 'You crouch low along the moss. A snicker — sharp ears twitch. The scout draws a wicked, jagged knife...',
    monster_slug: 'goblin_scout',
    xp_reward: 30,
    gold_reward: 18,
    item_reward: 'silver_ring',
    success_text: 'The goblin\'s lifeless hand drops a battered silver ring. You take it.',
    failure_text: 'The scout flees into the trees laughing. You collect yourself, ashamed.',
  },
  {
    slug: 'whispering_woods_wolf',
    title: 'Wolves at the Door',
    region: 'whispering_woods',
    level_req: 4,
    energy_cost: 7,
    duration_sec: 0,
    intro: 'A homestead has been losing sheep nightly. The husband points into the trees: "Wolves. Big ones."',
    narrative: 'Twigs crack beneath padded feet. Yellow eyes drift in the dark. With a snarl, the alpha lunges...',
    monster_slug: 'forest_wolf',
    xp_reward: 45,
    gold_reward: 25,
    item_reward: '',
    success_text: 'The wolf yields with a whimper. The family will sleep peacefully tonight.',
    failure_text: 'You crawl back to the homestead clutching your wounds. The wife mutters prayers over you.',
  },
  {
    slug: 'whispering_woods_bandit',
    title: 'The Hooded One',
    region: 'whispering_woods',
    level_req: 5,
    energy_cost: 8,
    duration_sec: 0,
    intro: 'A bounty notice in Oaken Hollow: 12 gold and a fine helm for the bandit who has been robbing pilgrims.',
    narrative: 'You wait by the road, pretending to nap. Footsteps approach. A blade flashes in the moonlight as the hooded figure pounces...',
    monster_slug: 'bandit',
    xp_reward: 60,
    gold_reward: 35,
    item_reward: 'chain_helm',
    success_text: 'You strip the bandit of his loot. The reward and a fine chainmail coif are yours.',
    failure_text: 'The bandit escapes with your purse. You curse and head back to town with empty pockets.',
  },

  // Mistmoor Hills
  {
    slug: 'mistmoor_troll',
    title: 'Troll Under the Bridge',
    region: 'mistmoor_hills',
    level_req: 6,
    energy_cost: 10,
    duration_sec: 0,
    intro: 'The merchant guild promises gold to anyone who clears the troll from the King\'s Bridge.',
    narrative: 'The bridge looms ahead. A thick stink. From beneath the stones, a great hand grips the rail and a troll heaves itself into view...',
    monster_slug: 'hill_troll',
    xp_reward: 100,
    gold_reward: 50,
    item_reward: 'steel_longsword',
    success_text: 'The troll topples into the river with a thunderous splash. The guild pays handsomely.',
    failure_text: 'You flee with bruised ribs. The troll roars from beneath the bridge.',
  },
  {
    slug: 'mistmoor_orc_raid',
    title: 'Stop the Raiders',
    region: 'mistmoor_hills',
    level_req: 7,
    energy_cost: 10,
    duration_sec: 0,
    intro: 'Orc raiders have been burning farms. A captain points to a smoking field. "Bring me his head."',
    narrative: 'You crest the hill. Smoke. An orc with a notched axe turns slowly, baring yellow tusks...',
    monster_slug: 'orc_raider',
    xp_reward: 130,
    gold_reward: 65,
    item_reward: 'kite_shield',
    success_text: 'The orc topples. The farmer collapses to his knees in gratitude.',
    failure_text: 'The raider drives you off. The fires burn brighter.',
  },
  {
    slug: 'mistmoor_witch',
    title: 'The Witch of Mistmoor',
    region: 'mistmoor_hills',
    level_req: 9,
    energy_cost: 12,
    duration_sec: 0,
    intro: 'The village priest grips a charm. "Find the witch. End her. The mists thicken when she works.”',
    narrative: 'You step into a clearing of standing stones. The air shimmers green. A figure rises from a cauldron, eyes alight...',
    monster_slug: 'mistmoor_witch',
    xp_reward: 180,
    gold_reward: 90,
    item_reward: 'amulet_of_warding',
    success_text: 'The witch dissolves into mist. From her cauldron, an amulet shines.',
    failure_text: 'Her hex sends you reeling. You crawl from the clearing, mist-blind.',
  },

  // Crystal Caverns
  {
    slug: 'crystal_spider',
    title: 'The Web in the Dark',
    region: 'crystal_caverns',
    level_req: 10,
    energy_cost: 12,
    duration_sec: 0,
    intro: 'Miners have stopped returning. The guildmaster suspects a beast in the deep tunnels.',
    narrative: 'Your torch flickers. Silk threads cling to the walls. Eight eyes gleam from the ceiling above...',
    monster_slug: 'cave_spider',
    xp_reward: 220,
    gold_reward: 110,
    item_reward: 'chain_armor',
    success_text: 'The spider falls in a curl of legs. The miners cheer.',
    failure_text: 'You barely escape the webbing. Your torch sputters out as you flee.',
  },
  {
    slug: 'crystal_golem',
    title: 'Heart of Stone',
    region: 'crystal_caverns',
    level_req: 12,
    energy_cost: 14,
    duration_sec: 0,
    intro: 'A golem has awakened from ancient dwarven runes. It guards a vein of pure crystal.',
    narrative: 'The chamber thunders with each step. Crystals scatter light across the walls. The golem raises a fist of granite...',
    monster_slug: 'rock_golem',
    xp_reward: 320,
    gold_reward: 160,
    item_reward: 'plate_armor',
    success_text: 'The golem cracks and crumbles. You pry a glittering shard from its chest.',
    failure_text: 'The golem hammers you back through the corridor. You leave the crystal vein to it.',
  },
  {
    slug: 'crystal_overlord',
    title: 'The Overlord\'s Lair',
    region: 'crystal_caverns',
    level_req: 14,
    energy_cost: 16,
    duration_sec: 0,
    intro: 'Word reaches the king of an overlord crowning himself in the depths. The realm cannot allow it.',
    narrative: 'You stride into a hall of mirrored crystal. The Overlord laughs from a glittering throne, then springs at you...',
    monster_slug: 'caverns_overlord',
    xp_reward: 500,
    gold_reward: 300,
    item_reward: 'flameblade',
    success_text: 'The Overlord falls from his throne with a final, hateful breath. His blade — Flameblade — is yours.',
    failure_text: 'You stagger from the hall, the Overlord\'s laughter echoing.',
  },

  // Ashen Wastes
  {
    slug: 'ashen_revenant',
    title: 'Whispers in Ash',
    region: 'ashen_wastes',
    level_req: 16,
    energy_cost: 18,
    duration_sec: 0,
    intro: 'A scholar pays well for proof that revenants stalk the wastes. Bring back proof — or its head.',
    narrative: 'The dust kicks up around you. A grey, hollow figure rises from a heap of ash, eyes burning blue...',
    monster_slug: 'ash_revenant',
    xp_reward: 700,
    gold_reward: 350,
    item_reward: 'mage_robe',
    success_text: 'The revenant collapses to a heap of grey dust. You retrieve a scrap of glowing rune-script.',
    failure_text: 'Its cold hand sears your soul. You stagger back, hollowed.',
  },
  {
    slug: 'ashen_drake',
    title: 'Wings of Flame',
    region: 'ashen_wastes',
    level_req: 19,
    energy_cost: 20,
    duration_sec: 0,
    intro: 'A drake has been seen near the Ember Spires. Its scales would mend a king\'s armor.',
    narrative: 'The sky darkens. Wings beat once, twice. The drake lands with a bellow of flame...',
    monster_slug: 'fire_drake',
    xp_reward: 1000,
    gold_reward: 550,
    item_reward: 'ring_of_power',
    success_text: 'The drake plummets, its tail thrashing. From its hoard, a ring of power glows.',
    failure_text: 'You retreat through a wall of flame. The drake\'s laughter follows.',
  },

  // Endgame
  {
    slug: 'shadowfell_shadowlord',
    title: 'The Shadow Lord',
    region: 'shadowfell',
    level_req: 24,
    energy_cost: 30,
    duration_sec: 0,
    intro: 'The fate of Nexus itself rests on a single confrontation. The Shadow Lord stirs.',
    narrative: 'Darkness coils around you. From the void, a crown of black iron rises atop a being of pure shadow. He raises his hand and the world holds its breath...',
    monster_slug: 'shadow_lord',
    xp_reward: 3000,
    gold_reward: 1500,
    item_reward: 'dragonbane',
    success_text: 'The Shadow Lord shatters in a thousand shards of dusk. Light returns to Nexus Dominion, and the legendary Dragonbane is yours.',
    failure_text: 'You fall. The kingdom awaits another hero.',
  },

  // Story / Skill quests (no monster)
  {
    slug: 'help_old_hermit',
    title: 'Aid the Old Hermit',
    region: 'whispering_woods',
    level_req: 1,
    energy_cost: 3,
    duration_sec: 0,
    intro: 'An old hermit asks for herbs from a perilous patch of nettles.',
    narrative: 'You weave through brambles, plucking the herbs while avoiding their thorny barbs.',
    monster_slug: '',
    xp_reward: 15,
    gold_reward: 10,
    item_reward: '',
    success_text: 'The hermit smiles, gums showing. "Here, traveler. A few coins for your trouble."',
    failure_text: 'Your hands are too clumsy. You return scratched and herb-less.',
  },
  {
    slug: 'lost_journal',
    title: 'The Lost Journal',
    region: 'mistmoor_hills',
    level_req: 6,
    energy_cost: 5,
    duration_sec: 0,
    intro: 'A traveling scribe lost his journal on the trail. It must be returned.',
    narrative: 'You follow the trail for hours, sifting through leaves and brush. At last you spot a leather cover.',
    monster_slug: '',
    xp_reward: 60,
    gold_reward: 30,
    item_reward: '',
    success_text: 'The scribe weeps and presses a coin into your hand. "My life\'s work."',
    failure_text: 'You search until dusk but find nothing.',
  },

  // ====================================================================
  // EXPANSION QUESTS — two per new region. Rewards scaled against the
  // per-kill XP formula (`9 * lvl^0.7`) at ~3x so a successful quest is
  // worth a small handful of hunts. Kill quests target the region's
  // signature roster monster; non-kill quests are fetch/escort flavor.
  // ====================================================================

  // ===== Emberreach =====
  {
    slug: 'emberreach_drake_eggs',
    title: 'The Drake Egg Patrol',
    region: 'emberreach',
    level_req: 28,
    energy_cost: 6, duration_sec: 0,
    intro: 'A Wyrmkin elder beckons you over the lava-bridge. "The whelps have grown. We need them culled before the moot."',
    narrative: 'You pick your way across the basalt. The drake whelp is nesting in the geothermal hollow, scales already singed black.',
    monster_slug: 'emberreach_drake_whelp', xp_reward: 280, gold_reward: 340, item_reward: '',
    success_text: 'The elder nods once. "The clans will remember." A pouch of clan-marked coin changes hands.',
    failure_text: 'You stumble back through the steam. The elder will not name you again this season.',
  },
  {
    slug: 'emberreach_clan_envoy',
    title: 'Envoy to the Wyrmkin',
    region: 'emberreach', level_req: 32,
    energy_cost: 5, duration_sec: 0,
    intro: 'The Iron Watch needs a letter delivered into Wyrmkin lands. Nobody else will take it.',
    narrative: 'You walk in clear daylight, banner up, hands open. Three Wyrmkin scouts watch from a ridge. They do not stop you.',
    monster_slug: '', xp_reward: 320, gold_reward: 400, item_reward: '',
    success_text: 'The envoy reads the letter, grunts, and writes a reply in clan script. The road back is quiet.',
    failure_text: 'You misread a sigil at a roadside shrine and walk into a hunting party. They send you back without the letter.',
  },

  // ===== Hammerhand Pass =====
  {
    slug: 'hammerhand_mine_check',
    title: 'The Picker Survey',
    region: 'hammerhand_pass', level_req: 52,
    energy_cost: 7, duration_sec: 0,
    intro: '"Three pickers in two weeks, gone mad in the shaft. We need eyes."',
    narrative: 'The tunnels echo. You find one of the missing — bloodied, scrap-mad, swinging at you with a pick.',
    monster_slug: 'hammerhand_picker', xp_reward: 490, gold_reward: 720, item_reward: '',
    success_text: 'The foreman pays you in gold dust. "Tell nobody what was down there." You don\'t.',
    failure_text: 'You crawl out alive. That is the only reward today.',
  },
  {
    slug: 'hammerhand_ore_caravan',
    title: 'The Ore Caravan',
    region: 'hammerhand_pass', level_req: 60,
    energy_cost: 7, duration_sec: 0,
    intro: 'Iron-Watch quartermaster: "Iron ore is overdue. Drake or worse. Bring it through."',
    narrative: 'The pass narrows. Two pit drakes turn at the sound of the wagon wheels.',
    monster_slug: 'hammerhand_pit_drake', xp_reward: 560, gold_reward: 920, item_reward: '',
    success_text: 'The wagons roll into Aedric on time. The quartermaster initials the manifest in your favour.',
    failure_text: 'The lead wagon burns. You retreat with one ingot in your hand. It will not be enough.',
  },

  // ===== Conclave of Aedric =====
  {
    slug: 'conclave_runaway_apprentice',
    title: 'The Apprentice Question',
    region: 'conclave_aedric', level_req: 77,
    energy_cost: 7, duration_sec: 0,
    intro: 'A Conclave proctor extends a sealed scroll. "An initiate has gone rogue. Bring her in. Alive if possible."',
    narrative: 'You find the apprentice scratching wards into a courtyard floor. She turns when you call her name. She knew you would come.',
    monster_slug: 'conclave_initiate', xp_reward: 605, gold_reward: 1020, item_reward: '',
    success_text: 'The proctor accepts the unconscious initiate without comment. The Conclave\'s ledger marks you twice today.',
    failure_text: 'The ward bursts. You walk out of the courtyard. The apprentice does not.',
  },
  {
    slug: 'conclave_archive_breach',
    title: 'The Voidshard Theft',
    region: 'conclave_aedric', level_req: 90,
    energy_cost: 8, duration_sec: 0,
    intro: 'A Conclave senior knocks at midnight. "A voidshard reliquary is gone. The thief is still in the archive."',
    narrative: 'The archive is silent. The hierophant is reading by no candle. He looks up when you enter.',
    monster_slug: 'conclave_voidshard', xp_reward: 660, gold_reward: 1180, item_reward: '',
    success_text: 'The reliquary returns to its case. The senior gives you a quiet nod and a quieter purse.',
    failure_text: 'You back out of the archive with empty hands. The reliquary is not coming home today.',
  },

  // ===== Saltmarsh =====
  {
    slug: 'saltmarsh_tide_bell',
    title: 'The Tide Bell',
    region: 'saltmarsh', level_req: 107,
    energy_cost: 8, duration_sec: 0,
    intro: 'A drowned chapel has its bell ringing again. Nobody is alive to ring it.',
    narrative: 'You wade through brackish water to the chapel door. A priest in damp robes waits inside. He is not breathing.',
    monster_slug: 'saltmarsh_tidefall_priest', xp_reward: 725, gold_reward: 1320, item_reward: '',
    success_text: 'The bell stops. The water settles. The village pays in salt-marked silver and never asks again.',
    failure_text: 'You retreat to shore. The bell keeps ringing. Tomorrow somebody else will try.',
  },
  {
    slug: 'saltmarsh_crocodile_hunt',
    title: 'Salt Crocodile Cull',
    region: 'saltmarsh', level_req: 115,
    energy_cost: 8, duration_sec: 0,
    intro: 'Saltmarsh fishermen pool their last coin: "The big one. Kill it or we lose the season."',
    narrative: 'You wait at the river-bend in the dawn cold. The water is too still. Then it isn\'t.',
    monster_slug: 'saltmarsh_crocodile', xp_reward: 770, gold_reward: 1420, item_reward: '',
    success_text: 'The fishermen drag the carcass to shore and split your purse fairly. Mostly.',
    failure_text: 'You lose a boot to it. You keep both legs. It is something.',
  },

  // ===== Frostvale =====
  {
    slug: 'frostvale_wendigo_track',
    title: 'The Wendigo Tracks',
    region: 'frostvale', level_req: 142,
    energy_cost: 8, duration_sec: 0,
    intro: 'A trapper points at footprints in the snow. "Not a man\'s. Not a beast\'s. You take this one."',
    narrative: 'You follow the prints uphill into thinning trees. The wendigo is waiting for you, mouth open in something that isn\'t a smile.',
    monster_slug: 'frostvale_wendigo', xp_reward: 858, gold_reward: 1680, item_reward: '',
    success_text: 'The trapper builds a cairn over the body. He doesn\'t name it. You don\'t either.',
    failure_text: 'You stumble down the slope at dusk. The wendigo does not follow. It will be back.',
  },
  {
    slug: 'frostvale_clan_truce',
    title: 'The Clan Truce',
    region: 'frostvale', level_req: 155,
    energy_cost: 8, duration_sec: 0,
    intro: 'Two frost-giant clans want a sit-down. They need a neutral hand to carry the message.',
    narrative: 'You walk the ridge between the two camps. Both sides have arrows nocked. Neither shoots.',
    monster_slug: '', xp_reward: 920, gold_reward: 1840, item_reward: '',
    success_text: 'The talks happen. Whatever was said, two clans walk away with their dead unburned.',
    failure_text: 'You drop the message in deep snow. By the time you find it, the talks have ended badly.',
  },

  // ===== Black Spire =====
  {
    slug: 'blackspire_cultist_break',
    title: 'Break the Cult',
    region: 'black_spire', level_req: 177,
    energy_cost: 9, duration_sec: 0,
    intro: 'The Iron Watch has located a Fellblade cell. Officers want it cleared, no negotiations.',
    narrative: 'You take the cell room by room. The cultists do not surrender. The Iron Watch did not ask you to take them in.',
    monster_slug: 'blackspire_cultist', xp_reward: 983, gold_reward: 2040, item_reward: '',
    success_text: 'The Watch officer logs the kill count without comment. The bounty is paid the same day.',
    failure_text: 'You retreat down the spire stairs, robe torn. The cell is still there. Tomorrow is another tally.',
  },
  {
    slug: 'blackspire_pyromancer_warding',
    title: 'The Pyromancer Trap',
    region: 'black_spire', level_req: 190,
    energy_cost: 9, duration_sec: 0,
    intro: 'A Conclave scout: "A pyromancer adept is binding a ward to the spire face. Break the binding before he finishes."',
    narrative: 'You sprint up the scaffolding. The pyromancer turns, palm bright. You have one minute to interrupt the chant.',
    monster_slug: 'blackspire_pyromancer', xp_reward: 1040, gold_reward: 2180, item_reward: '',
    success_text: 'The binding fizzles. The scout nods, vanishes. The Conclave will know the favour was theirs to repay.',
    failure_text: 'The chant completes. The ward holds. You walk down with a scorched arm and a lesson.',
  },

  // ===== Stormpeaks =====
  {
    slug: 'stormpeaks_sky_pirate_raid',
    title: 'Sky-Pirate Reprisal',
    region: 'stormpeaks', level_req: 205,
    energy_cost: 9, duration_sec: 0,
    intro: 'A trade-caravan never reached the high-pass. Captain Vorrik\'s crew took the cargo.',
    narrative: 'You climb to the eyrie. The pirates have made a nest of the high stone. They see you coming and laugh.',
    monster_slug: 'stormpeaks_vorrik', xp_reward: 1100, gold_reward: 2340, item_reward: '',
    success_text: 'The caravan goods come home with you. The trader weeps once, pays, and goes back to his ledger.',
    failure_text: 'You retreat empty-handed. Vorrik adds your name to a list he keeps.',
  },
  {
    slug: 'stormpeaks_drake_roost',
    title: 'The Drake Roost',
    region: 'stormpeaks', level_req: 215,
    energy_cost: 9, duration_sec: 0,
    intro: 'Wyrmkin elders sent word: an unaligned lightning drake has claimed a Wyrmkin shrine. Clear it.',
    narrative: 'The shrine reeks of ozone. The drake is the size of a barn. You raise your sword and step into the chamber.',
    monster_slug: 'stormpeaks_lightning_drake', xp_reward: 1180, gold_reward: 2480, item_reward: '',
    success_text: 'The drake falls onto the shrine floor. The elders arrive at dawn to bless your work.',
    failure_text: 'You retreat singed. The shrine remains the drake\'s, for now.',
  },

  // ===== Voidshade Hollow =====
  {
    slug: 'voidshade_seal',
    title: 'Sealing the Hollow',
    region: 'voidshade_hollow', level_req: 234,
    energy_cost: 9, duration_sec: 0,
    intro: 'A Conclave senior cannot speak of this. The Hollow is widening. A void reaver is feeding it.',
    narrative: 'You step through the seam. Reality slips a half-inch beside you. The reaver does not so much attack as remember you.',
    monster_slug: 'voidshade_reaver', xp_reward: 1230, gold_reward: 2640, item_reward: '',
    success_text: 'The seal holds. The senior writes nothing down. You are paid in coin that was never struck.',
    failure_text: 'The seam widens by a finger\'s width. The senior tells you not to come back.',
  },
  {
    slug: 'voidshade_hierophant',
    title: 'The First Dark',
    region: 'voidshade_hollow', level_req: 250,
    energy_cost: 10, duration_sec: 0,
    intro: 'The Conclave seniors have called you over an open void-line. "End the Shade of the First Dark. Today."',
    narrative: 'You step into a vault older than the realm. The Shade rises without speaking. It does not need to.',
    monster_slug: 'voidshade_first_dark', xp_reward: 1300, gold_reward: 2780, item_reward: '',
    success_text: 'The Shade folds. The seniors do not thank you. They never will.',
    failure_text: 'You stumble back through the void-line. Your reflection does not stumble with you.',
  },

  // ===== Mooncradle =====
  {
    slug: 'mooncradle_pale_court',
    title: 'Audience with the Pale Court',
    region: 'mooncradle', level_req: 263,
    energy_cost: 10, duration_sec: 0,
    intro: 'The Pale Court has asked for you. Refusing was never an option.',
    narrative: 'You step onto the cradle. The Archon meets you on the silver path. There is no fight. There is only the offer.',
    monster_slug: 'mooncradle_archon', xp_reward: 1340, gold_reward: 2920, item_reward: '',
    success_text: 'You return with a tile of moonglass that should not exist. The Conclave will pay handsomely.',
    failure_text: 'You return with empty hands. The Court will call you again. Less politely.',
  },
  {
    slug: 'mooncradle_silver_wyrm',
    title: 'The Silver Wyrm',
    region: 'mooncradle', level_req: 275,
    energy_cost: 10, duration_sec: 0,
    intro: 'Wyrmkin elders send a runner: a Silver Wyrm has broken its oaths. Cut it down.',
    narrative: 'You meet the Silver Wyrm at moonset. It does not pretend not to know why you are there.',
    monster_slug: 'mooncradle_silver_wyrm', xp_reward: 1390, gold_reward: 3080, item_reward: '',
    success_text: 'The Wyrm folds at moonset. The runner takes the scale you offer and is gone before sunrise.',
    failure_text: 'You retreat. The Wyrm will write you into a different oath now.',
  },

  // ===== Worldspine =====
  {
    slug: 'worldspine_old_bones',
    title: 'The Marrow Lord',
    region: 'worldspine', level_req: 295,
    energy_cost: 10, duration_sec: 0,
    intro: 'A bone-priest sets a coin on the road. "The Marrow Lord wants company. End that interest."',
    narrative: 'You climb into the ribcage of a fallen titan. The Marrow Lord is reading by candle. He puts the book down.',
    monster_slug: 'worldspine_marrow_lord', xp_reward: 1430, gold_reward: 3220, item_reward: '',
    success_text: 'The candle goes out. The priest finds the coin on his doorstep at dawn.',
    failure_text: 'You retreat down the ribs. The book is still on the lectern. Closed, now.',
  },
  {
    slug: 'worldspine_old_wyrm',
    title: 'The Old Wyrm of the Spine',
    region: 'worldspine', level_req: 310,
    energy_cost: 10, duration_sec: 0,
    intro: 'The Wyrmkin clans summon you. "The Old Wyrm has woken. Honour the contract."',
    narrative: 'You walk along the spine ridge in the cold light. The Wyrm rises from the marrow valley. You step forward.',
    monster_slug: 'worldspine_old_wyrm', xp_reward: 1480, gold_reward: 3340, item_reward: '',
    success_text: 'The clans send a runner with a clan-marked axe. The contract is honoured both ways.',
    failure_text: 'You walk back along the ridge. The Wyrm watches you the whole way.',
  },

  // ===== The Eternal Throne =====
  {
    slug: 'throne_seven_kings',
    title: 'Herald of the Seven Kings',
    region: 'eternal_throne', level_req: 325,
    energy_cost: 12, duration_sec: 0,
    intro: 'Iron Watch high command, in person. "The Herald has crossed into our reach. We do not let it leave."',
    narrative: 'You walk into a chapel that no map remembers. The Herald stands at the altar. It opens its mouth and the world quiets.',
    monster_slug: 'throne_seven_kings', xp_reward: 1540, gold_reward: 3560, item_reward: '',
    success_text: 'The Herald falls. The Watch records the kill in a ledger the public will never see.',
    failure_text: 'You walk out of the chapel without your weapon. The Herald let you. Worse.',
  },
  {
    slug: 'throne_dawn_unmaker',
    title: 'Holding the Dawn',
    region: 'eternal_throne', level_req: 340,
    energy_cost: 12, duration_sec: 0,
    intro: 'A dawn priest stops you on the road. "The Dawn-Unmaker walks tomorrow. Reach the high stone before it does."',
    narrative: 'You climb through the dawn-line. The Unmaker reaches the high stone first. You arrive in time to interrupt the start of the ritual.',
    monster_slug: 'throne_dawn_unmaker', xp_reward: 1600, gold_reward: 3760, item_reward: '',
    success_text: 'The Unmaker withdraws. The priest writes a name in a ledger nobody reads. It is yours.',
    failure_text: 'The ritual completes. One star goes out tonight. You will not know its name.',
  },
];
