// GENERATED by mascot/cinematic/build.mjs from src/embed.js — do not edit directly.
// src/embed.js
import * as THREE12 from "three";

// src/post.js
import * as THREE5 from "three";
import { UnrealBloomPass } from "three/addons/postprocessing/UnrealBloomPass.js";
import { FullScreenQuad } from "three/addons/postprocessing/Pass.js";

// src/post-occlusion.js
import * as THREE2 from "three";

// src/post-common.js
import * as THREE from "three";
var VERT = "varying vec2 vUv; void main(){ vUv = uv; gl_Position = vec4(position.xy, 0.0, 1.0); }";
var DEPTH = (
  /* glsl */
  `
  #include <packing>
  uniform sampler2D tDepth;
  uniform float uNear;
  uniform float uFar;
  float viewZAt(vec2 uv) { return perspectiveDepthToViewZ(texture2D(tDepth, uv).x, uNear, uFar); }
`
);
var LUMA = "const vec3 LUMA = vec3(0.2126, 0.7152, 0.0722);";
var pass = (uniforms, fragmentShader, defines = {}) => new THREE.ShaderMaterial({ uniforms, defines, vertexShader: VERT, fragmentShader, depthWrite: false, depthTest: false });
var depthUniforms = () => ({ tDepth: { value: null }, uNear: { value: 0.1 }, uFar: { value: 300 } });

// src/post-occlusion.js
function aoMaterial() {
  return pass(
    { ...depthUniforms(), uProj: { value: new THREE2.Matrix4() }, uInvProj: { value: new THREE2.Matrix4() }, uTexel: { value: new THREE2.Vector2() }, uRadius: { value: 0.45 } },
    /* glsl */
    `
    uniform sampler2D tDepth;
    uniform mat4 uProj;
    uniform mat4 uInvProj;
    uniform vec2 uTexel;
    uniform float uRadius;
    varying vec2 vUv;
    vec3 viewPos(vec2 uv) {
      float d = texture2D(tDepth, uv).x;
      vec4 v = uInvProj * vec4(uv * 2.0 - 1.0, d * 2.0 - 1.0, 1.0);
      return v.xyz / v.w;
    }
    void main() {
      if (texture2D(tDepth, vUv).x >= 0.99999) { gl_FragColor = vec4(1.0); return; }
      vec3 p = viewPos(vUv);
      vec3 pr = viewPos(vUv + vec2(uTexel.x, 0.0)) - p;
      vec3 pl = p - viewPos(vUv - vec2(uTexel.x, 0.0));
      vec3 pu = viewPos(vUv + vec2(0.0, uTexel.y)) - p;
      vec3 pd = p - viewPos(vUv - vec2(0.0, uTexel.y));
      vec3 n = normalize(cross(abs(pr.z) < abs(pl.z) ? pr : pl, abs(pu.z) < abs(pd.z) ? pu : pd));
      if (dot(n, p) > 0.0) n = -n;
      float ign = fract(52.9829189 * fract(dot(gl_FragCoord.xy, vec2(0.06711056, 0.00583715))));
      vec3 t = normalize(cross(n, abs(n.y) < 0.99 ? vec3(0.0, 1.0, 0.0) : vec3(1.0, 0.0, 0.0)));
      vec3 b = cross(n, t);
      float occ = 0.0;
      for (int i = 0; i < 12; i++) {
        float fi = float(i);
        float r = (fi + 0.5) / 12.0;
        float a = ign * 6.2831853 + fi * 2.39996323;
        vec3 dir = (t * cos(a) + b * sin(a)) * sqrt(r) + n * sqrt(1.0 - r);
        vec3 s = p + dir * uRadius * mix(0.2, 1.0, r * r);
        vec4 clip = uProj * vec4(s, 1.0);
        float sz = viewPos(clip.xy / clip.w * 0.5 + 0.5).z;
        float range = smoothstep(0.0, 1.0, uRadius / max(abs(p.z - sz), 1e-3));
        occ += step(s.z + 0.03, sz) * range;
      }
      float ao = clamp(1.0 - occ / 12.0, 0.0, 1.0);
      gl_FragColor = vec4(ao, ao, ao, 1.0);
    }`
  );
}
function aoBlurMaterial() {
  return pass(
    { ...depthUniforms(), tAO: { value: null }, uTexel: { value: new THREE2.Vector2() } },
    /* glsl */
    `
    ${DEPTH}
    uniform sampler2D tAO;
    uniform vec2 uTexel;
    varying vec2 vUv;
    void main() {
      float cz = viewZAt(vUv);
      float sum = 0.0;
      float wsum = 0.0;
      for (int y = -2; y <= 1; y++) {
        for (int x = -2; x <= 1; x++) {
          vec2 o = (vec2(float(x), float(y)) + 0.5) * uTexel;
          float w = exp(-abs(viewZAt(vUv + o) - cz) / max(abs(cz) * 0.04, 0.02));
          sum += texture2D(tAO, vUv + o).r * w;
          wsum += w;
        }
      }
      float ao = sum / max(wsum, 1e-4);
      gl_FragColor = vec4(ao, ao, ao, 1.0);
    }`
  );
}

// src/post-dof.js
import * as THREE3 from "three";
function dofPrefilterMaterial() {
  return pass(
    { ...depthUniforms(), tColor: { value: null }, uTexel: { value: new THREE3.Vector2() }, uFocus: { value: 5 }, uCoc: { value: 5 }, uMaxBlur: { value: 8 } },
    /* glsl */
    `
    ${DEPTH}
    ${LUMA}
    uniform sampler2D tColor;
    uniform vec2 uTexel;
    uniform float uFocus;
    uniform float uCoc;
    uniform float uMaxBlur;
    varying vec2 vUv;
    float cocAt(float d) { return clamp(uCoc * (1.0 - uFocus / max(d, 1e-3)), -uMaxBlur, uMaxBlur); }
    void main() {
      vec2 o = uTexel * 0.5;
      vec2 uv0 = vUv + vec2(-o.x, -o.y);
      vec2 uv1 = vUv + vec2(o.x, -o.y);
      vec2 uv2 = vUv + vec2(-o.x, o.y);
      vec2 uv3 = vUv + vec2(o.x, o.y);
      vec3 c0 = texture2D(tColor, uv0).rgb;
      vec3 c1 = texture2D(tColor, uv1).rgb;
      vec3 c2 = texture2D(tColor, uv2).rgb;
      vec3 c3 = texture2D(tColor, uv3).rgb;
      float w0 = 1.0 / (1.0 + dot(c0, LUMA));
      float w1 = 1.0 / (1.0 + dot(c1, LUMA));
      float w2 = 1.0 / (1.0 + dot(c2, LUMA));
      float w3 = 1.0 / (1.0 + dot(c3, LUMA));
      vec3 col = (c0 * w0 + c1 * w1 + c2 * w2 + c3 * w3) / (w0 + w1 + w2 + w3);
      float d = min(min(-viewZAt(uv0), -viewZAt(uv1)), min(-viewZAt(uv2), -viewZAt(uv3)));
      gl_FragColor = vec4(col, cocAt(d));
    }`
  );
}
function dofGatherMaterial(taps) {
  return pass(
    { tHalf: { value: null }, uTexel: { value: new THREE3.Vector2() }, uMaxBlur: { value: 8 } },
    /* glsl */
    `
    ${LUMA}
    uniform sampler2D tHalf;
    uniform vec2 uTexel;
    uniform float uMaxBlur;
    varying vec2 vUv;
    void main() {
      vec4 c = texture2D(tHalf, vUv);
      float cc = abs(c.a);
      vec3 acc = c.rgb;
      float tot = 1.0;
      float near = 0.0;
      float ang = 0.0;
      for (int i = 0; i < TAPS; i++) {
        ang += 2.39996323;
        float r = uMaxBlur * sqrt((float(i) + 0.5) / float(TAPS));
        vec4 s = texture2D(tHalf, vUv + vec2(cos(ang), sin(ang)) * uTexel * r);
        float sc = abs(s.a);
        if (s.a > c.a) sc = min(sc, cc * 2.0);
        float m = smoothstep(r - 1.0, r + 1.0, sc);
        float w = m * (1.0 + min(dot(s.rgb, LUMA), 6.0) * 0.25);
        acc += s.rgb * w;
        tot += w;
        if (s.a < -0.5) near += m;
      }
      gl_FragColor = vec4(acc / tot, clamp(near / float(TAPS) * 2.5, 0.0, 1.0));
    }`,
    { TAPS: taps }
  );
}
function compositeMaterial() {
  return pass(
    { ...depthUniforms(), tColor: { value: null }, tDof: { value: null }, tAO: { value: null }, uFocus: { value: 5 }, uCoc: { value: 5 }, uAO: { value: 0 }, uDof: { value: 0 } },
    /* glsl */
    `
    ${DEPTH}
    ${LUMA}
    uniform sampler2D tColor;
    uniform sampler2D tDof;
    uniform sampler2D tAO;
    uniform float uFocus;
    uniform float uCoc;
    uniform float uAO;
    uniform float uDof;
    varying vec2 vUv;
    void main() {
      vec3 col = texture2D(tColor, vUv).rgb;
      if (uAO > 0.0) {
        float ao = texture2D(tAO, vUv).r;
        col *= mix(1.0, mix(ao, 1.0, smoothstep(0.8, 3.0, dot(col, LUMA))), uAO);
      }
      if (uDof > 0.0) {
        float coc = abs(uCoc * (1.0 - uFocus / max(-viewZAt(vUv), 1e-3)));
        vec4 b = texture2D(tDof, vUv);
        col = mix(col, b.rgb, max(smoothstep(0.75, 2.5, coc), b.a));
      }
      gl_FragColor = vec4(col, 1.0);
    }`
  );
}

// src/post-final.js
import * as THREE4 from "three";
function streakMaterial() {
  return pass(
    { tInput: { value: null }, uTexel: { value: new THREE4.Vector2() }, uSpread: { value: 1 } },
    /* glsl */
    `
    uniform sampler2D tInput;
    uniform vec2 uTexel;
    uniform float uSpread;
    varying vec2 vUv;
    void main() {
      vec3 c = vec3(0.0);
      float tot = 0.0;
      for (int i = -12; i <= 12; i++) {
        float w = exp(-abs(float(i)) * 0.18);
        c += texture2D(tInput, vUv + vec2(float(i) * uTexel.x * uSpread, 0.0)).rgb * w;
        tot += w;
      }
      gl_FragColor = vec4(c / tot, 1.0);
    }`
  );
}
function finalMaterial() {
  return pass(
    {
      tInput: { value: null },
      tStreak: { value: null },
      uInTexel: { value: new THREE4.Vector2() },
      uSharp: { value: 0.18 },
      uStreak: { value: 0 },
      uExposure: { value: 1 },
      uTime: { value: 0 },
      uGrain: { value: 0.035 },
      uVignette: { value: 0.4 },
      uCA: { value: 2e-3 },
      uBars: { value: 0 },
      uFade: { value: 0 },
      uAspect: { value: 1 }
    },
    /* glsl */
    `
    ${LUMA}
    uniform sampler2D tInput;
    uniform sampler2D tStreak;
    uniform vec2 uInTexel;
    uniform float uSharp;
    uniform float uStreak;
    uniform float uExposure;
    uniform float uTime;
    uniform float uGrain;
    uniform float uVignette;
    uniform float uCA;
    uniform float uBars;
    uniform float uFade;
    uniform float uAspect;
    varying vec2 vUv;
    const mat3 ACESIn = mat3(0.59719, 0.07600, 0.02840, 0.35458, 0.90834, 0.13383, 0.04823, 0.01566, 0.83777);
    const mat3 ACESOut = mat3(1.60475, -0.10208, -0.00327, -0.53108, 1.10813, -0.07276, -0.07367, -0.00605, 1.07602);
    vec3 rrtOdt(vec3 v) {
      vec3 a = v * (v + 0.0245786) - 0.000090537;
      vec3 b = v * (0.983729 * v + 0.4329510) + 0.238081;
      return a / b;
    }
    float hash(vec2 p) {
      vec3 p3 = fract(vec3(p.xyx) * 0.1031);
      p3 += dot(p3, p3.yzx + 33.33);
      return fract((p3.x + p3.y) * p3.z);
    }
    float soft(vec3 c) { float l = dot(c, LUMA); return l / (1.0 + l); }
    void main() {
      vec3 c = texture2D(tInput, vUv).rgb;
      vec3 n = texture2D(tInput, vUv + vec2(0.0, uInTexel.y)).rgb;
      vec3 s = texture2D(tInput, vUv - vec2(0.0, uInTexel.y)).rgb;
      vec3 e = texture2D(tInput, vUv + vec2(uInTexel.x, 0.0)).rgb;
      vec3 w = texture2D(tInput, vUv - vec2(uInTexel.x, 0.0)).rgb;
      float lc = soft(c);
      float ln = soft(n);
      float ls = soft(s);
      float le = soft(e);
      float lw = soft(w);
      float mn = min(lc, min(min(ln, ls), min(le, lw)));
      float mx = max(lc, max(max(ln, ls), max(le, lw)));
      float amp = clamp(min(mn, 1.0 - mx) / max(mx, 1e-4), 0.0, 1.0);
      float k = -sqrt(amp) * uSharp;
      vec3 col = max((c + (n + s + e + w) * k) / (1.0 + 4.0 * k), 0.0);
      vec2 d = vUv - 0.5;
      vec2 dd = d * vec2(uAspect, 1.0);
      float r2 = dot(dd, dd);
      vec2 off = d * r2 * uCA * 4.0;
      col.r += texture2D(tInput, vUv - off).r - c.r;
      col.b += texture2D(tInput, vUv + off).b - c.b;
      col += texture2D(tStreak, vUv).rgb * vec3(0.55, 0.85, 0.4) * uStreak;
      col = max(col, 0.0) * uExposure;
      col *= clamp(1.0 - uVignette * pow(r2 * 1.6, 1.3), 0.0, 1.0);
      col = clamp(ACESOut * rrtOdt(ACESIn * col), 0.0, 1.0);
      col = pow(col, vec3(1.0 / 2.2));
      float l = dot(col, LUMA);
      col = mix(vec3(l), col, 0.94);
      col += vec3(-0.006, 0.004, -0.01) * (1.0 - l) * (1.0 - l);
      col += vec3(0.018, 0.02, -0.006) * l * l;
      col = mix(col, col * col * (3.0 - 2.0 * col), 0.18);
      float g = hash(gl_FragCoord.xy + fract(uTime * 7.13) * 431.0) - 0.5;
      col += g * uGrain * (1.0 - l * 0.7);
      col += (hash(gl_FragCoord.xy * 1.37 + 17.0) - 0.5) / 255.0;
      float bar = step(vUv.y, uBars) + step(1.0 - uBars, vUv.y);
      col = mix(col, vec3(0.0), max(bar, uFade));
      gl_FragColor = vec4(clamp(col, 0.0, 1.0), 1.0);
    }`
  );
}

// src/post.js
var halfFloat = (w, h, extra = {}) => new THREE5.WebGLRenderTarget(w, h, { type: THREE5.HalfFloatType, depthBuffer: false, ...extra });
var Post = class {
  constructor(renderer, quality) {
    this.renderer = renderer;
    this.q = quality;
    this.fsq = new FullScreenQuad();
    this.bloom = new UnrealBloomPass(new THREE5.Vector2(256, 256), 0.3, 0.45, 1.95);
    this.bloom.bloomTintColors = [
      new THREE5.Vector3(0.62, 1, 0.48),
      new THREE5.Vector3(0.76, 1, 0.6),
      new THREE5.Vector3(0.9, 1, 0.82),
      new THREE5.Vector3(1, 1, 0.96),
      new THREE5.Vector3(0.96, 1, 1)
    ];
    this.ao = aoMaterial();
    this.aoBlur = aoBlurMaterial();
    this.dofPre = dofPrefilterMaterial();
    this.dofGather = dofGatherMaterial(Math.max(1, quality.dofTaps));
    this.comp = compositeMaterial();
    this.streak = streakMaterial();
    this.final = finalMaterial();
    this.w = 2;
    this.h = 2;
    this.outW = 2;
    this.outH = 2;
    this.targets();
  }
  targets() {
    for (const t of [this.sceneRT, this.aoRT, this.aoBlurRT, this.dofHalf, this.dofBlur, this.compRT, this.streakA, this.streakB]) t?.dispose();
    const { w, h } = this;
    const hw = Math.max(2, w >> 1);
    const hh = Math.max(2, h >> 1);
    this.sceneRT = new THREE5.WebGLRenderTarget(w, h, { type: THREE5.HalfFloatType, samples: this.q.msaa, depthTexture: new THREE5.DepthTexture(w, h, THREE5.UnsignedIntType) });
    this.aoRT = new THREE5.WebGLRenderTarget(hw, hh, { depthBuffer: false });
    this.aoBlurRT = new THREE5.WebGLRenderTarget(hw, hh, { depthBuffer: false });
    this.dofHalf = halfFloat(hw, hh);
    this.dofBlur = halfFloat(hw, hh);
    this.compRT = halfFloat(w, h);
    this.streakA = halfFloat(Math.max(8, w >> 2), Math.max(8, h >> 3));
    this.streakB = halfFloat(Math.max(8, w >> 2), Math.max(8, h >> 3));
    this.bloom.setSize(w, h);
  }
  setQuality(q) {
    const msaa = q.msaa !== this.q.msaa;
    const taps = q.dofTaps !== this.q.dofTaps;
    this.q = q;
    if (taps) {
      this.dofGather.defines.TAPS = Math.max(1, q.dofTaps);
      this.dofGather.needsUpdate = true;
    }
    if (msaa) this.targets();
  }
  // Internal render size (dynamic resolution) and the display size it is upscaled to.
  setSize(w, h, outW, outH) {
    this.outW = outW;
    this.outH = outH;
    this.final.uniforms.uAspect.value = outW / outH;
    if (w === this.w && h === this.h) return;
    this.w = w;
    this.h = h;
    this.targets();
  }
  run(mat, target) {
    this.fsq.material = mat;
    this.renderer.setRenderTarget(target);
    this.fsq.render(this.renderer);
  }
  render(scene, camera, p) {
    const r = this.renderer;
    const q = this.q;
    r.setRenderTarget(this.sceneRT);
    r.render(scene, camera);
    let src = this.sceneRT;
    const useAO = q.ao;
    const useDof = q.dofTaps > 0 && p.maxBlur > 0.5;
    const depth = this.sceneRT.depthTexture;
    const half = new THREE5.Vector2(1 / Math.max(2, this.w >> 1), 1 / Math.max(2, this.h >> 1));
    for (const m of [this.ao, this.aoBlur, this.dofPre, this.comp]) {
      m.uniforms.tDepth.value = depth;
      m.uniforms.uNear.value = camera.near;
      m.uniforms.uFar.value = camera.far;
    }
    if (useAO || useDof) {
      if (useAO) {
        const a = this.ao.uniforms;
        a.uProj.value.copy(camera.projectionMatrix);
        a.uInvProj.value.copy(camera.projectionMatrixInverse);
        a.uTexel.value.set(1 / this.w, 1 / this.h);
        this.run(this.ao, this.aoRT);
        this.aoBlur.uniforms.tAO.value = this.aoRT.texture;
        this.aoBlur.uniforms.uTexel.value.copy(half);
        this.run(this.aoBlur, this.aoBlurRT);
      }
      if (useDof) {
        const d = this.dofPre.uniforms;
        d.tColor.value = this.sceneRT.texture;
        d.uTexel.value.set(1 / this.w, 1 / this.h);
        d.uFocus.value = p.focus;
        d.uCoc.value = p.coc * 0.5;
        d.uMaxBlur.value = p.maxBlur * 0.5;
        this.run(this.dofPre, this.dofHalf);
        const g = this.dofGather.uniforms;
        g.tHalf.value = this.dofHalf.texture;
        g.uTexel.value.copy(half);
        g.uMaxBlur.value = p.maxBlur * 0.5;
        this.run(this.dofGather, this.dofBlur);
      }
      const c = this.comp.uniforms;
      c.tColor.value = this.sceneRT.texture;
      c.tDof.value = this.dofBlur.texture;
      c.tAO.value = this.aoBlurRT.texture;
      c.uFocus.value = p.focus;
      c.uCoc.value = p.coc;
      c.uAO.value = useAO ? p.ao : 0;
      c.uDof.value = useDof ? 1 : 0;
      this.run(this.comp, this.compRT);
      src = this.compRT;
    }
    this.bloom.strength = p.bloom;
    this.bloom.render(r, null, src, 0, false);
    const f = this.final.uniforms;
    if (q.streaks) {
      const su = this.streak.uniforms;
      su.tInput.value = this.bloom.renderTargetBright.texture;
      su.uTexel.value.set(1 / this.streakA.width, 1 / this.streakA.height);
      su.uSpread.value = 1;
      this.run(this.streak, this.streakA);
      su.tInput.value = this.streakA.texture;
      su.uSpread.value = 3;
      this.run(this.streak, this.streakB);
      f.uStreak.value = p.streak;
    } else f.uStreak.value = 0;
    f.tStreak.value = this.streakB.texture;
    f.tInput.value = src.texture;
    f.uInTexel.value.set(1 / this.w, 1 / this.h);
    f.uSharp.value = this.w < this.outW * 0.98 ? 0.22 : 0.12;
    f.uExposure.value = p.exposure;
    f.uTime.value = p.time;
    f.uGrain.value = p.grain;
    f.uBars.value = p.bars ?? 0;
    f.uFade.value = p.fade ?? 0;
    this.run(this.final, null);
  }
  // Only the embed path (mascot/cinematic/src/embed.js) ever tears a Post instance down mid-session
  // — the standalone showcase page (main.js) lives for the tab's whole lifetime and never calls this.
  dispose() {
    for (const t of [this.sceneRT, this.aoRT, this.aoBlurRT, this.dofHalf, this.dofBlur, this.compRT, this.streakA, this.streakB]) t?.dispose();
    for (const m of [this.ao, this.aoBlur, this.dofPre, this.dofGather, this.comp, this.streak, this.final]) m?.dispose();
    this.bloom.dispose();
    this.fsq.dispose();
  }
};

// src/quality.js
var QUALITY = {
  low: { msaa: 0, dofTaps: 0, ao: false, streaks: false, maxDPR: 1, shadow: false },
  high: { msaa: 2, dofTaps: 20, ao: true, streaks: false, maxDPR: 1.5, shadow: true },
  ultra: { msaa: 4, dofTaps: 32, ao: true, streaks: true, maxDPR: 2, shadow: true }
};
function initialTier(coarsePointer, shortestScreenSide) {
  return coarsePointer || shortestScreenSide < 700 ? "low" : "high";
}
function createGovernor({ budgetMs = 19.5, windowSize = 40, minScale = 0.5, warmupMs = 3e3, holdMs = 2e4 } = {}) {
  const g = { scale: 1, samples: [], lastChange: 0, ceiling: 1, ceilingUntil: 0, since: 0 };
  return {
    get scale() {
      return g.scale;
    },
    reset(nowMs) {
      g.scale = 1;
      g.samples.length = 0;
      g.since = nowMs;
      g.ceiling = 1;
      g.ceilingUntil = 0;
    },
    // Returns true when the scale changed and the render targets must be resized.
    sample(dtMs, nowMs) {
      if (dtMs > 250 || nowMs - g.since < warmupMs) return false;
      g.samples.push(dtMs);
      if (g.samples.length > windowSize) g.samples.shift();
      if (g.samples.length < windowSize * 0.75 || nowMs - g.lastChange < 1200) return false;
      const slow = g.samples.filter((d) => d > budgetMs).length / g.samples.length;
      if (slow > 0.12 && g.scale > minScale) {
        g.ceiling = g.scale;
        g.ceilingUntil = nowMs + holdMs;
        g.scale = Math.max(minScale, g.scale * 0.85);
      } else if (slow === 0 && g.scale < 1 && (nowMs > g.ceilingUntil || g.scale * 1.08 < g.ceiling)) {
        g.scale = Math.min(1, g.scale * 1.08);
      } else return false;
      g.lastChange = nowMs;
      g.samples.length = 0;
      return true;
    }
  };
}

// src/scene.js
import * as THREE11 from "three";

// src/materials.js
import * as THREE6 from "three";
var v2 = (x, y = x) => new THREE6.Vector2(x, y);
var jellyMotion = { uTime: { value: 0 }, uJiggle: { value: 0 } };
function withRimGlow(mat, color, strength, gradient) {
  mat.onBeforeCompile = (shader) => {
    shader.uniforms.uRimColor = { value: new THREE6.Color(color) };
    shader.uniforms.uRimStrength = { value: strength };
    shader.uniforms.uTime = jellyMotion.uTime;
    shader.uniforms.uJiggle = jellyMotion.uJiggle;
    shader.vertexShader = `uniform float uTime;
uniform float uJiggle;
${shader.vertexShader}`.replace("#include <common>", "#include <common>\nvarying float vWorldY;").replace(
      "#include <begin_vertex>",
      `#include <begin_vertex>
      float jw = sin(uTime * 2.2 + position.y * 2.4) * uJiggle * 0.04;
      transformed.x += jw * normal.x;
      transformed.z += jw * normal.z;
      vWorldY = (modelMatrix * vec4(transformed, 1.0)).y;`
    );
    let frag = shader.fragmentShader.replace("#include <common>", "#include <common>\nuniform vec3 uRimColor;\nuniform float uRimStrength;\nvarying float vWorldY;");
    let gradLine = "";
    if (gradient) {
      frag = frag.replace("#include <common>", `#include <common>
uniform vec3 uTopTint;
uniform vec3 uBottomTint;`);
      shader.uniforms.uTopTint = { value: new THREE6.Color(gradient.top) };
      shader.uniforms.uBottomTint = { value: new THREE6.Color(gradient.bottom) };
      gradLine = `
        float gradT = clamp(vWorldY * 0.42 + 0.5, 0.0, 1.0);
        gl_FragColor.rgb += mix(uBottomTint, uTopTint, gradT) * 0.16;`;
    }
    shader.fragmentShader = frag.replace(
      "#include <dithering_fragment>",
      `#include <dithering_fragment>
        float rimFres = pow(1.0 - max(dot(normalize(vViewPosition), normalize(vNormal)), 0.0), 2.6);
        gl_FragColor.rgb += uRimColor * rimFres * uRimStrength;${gradLine}`
    );
  };
  mat.customProgramCacheKey = () => `rim-${color}-${strength}-${gradient ? gradient.top + gradient.bottom : ""}`;
  return mat;
}
function createMaterials(T, palette) {
  const p = palette;
  const jelly = withRimGlow(
    new THREE6.MeshPhysicalMaterial({
      name: "jelly",
      color: 15989732,
      transmission: 1,
      thickness: 1.1,
      ior: 1.34,
      roughness: 0.09,
      specularIntensity: 1,
      clearcoat: 1,
      clearcoatRoughness: 0.32,
      // spreads the specular so one key light does not become a hard hotspot
      normalMap: T.carbon.normalMap,
      normalScale: v2(0.05),
      // barely visible — sealed inside, not printed on top
      attenuationColor: new THREE6.Color(p.olive),
      attenuationDistance: 2.2,
      // almost no self-absorption — the gradient tint carries the color now
      emissive: new THREE6.Color(p.olive),
      emissiveIntensity: 0.075,
      // faint constant inner glow, evenly across the body — no discrete core mesh
      envMapIntensity: 0.85,
      side: THREE6.DoubleSide
    }),
    p.olive,
    0.3,
    { top: p.pale, bottom: p.neon }
  );
  const limb = jelly.clone();
  limb.thickness = 0.55;
  limb.attenuationDistance = 1.4;
  limb.normalMap = T.carbon.normalMap;
  limb.onBeforeCompile = jelly.onBeforeCompile;
  const fabric = new THREE6.MeshStandardMaterial({ name: "fabric", color: 658442, roughnessMap: T.carbon.roughnessMap, normalMap: T.carbon.normalMap, normalScale: v2(0.4), roughness: 1, metalness: 0.04 });
  const acetate = new THREE6.MeshPhysicalMaterial({ name: "acetate", color: p.ink, roughness: 0.42, clearcoat: 0.4, clearcoatRoughness: 0.35, envMapIntensity: 0.5, specularIntensity: 0.4 });
  const lens = lensGlassMaterial(p);
  const catchlight = new THREE6.MeshBasicMaterial({ name: "catchlight", map: T.radial, color: 16777215, transparent: true, opacity: 0.4, depthWrite: false, blending: THREE6.AdditiveBlending });
  const sclera = new THREE6.MeshPhysicalMaterial({ name: "sclera", color: p.eye, roughness: 0.32, envMapIntensity: 0.2, clearcoat: 0.22, clearcoatRoughness: 0.3 });
  const iris = new THREE6.MeshStandardMaterial({
    name: "iris",
    color: p.inkSoft,
    roughness: 0.4,
    envMapIntensity: 0.22,
    normalMap: T.iris.normalMap,
    normalScale: v2(0.6),
    roughnessMap: T.iris.roughnessMap
  });
  const inkPaint = new THREE6.MeshStandardMaterial({ name: "inkPaint", color: p.inkSoft, roughness: 0.4, envMapIntensity: 0.35 });
  const pupil = new THREE6.MeshStandardMaterial({ name: "pupil", color: 0, roughness: 0.06, envMapIntensity: 0.55 });
  const sparkle = new THREE6.MeshBasicMaterial({ name: "sparkle", color: 16777215, toneMapped: false });
  const felt = new THREE6.MeshStandardMaterial({ name: "felt", color: p.ink, roughness: 0.66, normalMap: T.felt.normalMap, roughnessMap: T.felt.roughnessMap, envMapIntensity: 0.5 });
  const feltTop = new THREE6.MeshStandardMaterial({ name: "feltTop", color: p.inkSoft, roughness: 0.72, normalMap: T.felt.normalMap, roughnessMap: T.felt.roughnessMap, envMapIntensity: 0.6 });
  const gold = new THREE6.MeshPhysicalMaterial({ name: "gold", color: p.gold, metalness: 1, roughness: 0.28, envMapIntensity: 1.5, clearcoat: 0.25 });
  const satin = new THREE6.MeshPhysicalMaterial({ name: "satin", color: p.inkSoft, roughness: 0.3, sheen: 1, sheenRoughness: 0.2, sheenColor: new THREE6.Color(p.pale), normalMap: T.satin.normalMap, normalScale: v2(0.6), envMapIntensity: 1.3, clearcoat: 0.15, clearcoatRoughness: 0.4 });
  const satinKnot = satin.clone();
  satinKnot.color = new THREE6.Color(p.inkSoft);
  const ground = new THREE6.ShadowMaterial({ opacity: 0.48 });
  const glow = new THREE6.MeshBasicMaterial({ color: p.olive, map: T.radial, transparent: true, opacity: 0.4, depthWrite: false });
  const caustic = causticMaterial(p);
  return { jelly, limb, fabric, acetate, lens, catchlight, sclera, iris, inkPaint, pupil, sparkle, felt, feltTop, gold, satin, satinKnot, ground, glow, caustic };
}
function lensGlassMaterial(p) {
  return new THREE6.ShaderMaterial({
    name: "lens",
    transparent: true,
    depthWrite: false,
    uniforms: { uColor: { value: new THREE6.Color(15989736) }, uRim: { value: new THREE6.Color(p.pale) } },
    vertexShader: (
      /* glsl */
      `
      varying vec3 vN;
      varying vec3 vV;
      void main() {
        vN = normalize(normalMatrix * normal);
        vec4 mv = modelViewMatrix * vec4(position, 1.0);
        vV = normalize(-mv.xyz);
        gl_Position = projectionMatrix * mv;
      }`
    ),
    fragmentShader: (
      /* glsl */
      `
      uniform vec3 uColor;
      uniform vec3 uRim;
      varying vec3 vN;
      varying vec3 vV;
      void main() {
        float fres = pow(1.0 - max(dot(vV, normalize(vN)), 0.0), 3.2);
        vec3 col = uColor + uRim * fres * 0.7;
        gl_FragColor = vec4(col, 0.05 + fres * 0.55);
      }`
    )
  });
}
function causticMaterial(p) {
  return new THREE6.ShaderMaterial({
    transparent: true,
    depthWrite: false,
    blending: THREE6.AdditiveBlending,
    uniforms: { uTime: jellyMotion.uTime, uColor: { value: new THREE6.Color(p.neon) }, uColor2: { value: new THREE6.Color(p.pale) } },
    vertexShader: "varying vec2 vUv; void main(){ vUv = uv; gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0); }",
    fragmentShader: (
      /* glsl */
      `
      uniform float uTime;
      uniform vec3 uColor;
      uniform vec3 uColor2;
      varying vec2 vUv;
      float ring(vec2 uv, float t) {
        float d = length(uv);
        return abs(sin((d * 9.0 - t * 1.1) + sin(uv.x * 5.0 + t * 0.7) * 1.4));
      }
      void main() {
        vec2 uv = vUv * 2.0 - 1.0;
        float fall = 1.0 - smoothstep(0.15, 1.0, length(uv));
        float r1 = pow(ring(uv, uTime), 5.0);
        float r2 = pow(ring(uv * 1.4 + 0.3, uTime * 0.8 + 2.0), 5.0);
        vec3 col = mix(uColor, uColor2, r2) * (r1 * 0.6 + r2 * 0.4);
        gl_FragColor = vec4(col * fall, (r1 + r2) * fall * 0.5);
      }`
    )
  });
}

// src/noise.js
function rng(seed) {
  let a = seed >>> 0;
  return function next() {
    a = a + 1831565813 >>> 0;
    let t = a;
    t = Math.imul(t ^ t >>> 15, t | 1);
    t ^= t + Math.imul(t ^ t >>> 7, t | 61);
    return ((t ^ t >>> 14) >>> 0) / 4294967296;
  };
}
var Noise2 = class {
  constructor(seed) {
    const rand = rng(seed);
    this.perm = new Uint16Array(512);
    this.vals = new Float32Array(256);
    const p = new Uint16Array(256);
    for (let i = 0; i < 256; i++) {
      p[i] = i;
      this.vals[i] = rand();
    }
    for (let i = 255; i > 0; i--) {
      const j = Math.floor(rand() * (i + 1));
      const tmp = p[i];
      p[i] = p[j];
      p[j] = tmp;
    }
    for (let i = 0; i < 512; i++) this.perm[i] = p[i & 255];
  }
  value(x, y, period) {
    const xi = Math.floor(x);
    const yi = Math.floor(y);
    const xf = x - xi;
    const yf = y - yi;
    const u = xf * xf * (3 - 2 * xf);
    const v = yf * yf * (3 - 2 * yf);
    const x0 = (xi % period + period) % period;
    const y0 = (yi % period + period) % period;
    const x1 = (x0 + 1) % period;
    const y1 = (y0 + 1) % period;
    const P = this.perm;
    const V = this.vals;
    const a = V[P[P[x0 & 255] + (y0 & 255)]];
    const b = V[P[P[x1 & 255] + (y0 & 255)]];
    const c = V[P[P[x0 & 255] + (y1 & 255)]];
    const d = V[P[P[x1 & 255] + (y1 & 255)]];
    return a + (b - a) * u + (c - a) * v + (a - b - c + d) * u * v;
  }
  // Fractal sum normalised to [0,1]; period doubles with frequency to keep tiling.
  fbm(x, y, period, octaves = 4, gain = 0.5) {
    let sum = 0;
    let amp = 1;
    let norm = 0;
    let f = 1;
    for (let o = 0; o < octaves; o++) {
      sum += this.value(x * f, y * f, period * f) * amp;
      norm += amp;
      amp *= gain;
      f *= 2;
    }
    return sum / norm;
  }
};
var clamp01 = (v) => v < 0 ? 0 : v > 1 ? 1 : v;
var smooth = (a, b, v) => {
  const t = clamp01((v - a) / (b - a));
  return t * t * (3 - 2 * t);
};

// src/texture-util.js
import * as THREE7 from "three";
var maxAniso = 8;
function dataTexture(data, w, h, srgb) {
  const t = new THREE7.DataTexture(data, w, h, THREE7.RGBAFormat);
  t.wrapS = t.wrapT = THREE7.RepeatWrapping;
  t.magFilter = THREE7.LinearFilter;
  t.minFilter = THREE7.LinearMipmapLinearFilter;
  t.generateMipmaps = true;
  t.anisotropy = maxAniso;
  t.colorSpace = srgb ? THREE7.SRGBColorSpace : THREE7.NoColorSpace;
  t.needsUpdate = true;
  return t;
}
function heightToNormal(H, w, h, strength) {
  const out = new Uint8Array(w * h * 4);
  for (let y = 0; y < h; y++) {
    const yu = (y + 1) % h * w;
    const yd = (y - 1 + h) % h * w;
    for (let x = 0; x < w; x++) {
      const xr = (x + 1) % w;
      const xl = (x - 1 + w) % w;
      const dx = (H[y * w + xr] - H[y * w + xl]) * strength;
      const dy = (H[yu + x] - H[yd + x]) * strength;
      const inv = 1 / Math.sqrt(dx * dx + dy * dy + 1);
      const i = (y * w + x) * 4;
      out[i] = (-dx * inv * 0.5 + 0.5) * 255;
      out[i + 1] = (-dy * inv * 0.5 + 0.5) * 255;
      out[i + 2] = (inv * 0.5 + 0.5) * 255;
      out[i + 3] = 255;
    }
  }
  return out;
}
function grayToRGBA(G) {
  const out = new Uint8Array(G.length * 4);
  for (let i = 0; i < G.length; i++) {
    const v = clamp01(G[i]) * 255;
    out[i * 4] = v;
    out[i * 4 + 1] = v;
    out[i * 4 + 2] = v;
    out[i * 4 + 3] = 255;
  }
  return out;
}

// src/textures.js
function carbonTwillTextures(size = 256, cells = 18) {
  const n = size * size;
  const H = new Float32Array(n);
  const R = new Float32Array(n);
  const nz = new Noise2(31);
  for (let y = 0; y < size; y++) {
    for (let x = 0; x < size; x++) {
      const i = y * size + x;
      const gx = x / size * cells;
      const gy = y / size * cells;
      const diag = (Math.floor(gx) + Math.floor(gy)) % 4;
      const fx = gx - Math.floor(gx);
      const fy = gy - Math.floor(gy);
      const strand = diag < 2 ? Math.sin(fx * Math.PI) : Math.sin(fy * Math.PI);
      const fiber = nz.fbm(gx * 3, gy * 3, cells * 3, 3);
      H[i] = strand * 0.35 + fiber * 0.1;
      R[i] = 0.32 + 0.14 * strand + 0.06 * fiber;
    }
  }
  return {
    normalMap: dataTexture(heightToNormal(H, size, size, 0.9), size, size, false),
    roughnessMap: dataTexture(grayToRGBA(R), size, size, false)
  };
}
function satinTextures(size = 256, cells = 10) {
  const n = size * size;
  const H = new Float32Array(n);
  const R = new Float32Array(n);
  const nz = new Noise2(58);
  for (let y = 0; y < size; y++) {
    for (let x = 0; x < size; x++) {
      const i = y * size + x;
      const gx = x / size * cells;
      const gy = y / size * cells;
      const float = Math.sin(gx * Math.PI * 2) * 0.15;
      const fiber = nz.fbm(gx * 4, gy * 4, cells * 4, 3);
      H[i] = float + fiber * 0.22;
      R[i] = 0.22 + 0.1 * fiber;
    }
  }
  return {
    normalMap: dataTexture(heightToNormal(H, size, size, 1.1), size, size, false),
    roughnessMap: dataTexture(grayToRGBA(R), size, size, false)
  };
}
function feltTextures(size = 192) {
  const n = size * size;
  const H = new Float32Array(n);
  const R = new Float32Array(n);
  const nz = new Noise2(11);
  for (let y = 0; y < size; y++) {
    for (let x = 0; x < size; x++) {
      const i = y * size + x;
      const u = x / size;
      const v = y / size;
      const fiber = nz.fbm(u * 40, v * 40, 40, 4);
      H[i] = fiber * 0.5;
      R[i] = 0.6 + 0.2 * fiber;
    }
  }
  return {
    normalMap: dataTexture(heightToNormal(H, size, size, 1.4), size, size, false),
    roughnessMap: dataTexture(grayToRGBA(R), size, size, false)
  };
}
function irisTextures(size = 128) {
  const n = size * size;
  const H = new Float32Array(n);
  const R = new Float32Array(n);
  const nz = new Noise2(71);
  const cx = size / 2;
  const cy = size / 2;
  for (let y = 0; y < size; y++) {
    for (let x = 0; x < size; x++) {
      const i = y * size + x;
      const dx = (x - cx) / (size / 2);
      const dy = (y - cy) / (size / 2);
      const r = Math.min(1, Math.hypot(dx, dy));
      const a = Math.atan2(dy, dx);
      const spokes = Math.sin(a * 24 + nz.fbm(r * 4, a, 8, 2) * 3) * 0.5 + 0.5;
      H[i] = spokes * (0.15 + r * 0.35) + nz.fbm(dx * 6 + 8, dy * 6 + 8, 12, 3) * 0.12;
      R[i] = 0.28 + 0.22 * spokes - 0.12 * smooth(0.72, 1, r);
    }
  }
  return {
    normalMap: dataTexture(heightToNormal(H, size, size, 1.6), size, size, false),
    roughnessMap: dataTexture(grayToRGBA(R), size, size, false)
  };
}
function radialTextures(size = 128) {
  const n = size * size;
  const A = new Uint8Array(n * 4);
  const cx = size / 2;
  const cy = size / 2;
  for (let y = 0; y < size; y++) {
    for (let x = 0; x < size; x++) {
      const i = y * size + x;
      const d = Math.hypot(x - cx, y - cy) / (size / 2);
      const a = 1 - smooth(0.15, 1, d);
      A[i * 4] = A[i * 4 + 1] = A[i * 4 + 2] = 255;
      A[i * 4 + 3] = Math.min(255, a * 255);
    }
  }
  return dataTexture(A, size, size, false);
}

// src/body.js
import * as THREE8 from "three";

// src/profile.js
var PROFILE = [
  [0.02, -1.08],
  [0.5, -1.02],
  [0.8, -0.88],
  [0.97, -0.6],
  [1.02, -0.22],
  [1, 0.18],
  [0.9, 0.52],
  [0.7, 0.83],
  [0.44, 1.04],
  [0, 1.2]
];
var TOP_OF_HEAD_Y = PROFILE[PROFILE.length - 1][1];
var SOLE_Y = PROFILE[0][1];
function catmullRom(p0, p1, p2, p3, t) {
  const t2 = t * t;
  const t3 = t2 * t;
  return 0.5 * (2 * p1 + (-p0 + p2) * t + (2 * p0 - 5 * p1 + 4 * p2 - p3) * t2 + (-p0 + 3 * p1 - 3 * p2 + p3) * t3);
}
function bodyRadiusAtY(y) {
  const pts = PROFILE;
  const n = pts.length;
  if (y <= pts[0][1]) return pts[0][0];
  if (y >= pts[n - 1][1]) return pts[n - 1][0];
  for (let i = 0; i < n - 1; i++) {
    const y0 = pts[i][1];
    const y1 = pts[i + 1][1];
    if (y >= y0 && y <= y1) {
      const t = (y - y0) / (y1 - y0);
      const p0 = pts[Math.max(0, i - 1)][0];
      const p1 = pts[i][0];
      const p2 = pts[i + 1][0];
      const p3 = pts[Math.min(n - 1, i + 2)][0];
      return catmullRom(p0, p1, p2, p3, t);
    }
  }
  return 0;
}
var FACE_CLEARANCE = 0.02;
function forwardZFor(y, halfDepth = 0) {
  const r = bodyRadiusAtY(y);
  return r * (1 + FACE_CLEARANCE) + halfDepth;
}

// src/body.js
var FOOT_DROP = 0.1;
var GROUND_Y = SOLE_Y - FOOT_DROP;
function latheBody() {
  const pts3 = PROFILE.map(([x, y]) => new THREE8.Vector3(x, y, 0));
  const curve = new THREE8.CatmullRomCurve3(pts3, false, "catmullrom", 0.4);
  const pts2 = curve.getPoints(72).map((p) => new THREE8.Vector2(Math.max(0, p.x), p.y));
  const geo = new THREE8.LatheGeometry(pts2, 176);
  geo.computeVertexNormals();
  return geo;
}
function curvedLimb(points, radius, material, capRadius = radius * 1.15) {
  const group = new THREE8.Group();
  const curve = new THREE8.CatmullRomCurve3(points.map((p) => new THREE8.Vector3(...p)));
  const tube = new THREE8.Mesh(new THREE8.TubeGeometry(curve, 20, radius, 10, false), material);
  const capPos = points[points.length - 1];
  const cap = new THREE8.Mesh(new THREE8.SphereGeometry(capRadius, 14, 10), material);
  cap.scale.set(1, 0.82, 1);
  cap.position.set(...capPos);
  tube.castShadow = cap.castShadow = true;
  group.add(tube, cap);
  return group;
}
function arm(sign) {
  const shoulderY = 0.22;
  const r = bodyRadiusAtY(shoulderY);
  const pts = [
    [sign * r * 0.92, shoulderY, 0.14],
    [sign * 1.18, -0.05, 0.22],
    [sign * 1.28, -0.42, 0.3],
    [sign * 1.16, -0.76, 0.34]
  ];
  return { pts, radius: 0.13 };
}
function leg(sign) {
  const hipY = GROUND_Y + 0.5;
  const pts = [
    [sign * 0.28, hipY, 0.18],
    [sign * 0.3, GROUND_Y + 0.22, 0.24],
    [sign * 0.3, GROUND_Y + 0.06, 0.3]
  ];
  return { pts, radius: 0.15 };
}
function foot(sign, materials) {
  const f = new THREE8.Mesh(new THREE8.SphereGeometry(0.19, 18, 12), materials.limb);
  f.scale.set(1.15, 0.62, 1.35);
  f.position.set(sign * 0.3, GROUND_Y + 0.19 * 0.62, 0.36);
  f.castShadow = f.receiveShadow = true;
  f.name = `foot${sign > 0 ? "R" : "L"}`;
  return f;
}
function buildBody(materials, textures) {
  const group = new THREE8.Group();
  const body = new THREE8.Mesh(latheBody(), materials.jelly);
  body.castShadow = body.receiveShadow = true;
  group.add(body);
  const fabric = new THREE8.Mesh(new THREE8.SphereGeometry(0.6, 22, 16), materials.fabric);
  fabric.scale.set(1, 1.22, 0.52);
  fabric.position.set(0, -0.02, 0.02);
  group.add(fabric);
  const bubbleGeo = new THREE8.SphereGeometry(1, 10, 8);
  const rand = rng(42);
  for (let i = 0; i < 14; i++) {
    const r = 0.02 + rand() * 0.05;
    const theta = rand() * Math.PI * 2;
    const u = rand() * 2 - 1;
    const rad = 0.3 + rand() * 0.55;
    const py = -0.7 + rand() * 1.6;
    const b = new THREE8.Mesh(bubbleGeo, materials.lens);
    b.scale.setScalar(r);
    b.position.set(Math.cos(theta) * rad * Math.sqrt(1 - u * u) * 0.9, py, Math.sin(theta) * rad * Math.sqrt(1 - u * u) * 0.9);
    group.add(b);
  }
  for (const sign of [-1, 1]) {
    const a = arm(sign);
    group.add(curvedLimb(a.pts, a.radius, materials.limb));
    const l = leg(sign);
    group.add(curvedLimb(l.pts, l.radius, materials.limb, 0.17));
    group.add(foot(sign, materials));
  }
  void textures;
  return group;
}

// src/face.js
import * as THREE9 from "three";
var EYE_Y = 0.32;
var EYE_X = 0.32;
var TUBE_R = 0.032;
var RING_R = 0.27;
var SCLERA_R = 0.14;
var MARGIN = 0.17;
function layout() {
  const bodyR = bodyRadiusAtY(EYE_Y);
  const ringZ = forwardZFor(EYE_Y, TUBE_R) + MARGIN;
  const lensZ = ringZ + 0.025;
  const scleraZ = bodyR + 0.03;
  const sclerePoleZ = scleraZ + SCLERA_R;
  const irisZ = sclerePoleZ + 0.01;
  const pupilZ = irisZ + 0.015;
  return {
    bodyR,
    ringZ,
    ringBackZ: ringZ - TUBE_R,
    lensZ,
    scleraZ,
    sclerePoleZ,
    irisZ,
    pupilZ,
    sparkleZ: lensZ - 0.01
  };
}
function glassesRing(sign, materials) {
  const g = new THREE9.Group();
  const L = layout();
  const ring = new THREE9.Mesh(new THREE9.TorusGeometry(RING_R, TUBE_R, 20, 72, Math.PI * 2), materials.acetate);
  const lensMesh = new THREE9.Mesh(new THREE9.CircleGeometry(RING_R * 0.94, 40), materials.lens);
  lensMesh.position.z = L.lensZ - L.ringZ;
  const catchlight = new THREE9.Mesh(new THREE9.PlaneGeometry(RING_R * 0.55, RING_R * 0.32), materials.catchlight);
  catchlight.position.set(-RING_R * 0.33, RING_R * 0.36, L.lensZ - L.ringZ + 8e-3);
  catchlight.rotation.z = 0.3;
  const temple = new THREE9.Mesh(new THREE9.CylinderGeometry(0.018, 0.018, 0.3, 10), materials.acetate);
  temple.rotation.z = Math.PI / 2;
  temple.rotation.y = sign * -0.18;
  temple.position.set(sign * (RING_R + 0.12), 0, -0.08);
  g.add(ring, lensMesh, catchlight, temple);
  g.position.set(sign * EYE_X, EYE_Y, L.ringZ);
  g.name = `glassesRing${sign > 0 ? "R" : "L"}`;
  return g;
}
function eye(sign, materials) {
  const L = layout();
  const g = new THREE9.Group();
  const sclera = new THREE9.Mesh(new THREE9.SphereGeometry(SCLERA_R, 24, 18), materials.sclera);
  sclera.position.z = L.scleraZ;
  sclera.name = `sclera${sign > 0 ? "R" : "L"}`;
  const iris = new THREE9.Mesh(new THREE9.CircleGeometry(0.085, 24), materials.iris);
  iris.position.z = L.irisZ;
  const pupil = new THREE9.Mesh(new THREE9.CircleGeometry(0.045, 18), materials.pupil);
  pupil.position.z = L.pupilZ;
  pupil.name = `pupil${sign > 0 ? "R" : "L"}`;
  const sparkleA = new THREE9.Mesh(new THREE9.CircleGeometry(0.022, 10), materials.sparkle);
  sparkleA.position.set(-0.04, 0.045, L.sparkleZ);
  const sparkleB = new THREE9.Mesh(new THREE9.CircleGeometry(0.012, 8), materials.sparkle);
  sparkleB.position.set(0.028, -0.035, L.sparkleZ);
  g.add(sclera, iris, pupil, sparkleA, sparkleB);
  g.position.set(sign * EYE_X, EYE_Y, 0);
  return g;
}
function lidShadow(sign, materials) {
  const L = layout();
  const mat = materials.inkPaint.clone();
  mat.transparent = true;
  mat.opacity = 0.32;
  mat.depthWrite = false;
  const ring = new THREE9.Mesh(new THREE9.TorusGeometry(SCLERA_R * 0.9, 0.024, 8, 20, Math.PI * 0.6), mat);
  ring.rotation.z = Math.PI * 0.2;
  ring.scale.set(1, 0.62, 0.4);
  ring.position.set(sign * EYE_X, EYE_Y + 8e-3, L.scleraZ + 0.03);
  return ring;
}
function eyelid(sign, materials) {
  const L = layout();
  const lid = new THREE9.Mesh(new THREE9.SphereGeometry(SCLERA_R * 1.08, 16, 12), materials.jelly);
  lid.position.set(sign * EYE_X, EYE_Y + 0.02, L.sclerePoleZ - 0.02);
  lid.scale.set(1.05, 0.02, 0.5);
  lid.name = `eyelid${sign > 0 ? "R" : "L"}`;
  return lid;
}
var BROW_Y = EYE_Y + 0.315;
function brow(sign, materials) {
  const z0 = bodyRadiusAtY(BROW_Y) * 1.012;
  const curve = new THREE9.CatmullRomCurve3([
    new THREE9.Vector3(-0.1, -4e-3, 0),
    new THREE9.Vector3(-0.045, 0.02, 3e-3),
    new THREE9.Vector3(0, 0.026, 4e-3),
    new THREE9.Vector3(0.045, 0.016, 2e-3),
    new THREE9.Vector3(0.1, -0.012, 0)
  ]);
  const geo = new THREE9.TubeGeometry(curve, 20, 0.037, 10, false);
  const b = new THREE9.Mesh(geo, materials.acetate);
  b.scale.set(1, 0.62, 1);
  b.position.set(sign * EYE_X, BROW_Y, z0);
  b.rotation.y = -sign * 0.16;
  b.castShadow = true;
  return b;
}
function buildFace(materials) {
  const group = new THREE9.Group();
  for (const sign of [-1, 1]) {
    group.add(glassesRing(sign, materials));
    group.add(eye(sign, materials));
    group.add(lidShadow(sign, materials));
    group.add(eyelid(sign, materials));
    group.add(brow(sign, materials));
  }
  const bridge = new THREE9.Mesh(new THREE9.CylinderGeometry(0.016, 0.016, 0.12, 8), materials.acetate);
  bridge.rotation.z = Math.PI / 2;
  bridge.position.set(0, EYE_Y, layout().ringZ);
  group.add(bridge);
  const mouthY = EYE_Y - RING_R - 0.1;
  const mouthZ = bodyRadiusAtY(mouthY) * 1.02;
  const mouthCurve = new THREE9.CatmullRomCurve3([
    new THREE9.Vector3(-0.17, 0.018, 0),
    new THREE9.Vector3(-0.08, -0.014, 4e-3),
    new THREE9.Vector3(0, -0.022, 6e-3),
    new THREE9.Vector3(0.08, -0.014, 4e-3),
    new THREE9.Vector3(0.17, 0.018, 0)
  ]);
  const mouth = new THREE9.Mesh(new THREE9.TubeGeometry(mouthCurve, 24, 0.013, 8, false), materials.inkPaint);
  mouth.position.set(0, mouthY, mouthZ);
  group.add(mouth);
  return group;
}

// src/accessories.js
import * as THREE10 from "three";
var BOW_Y = -0.48;
var BOW_Z = forwardZFor(BOW_Y, 0.03) + 0.06;
var BAND_H = 0.2;
var BAND_BOTTOM_R = 0.44;
var EMBED = 0.02;
function findHatBottomY() {
  let y = TOP_OF_HEAD_Y;
  const step = 2e-3;
  while (y > SOLE_Y && bodyRadiusAtY(y) < BAND_BOTTOM_R) y -= step;
  return y - EMBED;
}
var HAT_BOTTOM_Y = findHatBottomY();
function boardGeometry(size, thickness, radius, bevel) {
  const s = size / 2;
  const shape = new THREE10.Shape();
  shape.moveTo(-s + radius, -s);
  shape.lineTo(s - radius, -s);
  shape.quadraticCurveTo(s, -s, s, -s + radius);
  shape.lineTo(s, s - radius);
  shape.quadraticCurveTo(s, s, s - radius, s);
  shape.lineTo(-s + radius, s);
  shape.quadraticCurveTo(-s, s, -s, s - radius);
  shape.lineTo(-s, -s + radius);
  shape.quadraticCurveTo(-s, -s, -s + radius, -s);
  const geo = new THREE10.ExtrudeGeometry(shape, { depth: thickness, bevelEnabled: true, bevelThickness: bevel, bevelSize: bevel, bevelSegments: 2, curveSegments: 6 });
  geo.rotateX(-Math.PI / 2);
  geo.translate(0, -thickness / 2, 0);
  return geo;
}
function buildHat(materials) {
  const hat = new THREE10.Group();
  const band = new THREE10.Mesh(new THREE10.CylinderGeometry(0.38, 0.44, BAND_H, 28), materials.felt);
  band.position.y = HAT_BOTTOM_Y + BAND_H / 2;
  band.name = "hatBand";
  const board = new THREE10.Mesh(boardGeometry(0.94, 0.05, 0.03, 8e-3), materials.feltTop);
  board.position.y = HAT_BOTTOM_Y + BAND_H + 0.025;
  const button = new THREE10.Mesh(new THREE10.SphereGeometry(0.035, 10, 8), materials.gold);
  button.position.y = board.position.y + 0.045;
  band.castShadow = board.castShadow = true;
  hat.add(band, board, button);
  hat.add(buildTassel(materials, button.position.y));
  hat.position.set(0.02, 0, 0.03);
  hat.rotation.set(-0.04, 0.3, -0.1);
  hat.name = "hat";
  return hat;
}
function buildTassel(materials, buttonY) {
  const group = new THREE10.Group();
  const anchor = new THREE10.Vector3(0, buttonY, 0);
  const knee = new THREE10.Vector3(0.32, buttonY - 0.05, 0.2);
  const drop = new THREE10.Vector3(0.54, buttonY - 0.55, 0.34);
  const cordStrands = 3;
  for (let i = 0; i < cordStrands; i++) {
    const a = i / cordStrands * Math.PI * 2;
    const twist = new THREE10.Vector3(Math.cos(a) * 0.02, 0, Math.sin(a) * 0.02);
    const curve = new THREE10.CatmullRomCurve3([
      anchor.clone(),
      knee.clone().add(twist),
      drop.clone().add(twist.clone().multiplyScalar(0.6))
    ]);
    const strand = new THREE10.Mesh(new THREE10.TubeGeometry(curve, 20, 0.018, 8, false), materials.gold);
    strand.castShadow = true;
    group.add(strand);
  }
  const cap = new THREE10.Mesh(new THREE10.TorusGeometry(0.055, 0.016, 8, 16), materials.gold);
  cap.position.copy(drop).y += 0.16;
  cap.rotation.x = Math.PI / 2;
  group.add(cap);
  const fringeCount = 12;
  for (let i = 0; i < fringeCount; i++) {
    const a = i / fringeCount * Math.PI * 2;
    const thread = new THREE10.Mesh(new THREE10.CylinderGeometry(7e-3, 15e-4, 0.24, 5), materials.gold);
    thread.position.copy(drop).add(new THREE10.Vector3(Math.cos(a) * 0.035, -0.2, Math.sin(a) * 0.035));
    thread.rotation.set(Math.cos(a) * 0.32, 0, Math.sin(a) * 0.32);
    group.add(thread);
  }
  group.name = "tassel";
  return group;
}
function puffWing(geo, sign, amount) {
  const pos = geo.attributes.position;
  for (let i = 0; i < pos.count; i++) {
    const x = pos.getX(i);
    const y = pos.getY(i);
    const xt = THREE10.MathUtils.clamp(x / (sign * WING_W), 0, 1);
    const yt = 1 - Math.min(1, Math.abs(y) / 0.15);
    pos.setZ(i, pos.getZ(i) + Math.sin(xt * Math.PI) * yt * amount);
  }
  geo.computeVertexNormals();
}
var WING_W = 0.34;
var WING_DEPTH = 0.062;
function bowWing(sign, materials) {
  const shape = new THREE10.Shape();
  shape.moveTo(0, 0.035);
  shape.quadraticCurveTo(sign * 0.16, 0.1, sign * (WING_W - 0.05), 0.15);
  shape.quadraticCurveTo(sign * (WING_W + 0.03), 0.17, sign * (WING_W + 0.03), 0);
  shape.quadraticCurveTo(sign * (WING_W + 0.03), -0.17, sign * (WING_W - 0.05), -0.15);
  shape.quadraticCurveTo(sign * 0.16, -0.1, 0, -0.035);
  shape.closePath();
  const geo = new THREE10.ExtrudeGeometry(shape, { depth: WING_DEPTH, bevelEnabled: true, bevelThickness: 0.02, bevelSize: 0.018, bevelSegments: 4, curveSegments: 12 });
  puffWing(geo, sign, 0.12);
  const wing = new THREE10.Mesh(geo, materials.satin);
  wing.rotation.y = sign * -0.36;
  wing.castShadow = true;
  const group = new THREE10.Group();
  group.add(wing);
  for (const t of [0.32, 0.56, 0.82]) {
    const crease = new THREE10.Mesh(new THREE10.CylinderGeometry(7e-3, 7e-3, 0.26, 6), materials.satinKnot);
    crease.rotation.z = Math.PI / 2;
    crease.rotation.y = sign * -0.32;
    crease.position.set(sign * WING_W * t, 0, 0.026 + Math.sin(t * Math.PI) * 0.06);
    group.add(crease);
  }
  return group;
}
function buildBow(materials) {
  const bow = new THREE10.Group();
  bow.add(bowWing(-1, materials), bowWing(1, materials));
  const knot = new THREE10.Mesh(new THREE10.CylinderGeometry(0.05, 0.055, 0.1, 14), materials.satinKnot);
  knot.rotation.z = Math.PI / 2;
  const cinchL = new THREE10.Mesh(new THREE10.TorusGeometry(0.03, 0.01, 8, 16), materials.satinKnot);
  cinchL.rotation.y = Math.PI / 2;
  cinchL.position.x = -0.13;
  const cinchR = cinchL.clone();
  cinchR.position.x = 0.13;
  bow.add(knot, cinchL, cinchR);
  bow.name = "bow";
  return bow;
}

// src/scene.js
var PALETTE = {
  bg: "#050706",
  deep: "#0D4A02",
  bottle: "#297F04",
  neon: "#5AB60D",
  olive: "#99E72A",
  softOlive: "#848D68",
  pale: "#C8DDA6",
  ink: "#0A0C0A",
  inkSoft: "#2A2E24",
  eye: "#F4FAEA",
  gold: "#D9A521"
};
function addLights(scene, p) {
  const key = new THREE11.DirectionalLight(16773846, 1.5);
  key.position.set(-2.8, 2.2, 4.6);
  key.castShadow = true;
  key.shadow.mapSize.set(1024, 1024);
  key.shadow.camera.near = 1;
  key.shadow.camera.far = 10;
  key.shadow.camera.left = -2;
  key.shadow.camera.right = 2;
  key.shadow.camera.top = 2;
  key.shadow.camera.bottom = -2;
  key.shadow.bias = -18e-4;
  scene.add(key);
  const fill = new THREE11.DirectionalLight(14675680, 1);
  fill.position.set(3, 1.6, 3.2);
  scene.add(fill);
  const rim = new THREE11.DirectionalLight(13163942, 1.1);
  rim.position.set(0.4, 1.3, -3.4);
  scene.add(rim);
  const underglow = new THREE11.PointLight(new THREE11.Color(p.olive), 0.9, 4, 2);
  underglow.position.set(0, -0.9, 1.1);
  scene.add(underglow);
  const underFill = new THREE11.PointLight(new THREE11.Color(p.pale), 0.7, 5, 1.6);
  underFill.position.set(0, -0.4, 2.4);
  scene.add(underFill);
  const overhead = new THREE11.DirectionalLight(new THREE11.Color(p.pale), 0.75);
  overhead.position.set(0, 5, 1.2);
  scene.add(overhead);
  scene.add(new THREE11.HemisphereLight(new THREE11.Color(p.bottle), 659974, 0.6));
}
function softStudioEnvironment(renderer, p) {
  const envScene = new THREE11.Scene();
  const sky = new THREE11.Mesh(
    new THREE11.SphereGeometry(20, 16, 12),
    new THREE11.ShaderMaterial({
      side: THREE11.BackSide,
      uniforms: { top: { value: new THREE11.Color(1318160) }, bottom: { value: new THREE11.Color(131842) } },
      vertexShader: "varying vec3 vP; void main(){ vP = position; gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0); }",
      fragmentShader: "varying vec3 vP; uniform vec3 top; uniform vec3 bottom; void main(){ float h = clamp(normalize(vP).y * 0.5 + 0.5, 0.0, 1.0); gl_FragColor = vec4(mix(bottom, top, pow(h, 0.8)), 1.0); }"
    })
  );
  envScene.add(sky);
  const panel = (x, y, z, ry, w, h, color, intensity) => {
    const m = new THREE11.Mesh(new THREE11.PlaneGeometry(w, h), new THREE11.MeshBasicMaterial({ color, toneMapped: false }));
    m.material.color.multiplyScalar(intensity);
    m.position.set(x, y, z);
    m.rotation.y = ry;
    envScene.add(m);
  };
  panel(-4, 5, 3, Math.PI * 0.15, 6, 6, 16774104, 0.7);
  panel(4, 1.5, 4, -Math.PI * 0.2, 5, 5, 14675680, 0.3);
  panel(0, -1.5, -5, Math.PI, 6, 4, new THREE11.Color(p.neon), 0.5);
  const pmrem = new THREE11.PMREMGenerator(renderer);
  const env = pmrem.fromScene(envScene, 0.35).texture;
  sky.geometry.dispose();
  sky.material.dispose();
  return env;
}
function buildScene(renderer, palette = PALETTE) {
  const p = palette;
  const scene = new THREE11.Scene();
  scene.background = new THREE11.Color(p.bg);
  scene.environment = softStudioEnvironment(renderer, p);
  const textures = {
    carbon: carbonTwillTextures(),
    satin: satinTextures(),
    felt: feltTextures(),
    radial: radialTextures(),
    iris: irisTextures()
  };
  const materials = createMaterials(textures, p);
  const mascot = new THREE11.Group();
  const body = buildBody(materials, textures);
  const face = buildFace(materials);
  const hat = buildHat(materials);
  const bow = buildBow(materials);
  bow.position.set(0, BOW_Y, BOW_Z);
  mascot.add(body, face, hat, bow);
  scene.add(mascot);
  const ground = new THREE11.Mesh(new THREE11.PlaneGeometry(9, 9), materials.ground);
  ground.rotation.x = -Math.PI / 2;
  ground.position.y = GROUND_Y;
  ground.receiveShadow = true;
  scene.add(ground);
  const glow = new THREE11.Mesh(new THREE11.PlaneGeometry(2.4, 2.4), materials.glow);
  glow.rotation.x = -Math.PI / 2;
  glow.position.y = GROUND_Y + 2e-3;
  scene.add(glow);
  const caustic = new THREE11.Mesh(new THREE11.PlaneGeometry(2, 2), materials.caustic);
  caustic.rotation.x = -Math.PI / 2;
  caustic.position.y = GROUND_Y + 4e-3;
  scene.add(caustic);
  const sparkleGeo = new THREE11.PlaneGeometry(1, 1);
  for (const [x, y, z, s] of [[-1.55, 0.75, 0.6, 0.05], [1.5, -0.15, 0.9, 0.035], [-1.15, -0.85, 1.1, 0.03]]) {
    const spark = new THREE11.Mesh(sparkleGeo, materials.sparkle);
    spark.position.set(x, y, z);
    spark.scale.setScalar(s);
    spark.rotation.z = Math.PI / 4;
    scene.add(spark);
  }
  addLights(scene, p);
  const pupils = [face.getObjectByName("pupilL"), face.getObjectByName("pupilR")];
  const eyelids = [face.getObjectByName("eyelidL"), face.getObjectByName("eyelidR")];
  const eyeBase = pupils.map((p2) => p2.position.clone());
  const tassel = hat.getObjectByName("tassel");
  const state = {
    blinkAt: performance.now() + 2400 + Math.random() * 2e3,
    blinkPhase: 0,
    jiggle: 0
  };
  function impulse() {
    state.jiggle = 1;
  }
  function animate(t, nowMs, pointer, reducedMotion) {
    if (reducedMotion) return;
    const breathe = Math.sin(t * 1.1) * 0.016;
    mascot.scale.set(1 - breathe * 0.6, 1 + breathe, 1 - breathe * 0.6);
    state.jiggle *= 0.92;
    jellyMotion.uTime.value = t;
    jellyMotion.uJiggle.value = 0.07 + state.jiggle * 0.85;
    if (tassel) {
      tassel.rotation.z = Math.sin(t * 1.6) * 0.05;
      tassel.rotation.x = Math.cos(t * 1.3) * 0.03;
    }
    if (nowMs > state.blinkAt && state.blinkPhase === 0) state.blinkPhase = 1e-4;
    if (state.blinkPhase > 0) {
      state.blinkPhase += 0.09;
      const s = state.blinkPhase < 1 ? Math.sin(state.blinkPhase * Math.PI) : 0;
      for (const lid of eyelids) if (lid) lid.scale.y = 0.02 + s * 1.05;
      if (state.blinkPhase >= 1) {
        state.blinkPhase = 0;
        state.blinkAt = nowMs + 3600 + Math.random() * 2400;
      }
    }
    pupils.forEach((p2, i) => {
      if (!p2) return;
      const base = eyeBase[i];
      const tx = base.x + pointer.x;
      const ty = base.y + pointer.y;
      p2.position.x += (tx - p2.position.x) * 0.15;
      p2.position.y += (ty - p2.position.y) * 0.15;
    });
  }
  return { scene, mascot, materials, animate, impulse };
}

// src/palette.js
var hex2rgb = (h) => {
  const s = h.replace("#", "");
  return [0, 2, 4].map((i) => parseInt(s.slice(i, i + 2), 16) / 255);
};
var rgb2hex = (r, g, b) => `#${[r, g, b].map((v) => Math.round(Math.max(0, Math.min(1, v)) * 255).toString(16).padStart(2, "0")).join("")}`;
function rgb2hsl(r, g, b) {
  const mx = Math.max(r, g, b);
  const mn = Math.min(r, g, b);
  const d = mx - mn;
  let h = 0;
  const l = (mx + mn) / 2;
  const s = d === 0 ? 0 : d / (1 - Math.abs(2 * l - 1));
  if (d) {
    if (mx === r) h = (g - b) / d % 6;
    else if (mx === g) h = (b - r) / d + 2;
    else h = (r - g) / d + 4;
    h *= 60;
    if (h < 0) h += 360;
  }
  return [h, s, l];
}
function hsl2rgb(h, s, l) {
  const c = (1 - Math.abs(2 * l - 1)) * s;
  const x = c * (1 - Math.abs(h / 60 % 2 - 1));
  const m = l - c / 2;
  const t = h < 60 ? [c, x, 0] : h < 120 ? [x, c, 0] : h < 180 ? [0, c, x] : h < 240 ? [0, x, c] : h < 300 ? [x, 0, c] : [c, 0, x];
  return t.map((v) => v + m);
}
var BASE_RAMP = { deep: "#0D4A02", bottle: "#297F04", neon: "#5AB60D", olive: "#99E72A", pale: "#C8DDA6" };
var SPREAD = { deep: -0.34, bottle: -0.18, neon: 0, olive: 0.18, pale: 0.42 };
var HEX6 = /^#[0-9a-fA-F]{6}$/;
function retint(rampHex, hue, satTarget) {
  const [, s0, l0] = rgb2hsl(...hex2rgb(rampHex));
  const s = Math.min(1, Math.max(0.3, s0 * satTarget));
  const l = Math.max(0.04, Math.min(0.94, l0));
  return rgb2hex(...hsl2rgb((hue % 360 + 360) % 360, s, l));
}
function tintPalette(accentHex) {
  const accent = HEX6.test(accentHex || "") ? accentHex : BASE_RAMP.olive;
  const [h0, s0] = rgb2hsl(...hex2rgb(accent));
  const satTarget = 0.55 + s0 * 0.55;
  const drift = (40 - h0 + 540) % 360 - 180;
  const spreadDeg = (Math.sign(drift) || 1) * Math.min(70, Math.max(26, Math.abs(drift)));
  const out = {};
  for (const k of Object.keys(BASE_RAMP)) out[k] = retint(BASE_RAMP[k], h0 + spreadDeg * SPREAD[k], satTarget);
  return {
    bg: "#050706",
    ink: "#0A0C0A",
    inkSoft: "#2A2E24",
    eye: "#F4FAEA",
    gold: "#D9A521",
    softOlive: retint("#848D68", h0 + spreadDeg * 0.08, Math.max(0.4, satTarget * 0.6)),
    ...out
  };
}

// src/embed.js
function hasWebGL2() {
  try {
    return !!document.createElement("canvas").getContext("webgl2");
  } catch {
    return false;
  }
}
function disposeMaterial(m) {
  for (const k of ["map", "normalMap", "roughnessMap", "metalnessMap", "emissiveMap", "sheenColorMap"]) if (m[k]) m[k].dispose();
  m.dispose();
}
function disposeScene(scene) {
  scene.traverse((obj) => {
    if (obj.geometry) obj.geometry.dispose();
    if (obj.material) (Array.isArray(obj.material) ? obj.material : [obj.material]).forEach(disposeMaterial);
  });
  if (scene.environment) scene.environment.dispose();
}
function mount(el, opts = {}) {
  if (!el || !hasWebGL2()) return null;
  const reducedMotion = opts.reducedMotion ?? matchMedia("(prefers-reduced-motion: reduce)").matches;
  const coarse = matchMedia("(pointer: coarse)").matches;
  const canvas = document.createElement("canvas");
  canvas.setAttribute("aria-hidden", "true");
  canvas.style.cssText = "display:block;width:100%;height:100%;";
  el.appendChild(canvas);
  const renderer = new THREE12.WebGLRenderer({ canvas, antialias: false, alpha: true, powerPreference: "low-power" });
  renderer.toneMapping = THREE12.NoToneMapping;
  renderer.outputColorSpace = THREE12.LinearSRGBColorSpace;
  renderer.shadowMap.enabled = true;
  renderer.shadowMap.type = THREE12.PCFSoftShadowMap;
  const palette = tintPalette(opts.accent);
  const { scene, animate } = buildScene(renderer, palette);
  scene.background = null;
  const CAM_DIST = 8;
  const camera = new THREE12.PerspectiveCamera(26, 1, 0.1, 40);
  camera.position.set(0, 0.3, CAM_DIST);
  camera.lookAt(0, -0.05, 0);
  let tier = coarse ? "low" : opts.quality && opts.quality !== "auto" ? opts.quality : initialTier(coarse, Math.min(innerWidth, innerHeight));
  const post = new Post(renderer, QUALITY[tier]);
  const governor = createGovernor();
  function resize() {
    const w = el.clientWidth || 1;
    const h = el.clientHeight || 1;
    camera.aspect = w / h;
    camera.updateProjectionMatrix();
    const dpr = Math.min(devicePixelRatio || 1, QUALITY[tier].maxDPR, coarse ? 1.5 : 2);
    renderer.setPixelRatio(dpr);
    const outW = Math.round(w * dpr);
    const outH = Math.round(h * dpr);
    const inW = Math.max(2, Math.round(outW * governor.scale));
    const inH = Math.max(2, Math.round(outH * governor.scale));
    renderer.setSize(w, h, false);
    post.setSize(inW, inH, outW, outH);
  }
  const ro = new ResizeObserver(resize);
  ro.observe(el);
  resize();
  const pointer = new THREE12.Vector2(0, 0);
  const onMove = (e) => {
    const nx = e.clientX / innerWidth * 2 - 1;
    const ny = e.clientY / innerHeight * 2 - 1;
    pointer.set(nx * 0.05, -ny * 0.035);
  };
  if (!reducedMotion) window.addEventListener("mousemove", onMove, { passive: true });
  let visible = document.visibilityState === "visible";
  let req = 0;
  const onVis = () => {
    visible = document.visibilityState === "visible";
    if (visible && !reducedMotion && !req) req = requestAnimationFrame(loop);
  };
  document.addEventListener("visibilitychange", onVis);
  let last = performance.now();
  let slowStreak = 0;
  let lowFpsFired = false;
  const params = { focus: CAM_DIST, coc: 3.2, maxBlur: 5, bloom: 0.34, exposure: 1.6, grain: 0.03, ao: 0.6, streak: 0, time: 0 };
  function renderOnce() {
    post.render(scene, camera, params);
  }
  function loop(nowMs) {
    req = 0;
    if (!visible) return;
    const dt = nowMs - last;
    last = nowMs;
    if (governor.sample(dt, nowMs)) resize();
    if (tier === "low" && governor.scale <= 0.51 && dt > 33.3) slowStreak++;
    else slowStreak = Math.max(0, slowStreak - 1);
    if (!lowFpsFired && slowStreak > 90) {
      lowFpsFired = true;
      opts.onLowFps?.();
    }
    animate(nowMs / 1e3, nowMs, pointer, false);
    params.time = nowMs / 1e3;
    post.render(scene, camera, params);
    req = requestAnimationFrame(loop);
  }
  if (reducedMotion) renderOnce();
  else req = requestAnimationFrame(loop);
  function dispose() {
    cancelAnimationFrame(req);
    req = 0;
    ro.disconnect();
    document.removeEventListener("visibilitychange", onVis);
    window.removeEventListener("mousemove", onMove);
    disposeScene(scene);
    post.dispose();
    renderer.dispose();
    renderer.forceContextLoss();
    canvas.remove();
  }
  return { dispose };
}
export {
  hasWebGL2,
  mount
};
