// backend/src/utils/archive.js

/**
 * Generate a self-contained HTML transcript for a ticket.
 * All styling is inline so the archive is viewable without external resources.
 */
export function generateHtmlTranscript(ticket) {
  const messages = ticket.messages || [];
  const createdAt = new Date(ticket.createdAt).toLocaleString("en-US");
  const closedAt = ticket.closedAt ? new Date(ticket.closedAt).toLocaleString("en-US") : "N/A";

  const messagesHtml = messages.length === 0
    ? '<p style="color:#999;text-align:center;padding:20px;">No messages recorded.</p>'
    : messages.map((msg) => {
        const time = new Date(msg.createdAt).toLocaleString("en-US");
        const avatarLetter = (msg.authorTag || "?")[0].toUpperCase();
        const attachmentsHtml = msg.attachments?.length
          ? msg.attachments.map((url) =>
              `<a href="${esc(url)}" target="_blank" style="display:block;color:#00b0f4;font-size:12px;margin-top:4px;">${esc(url)}</a>`
            ).join("")
          : "";

        return `
          <div style="display:flex;gap:12px;padding:10px 0;border-bottom:1px solid #2f3136;">
            <div style="width:38px;height:38px;border-radius:50%;background:#5865f2;display:flex;align-items:center;justify-content:center;font-weight:700;font-size:16px;color:white;flex-shrink:0;">${avatarLetter}</div>
            <div style="flex:1;">
              <div style="display:flex;align-items:baseline;gap:8px;margin-bottom:4px;">
                <span style="font-weight:600;color:#e3e5e8;">${esc(msg.authorTag)}</span>
                <span style="font-size:11px;color:#72767d;">${time}</span>
              </div>
              <div style="color:#dcddde;white-space:pre-wrap;word-break:break-word;">${esc(msg.content)}</div>
              ${attachmentsHtml}
            </div>
          </div>`;
      }).join("");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Ticket Archive — ${esc(ticket.id)}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'Whitney', 'Helvetica Neue', Helvetica, Arial, sans-serif; background: #36393f; color: #dcddde; min-height: 100vh; }
    a { color: #00b0f4; }
  </style>
</head>
<body>
  <div style="max-width:800px;margin:0 auto;padding:20px;">
    <!-- Header -->
    <div style="background:#2f3136;border-radius:8px;padding:24px;margin-bottom:16px;">
      <div style="display:flex;align-items:center;gap:12px;margin-bottom:16px;">
        <div style="width:48px;height:48px;background:#5865f2;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:24px;">🎫</div>
        <div>
          <h1 style="font-size:20px;font-weight:700;color:white;">Ticket Archive</h1>
          <p style="font-size:13px;color:#72767d;">ID: ${esc(ticket.id)}</p>
        </div>
      </div>
      <div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:12px;">
        ${metaCard("🕐 Opened", createdAt)}
        ${metaCard("🔒 Closed", closedAt)}
        ${metaCard("👤 Creator", ticket.creator?.username || "Unknown")}
        ${metaCard("🛡️ Assigned To", ticket.assignee?.username || "Unassigned")}
        ${ticket.closeReason ? metaCard("📝 Close Reason", ticket.closeReason) : ""}
      </div>
    </div>

    ${ticket.application ? applicationSection(ticket.application) : ""}

    <!-- Messages -->
    <div style="background:#2f3136;border-radius:8px;padding:24px;">
      <h2 style="font-size:16px;font-weight:600;color:white;margin-bottom:16px;">💬 Messages (${messages.length})</h2>
      ${messagesHtml}
    </div>

    <p style="text-align:center;font-size:11px;color:#72767d;margin-top:16px;">
      Generated by Discord SaaS Bot Platform &bull; ${new Date().toLocaleString("en-US")}
    </p>
  </div>
</body>
</html>`;
}

function metaCard(label, value) {
  return `<div style="background:#36393f;border-radius:6px;padding:10px;">
    <p style="font-size:11px;color:#72767d;margin-bottom:4px;">${label}</p>
    <p style="font-size:13px;color:#e3e5e8;word-break:break-word;">${esc(String(value))}</p>
  </div>`;
}

function applicationSection(application) {
  const answers = application.answers || {};
  const questions = application.form?.questions || [];

  const qaHtml = questions.map((q) => {
    const answer = answers[q.id] || "*No answer provided*";
    return `<div style="margin-bottom:14px;">
      <p style="font-size:12px;font-weight:600;color:#72767d;text-transform:uppercase;letter-spacing:0.5px;margin-bottom:4px;">${esc(q.label)}</p>
      <p style="color:#dcddde;white-space:pre-wrap;">${esc(String(answer))}</p>
    </div>`;
  }).join("");

  return `<div style="background:#2f3136;border-radius:8px;padding:24px;margin-bottom:16px;">
    <h2 style="font-size:16px;font-weight:600;color:white;margin-bottom:16px;">📋 Application Transcript</h2>
    ${qaHtml || '<p style="color:#72767d;">No questions found.</p>'}
  </div>`;
}

function esc(str) {
  return String(str)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}
