// Четвърта партида „мокъп" екрани: интернет/имейл, карти, всекидневие, пари,
// забавление и снимки. Стартиране (от zabobovdol/):
//   node scripts/howto-mockups/gen-4.js
const { phone, I, av, tip, navTitle, setRow, toggle, render } = require("./_shell");

const S = {};

// Браузър с адресна лента.
function browser(url, body, opts = {}) {
  const star = opts.star ? `<span class="ring ringr" style="color:#f5c518;padding:2px">★</span>` : `<span style="color:#888">★</span>`;
  return `<div style="background:#f1f3f4;padding:9px 10px;display:flex;align-items:center;gap:8px;border-bottom:1px solid #ddd">
    ${opts.secure?`<span style="color:#0a7d2c">${I.lock}</span>`:''}
    <div style="flex:1;background:#fff;border-radius:20px;padding:8px 14px;color:#111;font-size:14px;display:flex;align-items:center;gap:8px">${url}</div>
    ${star}<span style="color:#888">⋮</span></div>${body}`;
}
const gmailHdr = (title) => `<div style="background:#fff;padding:11px 14px;display:flex;align-items:center;gap:12px;border-bottom:1px solid #eee"><span>${I.back}</span><div style="flex:1;font-weight:700;font-size:16px;color:#111">${title}</div></div>`;

// ═══ ИНТЕРНЕТ / БРАУЗЪР ═══
S["bookmark-add"] = browser(`bobovdol.bg`, `<div class="grow" style="background:#fff;padding:20px"><div style="height:90px;border-radius:10px;background:linear-gradient(135deg,#dbeafe,#93c5fd);margin-bottom:14px"></div><div style="color:#444;font-size:14px">Любимият Ви сайт. Натиснете звездичката горе, за да го запазите.</div></div>`, { star: true }) + tip("Натиснете звездичката ★ —<br>сайтът се запазва в любими","right:30px;top:54px");

S["bookmarks-list"] = navTitle("#fff","#111","Отметки (любими)") + `<div class="grow" style="background:#fff">${[["⭐","Бобов дол — портал","bobovdol.bg",1],["🏥","Здравно досие","his.bg",0],["📰","Новини","news.bg",0]].map(([e,t,u,h])=>`<div class="${h?'ring':''}" style="display:flex;align-items:center;gap:14px;padding:14px 16px;border-bottom:1px solid #f3f3f3;${h?'border-radius:10px;margin:4px 8px;':''}"><span style="font-size:20px">${e}</span><div style="flex:1"><div style="font-size:15px;color:#111;font-weight:600">${t}</div><div style="font-size:12px;color:#888">${u}</div></div></div>`).join("")}</div>` + tip("Натиснете ⋮ → „Отметки“ и изберете<br>запазен сайт от списъка","left:50%;top:120px;transform:translateX(-50%)");

S["new-tab"] = navTitle("#333","#fff","Раздели (табове)") + `<div class="grow" style="background:#e5e7eb;padding:14px"><div style="display:grid;grid-template-columns:1fr 1fr;gap:12px">${[["bobovdol.bg","#dbeafe"],["news.bg","#fde68a"]].map(([u,c])=>`<div style="background:#fff;border-radius:12px;overflow:hidden;box-shadow:0 2px 6px rgba(0,0,0,.1)"><div style="height:80px;background:${c}"></div><div style="padding:8px;font-size:12px;color:#111;display:flex;justify-content:space-between">${u}<span>✕</span></div></div>`).join("")}</div></div><div style="background:#333;padding:14px;display:flex;justify-content:center"><div class="ring ringr" style="width:50px;height:50px;border-radius:50%;background:#fff;color:#333;display:flex;align-items:center;justify-content:center;font-size:28px">+</div></div>` + tip("Натиснете „+“, за да отворите<br>нов празен раздел","left:50%;bottom:130px;transform:translateX(-50%)");

S["close-tab"] = navTitle("#333","#fff","Раздели (табове)") + `<div class="grow" style="background:#e5e7eb;padding:14px"><div style="display:grid;grid-template-columns:1fr 1fr;gap:12px">${[["bobovdol.bg","#dbeafe",1],["реклама","#fecaca",0]].map(([u,c,first])=>`<div style="background:#fff;border-radius:12px;overflow:hidden;box-shadow:0 2px 6px rgba(0,0,0,.1)"><div style="height:80px;background:${c}"></div><div style="padding:8px;font-size:12px;color:#111;display:flex;justify-content:space-between">${u}<span class="${first?'':'ring ringr'}" style="${first?'':'border-radius:50%;padding:0 4px;background:#ef4444;color:#fff;'}">✕</span></div></div>`).join("")}</div></div>` + tip("Натиснете хиксчето ✕ на раздела,<br>за да го затворите","right:20px;top:170px");

S["refresh"] = browser(`<span style="flex:1">bobovdol.bg</span><span class="ring ringr" style="color:#1877f2;padding:2px;font-size:18px">↻</span>`, `<div class="grow" style="background:#fff;display:flex;align-items:center;justify-content:center;color:#bbb;flex-direction:column"><div style="font-size:40px">↻</div><div style="font-size:14px;margin-top:8px">страницата се зарежда наново</div></div>`) + tip("Натиснете кръгчето-стрелка ↻,<br>за да заредите страницата наново","right:20px;top:54px");

S["zoom-page"] = browser(`bobovdol.bg`, `<div class="grow" style="background:#fff;padding:20px"><div style="font-size:26px;color:#111;line-height:1.4;font-weight:600">Така текстът става по-голям и четим.</div><div class="ring ringr" style="position:absolute;left:40%;top:55%;width:90px;height:90px;border-radius:50%;border:3px dashed #1877f2"></div></div>`) + tip("Допрете с два пръста и ги раздалечете,<br>за да уголемите текста","left:50%;bottom:140px;transform:translateX(-50%)");

S["translate-page"] = browser(`example.com`, `<div class="grow" style="background:#fff"><div class="ring" style="background:#e8f0fe;padding:12px 16px;display:flex;align-items:center;gap:10px;border-radius:0"><span style="font-size:20px">🌐</span><div style="flex:1;font-size:14px;color:#1a73e8;font-weight:600">Преведи тази страница на български?</div><div style="background:#1a73e8;color:#fff;padding:6px 14px;border-radius:16px;font-size:13px;font-weight:700">Преведи</div></div><div style="padding:20px;color:#999;font-size:14px">This is a page in English...</div></div>`) + tip("Натиснете „Преведи“ в синята лента —<br>страницата става на български","left:50%;top:62px;transform:translateX(-50%)");

S["save-image"] = browser(`bobovdol.bg`, `<div class="grow" style="background:#fff;padding:18px;position:relative"><div style="height:200px;border-radius:12px;background:linear-gradient(135deg,#fcd34d,#f59e0b);box-shadow:0 0 0 3px #1877f2"></div><div style="position:absolute;left:40px;top:120px;background:#fff;border-radius:12px;box-shadow:0 8px 24px rgba(0,0,0,.25);overflow:hidden;width:230px">${["Отвори в нов раздел","Запази изображението","Сподели"].map((t,i)=>`<div class="${i===1?'ring':''}" style="padding:13px 16px;font-size:14px;color:${i===1?'#1877f2':'#111'};font-weight:${i===1?700:400};border-bottom:1px solid #f3f3f3;${i===1?'border-radius:8px;':''}">${t}</div>`).join("")}</div></div>`) + tip("Задръжте пръст върху снимката →<br>„Запази изображението“","left:50%;top:54px;transform:translateX(-50%)");

S["clear-history"] = navTitle("#fff","#111","Изчистване на данни") + `<div class="grow" style="background:#fff">${setRow("🕘","История на сърфирането", toggle(true), true)}${setRow("🍪","Бисквитки", toggle(true))}${setRow("🖼️","Кеш (временни файлове)", toggle(true))}<div style="padding:16px"><div class="ring" style="background:#1877f2;color:#fff;padding:13px;border-radius:10px;text-align:center;font-weight:700;border-radius:10px">Изчисти данните</div></div></div>` + tip("Изберете „История“ → натиснете<br>„Изчисти данните“","left:50%;bottom:120px;transform:translateX(-50%)");

S["downloads"] = navTitle("#fff","#111","Изтегляния") + `<div class="grow" style="background:#fff">${[["🖼️","snimka.jpg","днес • 1,2 MB"],["📄","smetka.pdf","днес • 240 KB"],["🎵","pesen.mp3","вчера • 3,4 MB"]].map(([e,n,d])=>`<div style="display:flex;align-items:center;gap:14px;padding:14px 16px;border-bottom:1px solid #f3f3f3"><span style="font-size:24px">${e}</span><div style="flex:1"><div style="font-size:15px;color:#111">${n}</div><div style="font-size:12px;color:#888">${d}</div></div></div>`).join("")}</div>` + tip("Менюто ⋮ → „Изтегляния“ показва<br>свалените файлове и снимки","left:50%;top:120px;transform:translateX(-50%)");

// ═══ ИМЕЙЛ (Gmail) ═══
S["mail-delete"] = gmailHdr("") + `<div style="background:#fff;padding:11px 14px;display:flex;gap:22px;justify-content:flex-end;border-bottom:1px solid #eee;color:#5f6368"><span class="ring ringr" style="color:#ea4335;padding:3px">${I.trash}</span><span>↩️</span><span>⋮</span></div><div class="grow" style="background:#fff;padding:16px"><div style="font-weight:700;font-size:17px;color:#111">Реклама — намаления</div><div style="font-size:13px;color:#888;margin:6px 0">от: shop@reklama.info</div><div style="font-size:14px;color:#444">Не Ви е нужно това писмо.</div></div>` + tip("Отворете писмото → натиснете<br>кошчето 🗑️ горе","right:20px;top:58px");

S["mail-sent"] = `<div style="background:#fff;padding:11px 14px;display:flex;align-items:center;gap:14px;border-bottom:1px solid #eee"><span style="font-size:20px">☰</span><div style="flex:1;font-weight:700;font-size:16px;color:#111">Изпратени</div></div><div class="grow" style="background:#fff">${[["М","До: Мария","Поздрав от баба","09:10"],["Н","До: НОИ","Молба за справка","вчера"]].map(([i,f,s,t])=>`<div style="display:flex;gap:12px;padding:13px 14px;border-bottom:1px solid #f3f3f3">${av(i,"#34a853",40)}<div style="flex:1"><div style="display:flex;justify-content:space-between"><span style="font-size:15px;color:#111">${f}</span><span style="font-size:12px;color:#888">${t}</span></div><div style="font-size:14px;color:#5f6368">${s}</div></div></div>`).join("")}</div>` + tip("Менюто ☰ → „Изпратени“ показва<br>писмата, които Вие сте пратили","left:50%;top:120px;transform:translateX(-50%)");

S["mail-search"] = `<div style="background:#fff;padding:11px 14px;display:flex;align-items:center;gap:12px;border-bottom:1px solid #eee"><span>${I.back}</span><div class="ring" style="flex:1;background:#f0f2f5;border-radius:20px;padding:9px 14px;color:#111;font-size:15px;border-radius:20px">аптека</div></div><div class="grow" style="background:#fff">${[["А","Аптека Здраве","Поръчката е готова","пон"]].map(([i,f,s,t])=>`<div style="display:flex;gap:12px;padding:13px 14px;border-bottom:1px solid #f3f3f3">${av(i,"#ea4335",40)}<div style="flex:1"><div style="font-size:15px;color:#111">${f}</div><div style="font-size:14px;color:#5f6368">${s}</div></div></div>`).join("")}</div>` + tip("Натиснете лупата горе и напишете<br>дума от писмото, което търсите","left:50%;top:62px;transform:translateX(-50%)");

S["mail-forward"] = gmailHdr("") + `<div class="grow" style="background:#fff;padding:16px;position:relative"><div style="font-weight:700;font-size:16px;color:#111">Сметка за ток</div><div style="font-size:14px;color:#444;margin-top:8px">Прикачен файл: smetka.pdf</div><div style="position:absolute;right:20px;bottom:20px;background:#fff;border-radius:12px;box-shadow:0 8px 24px rgba(0,0,0,.2);overflow:hidden;width:180px">${["Отговори","Отговори на всички","Препрати"].map((t,i)=>`<div class="${i===2?'ring':''}" style="padding:12px 16px;font-size:14px;color:${i===2?'#1a73e8':'#111'};font-weight:${i===2?700:400};border-bottom:1px solid #f3f3f3;${i===2?'border-radius:8px;':''}">${t}</div>`).join("")}</div></div>` + tip("Натиснете ↩️ / ⋮ → „Препрати“,<br>после въведете кому","right:14px;bottom:150px");

S["mail-add-contact"] = gmailHdr("Нов контакт") + `<div style="background:#fff;padding:20px;text-align:center;border-bottom:8px solid #eef0f2">${av("👤","#cfd8e3",70)}</div><div class="grow" style="background:#fff">${["Име|Иван Петров","Имейл|ivan@abv.bg"].map(r=>{const[l,v]=r.split("|");return `<div style="padding:14px 18px;border-bottom:1px solid #f3f3f3"><div style="font-size:12px;color:#1a73e8">${l}</div><div style="font-size:16px;color:#111;margin-top:2px">${v}</div></div>`}).join("")}<div style="padding:16px"><div class="ring" style="background:#1a73e8;color:#fff;padding:13px;border-radius:10px;text-align:center;font-weight:700;border-radius:10px">Запази контакта</div></div></div>` + tip("Въведете име и имейл →<br>„Запази контакта“","left:50%;bottom:120px;transform:translateX(-50%)");

// ═══ КАРТИ И ВСЕКИДНЕВИЕ ═══
const mapBg = `<div style="position:absolute;inset:0;background:linear-gradient(135deg,#e8f5e9,#c8e6c9)"></div><div style="position:absolute;inset:0;background:repeating-linear-gradient(45deg,transparent,transparent 38px,rgba(255,255,255,.5) 38px,rgba(255,255,255,.5) 40px)"></div>`;
S["my-location"] = `${mapBg}<div style="position:relative;flex:1"></div><div style="position:absolute;left:50%;top:45%;transform:translate(-50%,-50%)"><div style="width:26px;height:26px;border-radius:50%;background:#1a73e8;border:4px solid #fff;box-shadow:0 2px 8px rgba(0,0,0,.3)"></div></div><div style="position:absolute;right:18px;bottom:30px"><div class="ring ringr" style="width:54px;height:54px;border-radius:50%;background:#fff;display:flex;align-items:center;justify-content:center;font-size:24px;box-shadow:0 4px 12px rgba(0,0,0,.2)">📍</div></div>` + tip("Натиснете кръгчето долу вдясно —<br>синята точка показва къде сте","right:14px;bottom:96px");

S["share-location"] = `${mapBg}<div style="position:relative;margin-top:auto;background:#fff;border-radius:18px 18px 0 0;padding:18px"><div style="font-weight:700;font-size:16px;color:#111;margin-bottom:12px">Споделете местоположението си</div><div style="display:flex;gap:16px">${[["🟣","Viber",1],["💬","Съобщ.",0],["📧","Имейл",0]].map(([e,l,h])=>`<div style="text-align:center;font-size:12px;color:#444"><div class="${h?'ring ringr':''}" style="width:54px;height:54px;border-radius:50%;background:#f0f2f5;display:flex;align-items:center;justify-content:center;font-size:24px;margin:0 auto 5px">${e}</div>${l}</div>`).join("")}</div></div>` + tip("„Сподели местоположение“ → изберете<br>как (напр. Viber) → пратете на близък","left:50%;top:90px;transform:translateX(-50%)");

S["transit"] = `${mapBg}<div style="position:relative;padding:12px"><div style="background:#fff;border-radius:14px;padding:12px;box-shadow:0 4px 14px rgba(0,0,0,.12)"><div style="display:flex;gap:10px;margin-bottom:10px">${["🚶","🚌","🚗"].map((e,i)=>`<div class="${i===1?'ring ringr':''}" style="flex:1;text-align:center;padding:8px;border-radius:10px;background:${i===1?'#e8f0fe':'#f5f5f5'};font-size:20px">${e}</div>`).join("")}</div><div style="font-size:14px;color:#111;font-weight:600">Автобус до Дупница</div><div style="font-size:13px;color:#888">тръгва 14:20 • 35 мин</div></div></div>` + tip("Изберете иконата автобус 🚌 —<br>показва разписание и спирки","left:50%;top:90px;transform:translateX(-50%)");

S["notes"] = navTitle("#fff","#111","Бележки") + `<div class="grow" style="background:#fffbea;padding:20px"><div style="font-size:18px;color:#111;line-height:1.8">Купи хляб и мляко<br>Обади се на лекаря<br>Плати тока до петък|</div></div>` + tip("Натиснете „+“ и пишете каквото<br>искате да запомните","left:50%;top:120px;transform:translateX(-50%)");

S["calendar-event"] = navTitle("#1a73e8","#fff","Ново събитие") + `<div class="grow" style="background:#fff">${[["📝","Заглавие","Преглед при лекаря"],["📅","Дата","петък, 27 юни"],["🕐","Час","10:30"],["🔔","Напомняне","1 час преди"]].map(([e,l,v])=>`<div style="display:flex;align-items:center;gap:14px;padding:15px 16px;border-bottom:1px solid #f3f3f3"><span style="font-size:18px">${e}</span><div style="flex:1"><div style="font-size:12px;color:#888">${l}</div><div style="font-size:15px;color:#111">${v}</div></div></div>`).join("")}<div style="padding:16px"><div class="ring" style="background:#1a73e8;color:#fff;padding:13px;border-radius:10px;text-align:center;font-weight:700;border-radius:10px">Запази</div></div></div>` + tip("Попълнете какво и кога →<br>„Запази“. Ще Ви напомни","left:50%;bottom:120px;transform:translateX(-50%)");

S["timer"] = phone(`<div class="grow" style="background:#111;color:#fff;display:flex;flex-direction:column;align-items:center;justify-content:center"><div style="font-size:64px;font-weight:200;font-variant-numeric:tabular-nums">10:00</div><div style="font-size:15px;opacity:.7;margin-top:6px">таймер за готвене</div><div style="display:flex;gap:26px;margin-top:34px"><div style="width:64px;height:64px;border-radius:50%;background:#333;display:flex;align-items:center;justify-content:center;font-size:14px">Отказ</div><div class="ring ringr" style="width:64px;height:64px;border-radius:50%;background:#0a3d2e;color:#34c759;display:flex;align-items:center;justify-content:center;font-size:14px;font-weight:700">Старт</div></div></div>${tip("Задайте минутите → „Старт“.<br>Звъни, когато изтече","left:50%;bottom:120px;transform:translateX(-50%)")}`, "#111", "#fff");

S["stopwatch"] = phone(`<div class="grow" style="background:#111;color:#fff;display:flex;flex-direction:column;align-items:center;justify-content:center"><div style="font-size:60px;font-weight:200;font-variant-numeric:tabular-nums">00:42,8</div><div style="display:flex;gap:26px;margin-top:34px"><div style="width:64px;height:64px;border-radius:50%;background:#333;display:flex;align-items:center;justify-content:center;font-size:14px">Нулирай</div><div class="ring ringr" style="width:64px;height:64px;border-radius:50%;background:#3d0a0a;color:#ff453a;display:flex;align-items:center;justify-content:center;font-size:14px;font-weight:700">Стоп</div></div></div>${tip("„Старт“ започва да мери,<br>„Стоп“ спира хронометъра","left:50%;bottom:120px;transform:translateX(-50%)")}`, "#111", "#fff");

S["translate-word"] = navTitle("#fff","#111","Преводач") + `<div class="grow" style="background:#fff"><div style="padding:16px;border-bottom:1px solid #eee"><div style="font-size:12px;color:#1a73e8;margin-bottom:6px">Английски</div><div style="font-size:20px;color:#111">Good morning</div></div><div style="padding:16px;background:#f0f6ff"><div style="font-size:12px;color:#1a73e8;margin-bottom:6px">Български</div><div style="font-size:20px;color:#111;font-weight:600">Добро утро</div><div class="ring ringr" style="display:inline-block;margin-top:10px;color:#1a73e8;padding:3px">${I.mic}</div></div></div>` + tip("Напишете или кажете думата горе —<br>преводът се появява долу","left:50%;top:120px;transform:translateX(-50%)");

S["ring-phone"] = phone(`<div class="grow" style="background:#eef2ff;display:flex;flex-direction:column;align-items:center;justify-content:center;padding:20px"><div class="ring ringr" style="width:120px;height:120px;border-radius:50%;background:#fff;display:flex;align-items:center;justify-content:center;font-size:54px;box-shadow:0 8px 24px rgba(0,0,0,.1)">🔊📱</div><div style="font-size:17px;font-weight:700;color:#111;margin-top:20px;text-align:center">Телефонът звъни силно,<br>дори да е на тихо</div><div style="font-size:14px;color:#888;margin-top:8px;text-align:center">От компютър отворете „Намери устройството“ и натиснете „Звънни“</div></div>${tip("Натиснете „Звънни“ — телефонът<br>издава звук, за да го намерите","left:50%;bottom:90px;transform:translateX(-50%)")}`, "#eef2ff");

S["night-mode"] = navTitle("#fff","#111","Нощен режим") + `<div class="grow" style="background:#fff">${setRow("🌙","Нощно осветление (топъл екран)", toggle(true), true)}${setRow("🌑","Тъмна тема", toggle(true))}<div style="padding:14px 18px;font-size:13px;color:#888">Вечер екранът става по-топъл и тъмен — по-щадящ за очите.</div></div>` + tip("Включете „Нощно осветление“ —<br>вечер екранът е по-мек за очите","right:10px;top:64px");

S["shopping-list"] = navTitle("#fff","#111","Списък за пазар") + `<div class="grow" style="background:#fff">${[["Хляб",1],["Мляко",1],["Яйца",0],["Домати",0],["Кафе",0]].map(([t,d])=>`<div style="display:flex;align-items:center;gap:14px;padding:14px 18px;border-bottom:1px solid #f3f3f3"><div style="width:24px;height:24px;border-radius:6px;border:2px solid ${d?'#34c759':'#ccc'};background:${d?'#34c759':'#fff'};color:#fff;display:flex;align-items:center;justify-content:center;font-size:14px">${d?'✓':''}</div><div style="font-size:16px;color:${d?'#aaa':'#111'};text-decoration:${d?'line-through':'none'}">${t}</div></div>`).join("")}</div>` + tip("Пишете продуктите един по един.<br>Чукнете кутийката, щом купите","left:50%;top:120px;transform:translateX(-50%)");

// ═══ БЕЗОПАСНОСТ / ПАРИ ═══
S["find-device"] = `${mapBg}<div style="position:absolute;left:46%;top:38%;font-size:34px">📍</div><div style="position:relative;margin-top:auto;background:#fff;border-radius:18px 18px 0 0;padding:18px"><div style="font-weight:700;font-size:16px;color:#111">Моят телефон</div><div style="font-size:13px;color:#888;margin:4px 0 14px">видян: до дома, преди 5 мин</div><div style="display:flex;gap:10px">${[["🔊","Звънни",0],["🔒","Заключи",1],["🗑️","Изтрий",0]].map(([e,l,h])=>`<div class="${h?'ring':''}" style="flex:1;text-align:center;padding:12px 6px;border-radius:12px;background:${h?'#fff4f4':'#f0f2f5'};font-size:13px;color:${h?'#b91c1c':'#111'};${h?'border-radius:12px;font-weight:700;':''}"><div style="font-size:22px;margin-bottom:4px">${e}</div>${l}</div>`).join("")}</div></div>` + tip("От друг телефон/компютър отворете<br>„Намери устройството“ → Звънни/Заключи","left:50%;top:80px;transform:translateX(-50%)");

S["2fa"] = phone(`<div class="grow" style="background:#fff;display:flex;flex-direction:column;align-items:center;justify-content:center;padding:24px"><div style="font-size:46px;margin-bottom:10px">🔐</div><div style="font-size:17px;font-weight:700;color:#111;text-align:center">Въведете кода от SMS</div><div style="font-size:13px;color:#888;margin:6px 0 20px;text-align:center">Пратихме 6-цифрен код на телефона Ви</div><div style="display:flex;gap:8px">${["4","8","2","—","—","—"].map((d,i)=>`<div class="${i===3?'ring':''}" style="width:42px;height:52px;border:2px solid ${i<3?'#1877f2':'#ddd'};border-radius:10px;display:flex;align-items:center;justify-content:center;font-size:24px;color:#111;${i===3?'border-radius:10px;':''}">${d==='—'?'':d}</div>`).join("")}</div><div style="font-size:13px;color:#1877f2;margin-top:18px">Кодът се сменя всеки път — затова е по-сигурно</div></div>${tip("Освен парола, въведете и кода от SMS —<br>двойна защита на профила","left:50%;bottom:80px;transform:translateX(-50%)")}`);

S["fake-prize"] = phone(`<div class="grow" style="background:#fff;display:flex;align-items:center;justify-content:center;padding:20px;position:relative"><div style="background:#fff;border:2px solid #fca5a5;border-radius:18px;padding:24px;text-align:center;box-shadow:0 12px 30px rgba(0,0,0,.15);max-width:280px"><div style="font-size:44px">🎉</div><div style="font-size:20px;font-weight:800;color:#dc2626;margin:8px 0">ПЕЧЕЛИТЕ iPhone!</div><div style="font-size:14px;color:#444;margin-bottom:16px">Вие сте 1 000 000-ят посетител! Въведете картата си, за да получите наградата.</div><div style="background:#dc2626;color:#fff;padding:12px;border-radius:10px;font-weight:700">Вземи наградата</div></div><div class="ring" style="position:absolute;left:30px;bottom:60px;background:#0a3d2e;color:#fff;padding:10px 16px;border-radius:10px;font-weight:700;font-size:14px;border-radius:10px">✕ Затвори — това е измама</div></div>${tip("Никой не подарява телефони онлайн.<br>Затворете и не въвеждайте карта","left:50%;top:60px;transform:translateX(-50%)")}`);

S["bill-barcode"] = phone(`<div class="grow" style="background:#fff;padding:20px"><div style="border:1px solid #ddd;border-radius:14px;padding:18px"><div style="font-weight:700;font-size:16px;color:#111">Сметка за ток</div><div style="display:flex;justify-content:space-between;margin:14px 0;font-size:15px;color:#111"><span>За плащане:</span><b>48,60 лв</b></div><div style="display:flex;justify-content:space-between;font-size:13px;color:#888"><span>Срок:</span><span>30 юни</span></div><div class="ring" style="margin-top:18px;padding:14px;background:#fff;border-radius:8px;text-align:center;border-radius:8px"><div style="font-family:monospace;font-size:34px;letter-spacing:1px;color:#111">▌║▌▌║║▌║▌║▌║║▌</div><div style="font-size:12px;color:#888;margin-top:6px">3800 1234 5678 90</div></div></div><div style="text-align:center;font-size:13px;color:#888;margin-top:14px">Покажете баркода на касата (EasyPay, поща, банка)</div></div>${tip("Покажете този баркод на касата —<br>касиерът сканира и плащате","left:50%;top:70px;transform:translateX(-50%)")}`);

S["bank-balance"] = phone(`${navTitle("#0a3d6b","#fff","Моята банка")}<div class="grow" style="background:#fff;padding:18px"><div style="background:linear-gradient(135deg,#0a3d6b,#1565c0);color:#fff;border-radius:16px;padding:20px"><div style="font-size:13px;opacity:.8">Разплащателна сметка</div><div class="ring" style="font-size:30px;font-weight:800;margin:6px 0;border-radius:8px;display:inline-block">1 248,30 лв</div><div style="font-size:12px;opacity:.8;font-family:monospace">BG•• •••• •••• 4521</div></div><div style="margin-top:16px">${[["⬆️","Превод",""],["📊","Движения",""],["💳","Моите карти",""]].map(([e,l])=>`<div style="display:flex;align-items:center;gap:14px;padding:14px 4px;border-bottom:1px solid #f0f0f0;font-size:15px;color:#111"><span style="font-size:18px">${e}</span><span style="flex:1">${l}</span><span style="color:#888">›</span></div>`).join("")}</div></div>${tip("След вход с код виждате баланса.<br>Никога не казвайте кода на друг","left:50%;top:150px;transform:translateX(-50%)")}`);

S["bank-transfer"] = phone(`${navTitle("#0a3d6b","#fff","Превод")}<div class="grow" style="background:#fff">${[["Получател","Мария Петрова"],["IBAN","BG•• •••• •••• 7788"],["Сума","100,00 лв"],["Основание","за подарък"]].map(([l,v])=>`<div style="padding:14px 18px;border-bottom:1px solid #f3f3f3"><div style="font-size:12px;color:#0a3d6b">${l}</div><div style="font-size:16px;color:#111;margin-top:2px">${v}</div></div>`).join("")}<div style="padding:16px"><div class="ring" style="background:#0a3d6b;color:#fff;padding:14px;border-radius:10px;text-align:center;font-weight:700;border-radius:10px">Потвърди превода</div></div><div style="padding:0 18px;font-size:12px;color:#b91c1c">Проверете два пъти IBAN и сумата.</div></div>${tip("Въведете IBAN и сума → проверете →<br>„Потвърди“ (често с код по SMS)","left:50%;bottom:130px;transform:translateX(-50%)")}`);

// ═══ ПАЗАРУВАНЕ / ЗАБАВЛЕНИЕ ═══
S["return-item"] = phone(`${navTitle("#fff","#111","Моята поръчка")}<div class="grow" style="background:#fff;padding:16px"><div style="display:flex;gap:14px;border-bottom:1px solid #eee;padding-bottom:14px"><div style="width:70px;height:70px;border-radius:10px;background:linear-gradient(135deg,#fcd34d,#f59e0b)"></div><div><div style="font-weight:700;color:#111">Зимни чехли</div><div style="font-size:13px;color:#888">29,90 лв • доставено</div></div></div><div class="ring" style="margin-top:18px;border:1px solid #ddd;color:#111;padding:13px;border-radius:10px;text-align:center;font-weight:700;border-radius:10px">↩ Върни стоката</div><div style="font-size:13px;color:#888;margin-top:12px;text-align:center">Имате право да върнете до 14 дни.</div></div>${tip("Отворете поръчката → „Върни стоката“<br>→ изберете причина","left:50%;bottom:140px;transform:translateX(-50%)")}`);

S["compare-prices"] = phone(`${navTitle("#fff","#111","Сравнение на цени")}<div class="grow" style="background:#fff;padding:14px"><div style="font-weight:700;color:#111;margin-bottom:12px">Кафемашина „Делукс“</div>${[["Магазин А","119 лв",1],["Магазин Б","135 лв",0],["Магазин В","129 лв",0]].map(([n,p,h])=>`<div class="${h?'ring':''}" style="display:flex;justify-content:space-between;align-items:center;padding:14px;border:1px solid #eee;border-radius:12px;margin-bottom:10px;${h?'border-radius:12px;':''}"><span style="font-size:15px;color:#111">${n}</span><span style="font-weight:800;color:${h?'#16a34a':'#111'};font-size:17px">${p}</span></div>`).join("")}</div>${tip("Един и същ продукт в няколко магазина —<br>зеленото е най-евтино","left:50%;top:130px;transform:translateX(-50%)")}`);

S["receipt-warranty"] = phone(`${navTitle("#fff","#111","Гаранция")}<div class="grow" style="background:#fff;display:flex;flex-direction:column;align-items:center;justify-content:center;padding:20px"><div class="ring" style="background:#fff;border:1px dashed #bbb;border-radius:10px;padding:18px;width:220px;text-align:center;font-family:monospace;font-size:13px;color:#333;box-shadow:0 6px 18px rgba(0,0,0,.1);border-radius:10px">МАГАЗИН ТЕХНО<br>───────────<br>Кафемашина 119,00<br>ДДС 19,83<br>───────────<br>ОБЩО 119,00 лв<br>20.06.2026<br>▌║▌║▌▌║▌║</div><div style="font-size:14px;color:#444;margin-top:16px;text-align:center">Снимайте бележката и я пазете —<br>трябва при гаранция</div></div>${tip("Снимайте касовата бележка веднага —<br>тя е гаранцията Ви","left:50%;top:70px;transform:translateX(-50%)")}`);

const player = (title, sub, color, emoji) => phone(`<div class="grow" style="background:linear-gradient(160deg,${color});color:#fff;display:flex;flex-direction:column;align-items:center;justify-content:center;padding:20px"><div style="width:180px;height:180px;border-radius:18px;background:rgba(255,255,255,.18);display:flex;align-items:center;justify-content:center;font-size:70px">${emoji}</div><div style="font-size:19px;font-weight:700;margin-top:18px;text-align:center">${title}</div><div style="font-size:14px;opacity:.8;margin-top:4px">${sub}</div><div style="display:flex;align-items:center;gap:26px;margin-top:24px;font-size:26px">⏮️<div class="ring ringr" style="width:66px;height:66px;border-radius:50%;background:#fff;color:#000;display:flex;align-items:center;justify-content:center">${I.play}</div>⏭️</div></div>${tip("Натиснете големия бутон ▶,<br>за да пуснете","left:50%;bottom:110px;transform:translateX(-50%)")}`, "#222", "#fff");
S["radio"] = player("Радио Фокус", "на живо • FM", "#7e22ce,#4c1d95", "📻");
S["audiobook"] = player("Под игото — аудиокнига", "глава 3 • 42 мин", "#0f766e,#134e4a", "🎧");

S["tv-online"] = phone(`<div style="background:#000;height:210px;display:flex;align-items:center;justify-content:center;position:relative"><div style="color:#fff;font-size:50px">📺</div><div style="position:absolute;top:10px;left:12px;background:#dc2626;color:#fff;font-size:11px;padding:2px 8px;border-radius:4px;font-weight:700">НА ЖИВО</div><div class="ring ringr" style="position:absolute;width:60px;height:60px;border-radius:50%;background:rgba(255,255,255,.9);display:flex;align-items:center;justify-content:center;color:#000">${I.play}</div></div><div class="grow" style="background:#fff;padding:14px">${[["БНТ 1","Новини",1],["bTV","Сериал",0],["Nova","Филм",0]].map(([n,s,h])=>`<div class="${h?'ring':''}" style="display:flex;align-items:center;gap:12px;padding:12px;border-bottom:1px solid #f3f3f3;${h?'border-radius:10px;margin:2px 6px;':''}"><div style="width:46px;height:32px;border-radius:6px;background:#1e3a8a;color:#fff;display:flex;align-items:center;justify-content:center;font-size:11px;font-weight:700">TV</div><div style="flex:1"><div style="font-size:15px;color:#111;font-weight:600">${n}</div><div style="font-size:12px;color:#888">${s}</div></div></div>`).join("")}</div>${tip("Изберете телевизия от списъка →<br>натиснете ▶, за да гледате","left:50%;top:150px;transform:translateX(-50%)")}`);

S["recipes"] = phone(`${navTitle("#e67e22","#fff","Рецепти")}<div class="grow" style="background:#fff">${[["🥘","Боб яхния","45 мин • лесно",1],["🍲","Супа топчета","60 мин"],["🥗","Шопска салата","15 мин"]].map(([e,n,d,h])=>`<div class="${h?'ring':''}" style="display:flex;align-items:center;gap:14px;padding:14px 16px;border-bottom:1px solid #f3f3f3;${h?'border-radius:10px;margin:4px 8px;':''}"><div style="width:56px;height:56px;border-radius:12px;background:linear-gradient(135deg,#fde68a,#f59e0b);display:flex;align-items:center;justify-content:center;font-size:28px">${e}</div><div style="flex:1"><div style="font-size:15px;font-weight:700;color:#111">${n}</div><div style="font-size:12px;color:#888">${d}</div></div></div>`).join("")}</div>${tip("Напишете ястие в търсачката или<br>изберете рецепта от списъка","left:50%;top:120px;transform:translateX(-50%)")}`);

S["solitaire"] = phone(`<div class="grow" style="background:linear-gradient(160deg,#15803d,#14532d);padding:18px"><div style="display:flex;justify-content:space-between;margin-bottom:20px">${["🂠","🂠","🂠","🂠"].map(()=>`<div style="width:48px;height:66px;border-radius:8px;background:#fff;border:1px solid #ccc;display:flex;align-items:center;justify-content:center;color:#1e3a8a;font-size:13px">🂠</div>`).join("")}</div><div style="display:flex;justify-content:space-between">${["♠ A","♥ 5","♣ 9","♦ K","♠ 7"].map((c,i)=>`<div class="${i===1?'ring':''}" style="width:48px;height:70px;border-radius:8px;background:#fff;display:flex;align-items:center;justify-content:center;color:${i%2?'#dc2626':'#111'};font-size:16px;font-weight:700;${i===1?'border-radius:8px;':''}">${c}</div>`).join("")}</div></div>${tip("Местете картите с пръст по<br>правилата — за разтуха","left:50%;bottom:120px;transform:translateX(-50%)")}`, "#14532d", "#fff");

S["ebook"] = phone(`<div class="grow" style="background:#f5ecd7;padding:24px 22px;color:#3b2f1e"><div style="font-size:13px;color:#9a8a6a;text-align:center;margin-bottom:16px">Под игото — стр. 24</div><div style="font-size:18px;line-height:1.8">Тоз, който падне в бой за свобода, той не умира... Думите отекнаха в тихата стая и всички притихнаха развълнувани.</div></div><div style="background:#efe4c8;padding:14px;display:flex;justify-content:space-around;color:#7a6a4a;font-size:13px"><span class="ring" style="border-radius:6px;padding:4px 8px">Аа размер</span><span>🔖 Отметка</span><span>🌙 Нощем</span></div>${tip("Чукнете вдясно за следваща страница.<br>„Аа“ уголемява буквите","left:30px;bottom:90px")}`, "#f5ecd7");

S["movies"] = phone(`<div style="background:#000;height:200px;display:flex;align-items:center;justify-content:center;position:relative"><div style="color:#fff;font-size:46px">🎬</div><div class="ring ringr" style="position:absolute;width:60px;height:60px;border-radius:50%;background:rgba(255,255,255,.9);display:flex;align-items:center;justify-content:center;color:#000">${I.play}</div></div><div class="grow" style="background:#111;color:#fff;padding:14px"><div style="font-weight:700;font-size:16px">Българско кино — класика</div><div style="font-size:13px;opacity:.7;margin-top:4px">безплатно • с реклами</div><div style="display:flex;gap:10px;margin-top:14px;overflow:hidden">${["🎞️","🎭","📽️"].map(e=>`<div style="width:90px;height:60px;border-radius:8px;background:#333;display:flex;align-items:center;justify-content:center;font-size:24px">${e}</div>`).join("")}</div></div>${tip("Изберете филм → натиснете ▶.<br>Гледането през Wi-Fi пести данни","left:50%;top:150px;transform:translateX(-50%)")}`, "#111", "#fff");

S["photo-timer"] = phone(`<div class="grow" style="background:linear-gradient(160deg,#8d99ae,#4a5568);position:relative;display:flex;flex-direction:column"><div style="flex:1;display:flex;align-items:center;justify-content:center;font-size:60px">👵👦</div><div style="position:absolute;top:14px;right:14px;background:rgba(0,0,0,.5);color:#fff;border-radius:20px;padding:6px 12px;font-size:14px">⏱️ 10 сек</div><div style="background:rgba(0,0,0,.4);padding:18px 0;display:flex;align-items:center;justify-content:space-around"><div class="ring ringr" style="background:#fff;color:#000;width:54px;height:54px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:13px;font-weight:700">10с</div><div style="width:72px;height:72px;border-radius:50%;background:#fff;border:5px solid rgba(255,255,255,.5)"></div><div style="color:#fff;font-size:24px">🔄</div></div></div>${tip("Включете таймера (10 сек) → натиснете<br>снимане → влезте в кадър","left:50%;bottom:120px;transform:translateX(-50%)")}`, "#4a5568", "#fff");

S["group-video"] = phone(`<div class="grow" style="background:#111;padding:4px"><div style="display:grid;grid-template-columns:1fr 1fr;gap:4px;height:100%">${[["М","#7e57c2"],["И","#42a5f5"],["Е","#66bb6a"],["П","#ffa726"]].map(([i,c])=>`<div style="background:${c};border-radius:10px;display:flex;align-items:center;justify-content:center;color:#fff;font-size:34px;font-weight:700;position:relative">${i}<span style="position:absolute;bottom:6px;left:8px;font-size:11px;background:rgba(0,0,0,.4);padding:1px 6px;border-radius:6px">${i==='М'?'Мария':i==='И'?'Иван':i==='Е'?'Елена':'Петър'}</span></div>`).join("")}</div></div><div style="background:#000;padding:16px;display:flex;justify-content:center;gap:24px"><div style="width:50px;height:50px;border-radius:50%;background:#333;display:flex;align-items:center;justify-content:center;font-size:20px">🎤</div><div style="width:50px;height:50px;border-radius:50%;background:#dc2626;display:flex;align-items:center;justify-content:center;transform:rotate(135deg)">${I.phone}</div><div class="ring ringr" style="width:50px;height:50px;border-radius:50%;background:#34c759;display:flex;align-items:center;justify-content:center;color:#fff">${I.video}</div></div>${tip("Започнете видео разговор и „Добави хора“ —<br>виждате всички едновременно","left:50%;top:120px;transform:translateX(-50%)")}`, "#000", "#fff");

// ═══ СНИМКИ ═══
S["photo-delete"] = phone(`<div style="background:#000;color:#fff;padding:11px 14px;display:flex;align-items:center;gap:14px"><span>${I.back}</span><div style="flex:1"></div><span>↗️</span><span class="ring ringr" style="color:#ff6b6b;padding:3px">${I.trash}</span></div><div class="grow" style="background:#000;display:flex;align-items:center;justify-content:center"><div style="width:240px;height:300px;border-radius:8px;background:linear-gradient(135deg,#fbbf24,#f59e0b);display:flex;align-items:center;justify-content:center;font-size:50px">🏖️</div></div>${tip("Отворете снимката → натиснете<br>кошчето 🗑️, за да я изтриете","right:16px;top:54px")}`, "#000", "#fff");

S["set-wallpaper"] = phone(`<div style="background:#000;color:#fff;padding:11px 14px;display:flex;align-items:center;gap:14px"><span>${I.back}</span><div style="flex:1"></div><span class="ring ringr" style="padding:3px">⋮</span></div><div style="flex:1;background:#000;display:flex;align-items:center;justify-content:center"><div style="width:220px;height:280px;border-radius:8px;background:linear-gradient(135deg,#60a5fa,#2563eb);display:flex;align-items:center;justify-content:center;font-size:48px">🏞️</div></div><div style="background:#1a1a1a;color:#fff;border-radius:14px;margin:0 12px 14px;overflow:hidden">${["Редактирай","Задай като фон","Подробности"].map((t,i)=>`<div class="${i===1?'ring':''}" style="padding:13px 16px;font-size:15px;color:${i===1?'#4da3ff':'#fff'};font-weight:${i===1?700:400};border-bottom:1px solid #333;${i===1?'border-radius:8px;':''}">${t}</div>`).join("")}</div>${tip("Отворете снимката → ⋮ →<br>„Задай като фон“","right:16px;top:54px")}`, "#000", "#fff");

S["create-album"] = phone(`${navTitle("#fff","#111","Нов албум")}<div style="background:#fff;padding:16px;border-bottom:8px solid #eef0f2"><div style="border-bottom:1px solid #1877f2;padding:8px 0;font-size:17px;color:#111">Внуците ❤️|</div><div style="font-size:12px;color:#888;margin-top:4px">име на албума</div></div><div class="grow" style="background:#fff;padding:3px"><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:3px">${["#fbbf24","#60a5fa","#34d399","#f87171","#a78bfa","#fb923c"].map((c,i)=>`<div style="aspect-ratio:1;background:${c};display:flex;align-items:center;justify-content:center;font-size:22px">🖼️${i<2?'<div style="position:absolute" ></div>':''}</div>`).join("")}</div></div>${tip("Дайте име на албума → изберете снимки →<br>„Запази“. Така са подредени","left:50%;top:130px;transform:translateX(-50%)")}`);

S["photo-restore"] = phone(`${navTitle("#fff","#111","Кошче (изтрити)")}<div style="padding:12px 16px;font-size:13px;color:#888;background:#fff">Изтритите снимки се пазят тук 30 дни.</div><div class="grow" style="background:#fff;padding:3px"><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:3px">${["#fbbf24","#60a5fa","#34d399"].map((c,i)=>`<div style="aspect-ratio:1;background:${c};position:relative;display:flex;align-items:center;justify-content:center;font-size:22px;opacity:.7">🖼️${i===0?'<div class="ring" style="position:absolute;inset:3px;border:2px solid #1877f2"></div>':''}</div>`).join("")}</div></div><div style="background:#fff;padding:14px;border-top:1px solid #eee;text-align:center"><div class="ring" style="display:inline-block;background:#1877f2;color:#fff;padding:11px 24px;border-radius:10px;font-weight:700;border-radius:10px">↩ Възстанови</div></div>${tip("Отворете „Кошче“ → изберете снимката<br>→ „Възстанови“","left:50%;bottom:80px;transform:translateX(-50%)")}`);

S["slideshow"] = phone(`<div style="background:#000;color:#fff;padding:11px 14px;display:flex;align-items:center;gap:14px"><span>${I.back}</span><div style="flex:1"></div><span class="ring ringr" style="padding:3px">⋮</span></div><div class="grow" style="background:#000;display:flex;align-items:center;justify-content:center;position:relative"><div style="width:280px;height:320px;border-radius:8px;background:linear-gradient(135deg,#f472b6,#db2777);display:flex;align-items:center;justify-content:center;font-size:54px">🌸</div><div style="position:absolute;bottom:20px;display:flex;gap:6px">${[1,0,0].map(a=>`<div style="width:8px;height:8px;border-radius:50%;background:${a?'#fff':'rgba(255,255,255,.4)'}"></div>`).join("")}</div></div>${tip("Отворете снимка → ⋮ → „Слайдшоу“ —<br>снимките се сменят сами","right:16px;top:54px")}`, "#000", "#fff");

S["photo-share"] = phone(`<div style="background:#000;height:220px;display:flex;align-items:center;justify-content:center"><div style="width:200px;height:180px;border-radius:8px;background:linear-gradient(135deg,#34d399,#059669);display:flex;align-items:center;justify-content:center;font-size:44px">🏞️</div></div><div class="grow" style="background:#fff;border-radius:18px 18px 0 0;margin-top:-18px;padding:18px"><div style="font-weight:700;font-size:15px;color:#111;margin-bottom:14px">Сподели чрез</div><div style="display:flex;gap:18px">${[["🟣","Viber",1],["📘","Messenger",0],["📧","Имейл",0],["💬","SMS",0]].map(([e,l,h])=>`<div style="text-align:center;font-size:12px;color:#444"><div class="${h?'ring ringr':''}" style="width:54px;height:54px;border-radius:50%;background:#f0f2f5;display:flex;align-items:center;justify-content:center;font-size:24px;margin:0 auto 5px">${e}</div>${l}</div>`).join("")}</div></div>${tip("Отворете снимка → ↗ Сподели →<br>изберете приложение (напр. Viber)","left:50%;top:150px;transform:translateX(-50%)")}`);

S["photo-zoom"] = phone(`<div class="grow" style="background:#000;display:flex;align-items:center;justify-content:center;position:relative"><div style="width:300px;height:380px;border-radius:8px;background:linear-gradient(135deg,#fbbf24,#dc2626);display:flex;align-items:center;justify-content:center;font-size:90px;transform:scale(1.2)">🌻</div><div class="ring ringr" style="position:absolute;left:38%;top:42%;width:90px;height:90px;border-radius:50%;border:3px dashed #fff"></div></div>${tip("Допрете с два пръста и ги раздалечете,<br>за да приближите снимката","left:50%;bottom:90px;transform:translateX(-50%)")}`, "#000", "#fff");

render(S).catch((e) => { console.error(e); process.exit(1); });
