// Шеста партида „мокъп" екрани: още телефонни действия, приложения, е-услуги,
// транспорт, телемедицина, спешност и безопасност. Стилизирани, обучителни.
// Стартиране (от zabobovdol/):  node scripts/howto-mockups/gen-6.js
const { phone, I, av, tip, navTitle, setRow, toggle, render } = require("./_shell");

const S = {};
const green = "#34c759", redc = "#ff3b30";
const settings = (title, rows, tipHtml = "") => navTitle("#fff","#111",title) + `<div class="grow" style="background:#fff">${rows}</div>` + tipHtml;

// Галерия (намиране на снимки)
S["gallery"] = navTitle("#fff","#111","Галерия") + `<div class="grow" style="background:#fff;padding:3px"><div style="padding:8px 10px 4px;font-size:13px;color:#888">Днес</div><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:3px">${["#fbbf24","#60a5fa","#34d399","#f87171","#a78bfa","#fb923c","#22d3ee","#f472b6","#4ade80"].map(c=>`<div style="aspect-ratio:1;background:${c};display:flex;align-items:center;justify-content:center;font-size:24px">🖼️</div>`).join("")}</div></div>` + tip("Отворете „Галерия/Снимки“ — всичките<br>ви снимки са тук, подредени по дата","left:50%;top:120px;transform:translateX(-50%)");

// Заснемане на видео
S["video-record"] = phone(`<div class="grow" style="background:linear-gradient(160deg,#5b6470,#2c333d);position:relative;display:flex;flex-direction:column"><div style="position:absolute;top:14px;left:50%;transform:translateX(-50%);background:rgba(0,0,0,.5);color:#fff;border-radius:20px;padding:5px 12px;font-size:13px;display:flex;align-items:center;gap:6px"><span style="width:9px;height:9px;border-radius:50%;background:#ff3b30"></span> 00:14</div><div style="flex:1;display:flex;align-items:center;justify-content:center;font-size:60px">🌳</div><div style="background:rgba(0,0,0,.4);padding:8px 0 16px"><div style="display:flex;justify-content:center;gap:20px;color:#fff;font-size:13px;margin-bottom:12px"><span>Снимка</span><span style="color:#ff3b30;font-weight:700;border-bottom:2px solid #ff3b30;padding-bottom:2px">ВИДЕО</span></div><div style="display:flex;align-items:center;justify-content:space-around"><div style="width:40px"></div><div class="ring ringr" style="width:72px;height:72px;border-radius:50%;background:#ff3b30;border:5px solid rgba(255,255,255,.6)"></div><div style="color:#fff;font-size:22px">🔄</div></div></div></div>${tip("Изберете „Видео“ → натиснете червения<br>кръг да започне, пак за да спре","left:50%;bottom:120px;transform:translateX(-50%)")}`, "#2c333d", "#fff");

// Обаждане по Viber
S["viber-call"] = phone(`<div class="grow" style="background:linear-gradient(160deg,#6b5fb8,#3d3470);color:#fff;display:flex;flex-direction:column;align-items:center;padding-top:60px"><div style="font-size:14px;opacity:.8">Viber аудио разговор</div>${av("М","#b39ddb",96)}<div style="font-size:24px;font-weight:700;margin-top:16px">Мария (дъщеря)</div><div style="font-size:14px;opacity:.7;margin-top:4px">свързване…</div><div style="flex:1"></div><div style="font-size:12px;opacity:.75;margin-bottom:10px">безплатно през интернет</div><div style="display:flex;gap:24px;padding-bottom:46px">${["🔇","📹"].map(e=>`<div style="width:56px;height:56px;border-radius:50%;background:rgba(255,255,255,.18);display:flex;align-items:center;justify-content:center;font-size:22px">${e}</div>`).join("")}<div class="ring ringr" style="width:56px;height:56px;border-radius:50%;background:#ff3b30;display:flex;align-items:center;justify-content:center;transform:rotate(135deg)">${I.phone}</div></div></div>${tip("В чата с човека натиснете слушалката 📞 —<br>обаждането е безплатно през интернет","left:50%;bottom:120px;transform:translateX(-50%)")}`, "#3d3470", "#fff");

// Видео обаждане (1 към 1)
S["video-call"] = phone(`<div class="grow" style="background:#111;position:relative"><div style="position:absolute;inset:0;background:linear-gradient(135deg,#7e57c2,#5e35b1);display:flex;align-items:center;justify-content:center;font-size:80px">👩</div><div style="position:absolute;right:14px;top:14px;width:90px;height:120px;border-radius:12px;background:linear-gradient(135deg,#90caf9,#42a5f5);display:flex;align-items:center;justify-content:center;font-size:34px;border:2px solid #fff">🧓</div><div style="position:absolute;bottom:0;left:0;right:0;background:rgba(0,0,0,.35);padding:18px 0;display:flex;justify-content:center;gap:22px">${["🔇"].map(e=>`<div style="width:52px;height:52px;border-radius:50%;background:rgba(255,255,255,.2);display:flex;align-items:center;justify-content:center;font-size:20px">${e}</div>`).join("")}<div class="ring ringr" style="width:52px;height:52px;border-radius:50%;background:rgba(255,255,255,.2);display:flex;align-items:center;justify-content:center;font-size:20px">🔄</div><div style="width:52px;height:52px;border-radius:50%;background:#ff3b30;display:flex;align-items:center;justify-content:center;transform:rotate(135deg)">${I.phone}</div></div></div>${tip("Натиснете камерата 📹. Малкото прозорче<br>сте вие — стрелките 🔄 въртят камерата","left:50%;top:80px;transform:translateX(-50%)")}`, "#111", "#fff");

// Изпрати/копирай линк
S["share-link"] = phone(`${navTitle("#fff","#111","Бобов дол — портал")}<div class="grow" style="background:#fff;padding:16px;position:relative"><div style="background:#f0f2f5;border-radius:10px;padding:12px;color:#1a73e8;font-size:14px;word-break:break-all">zabobovdol.bg/uslugi</div><div style="position:absolute;left:30px;top:80px;background:#333;border-radius:10px;display:flex;overflow:hidden;box-shadow:0 6px 18px rgba(0,0,0,.3)"><div style="padding:10px 14px;color:#fff;font-size:14px;border-right:1px solid #555">Копирай</div><div class="ring" style="padding:10px 14px;color:#fff;font-size:14px;font-weight:700;border-radius:8px">Сподели</div></div></div>${tip("Задръжте върху адреса → „Копирай“,<br>после „Постави“ в съобщение; или „Сподели“","left:50%;top:140px;transform:translateX(-50%)")}`);

// Бързо набиране / любим контакт
S["speed-dial"] = phone(`${navTitle("#fff","#111","Любими")}<div class="grow" style="background:#fff;padding:14px"><div style="display:grid;grid-template-columns:1fr 1fr;gap:14px">${[["М","Мария","#7e57c2",1],["И","Иван","#42a5f5",0],["Л","Личен лекар","#66bb6a",0],["А","Аптека","#ffa726",0]].map(([i,n,c,h])=>`<div class="${h?'ring':''}" style="display:flex;flex-direction:column;align-items:center;gap:8px;padding:16px;border:1px solid #eee;border-radius:14px;${h?'border-radius:14px;':''}">${av(i,c,54)}<div style="font-size:14px;color:#111;font-weight:600">${n}</div><div style="color:${green};display:flex;align-items:center;gap:4px;font-size:13px">${I.phone}</div></div>`).join("")}</div></div>${tip("Добавете близките в „Любими“ —<br>после се звъни с едно докосване","left:50%;top:120px;transform:translateX(-50%)")}`);

// Снимка на контакт
S["contact-photo"] = phone(`${navTitle("#fff","#111","Редакция на контакт")}<div style="background:#fff;padding:24px;text-align:center;border-bottom:8px solid #eef0f2"><div style="position:relative;display:inline-block">${av("М","#7e57c2",90)}<div class="ring ringr" style="position:absolute;right:-4px;bottom:-4px;width:34px;height:34px;border-radius:50%;background:#1877f2;color:#fff;display:flex;align-items:center;justify-content:center;font-size:16px;border:3px solid #fff">📷</div></div><div style="font-weight:700;font-size:18px;color:#111;margin-top:10px">Мария (дъщеря)</div></div><div class="grow" style="background:#fff"></div>${tip("Отворете контакта → „Редактирай“ →<br>натиснете кръгчето 📷 и изберете снимка","left:50%;top:230px;transform:translateX(-50%)")}`);

// Пряк път към сайт на началния екран
S["home-shortcut"] = phone(`<div style="background:#f1f3f4;padding:9px 10px;display:flex;align-items:center;gap:8px;border-bottom:1px solid #ddd"><div style="flex:1;background:#fff;border-radius:20px;padding:8px 12px;color:#111;font-size:14px">zabobovdol.bg</div><span class="ring ringr" style="color:#888;padding:2px">⋮</span></div><div class="grow" style="background:#fff;display:flex;align-items:flex-start;justify-content:flex-end"><div style="background:#fff;border-radius:12px;box-shadow:0 8px 24px rgba(0,0,0,.2);margin:8px;overflow:hidden;width:230px">${["Нов раздел","Добави отметка","Добави към началния екран"].map((t,i)=>`<div class="${i===2?'ring':''}" style="padding:13px 16px;font-size:14px;color:${i===2?'#1877f2':'#111'};font-weight:${i===2?700:400};border-bottom:1px solid #f3f3f3;${i===2?'border-radius:8px;':''}">${t}</div>`).join("")}</div></div>${tip("Меню ⋮ → „Добави към началния екран“ —<br>сайтът става икона като приложение","right:14px;top:120px")}`);

// Гласова бележка
S["voice-memo"] = phone(`${navTitle("#fff","#111","Гласови бележки")}<div class="grow" style="background:#fff;display:flex;flex-direction:column;align-items:center;justify-content:center;padding:20px"><div style="display:flex;align-items:flex-end;gap:3px;height:60px;margin-bottom:24px">${[18,30,45,28,52,38,24,48,32,20,40].map(h=>`<div style="width:5px;height:${h}px;background:#ff3b30;border-radius:3px"></div>`).join("")}</div><div style="font-size:22px;color:#111;font-variant-numeric:tabular-nums">0:12</div><div class="ring ringr" style="width:78px;height:78px;border-radius:50%;background:#ff3b30;display:flex;align-items:center;justify-content:center;margin-top:24px;color:#fff;font-size:30px">⏺</div></div>${tip("Натиснете червения кръг и говорете —<br>записва гласа ви като бележка","left:50%;bottom:90px;transform:translateX(-50%)")}`);

// Автоматично заключване
S["auto-lock"] = settings("Заключване на екрана", `${setRow("⏱️","Автоматично заключване","след 30 сек", true)}${setRow("🔒","Изисквай ПИН/пръст", toggle(true))}<div style="padding:14px 18px;font-size:13px;color:#888">Екранът сам угасва и се заключва, ако не го ползвате — пести батерия и пази телефона.</div>`, tip("Изберете време (напр. 30 сек) —<br>екранът се заключва сам","right:10px;top:64px"));

// Спри изскачащи реклами
S["block-popups"] = settings("Браузър — настройки", `${setRow("🚫","Блокирай изскачащи прозорци", toggle(true), true)}${setRow("📢","Блокирай реклами", toggle(true))}${setRow("🔔","Известия от сайтове", toggle(false))}`, tip("Включете „Блокирай изскачащи прозорци“ —<br>спира досадните реклами","right:10px;top:64px"));

// Намали данни при видео
S["data-saver"] = settings("YouTube — настройки", `${setRow("📉","Пести данни", toggle(true), true)}${setRow("🎚️","Качество на видеото","ниско (480p)")}${setRow("📶","Високо качество само на Wi-Fi", toggle(true))}`, tip("Включете „Пести данни“ и гледайте на<br>по-ниско качество — харчи по-малко интернет","right:10px;top:64px"));

// Зареждане с ваучер
S["recharge-voucher"] = phone(`${navTitle("#fff","#111","Телефон")}<div class="grow" style="background:#fff;display:flex;flex-direction:column;align-items:center;justify-content:center;padding:24px"><div style="font-size:13px;color:#888;margin-bottom:10px">Наберете кода за зареждане:</div><div class="ring" style="font-size:30px;letter-spacing:2px;color:#111;font-family:monospace;border-radius:8px;padding:8px 14px;background:#f5f5f5;border-radius:8px">*123*КОД#</div><div style="font-size:14px;color:#444;margin-top:18px;text-align:center">Изтрийте сребристото поле на ваучера,<br>въведете кода и натиснете 📞</div><div style="width:64px;height:64px;border-radius:50%;background:${green};display:flex;align-items:center;justify-content:center;margin-top:20px;color:#fff">${I.phone}</div></div>${tip("Наберете звезда-код от ваучера и натиснете<br>обаждане — кредитът се добавя веднага","left:50%;top:120px;transform:translateX(-50%)")}`);

// Проверка на глоби КАТ
S["check-fines"] = phone(`${navTitle("#13399b","#fff","Проверка на глоби (КАТ)")}<div class="grow" style="background:#fff;padding:18px">${["ЕГН|●●●●●●●●●●","№ на лична карта|●●●●●●●●●","№ на шофьорска книжка|●●●●●●●●●"].map(r=>{const[l,v]=r.split("|");return `<div style="margin-bottom:14px"><div style="font-size:12px;color:#13399b">${l}</div><div style="border:1px solid #ccd0d5;border-radius:10px;padding:12px;font-size:15px;color:#111;margin-top:4px">${v}</div></div>`}).join("")}<div class="ring" style="background:#13399b;color:#fff;padding:14px;border-radius:10px;text-align:center;font-weight:700;border-radius:10px">Провери</div><div style="font-size:12px;color:#888;margin-top:10px">Официално: МВР / e-Government. Безплатно.</div></div>${tip("Въведете данните от документите си →<br>„Провери“. Услугата е безплатна","left:50%;top:60px;transform:translateX(-50%)")}`);

// Избирателна секция
S["polling-station"] = phone(`${navTitle("#0a7d4b","#fff","Къде гласувам?")}<div class="grow" style="background:#fff;padding:18px"><div style="font-size:12px;color:#0a7d4b;margin-bottom:4px">ЕГН</div><div style="border:1px solid #ccd0d5;border-radius:10px;padding:12px;font-size:15px;color:#111;margin-bottom:16px">●●●●●●●●●●</div><div class="ring" style="background:#0a7d4b;color:#fff;padding:13px;border-radius:10px;text-align:center;font-weight:700;margin-bottom:18px;border-radius:10px">Намери секцията</div><div style="background:#f0fdf4;border:1px solid #bbf7d0;border-radius:12px;padding:14px"><div style="font-weight:700;color:#111">Секция №12</div><div style="font-size:14px;color:#444;margin-top:4px">📍 ОУ „Хр. Ботев“, ул. Девети септември 5</div></div></div>${tip("Въведете ЕГН → показва коя е вашата<br>секция и адреса. Безплатно (sik.cik.bg)","left:50%;top:60px;transform:translateX(-50%)")}`);

// Сканиране на документ
S["scan-document"] = phone(`<div class="grow" style="background:#1a1a1a;position:relative;display:flex;align-items:center;justify-content:center"><div class="ring" style="width:240px;height:320px;background:#fff;border-radius:6px;box-shadow:0 0 0 2000px rgba(0,0,0,.6);position:relative;border-radius:6px"><div style="padding:18px;font-size:11px;color:#333;font-family:monospace;line-height:1.6">УДОСТОВЕРЕНИЕ<br>───────────<br>Име: .........<br>ЕГН: .........<br>Адрес: .......</div>${["top:-2px;left:-2px;border-top:3px solid #ffd166;border-left:3px solid #ffd166","top:-2px;right:-2px;border-top:3px solid #ffd166;border-right:3px solid #ffd166","bottom:-2px;left:-2px;border-bottom:3px solid #ffd166;border-left:3px solid #ffd166","bottom:-2px;right:-2px;border-bottom:3px solid #ffd166;border-right:3px solid #ffd166"].map(s=>`<div style="position:absolute;width:26px;height:26px;${s}"></div>`).join("")}</div></div><div style="background:#000;padding:18px;display:flex;justify-content:center"><div class="ring ringr" style="width:66px;height:66px;border-radius:50%;background:#fff;border:5px solid rgba(255,255,255,.5)"></div></div>${tip("Сложете документа на маса, насочете<br>камерата в рамката и снимайте","left:50%;top:90px;transform:translateX(-50%)")}`, "#000", "#fff");

// Билет за транспорт (градски/междуградски)
S["transit-ticket"] = phone(`${navTitle("#0a3d6b","#fff","Билет за автобус")}<div class="grow" style="background:#fff;display:flex;align-items:center;justify-content:center;padding:20px"><div style="background:#fff;border:1px solid #ddd;border-radius:16px;padding:20px;width:250px;text-align:center;box-shadow:0 10px 24px rgba(0,0,0,.12)"><div style="font-weight:700;color:#0a3d6b;font-size:16px">Бобов дол → Дупница</div><div style="font-size:13px;color:#888;margin:6px 0">днес 14:20 • място 12</div><div class="ring" style="margin:14px 0;font-family:monospace;font-size:30px;letter-spacing:1px;color:#111;border-radius:6px;padding:4px">▌║▌▌║║▌║▌║║▌</div><div style="font-size:12px;color:#888">Покажете кода на шофьора</div><div style="font-size:22px;font-weight:800;color:#111;margin-top:10px">4,00 лв</div></div></div>${tip("Купете билета в приложението →<br>покажете кода на шофьора/валидатора","left:50%;top:80px;transform:translateX(-50%)")}`);

// Такси приложение
S["taxi"] = phone(`<div style="position:absolute;inset:0;background:linear-gradient(135deg,#e8eef5,#cdd9e8)"></div><svg style="position:absolute;inset:0" width="390" height="500"><path d="M60 420 C 140 320, 240 300, 250 180" stroke="#0a3d6b" stroke-width="7" fill="none" stroke-linecap="round"/></svg><div style="position:absolute;left:54px;top:404px;font-size:26px">📍</div><div style="position:absolute;left:236px;top:150px;font-size:26px">🏁</div><div style="position:relative;margin-top:auto;background:#fff;border-radius:18px 18px 0 0;padding:18px"><div style="display:flex;align-items:center;gap:12px;margin-bottom:14px"><span style="font-size:26px">🚕</span><div style="flex:1"><div style="font-weight:700;color:#111">Такси до центъра</div><div style="font-size:13px;color:#888">~5 мин • кола 4 места</div></div><div style="font-weight:800;color:#111">~6 лв</div></div><div class="ring" style="background:#111;color:#fff;padding:14px;border-radius:12px;text-align:center;font-weight:700;border-radius:12px">Поръчай такси</div></div>${tip("Сложете адреса → „Поръчай“. Виждате колата,<br>шофьора и цената предварително","left:50%;top:80px;transform:translateX(-50%)")}`, "#cdd9e8");

// Телемедицина (видео при лекар)
S["telemedicine"] = phone(`<div class="grow" style="background:#0a3d4a;position:relative"><div style="position:absolute;inset:0;display:flex;align-items:center;justify-content:center;font-size:70px">🧑‍⚕️</div><div style="position:absolute;left:14px;top:14px;background:rgba(0,0,0,.4);color:#fff;font-size:12px;padding:4px 10px;border-radius:14px">Д-р Иванова • онлайн</div><div style="position:absolute;right:14px;top:14px;width:80px;height:108px;border-radius:12px;background:linear-gradient(135deg,#90caf9,#42a5f5);display:flex;align-items:center;justify-content:center;font-size:30px;border:2px solid #fff">🧓</div><div style="position:absolute;bottom:0;left:0;right:0;background:rgba(0,0,0,.35);padding:18px 0;display:flex;justify-content:center;gap:22px"><div style="width:52px;height:52px;border-radius:50%;background:rgba(255,255,255,.2);display:flex;align-items:center;justify-content:center;font-size:20px">🔇</div><div class="ring ringr" style="width:52px;height:52px;border-radius:50%;background:rgba(255,255,255,.2);display:flex;align-items:center;justify-content:center;font-size:20px">💬</div><div style="width:52px;height:52px;border-radius:50%;background:#ff3b30;display:flex;align-items:center;justify-content:center;transform:rotate(135deg)">${I.phone}</div></div></div>${tip("В уговорения час натиснете връзката —<br>говорите с лекаря по видео от вкъщи","left:50%;top:90px;transform:translateX(-50%)")}`, "#0a3d4a", "#fff");

// SOS бутон
S["sos-button"] = phone(`<div class="grow" style="background:#fff;display:flex;flex-direction:column;align-items:center;justify-content:center;padding:24px"><div class="ring ringr" style="width:150px;height:150px;border-radius:50%;background:#ff3b30;color:#fff;display:flex;flex-direction:column;align-items:center;justify-content:center;box-shadow:0 10px 30px rgba(255,59,48,.4)"><div style="font-size:40px;font-weight:800">SOS</div><div style="font-size:13px">задръжте</div></div><div style="font-size:16px;font-weight:700;color:#111;margin-top:24px;text-align:center">Спешна помощ</div><div style="font-size:14px;color:#666;margin-top:8px;text-align:center">Звъни на 112 и праща локацията ви<br>на близък автоматично</div></div>${tip("Задръжте бутона SOS 3 секунди — звъни на<br>спешния номер и известява близък","left:50%;bottom:80px;transform:translateX(-50%)")}`);

// Спешен контакт на заключен екран
S["emergency-contact-lock"] = phone(`<div class="grow" style="background:linear-gradient(160deg,#1e293b,#0f172a);color:#fff;display:flex;flex-direction:column;align-items:center;padding-top:70px"><div style="font-size:56px;font-weight:200">9:41</div><div style="opacity:.7;margin-top:4px">заключен екран</div><div style="flex:1"></div><div class="ring" style="background:rgba(255,255,255,.12);border-radius:14px;padding:14px 20px;margin-bottom:40px;text-align:center;border-radius:14px"><div style="font-size:13px;opacity:.8;margin-bottom:6px">При спешност без отключване:</div><div style="font-size:16px;font-weight:700;color:#ff6b6b">🚨 Спешно обаждане</div><div style="font-size:13px;margin-top:6px;opacity:.85">Близък: Мария — 088 ...</div></div></div>${tip("Дори заключен, телефонът показва спешния ви<br>контакт и медицинска информация","left:50%;top:200px;transform:translateX(-50%)")}`, "#0f172a", "#fff");

// Заключи приложение
S["lock-app"] = settings("Заключени приложения", `${setRow("🏦","Банково приложение", toggle(true), true)}${setRow("🟣","Viber", toggle(false))}${setRow("🖼️","Галерия", toggle(true))}<div style="padding:14px 18px;font-size:13px;color:#888">Заключеното приложение иска пръст/ПИН при отваряне — дори телефонът да е отключен.</div>`, tip("Включете ключето до приложението —<br>то ще иска пръст/ПИН да се отвори","right:10px;top:64px"));

// Освободи място (снимки)
S["free-space"] = settings("Памет на телефона", `<div style="padding:18px;border-bottom:8px solid #eef0f2"><div style="display:flex;justify-content:space-between;font-size:14px;color:#111;margin-bottom:8px"><span>Заето: 58 GB</span><span>Свободно: 6 GB</span></div><div style="height:12px;background:#eee;border-radius:6px;overflow:hidden;display:flex"><div style="width:55%;background:#1877f2"></div><div style="width:25%;background:#f59e0b"></div></div></div>${setRow("🗑️","Изчисти временни файлове","2,1 GB", true)}${setRow("🖼️","Големи стари снимки/видео","8 GB")}`, tip("Изчистете временни файлове и стари видеа,<br>за да освободите място","right:10px;top:300px"));

// Изход от чуждо устройство
S["logout-device"] = phone(`${navTitle("#fff","#111","Активни устройства")}<div class="grow" style="background:#fff">${[["💻","Компютър на сина","влязъл • вчера",1],["📱","Този телефон","сега","this"]].map(([e,n,d,h])=>`<div class="${h===1?'ring':''}" style="display:flex;align-items:center;gap:14px;padding:16px;border-bottom:1px solid #f3f3f3;${h===1?'border-radius:10px;margin:4px 8px;':''}"><span style="font-size:24px">${e}</span><div style="flex:1"><div style="font-size:15px;color:#111;font-weight:600">${n}</div><div style="font-size:12px;color:#888">${d}</div></div>${h===1?'<span style="color:#ef4444;font-weight:700;font-size:13px">Излез</span>':'<span style="color:#34a853;font-size:12px">тук</span>'}</div>`).join("")}</div>${tip("В настройките за сигурност → „Излез“ от<br>устройства, които вече не ползвате","right:10px;top:120px")}`);

// Прехвърляне на нов телефон
S["transfer-phone"] = phone(`<div class="grow" style="background:#fff;display:flex;flex-direction:column;align-items:center;justify-content:center;padding:24px"><div style="display:flex;align-items:center;gap:16px;margin-bottom:24px"><div style="width:64px;height:90px;border-radius:10px;background:#cfd8e3;display:flex;align-items:center;justify-content:center;font-size:28px">📱</div><div style="font-size:24px;color:#1877f2">→</div><div style="width:64px;height:90px;border-radius:10px;background:#1877f2;display:flex;align-items:center;justify-content:center;font-size:28px">📱</div></div><div style="font-size:17px;font-weight:700;color:#111;text-align:center">Прехвърляне на данните</div><div style="font-size:14px;color:#666;margin:8px 0 16px;text-align:center">Контакти, снимки и приложения от стария на новия телефон</div><div class="ring" style="background:#1877f2;color:#fff;padding:13px 28px;border-radius:10px;font-weight:700;border-radius:10px">Започни</div></div>${tip("При първото пускане новият телефон сам предлага<br>прехвърляне — следвайте стъпките","left:50%;bottom:90px;transform:translateX(-50%)")}`);

render(S).catch((e) => { console.error(e); process.exit(1); });
