// Generated by scripts/landing-docs.ts: the size [px] of each page of the sample documents on the landing page, its
// number among the pages of its document and, for a sheet of the drawing set, its scale.
export const LANDING_DOCS = {
  'lp-doc-tavola': { w: 820, h: 1160, args: { n: 1, of: 10 } },
  'lp-doc-locale': { w: 820, h: 1160, args: { n: 8, of: 10, scale: 25 } },
  'lp-doc-relazione': { w: 820, h: 1160, args: { n: 1, of: 27 } },
  'lp-doc-verifiche': { w: 820, h: 1160, args: { n: 4, of: 27 } },
} as const;
