// Generated by scripts/landing-drawings.ts: the size [px] and the scale of each drawing of the landing page.
export const LANDING_DRAWINGS = {
  'lp-plan': { w: 648, h: 730, scale: 20 },
  'lp-section': { w: 440, h: 1040, scale: 50 },
} as const;
