// Generated by scripts/icons-build.py from brand/premium/icons/icon-manifest.json: do not edit by hand.
// The painted icons of the LiftPilot Premium pack, served as public/icons/<name>-48.webp and -96.webp.
export const ICON_NAMES = [
  'activity', 'air-vent', 'alert-circle', 'alert-triangle', 'archive', 'arrow-down', 'arrow-down-to-line',
  'arrow-left', 'arrow-right', 'arrow-up', 'arrow-up-from-line', 'arrow-up-right', 'badge-check', 'ban', 'bar-chart',
  'bell', 'blueprint', 'book-open', 'box', 'box-select', 'brackets', 'brackets-check', 'brake', 'building',
  'building-2', 'building-check', 'building-gear', 'cabinet', 'cable', 'calculator', 'calculator-check', 'calendar',
  'camera', 'chart-line', 'chart-no-axes-combined', 'chart-pie', 'check', 'check-circle', 'check-circle-2',
  'check-square', 'chevron-down', 'chevron-left', 'chevron-right', 'chevron-up', 'circle-dashed', 'circle-dot',
  'circle-gauge', 'circle-help', 'clipboard', 'clipboard-check', 'clipboard-list', 'clipboard-pen', 'clipboard-pulse',
  'clock', 'cloud', 'code-2', 'cog', 'columns-3', 'compass', 'component', 'copy', 'cpu', 'cube', 'database',
  'dimensions', 'distance', 'door-open', 'download', 'draft-cad', 'drafting-compass', 'edit-3', 'elevator', 'ellipsis',
  'external-link', 'eye', 'file-cad', 'file-chart', 'file-check', 'file-clock', 'file-code', 'file-dashed',
  'file-database', 'file-dwg', 'file-dwg-outline', 'file-dxf', 'file-export', 'file-image', 'file-lock', 'file-pdf',
  'file-pen', 'file-search', 'file-spreadsheet', 'file-stack', 'file-text', 'file-warning', 'filter', 'fingerprint',
  'floor-plan', 'folder', 'footprints', 'gauge', 'gear', 'git-branch', 'glasses', 'globe', 'globe-lock', 'grid-2x2',
  'hand-coins', 'handshake', 'hard-hat', 'hash', 'history', 'home', 'info', 'layers', 'layout-dashboard', 'life-buoy',
  'link', 'link-2', 'list-checks', 'list-tree', 'lock', 'lock-keyhole', 'log-in', 'log-out', 'mail', 'map-pin',
  'maximize', 'menu', 'message-circle', 'microscope', 'minus', 'monitor', 'more-horizontal', 'motor', 'move-3d',
  'network', 'package', 'panel-left', 'panels-top-left', 'pause', 'pen-tool', 'percent', 'phone', 'play', 'plus',
  'printer', 'pulley', 'pulse', 'refresh-cw', 'rope', 'rotate-3d', 'route', 'route-check', 'ruler', 'save', 'scale',
  'scale-3d', 'search', 'send', 'server', 'settings', 'shield', 'shield-alert', 'shield-check', 'sitemap', 'sliders',
  'sliders-horizontal', 'sparkles', 'square', 'stack', 'star', 'tag', 'target', 'terminal', 'trash-2', 'triangle',
  'upload', 'user', 'user-check', 'user-cog', 'users', 'weight', 'weight-scale', 'wrench', 'x', 'x-circle', 'zap',
] as const;

export type IconName = (typeof ICON_NAMES)[number];
