<?php
/**
 * Carbon Stealth VCC — Admin Settings API
 * Save/load SMTP config from admin panel
 */
header('Content-Type: application/json; charset=UTF-8');
header('X-Content-Type-Options: nosniff');

$allowed = ['https://carbonstealth.eu','https://www.carbonstealth.eu'];
$origin = $_SERVER['HTTP_ORIGIN'] ?? '';
if (in_array($origin, $allowed)) {
    header("Access-Control-Allow-Origin: $origin");
    header('Access-Control-Allow-Methods: POST, OPTIONS');
    header('Access-Control-Allow-Headers: Content-Type');
}
if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') { http_response_code(204); exit; }
require_once __DIR__.'/_auth.php';
cs_require_admin();

$configFile = __DIR__.'/config.php';

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $data = json_decode(file_get_contents('php://input'), true);
    $action = $data['action'] ?? '';
    
    if ($action === 'save_smtp' && isset($data['data'])) {
        $smtp = $data['data'];
        $host = preg_replace('/[^a-zA-Z0-9.\-]/', '', (string)($smtp['host'] ?? 'authsmtp.securemail.pro'));
        $port = intval($smtp['port'] ?? 465);
        $user = filter_var($smtp['user'] ?? '', FILTER_SANITIZE_EMAIL);
        $to   = filter_var($smtp['to'] ?? '', FILTER_SANITIZE_EMAIL);
        $pass = (string)($smtp['pass'] ?? '');

        // Persist to a git-ignored local override file (NOT config.php, which is
        // env-driven). var_export escapes every string safely — no PHP-string
        // break-out is possible, so no code injection via any field.
        $localFile = __DIR__ . '/smtp-local.php';
        $prev = @include $localFile;
        if (!is_array($prev)) $prev = [];
        if ($pass === '' || $pass === '********') {
            $pass = (string)($prev['pass'] ?? ''); // keep existing password if blank
        }

        $cfg = [
            'host'   => $host,
            'port'   => $port,
            'secure' => ($port === 465 ? 'ssl' : 'tls'),
            'user'   => $user,
            'pass'   => $pass,
            'to'     => $to,
        ];
        // The guard makes the file refuse a direct HTTP hit on its own, exactly
        // like the other include-only files — it must not depend on the web
        // server's deny rule being present and correctly ordered. `return`
        // still works normally when config.php includes it.
        $php = "<?php\n// Auto-generated by CS Admin Panel — " . date('Y-m-d H:i:s') . "\n"
             . "// Local SMTP overrides for api/config.php. Git-ignored (holds the password).\n"
             . "if (isset(\$_SERVER['SCRIPT_FILENAME']) &&\n"
             . "    realpath(\$_SERVER['SCRIPT_FILENAME']) === realpath(__FILE__)) {\n"
             . "    http_response_code(404);\n"
             . "    exit;\n"
             . "}\n"
             . "return " . var_export($cfg, true) . ";\n";

        if ((function($f,$c){ $t=$f.'.tmp.'.getmypid();
        // tmp + rename is atomic on the same filesystem: an interrupted write
        // can never leave a half-written config that @include silently ignores
        if (@file_put_contents($t,$c,LOCK_EX)!==false) { @chmod($t,0600); @rename($t,$f); }
    })($localFile, $php) !== false) {
            @chmod($localFile, 0600);
            echo json_encode(['ok'=>true,'message'=>'SMTP config saved']);
        } else {
            http_response_code(500);
            echo json_encode(['ok'=>false,'error'=>'Cannot write config. Check permissions.']);
        }
        exit;
    }
}

echo json_encode(['ok'=>false,'error'=>'Invalid request']);
