<?php
/**
 * Carbon Stealth VCC — Admin Settings API
 * Save/load SMTP config from admin panel
 */
header('Content-Type: application/json; charset=UTF-8');
header('X-Content-Type-Options: nosniff');

$allowed = ['https://carbonstealth.eu','https://www.carbonstealth.eu'];
$origin = $_SERVER['HTTP_ORIGIN'] ?? '';
if (in_array($origin, $allowed)) {
    header("Access-Control-Allow-Origin: $origin");
    header('Access-Control-Allow-Methods: POST, OPTIONS');
    header('Access-Control-Allow-Headers: Content-Type');
}
if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') { http_response_code(204); exit; }

$configFile = __DIR__.'/config.php';

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $data = json_decode(file_get_contents('php://input'), true);
    $action = $data['action'] ?? '';
    
    if ($action === 'save_smtp' && isset($data['data'])) {
        $smtp = $data['data'];
        $host = preg_replace('/[^a-zA-Z0-9.\-]/', '', $smtp['host'] ?? 'smtp.gmail.com');
        $port = intval($smtp['port'] ?? 587);
        $user = filter_var($smtp['user'] ?? '', FILTER_SANITIZE_EMAIL);
        $pass = $smtp['pass'] ?? '';
        $to   = filter_var($smtp['to'] ?? '', FILTER_SANITIZE_EMAIL);
        
        if ($pass === '' || $pass === '********') {
            // Don't overwrite password if not provided
            echo json_encode(['ok'=>true,'message'=>'Config saved (password unchanged)']);
            exit;
        }
        
        $config = "<?php\n"
            . "// Auto-generated by CS Admin Panel — " . date('Y-m-d H:i:s') . "\n"
            . "define('SMTP_HOST',      '$host');\n"
            . "define('SMTP_PORT',      $port);\n"
            . "define('SMTP_SECURE',    '" . ($port === 465 ? 'ssl' : 'tls') . "');\n"
            . "define('SMTP_USER',      '$user');\n"
            . "define('SMTP_PASS',      '$pass');\n"
            . "define('SMTP_FROM',      '$user');\n"
            . "define('SMTP_FROM_NAME', 'Carbon Stealth VCC');\n"
            . "define('SMTP_TO',        '$to');\n"
            . "define('SMTP_DEBUG',     0);\n"
            . "define('RECAPTCHA_SECRET', '');\n";
        
        if (@file_put_contents($configFile, $config)) {
            echo json_encode(['ok'=>true,'message'=>'SMTP config saved']);
        } else {
            http_response_code(500);
            echo json_encode(['ok'=>false,'error'=>'Cannot write config file. Check permissions.']);
        }
        exit;
    }
}

echo json_encode(['ok'=>false,'error'=>'Invalid request']);
