// frontend/src/i18n/landingExtras.js
// Обиколката на таблото (ProductTour.jsx) и „Заменете ги“ (ReplaceBots.jsx) —
// за английския лендинг и 7-те превода. Собствен lazy чънк с компонентите,
// за да не расте бюджетът на LandingLocalized (30 KB gzip).
export const TOUR_KEYS = ["home", "tickets", "panels", "forms", "analytics", "premium"];
export const EXTRAS_COPY = {
  en: {
    tour: { heading: "The dashboard, for real.", sub: "Not mockups — real screenshots of the current dashboard, filled with demo data.", labels: ["Overview", "Tickets", "Panels", "Forms", "Analytics", "Premium"], alts: ["Server overview — stats, live tickets and system status", "Ticket list with statuses, assignees and satisfaction ratings", "Ticket panels with buttons, support roles and the channel they live in", "Application forms with their questions", "Ticket analytics — heatmap, staff leaderboard and application funnel", "Premium plan and billing through Discord"] },
    replace: { heading: "Replace these. All of them.", strike: "8 bots, 8 dashboards, 8 sets of permissions, 8 support channels.", tagline: "One bot. One dashboard. One subscription.", items: [["Ticket bot", "tickets & transcripts"], ["Application bot", "forms & review"], ["Verification bot", "captcha & roles"], ["Anti-spam bot", "scam cleanup"], ["Giveaway bot", "prizes & rerolls"], ["Leveling bot", "XP & level roles"], ["Sticky / schedule bot", "pinned & timed posts"], ["Logging bot", "edits & deletions"]] },
  },
  bg: {
    tour: { heading: "Таблото, наистина.", sub: "Не макети — истински снимки на текущото табло, попълнено с демо данни.", labels: ["Преглед", "Тикети", "Панели", "Форми", "Анализи", "Premium"], alts: ["Преглед на сървъра — статистики, отворени тикети и състояние на системата", "Списък с тикети със статуси, отговорници и оценки", "Тикет панели с бутони, роли за поддръжка и канала, в който са", "Форми за кандидатстване с въпросите им", "Анализи на тикетите — топлинна карта, класация на екипа и фуния на кандидатурите", "Планът Premium и плащане през Discord"] },
    replace: { heading: "Заменете ги. Всичките.", strike: "8 бота, 8 табла, 8 комплекта права, 8 канала за поддръжка.", tagline: "Един бот. Едно табло. Един абонамент.", items: [["Тикет бот", "тикети и архиви"], ["Бот за кандидатури", "форми и преглед"], ["Бот за верификация", "captcha и роли"], ["Анти-спам бот", "чистене на измами"], ["Бот за раздавания", "награди и ново теглене"], ["Бот за нива", "XP и роли за ниво"], ["Бот за закачени/планирани", "закачени и планирани съобщения"], ["Бот за дневник", "редакции и изтривания"]] },
  },
  de: {
    tour: { heading: "Das Dashboard, ganz echt.", sub: "Keine Mockups — echte Screenshots des aktuellen Dashboards, mit Demodaten gefüllt.", labels: ["Übersicht", "Tickets", "Panels", "Formulare", "Analysen", "Premium"], alts: ["Server-Übersicht — Statistiken, offene Tickets und Systemstatus", "Ticketliste mit Status, Zuständigen und Bewertungen", "Ticket-Panels mit Buttons, Support-Rollen und ihrem Kanal", "Bewerbungsformulare mit ihren Fragen", "Ticket-Analysen — Heatmap, Team-Rangliste und Bewerbungs-Funnel", "Premium-Plan und Abrechnung über Discord"] },
    replace: { heading: "Ersetze sie. Alle.", strike: "8 Bots, 8 Dashboards, 8 Rechte-Sets, 8 Support-Kanäle.", tagline: "Ein Bot. Ein Dashboard. Ein Abo.", items: [["Ticket-Bot", "Tickets & Transkripte"], ["Bewerbungs-Bot", "Formulare & Prüfung"], ["Verifizierungs-Bot", "Captcha & Rollen"], ["Anti-Spam-Bot", "Betrug entfernen"], ["Gewinnspiel-Bot", "Preise & Neuziehung"], ["Level-Bot", "XP & Level-Rollen"], ["Sticky-/Zeitplan-Bot", "angepinnte & geplante Posts"], ["Log-Bot", "Bearbeitungen & Löschungen"]] },
  },
  es: {
    tour: { heading: "El panel, de verdad.", sub: "Nada de maquetas: capturas reales del panel actual, con datos de demostración.", labels: ["Resumen", "Tickets", "Paneles", "Formularios", "Analítica", "Premium"], alts: ["Resumen del servidor — estadísticas, tickets abiertos y estado del sistema", "Lista de tickets con estados, responsables y valoraciones", "Paneles de tickets con botones, roles de soporte y su canal", "Formularios de solicitud con sus preguntas", "Analítica de tickets — mapa de calor, ranking del equipo y embudo de solicitudes", "Plan Premium y facturación a través de Discord"] },
    replace: { heading: "Sustitúyelos. A todos.", strike: "8 bots, 8 paneles, 8 conjuntos de permisos, 8 canales de soporte.", tagline: "Un bot. Un panel. Una suscripción.", items: [["Bot de tickets", "tickets y transcripciones"], ["Bot de solicitudes", "formularios y revisión"], ["Bot de verificación", "captcha y roles"], ["Bot anti-spam", "limpieza de estafas"], ["Bot de sorteos", "premios y nuevos sorteos"], ["Bot de niveles", "XP y roles por nivel"], ["Bot de fijados/programados", "mensajes fijados y programados"], ["Bot de registros", "ediciones y borrados"]] },
  },
  fr: {
    tour: { heading: "Le tableau de bord, pour de vrai.", sub: "Pas de maquettes : de vraies captures du tableau de bord actuel, rempli de données de démo.", labels: ["Aperçu", "Tickets", "Panneaux", "Formulaires", "Analyses", "Premium"], alts: ["Aperçu du serveur — statistiques, tickets ouverts et état du système", "Liste des tickets avec statuts, responsables et notes", "Panneaux de tickets avec boutons, rôles de support et leur salon", "Formulaires de candidature et leurs questions", "Analyses des tickets — carte de chaleur, classement de l'équipe et entonnoir des candidatures", "Offre Premium et facturation via Discord"] },
    replace: { heading: "Remplacez-les. Tous.", strike: "8 bots, 8 tableaux de bord, 8 jeux de permissions, 8 salons de support.", tagline: "Un bot. Un tableau de bord. Un abonnement.", items: [["Bot de tickets", "tickets et transcriptions"], ["Bot de candidatures", "formulaires et examen"], ["Bot de vérification", "captcha et rôles"], ["Bot anti-spam", "nettoyage des arnaques"], ["Bot de concours", "lots et retirages"], ["Bot de niveaux", "XP et rôles de niveau"], ["Bot épinglés/programmés", "messages épinglés et programmés"], ["Bot de journal", "modifications et suppressions"]] },
  },
  it: {
    tour: { heading: "La dashboard, davvero.", sub: "Niente mockup: screenshot reali della dashboard attuale, con dati dimostrativi.", labels: ["Panoramica", "Ticket", "Pannelli", "Moduli", "Analisi", "Premium"], alts: ["Panoramica del server — statistiche, ticket aperti e stato del sistema", "Elenco dei ticket con stati, assegnatari e valutazioni", "Pannelli ticket con pulsanti, ruoli di supporto e il loro canale", "Moduli di candidatura con le loro domande", "Analisi dei ticket — heatmap, classifica dello staff e funnel delle candidature", "Piano Premium e fatturazione tramite Discord"] },
    replace: { heading: "Sostituiscili. Tutti.", strike: "8 bot, 8 dashboard, 8 set di permessi, 8 canali di supporto.", tagline: "Un bot. Una dashboard. Un abbonamento.", items: [["Bot ticket", "ticket e trascrizioni"], ["Bot candidature", "moduli e revisione"], ["Bot di verifica", "captcha e ruoli"], ["Bot anti-spam", "pulizia delle truffe"], ["Bot giveaway", "premi e ri-estrazioni"], ["Bot livelli", "XP e ruoli per livello"], ["Bot fissati/programmati", "messaggi fissati e programmati"], ["Bot di log", "modifiche ed eliminazioni"]] },
  },
  nl: {
    tour: { heading: "Het dashboard, echt.", sub: "Geen mock-ups — echte screenshots van het huidige dashboard, gevuld met demodata.", labels: ["Overzicht", "Tickets", "Panelen", "Formulieren", "Analyses", "Premium"], alts: ["Serveroverzicht — statistieken, open tickets en systeemstatus", "Ticketlijst met statussen, behandelaars en beoordelingen", "Ticketpanelen met knoppen, supportrollen en hun kanaal", "Sollicitatieformulieren met hun vragen", "Ticketanalyses — heatmap, teamranglijst en sollicitatiefunnel", "Premium-abonnement en facturering via Discord"] },
    replace: { heading: "Vervang ze. Allemaal.", strike: "8 bots, 8 dashboards, 8 sets rechten, 8 supportkanalen.", tagline: "Eén bot. Eén dashboard. Eén abonnement.", items: [["Ticketbot", "tickets & transcripties"], ["Sollicitatiebot", "formulieren & beoordeling"], ["Verificatiebot", "captcha & rollen"], ["Anti-spambot", "oplichting opruimen"], ["Giveawaybot", "prijzen & hertrekking"], ["Levelbot", "XP & levelrollen"], ["Sticky-/planningsbot", "vastgezette & geplande berichten"], ["Logbot", "bewerkingen & verwijderingen"]] },
  },
  pl: {
    tour: { heading: "Panel, naprawdę.", sub: "Żadnych makiet — prawdziwe zrzuty obecnego panelu, wypełnionego danymi demo.", labels: ["Przegląd", "Tickety", "Panele", "Formularze", "Analityka", "Premium"], alts: ["Przegląd serwera — statystyki, otwarte tickety i stan systemu", "Lista ticketów ze statusami, osobami przypisanymi i ocenami", "Panele ticketów z przyciskami, rolami wsparcia i ich kanałem", "Formularze rekrutacyjne z pytaniami", "Analityka ticketów — mapa cieplna, ranking ekipy i lejek rekrutacji", "Plan Premium i rozliczenia przez Discorda"] },
    replace: { heading: "Zastąp je. Wszystkie.", strike: "8 botów, 8 paneli, 8 zestawów uprawnień, 8 kanałów wsparcia.", tagline: "Jeden bot. Jeden panel. Jedna subskrypcja.", items: [["Bot ticketów", "tickety i transkrypcje"], ["Bot rekrutacji", "formularze i ocena"], ["Bot weryfikacji", "captcha i role"], ["Bot antyspamowy", "sprzątanie oszustw"], ["Bot konkursów", "nagrody i ponowne losowanie"], ["Bot poziomów", "XP i role za poziom"], ["Bot przypiętych/planowanych", "posty przypięte i planowane"], ["Bot logów", "edycje i usunięcia"]] },
  },
};
