// Структурирани (контролирани) медицински списъци с двуезични етикети, за да
// може чужд спешен екип да разчете най-честите алергии и състояния. Свободният
// текст остава за всичко извън списъка (без автоматичен превод — опасно).

export const ALLERGIES = [
  // Лекарства
  { key: 'penicillin', bg: 'Пеницилин', en: 'Penicillin' },
  { key: 'cephalosporins', bg: 'Цефалоспорини', en: 'Cephalosporins' },
  { key: 'sulfonamides', bg: 'Сулфонамиди', en: 'Sulfonamides' },
  { key: 'tetracyclines', bg: 'Тетрациклини', en: 'Tetracyclines' },
  { key: 'macrolides', bg: 'Макролиди (еритромицин)', en: 'Macrolides (erythromycin)' },
  { key: 'quinolones', bg: 'Хинолони (ципрофлоксацин)', en: 'Quinolones (ciprofloxacin)' },
  { key: 'nsaid', bg: 'НСПВС (ибупрофен и др.)', en: 'NSAIDs (ibuprofen etc.)' },
  { key: 'aspirin', bg: 'Аспирин', en: 'Aspirin' },
  { key: 'codeine', bg: 'Кодеин', en: 'Codeine' },
  { key: 'opioids', bg: 'Морфин / опиоиди', en: 'Morphine / opioids' },
  { key: 'anesthetics', bg: 'Анестетици (обща упойка)', en: 'Anaesthetics (general)' },
  { key: 'lidocaine', bg: 'Местни упойки (лидокаин)', en: 'Local anaesthetics (lidocaine)' },
  { key: 'insulin', bg: 'Инсулин', en: 'Insulin' },
  { key: 'heparin', bg: 'Хепарин', en: 'Heparin' },
  { key: 'anticonvulsants', bg: 'Антиконвулсанти', en: 'Anticonvulsants' },
  { key: 'chemo', bg: 'Химиотерапевтици', en: 'Chemotherapy agents' },
  { key: 'iodine', bg: 'Йод / контрастна материя', en: 'Iodine / contrast dye' },
  { key: 'chlorhexidine', bg: 'Хлорхексидин', en: 'Chlorhexidine' },
  // Контакт / материали
  { key: 'latex', bg: 'Латекс', en: 'Latex' },
  { key: 'adhesive', bg: 'Лепенки / пластири', en: 'Adhesive plasters' },
  { key: 'nickel', bg: 'Никел', en: 'Nickel' },
  // Храни
  { key: 'peanuts', bg: 'Фъстъци', en: 'Peanuts' },
  { key: 'nuts', bg: 'Ядки', en: 'Tree nuts' },
  { key: 'sesame', bg: 'Сусам', en: 'Sesame' },
  { key: 'soy', bg: 'Соя', en: 'Soy' },
  { key: 'shellfish', bg: 'Морски дарове / ракообразни', en: 'Shellfish' },
  { key: 'fish', bg: 'Риба', en: 'Fish' },
  { key: 'eggs', bg: 'Яйца', en: 'Eggs' },
  { key: 'milk', bg: 'Мляко (лактоза)', en: 'Milk (lactose)' },
  { key: 'gluten', bg: 'Глутен', en: 'Gluten' },
  { key: 'wheat', bg: 'Пшеница', en: 'Wheat' },
  { key: 'gelatin', bg: 'Желатин', en: 'Gelatin' },
  // Околна среда / други
  { key: 'bee', bg: 'Ужилване от пчела/оса', en: 'Bee/wasp stings' },
  { key: 'pollen', bg: 'Полени', en: 'Pollen' },
  { key: 'dust_mites', bg: 'Домашен прах (акари)', en: 'Dust mites' },
  { key: 'animal_dander', bg: 'Животински косми', en: 'Animal dander' },
  { key: 'mold', bg: 'Плесени', en: 'Mould' },
];

export const CONDITIONS = [
  { key: 'diabetes_t1', bg: 'Диабет тип 1', en: 'Type 1 diabetes' },
  { key: 'diabetes_t2', bg: 'Диабет тип 2', en: 'Type 2 diabetes' },
  { key: 'epilepsy', bg: 'Епилепсия', en: 'Epilepsy' },
  { key: 'asthma', bg: 'Астма', en: 'Asthma' },
  { key: 'copd', bg: 'ХОББ', en: 'COPD' },
  { key: 'heart', bg: 'Сърдечно заболяване', en: 'Heart disease' },
  { key: 'hypertension', bg: 'Високо кръвно налягане', en: 'Hypertension' },
  { key: 'arrhythmia', bg: 'Аритмия', en: 'Arrhythmia' },
  { key: 'pacemaker', bg: 'Пейсмейкър', en: 'Pacemaker' },
  { key: 'stroke', bg: 'Прекаран инсулт', en: 'Previous stroke' },
  { key: 'anticoagulants', bg: 'Прием на антикоагуланти', en: 'On anticoagulants' },
  { key: 'kidney', bg: 'Бъбречно заболяване', en: 'Kidney disease' },
  { key: 'liver', bg: 'Чернодробно заболяване', en: 'Liver disease' },
  { key: 'thyroid', bg: 'Заболяване на щитовидната жлеза', en: 'Thyroid disorder' },
  { key: 'pregnancy', bg: 'Бременност', en: 'Pregnancy' },
  { key: 'hemophilia', bg: 'Хемофилия', en: 'Haemophilia' },
  { key: 'cancer', bg: 'Онкологично заболяване', en: 'Cancer' },
];

// Всички държави по света (ISO код, код за избиране, BG/EN име).
export const COUNTRIES = [
  { iso: 'AF', dial: '+93', bg: 'Афганистан', en: 'Afghanistan' },
  { iso: 'AL', dial: '+355', bg: 'Албания', en: 'Albania' },
  { iso: 'DZ', dial: '+213', bg: 'Алжир', en: 'Algeria' },
  { iso: 'AD', dial: '+376', bg: 'Андора', en: 'Andorra' },
  { iso: 'AO', dial: '+244', bg: 'Ангола', en: 'Angola' },
  { iso: 'AG', dial: '+1', bg: 'Антигуа и Барбуда', en: 'Antigua and Barbuda' },
  { iso: 'AR', dial: '+54', bg: 'Аржентина', en: 'Argentina' },
  { iso: 'AM', dial: '+374', bg: 'Армения', en: 'Armenia' },
  { iso: 'AU', dial: '+61', bg: 'Австралия', en: 'Australia' },
  { iso: 'AT', dial: '+43', bg: 'Австрия', en: 'Austria' },
  { iso: 'AZ', dial: '+994', bg: 'Азербайджан', en: 'Azerbaijan' },
  { iso: 'BS', dial: '+1', bg: 'Бахами', en: 'Bahamas' },
  { iso: 'BH', dial: '+973', bg: 'Бахрейн', en: 'Bahrain' },
  { iso: 'BD', dial: '+880', bg: 'Бангладеш', en: 'Bangladesh' },
  { iso: 'BB', dial: '+1', bg: 'Барбадос', en: 'Barbados' },
  { iso: 'BY', dial: '+375', bg: 'Беларус', en: 'Belarus' },
  { iso: 'BE', dial: '+32', bg: 'Белгия', en: 'Belgium' },
  { iso: 'BZ', dial: '+501', bg: 'Белиз', en: 'Belize' },
  { iso: 'BJ', dial: '+229', bg: 'Бенин', en: 'Benin' },
  { iso: 'BT', dial: '+975', bg: 'Бутан', en: 'Bhutan' },
  { iso: 'BO', dial: '+591', bg: 'Боливия', en: 'Bolivia' },
  { iso: 'BA', dial: '+387', bg: 'Босна и Херцеговина', en: 'Bosnia and Herzegovina' },
  { iso: 'BW', dial: '+267', bg: 'Ботсвана', en: 'Botswana' },
  { iso: 'BR', dial: '+55', bg: 'Бразилия', en: 'Brazil' },
  { iso: 'BN', dial: '+673', bg: 'Бруней', en: 'Brunei' },
  { iso: 'BG', dial: '+359', bg: 'България', en: 'Bulgaria' },
  { iso: 'BF', dial: '+226', bg: 'Буркина Фасо', en: 'Burkina Faso' },
  { iso: 'BI', dial: '+257', bg: 'Бурунди', en: 'Burundi' },
  { iso: 'CV', dial: '+238', bg: 'Кабо Верде', en: 'Cabo Verde' },
  { iso: 'KH', dial: '+855', bg: 'Камбоджа', en: 'Cambodia' },
  { iso: 'CM', dial: '+237', bg: 'Камерун', en: 'Cameroon' },
  { iso: 'CA', dial: '+1', bg: 'Канада', en: 'Canada' },
  { iso: 'CF', dial: '+236', bg: 'Централноафриканска република', en: 'Central African Republic' },
  { iso: 'TD', dial: '+235', bg: 'Чад', en: 'Chad' },
  { iso: 'CL', dial: '+56', bg: 'Чили', en: 'Chile' },
  { iso: 'CN', dial: '+86', bg: 'Китай', en: 'China' },
  { iso: 'CO', dial: '+57', bg: 'Колумбия', en: 'Colombia' },
  { iso: 'KM', dial: '+269', bg: 'Коморски острови', en: 'Comoros' },
  { iso: 'CG', dial: '+242', bg: 'Конго (Бразавил)', en: 'Congo (Republic)' },
  { iso: 'CD', dial: '+243', bg: 'Конго (ДР Конго)', en: 'Congo (DRC)' },
  { iso: 'CR', dial: '+506', bg: 'Коста Рика', en: 'Costa Rica' },
  { iso: 'CI', dial: '+225', bg: 'Кот д’Ивоар', en: 'Côte d’Ivoire' },
  { iso: 'HR', dial: '+385', bg: 'Хърватия', en: 'Croatia' },
  { iso: 'CU', dial: '+53', bg: 'Куба', en: 'Cuba' },
  { iso: 'CY', dial: '+357', bg: 'Кипър', en: 'Cyprus' },
  { iso: 'CZ', dial: '+420', bg: 'Чехия', en: 'Czechia' },
  { iso: 'DK', dial: '+45', bg: 'Дания', en: 'Denmark' },
  { iso: 'DJ', dial: '+253', bg: 'Джибути', en: 'Djibouti' },
  { iso: 'DM', dial: '+1', bg: 'Доминика', en: 'Dominica' },
  { iso: 'DO', dial: '+1', bg: 'Доминиканска република', en: 'Dominican Republic' },
  { iso: 'EC', dial: '+593', bg: 'Еквадор', en: 'Ecuador' },
  { iso: 'EG', dial: '+20', bg: 'Египет', en: 'Egypt' },
  { iso: 'SV', dial: '+503', bg: 'Салвадор', en: 'El Salvador' },
  { iso: 'GQ', dial: '+240', bg: 'Екваториална Гвинея', en: 'Equatorial Guinea' },
  { iso: 'ER', dial: '+291', bg: 'Еритрея', en: 'Eritrea' },
  { iso: 'EE', dial: '+372', bg: 'Естония', en: 'Estonia' },
  { iso: 'SZ', dial: '+268', bg: 'Есватини', en: 'Eswatini' },
  { iso: 'ET', dial: '+251', bg: 'Етиопия', en: 'Ethiopia' },
  { iso: 'FJ', dial: '+679', bg: 'Фиджи', en: 'Fiji' },
  { iso: 'FI', dial: '+358', bg: 'Финландия', en: 'Finland' },
  { iso: 'FR', dial: '+33', bg: 'Франция', en: 'France' },
  { iso: 'GA', dial: '+241', bg: 'Габон', en: 'Gabon' },
  { iso: 'GM', dial: '+220', bg: 'Гамбия', en: 'Gambia' },
  { iso: 'GE', dial: '+995', bg: 'Грузия', en: 'Georgia' },
  { iso: 'DE', dial: '+49', bg: 'Германия', en: 'Germany' },
  { iso: 'GH', dial: '+233', bg: 'Гана', en: 'Ghana' },
  { iso: 'GR', dial: '+30', bg: 'Гърция', en: 'Greece' },
  { iso: 'GD', dial: '+1', bg: 'Гренада', en: 'Grenada' },
  { iso: 'GT', dial: '+502', bg: 'Гватемала', en: 'Guatemala' },
  { iso: 'GN', dial: '+224', bg: 'Гвинея', en: 'Guinea' },
  { iso: 'GW', dial: '+245', bg: 'Гвинея-Бисау', en: 'Guinea-Bissau' },
  { iso: 'GY', dial: '+592', bg: 'Гаяна', en: 'Guyana' },
  { iso: 'HT', dial: '+509', bg: 'Хаити', en: 'Haiti' },
  { iso: 'HN', dial: '+504', bg: 'Хондурас', en: 'Honduras' },
  { iso: 'HU', dial: '+36', bg: 'Унгария', en: 'Hungary' },
  { iso: 'IS', dial: '+354', bg: 'Исландия', en: 'Iceland' },
  { iso: 'IN', dial: '+91', bg: 'Индия', en: 'India' },
  { iso: 'ID', dial: '+62', bg: 'Индонезия', en: 'Indonesia' },
  { iso: 'IR', dial: '+98', bg: 'Иран', en: 'Iran' },
  { iso: 'IQ', dial: '+964', bg: 'Ирак', en: 'Iraq' },
  { iso: 'IE', dial: '+353', bg: 'Ирландия', en: 'Ireland' },
  { iso: 'IL', dial: '+972', bg: 'Израел', en: 'Israel' },
  { iso: 'IT', dial: '+39', bg: 'Италия', en: 'Italy' },
  { iso: 'JM', dial: '+1', bg: 'Ямайка', en: 'Jamaica' },
  { iso: 'JP', dial: '+81', bg: 'Япония', en: 'Japan' },
  { iso: 'JO', dial: '+962', bg: 'Йордания', en: 'Jordan' },
  { iso: 'KZ', dial: '+7', bg: 'Казахстан', en: 'Kazakhstan' },
  { iso: 'KE', dial: '+254', bg: 'Кения', en: 'Kenya' },
  { iso: 'KI', dial: '+686', bg: 'Кирибати', en: 'Kiribati' },
  { iso: 'KW', dial: '+965', bg: 'Кувейт', en: 'Kuwait' },
  { iso: 'KG', dial: '+996', bg: 'Киргизстан', en: 'Kyrgyzstan' },
  { iso: 'LA', dial: '+856', bg: 'Лаос', en: 'Laos' },
  { iso: 'LV', dial: '+371', bg: 'Латвия', en: 'Latvia' },
  { iso: 'LB', dial: '+961', bg: 'Ливан', en: 'Lebanon' },
  { iso: 'LS', dial: '+266', bg: 'Лесото', en: 'Lesotho' },
  { iso: 'LR', dial: '+231', bg: 'Либерия', en: 'Liberia' },
  { iso: 'LY', dial: '+218', bg: 'Либия', en: 'Libya' },
  { iso: 'LI', dial: '+423', bg: 'Лихтенщайн', en: 'Liechtenstein' },
  { iso: 'LT', dial: '+370', bg: 'Литва', en: 'Lithuania' },
  { iso: 'LU', dial: '+352', bg: 'Люксембург', en: 'Luxembourg' },
  { iso: 'MG', dial: '+261', bg: 'Мадагаскар', en: 'Madagascar' },
  { iso: 'MW', dial: '+265', bg: 'Малави', en: 'Malawi' },
  { iso: 'MY', dial: '+60', bg: 'Малайзия', en: 'Malaysia' },
  { iso: 'MV', dial: '+960', bg: 'Малдиви', en: 'Maldives' },
  { iso: 'ML', dial: '+223', bg: 'Мали', en: 'Mali' },
  { iso: 'MT', dial: '+356', bg: 'Малта', en: 'Malta' },
  { iso: 'MH', dial: '+692', bg: 'Маршалови острови', en: 'Marshall Islands' },
  { iso: 'MR', dial: '+222', bg: 'Мавритания', en: 'Mauritania' },
  { iso: 'MU', dial: '+230', bg: 'Мавриций', en: 'Mauritius' },
  { iso: 'MX', dial: '+52', bg: 'Мексико', en: 'Mexico' },
  { iso: 'FM', dial: '+691', bg: 'Микронезия', en: 'Micronesia' },
  { iso: 'MD', dial: '+373', bg: 'Молдова', en: 'Moldova' },
  { iso: 'MC', dial: '+377', bg: 'Монако', en: 'Monaco' },
  { iso: 'MN', dial: '+976', bg: 'Монголия', en: 'Mongolia' },
  { iso: 'ME', dial: '+382', bg: 'Черна гора', en: 'Montenegro' },
  { iso: 'MA', dial: '+212', bg: 'Мароко', en: 'Morocco' },
  { iso: 'MZ', dial: '+258', bg: 'Мозамбик', en: 'Mozambique' },
  { iso: 'MM', dial: '+95', bg: 'Мианмар', en: 'Myanmar' },
  { iso: 'NA', dial: '+264', bg: 'Намибия', en: 'Namibia' },
  { iso: 'NR', dial: '+674', bg: 'Науру', en: 'Nauru' },
  { iso: 'NP', dial: '+977', bg: 'Непал', en: 'Nepal' },
  { iso: 'NL', dial: '+31', bg: 'Нидерландия', en: 'Netherlands' },
  { iso: 'NZ', dial: '+64', bg: 'Нова Зеландия', en: 'New Zealand' },
  { iso: 'NI', dial: '+505', bg: 'Никарагуа', en: 'Nicaragua' },
  { iso: 'NE', dial: '+227', bg: 'Нигер', en: 'Niger' },
  { iso: 'NG', dial: '+234', bg: 'Нигерия', en: 'Nigeria' },
  { iso: 'KP', dial: '+850', bg: 'Северна Корея', en: 'North Korea' },
  { iso: 'MK', dial: '+389', bg: 'Северна Македония', en: 'North Macedonia' },
  { iso: 'NO', dial: '+47', bg: 'Норвегия', en: 'Norway' },
  { iso: 'OM', dial: '+968', bg: 'Оман', en: 'Oman' },
  { iso: 'PK', dial: '+92', bg: 'Пакистан', en: 'Pakistan' },
  { iso: 'PW', dial: '+680', bg: 'Палау', en: 'Palau' },
  { iso: 'PS', dial: '+970', bg: 'Палестина', en: 'Palestine' },
  { iso: 'PA', dial: '+507', bg: 'Панама', en: 'Panama' },
  { iso: 'PG', dial: '+675', bg: 'Папуа Нова Гвинея', en: 'Papua New Guinea' },
  { iso: 'PY', dial: '+595', bg: 'Парагвай', en: 'Paraguay' },
  { iso: 'PE', dial: '+51', bg: 'Перу', en: 'Peru' },
  { iso: 'PH', dial: '+63', bg: 'Филипини', en: 'Philippines' },
  { iso: 'PL', dial: '+48', bg: 'Полша', en: 'Poland' },
  { iso: 'PT', dial: '+351', bg: 'Португалия', en: 'Portugal' },
  { iso: 'QA', dial: '+974', bg: 'Катар', en: 'Qatar' },
  { iso: 'RO', dial: '+40', bg: 'Румъния', en: 'Romania' },
  { iso: 'RU', dial: '+7', bg: 'Русия', en: 'Russia' },
  { iso: 'RW', dial: '+250', bg: 'Руанда', en: 'Rwanda' },
  { iso: 'KN', dial: '+1', bg: 'Сейнт Китс и Невис', en: 'Saint Kitts and Nevis' },
  { iso: 'LC', dial: '+1', bg: 'Сейнт Лусия', en: 'Saint Lucia' },
  {
    iso: 'VC',
    dial: '+1',
    bg: 'Сейнт Винсент и Гренадини',
    en: 'Saint Vincent and the Grenadines',
  },
  { iso: 'WS', dial: '+685', bg: 'Самоа', en: 'Samoa' },
  { iso: 'SM', dial: '+378', bg: 'Сан Марино', en: 'San Marino' },
  { iso: 'ST', dial: '+239', bg: 'Сао Томе и Принсипи', en: 'Sao Tome and Principe' },
  { iso: 'SA', dial: '+966', bg: 'Саудитска Арабия', en: 'Saudi Arabia' },
  { iso: 'SN', dial: '+221', bg: 'Сенегал', en: 'Senegal' },
  { iso: 'RS', dial: '+381', bg: 'Сърбия', en: 'Serbia' },
  { iso: 'SC', dial: '+248', bg: 'Сейшели', en: 'Seychelles' },
  { iso: 'SL', dial: '+232', bg: 'Сиера Леоне', en: 'Sierra Leone' },
  { iso: 'SG', dial: '+65', bg: 'Сингапур', en: 'Singapore' },
  { iso: 'SK', dial: '+421', bg: 'Словакия', en: 'Slovakia' },
  { iso: 'SI', dial: '+386', bg: 'Словения', en: 'Slovenia' },
  { iso: 'SB', dial: '+677', bg: 'Соломонови острови', en: 'Solomon Islands' },
  { iso: 'SO', dial: '+252', bg: 'Сомалия', en: 'Somalia' },
  { iso: 'ZA', dial: '+27', bg: 'Южна Африка', en: 'South Africa' },
  { iso: 'KR', dial: '+82', bg: 'Южна Корея', en: 'South Korea' },
  { iso: 'SS', dial: '+211', bg: 'Южен Судан', en: 'South Sudan' },
  { iso: 'ES', dial: '+34', bg: 'Испания', en: 'Spain' },
  { iso: 'LK', dial: '+94', bg: 'Шри Ланка', en: 'Sri Lanka' },
  { iso: 'SD', dial: '+249', bg: 'Судан', en: 'Sudan' },
  { iso: 'SR', dial: '+597', bg: 'Суринам', en: 'Suriname' },
  { iso: 'SE', dial: '+46', bg: 'Швеция', en: 'Sweden' },
  { iso: 'CH', dial: '+41', bg: 'Швейцария', en: 'Switzerland' },
  { iso: 'SY', dial: '+963', bg: 'Сирия', en: 'Syria' },
  { iso: 'TW', dial: '+886', bg: 'Тайван', en: 'Taiwan' },
  { iso: 'TJ', dial: '+992', bg: 'Таджикистан', en: 'Tajikistan' },
  { iso: 'TZ', dial: '+255', bg: 'Танзания', en: 'Tanzania' },
  { iso: 'TH', dial: '+66', bg: 'Тайланд', en: 'Thailand' },
  { iso: 'TL', dial: '+670', bg: 'Източен Тимор', en: 'Timor-Leste' },
  { iso: 'TG', dial: '+228', bg: 'Того', en: 'Togo' },
  { iso: 'TO', dial: '+676', bg: 'Тонга', en: 'Tonga' },
  { iso: 'TT', dial: '+1', bg: 'Тринидад и Тобаго', en: 'Trinidad and Tobago' },
  { iso: 'TN', dial: '+216', bg: 'Тунис', en: 'Tunisia' },
  { iso: 'TR', dial: '+90', bg: 'Турция', en: 'Turkey' },
  { iso: 'TM', dial: '+993', bg: 'Туркменистан', en: 'Turkmenistan' },
  { iso: 'TV', dial: '+688', bg: 'Тувалу', en: 'Tuvalu' },
  { iso: 'UG', dial: '+256', bg: 'Уганда', en: 'Uganda' },
  { iso: 'UA', dial: '+380', bg: 'Украйна', en: 'Ukraine' },
  { iso: 'AE', dial: '+971', bg: 'Обединени арабски емирства', en: 'United Arab Emirates' },
  { iso: 'GB', dial: '+44', bg: 'Великобритания', en: 'United Kingdom' },
  { iso: 'US', dial: '+1', bg: 'САЩ', en: 'United States' },
  { iso: 'UY', dial: '+598', bg: 'Уругвай', en: 'Uruguay' },
  { iso: 'UZ', dial: '+998', bg: 'Узбекистан', en: 'Uzbekistan' },
  { iso: 'VU', dial: '+678', bg: 'Вануату', en: 'Vanuatu' },
  { iso: 'VA', dial: '+379', bg: 'Ватикана', en: 'Vatican City' },
  { iso: 'VE', dial: '+58', bg: 'Венецуела', en: 'Venezuela' },
  { iso: 'VN', dial: '+84', bg: 'Виетнам', en: 'Vietnam' },
  { iso: 'YE', dial: '+967', bg: 'Йемен', en: 'Yemen' },
  { iso: 'ZM', dial: '+260', bg: 'Замбия', en: 'Zambia' },
  { iso: 'ZW', dial: '+263', bg: 'Зимбабве', en: 'Zimbabwe' },
];

const labelOf = (list, key, lang) => {
  const it = list.find((x) => x.key === key);
  return it ? (lang === 'en' ? it.en : it.bg) : key;
};

// CSV от ключове → масив от преведени етикети (за показване).
export function medLabels(list, csv, lang) {
  return String(csv || '')
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean)
    .map((k) => labelOf(list, k, lang));
}

// Държавите подредени по име на избрания език, с България най-отгоре.
export function sortedCountries(lang) {
  const name = (c) => (lang === 'en' ? c.en : c.bg);
  const arr = [...COUNTRIES].sort((a, b) =>
    name(a).localeCompare(name(b), lang === 'en' ? 'en' : 'bg')
  );
  const i = arr.findIndex((c) => c.iso === 'BG');
  if (i > 0) arr.unshift(arr.splice(i, 1)[0]);
  return arr;
}
