// FONTE DATI UNICA delle tavole di collegamento: morsettiere, cavi, dispositivi, distinta.
// Tutti i fogli (E00–E18) leggono da qui, così morsetti, fili e cavi restano coerenti.
// Caso di riferimento (ipotesi di esempio, da verificare con i dati di targa): trazione con motore asincrono 7,5 kW,
// inverter classe 11 kW / 24 A (dato di catalogo in 03-costi.md), 12 fermate espandibili a 24.

export const PROJ = {
  commessa: 'CS-QDM-001 (esempio)',
  impianto: 'Ascensore a trazione elettrica, 12 fermate (espandibile a 24)',
  rete: '3~ 400 V + N + PE · 50 Hz',
};

// Colori dei conduttori (EN 60204-1: nero potenza, rosso comando c.a., blu comando c.c., arancio interblocco,
// azzurro neutro, giallo/verde PE). La marcatura è DA VERIFICARE sul testo della norma (non appresa).
export const COLORS = {
  PW: 'nero',
  AC: 'rosso',
  DC: 'blu',
  IL: 'arancio',
  N: 'azzurro',
  PE: 'giallo/verde',
  SH: 'schermo',
  NU: 'numerato',
};

// Intervalli dei numeri di filo per foglio (nessuna collisione).
export const WIRE_RANGES = {
  E01: [100, 199], E02: [200, 299], E03: [300, 399], E04: [400, 449], E05: [450, 499], E06: [500, 599],
  E07: [600, 699], E08: [700, 799], E09: [800, 849], E10: [850, 899], E11: [900, 949], E12: [950, 999],
  E13: [1000, 1099], E14: [1100, 1199],
};

// Morsettiere. Riga: [morsetto, segnale, filo, colore, cavo, destinazione/origine, nota]
const R = (t, sig, w, c, cab, to, note = '') => ({ t, sig, w, c, cab, to, note });

export const STRIPS = {
  X1: {
    title: 'Potenza e macchina',
    sheet: 'E01',
    rows: [
      R('1', 'L1', '101', 'PW', 'W101', 'QGBT edificio', 'rete 3~'),
      R('2', 'L2', '102', 'PW', 'W101', 'QGBT edificio'),
      R('3', 'L3', '103', 'PW', 'W101', 'QGBT edificio'),
      R('4', 'N', '104', 'N', 'W101', 'QGBT edificio'),
      R('5', 'PE', 'PE', 'PE', 'W101', 'barra PE edificio'),
      R('11', 'U', '121', 'PW', 'W102', '-M1:U1', 'motore, cavo schermato'),
      R('12', 'V', '122', 'PW', 'W102', '-M1:V1'),
      R('13', 'W', '123', 'PW', 'W102', '-M1:W1'),
      R('14', 'PE', 'PE', 'PE', 'W102', '-M1:PE'),
      R('15', 'BR1+', '131', 'PW', 'W103', '-YB1:+', 'freno 1, c.c.'),
      R('16', 'BR1−', '132', 'PW', 'W103', '-YB1:−'),
      R('17', 'BR2+', '133', 'PW', 'W103', '-YB2:+', 'freno 2, c.c.'),
      R('18', 'BR2−', '134', 'PW', 'W103', '-YB2:−'),
      R('19', 'PTC1', '141', 'DC', 'W104', '-RT1:1', 'termistore motore'),
      R('20', 'PTC2', '142', 'DC', 'W104', '-RT1:2'),
    ],
  },
  X2: {
    title: 'Catena di sicurezza (campo)',
    sheet: 'E04',
    rows: [
      R('1', '+48 V → fossa', '401', 'DC', 'W201', '-SF1 (STOP fossa)', 'tratto A'),
      R('2', 'fossa → catena', '402', 'DC', 'W201', '-SF1 (STOP fossa)'),
      R('3', '+48 V → tetto', '403', 'DC', 'W210', 'XC:1 (STOP tetto, ispezione)', 'tratto A, cavo mobile'),
      R('4', 'tetto → catena', '404', 'DC', 'W210', 'XC:2'),
      R('5', 'limitatore →', '411', 'DC', 'W202', '-SG1 (limitatore di velocità)', 'tratto B'),
      R('6', '→ limitatore', '412', 'DC', 'W202', '-SG1'),
      R('7', 'paracadute →', '413', 'DC', 'W210', 'XC:3 (paracadute -SP1)', 'tratto B, cavo mobile'),
      R('8', '→ paracadute', '414', 'DC', 'W210', 'XC:4'),
      R('9', 'extracorsa →', '415', 'DC', 'W203', '-SQ1/-SQ2/-SQ3 (extracorsa, ammortizzatori)', 'tratto B'),
      R('10', '→ extracorsa', '416', 'DC', 'W203', '-SQ1/-SQ2/-SQ3'),
      R('11', 'serrature →', '421', 'DC', 'W204', 'XP1 (nodo di piano 1: ingresso catena)', 'tratto C'),
      R('12', '→ serrature (ritorno)', '422', 'DC', 'W204', 'XP12 (ultimo nodo: ritorno)'),
      R('13', 'porta cabina →', '431', 'DC', 'W210', 'XC:5 (-SD1 porta cabina)', 'tratto D, cavo mobile'),
      R('14', '→ porta cabina', '432', 'DC', 'W210', 'XC:6'),
      R('15', '0 V (48 V)', '400', 'DC', '—', 'rif. 0 V alimentatore -G1'),
    ],
  },
  X3: {
    title: 'Ingressi di campo (24 V c.c.)',
    sheet: 'E07',
    rows: [
      R('1', '+24 V campo', '601', 'DC', '—', 'distribuzione +24 V (-G2)'),
      R('2', '0 V campo', '602', 'DC', '—', 'distribuzione 0 V'),
      R('3', 'I11 rallent. alto', '611', 'DC', 'W205', '-SQ4 (vano)'),
      R('4', 'I12 rallent. basso', '612', 'DC', 'W205', '-SQ5 (vano)'),
      R('5', 'I13 ispezione attiva', '613', 'DC', 'W210', 'XC:7 (contatto aux commutatore)'),
      R('6', 'I14 chiave pompieri', '614', 'DC', 'W206', '-SK1 (piano designato)', 'anello fail-safe'),
      R('7', 'I15 sovraccarico', '615', 'DC', 'W210', 'XC:8 (pesacarico)'),
      R('8', 'I16 carico completo', '616', 'DC', 'W210', 'XC:9 (pesacarico)'),
      R('9', 'I23 porta aperta', '623', 'DC', 'W210', 'XC:10 (operatore porte)'),
      R('10', 'I24 porta chiusa', '624', 'DC', 'W210', 'XC:11 (operatore porte)'),
      R('11', 'I25 barriera/costa', '625', 'DC', 'W210', 'XC:12 (operatore porte)'),
      R('12', 'I26 allarme (copia)', '626', 'DC', 'W210', 'XC:13 (comunicatore)'),
      R('13', 'Encoder A', '631', 'DC', 'W105', '-B2:A', 'contatore veloce, coppia schermata'),
      R('14', 'Encoder /A', '632', 'DC', 'W105', '-B2:/A'),
      R('15', 'Encoder B', '633', 'DC', 'W105', '-B2:B'),
      R('16', 'Encoder /B', '634', 'DC', 'W105', '-B2:/B'),
      R('17', 'Encoder Z', '635', 'DC', 'W105', '-B2:Z'),
      R('18', 'Encoder /Z', '636', 'DC', 'W105', '-B2:/Z'),
      R('19', 'Encoder +V', '637', 'DC', 'W105', '-B2:+V'),
      R('20', 'Encoder 0 V', '638', 'DC', 'W105', '-B2:0V'),
      R('21', 'Pesacarico 4–20 mA +', '641', 'DC', 'W211', 'XC:14 (schermato)', 'ingresso analogico A0'),
      R('22', 'Pesacarico 4–20 mA −', '642', 'DC', 'W211', 'XC:15'),
      R('23', 'I27 ispezione: SALITA (serie con MARCIA)', '627', 'DC', 'W210', 'XC:36 (-SI2 + -SI4)'),
      R('24', 'I28 ispezione: DISCESA (serie con MARCIA)', '628', 'DC', 'W210', 'XC:37 (-SI3 + -SI4)'),
    ],
  },
  X4: {
    title: 'Uscite (consensi e comandi)',
    sheet: 'E08',
    rows: [
      R('1', 'Q10 porte: apri', '751', 'DC', 'W210', 'XC:16 (operatore porte)'),
      R('2', 'Q11 porte: chiudi', '752', 'DC', 'W210', 'XC:17 (operatore porte)'),
      R('3', 'Q12 luce cabina (comando)', '753', 'AC', 'W210', 'XC:18 (relè luce cabina)'),
      R('4', 'Q13 ventola', '754', 'DC', 'W207', '-M2 ventola cabina/quadro'),
      R('5', 'Q15 avvisatore fuori servizio', '755', 'DC', 'W207', '-HA1'),
      R('6', 'Q16 spia fuori servizio piano', '756', 'DC', 'W206', '-HL1 (piano principale)'),
      R('7', '+24 V uscite', '757', 'DC', '—', 'alimentazione carichi'),
      R('8', '0 V uscite', '758', 'DC', '—', 'riferimento'),
    ],
  },
  X5: {
    title: 'Bus CAN e comunicazioni',
    sheet: 'E09',
    rows: [
      R('1', 'CAN1 H (cabina)', '801', 'DC', 'W212', 'XC:19', 'coppia twistata 120 Ω'),
      R('2', 'CAN1 L (cabina)', '802', 'DC', 'W212', 'XC:20'),
      R('3', 'CAN1 schermo', '803', 'SH', 'W212', 'XC:21 (a terra solo lato quadro)'),
      R('4', 'CAN1 +24 V', '804', 'DC', 'W212', 'XC:22'),
      R('5', 'CAN1 0 V', '805', 'DC', 'W212', 'XC:23'),
      R('6', 'CAN2 H (piani)', '811', 'DC', 'W208', 'XP1:H', 'dorsale vano, coppia twistata 120 Ω'),
      R('7', 'CAN2 L (piani)', '812', 'DC', 'W208', 'XP1:L'),
      R('8', 'CAN2 schermo', '813', 'SH', 'W208', 'XP1:S (a terra solo lato quadro)'),
      R('9', 'CAN2 +24 V', '814', 'DC', 'W208', 'XP1:+'),
      R('10', 'CAN2 0 V', '815', 'DC', 'W208', 'XP1:−'),
    ],
  },
  X6: {
    title: 'Ausiliari 230 V e batteria',
    sheet: 'E03',
    rows: [
      R('1', 'L luce cabina (QF2)', '311', 'PW', 'W209', 'XC:24', 'a monte del generale'),
      R('2', 'N luce cabina', '312', 'N', 'W209', 'XC:25'),
      R('3', 'PE luce cabina', 'PE', 'PE', 'W209', 'XC:26'),
      R('4', 'L luce/prese vano (QF2)', '313', 'PW', 'W213', 'luce vano, prese fossa/tetto'),
      R('5', 'N luce/prese vano', '314', 'N', 'W213', ''),
      R('6', 'PE luce/prese vano', 'PE', 'PE', 'W213', ''),
      R('7', 'L porte (operatore)', '315', 'PW', 'W210', 'XC:27'),
      R('8', 'N porte (operatore)', '316', 'N', 'W210', 'XC:28'),
      R('9', 'PE porte', 'PE', 'PE', 'W210', 'XC:29'),
      R('10', 'Batteria + (ARD, luce emerg., allarme)', '331', 'DC', 'W214', '-G4 (batteria 12 V)'),
      R('11', 'Batteria −', '332', 'DC', 'W214', '-G4'),
    ],
  },
  XC: {
    title: 'Cabina — cavo mobile (conduttori numerati)',
    sheet: 'E10',
    rows: [
      R('1', 'Catena: tetto, uscita', '403', 'NU', 'W210', 'X2:3 → -SF2 STOP tetto'),
      R('2', 'Catena: tetto, ritorno', '404', 'NU', 'W210', 'X2:4 ← -SF3 ispezione'),
      R('3', 'Catena: paracadute, uscita', '413', 'NU', 'W210', 'X2:7 → -SP1'),
      R('4', 'Catena: paracadute, ritorno', '414', 'NU', 'W210', 'X2:8 ← -SP1'),
      R('5', 'Catena: porta cabina, uscita', '431', 'NU', 'W210', 'X2:13 → -SD1'),
      R('6', 'Catena: porta cabina, ritorno', '432', 'NU', 'W210', 'X2:14 ← -SD1'),
      R('7', 'Ispezione attiva (aux)', '613', 'NU', 'W210', 'X3:5'),
      R('8', 'Sovraccarico', '615', 'NU', 'W210', 'X3:7'),
      R('9', 'Carico completo', '616', 'NU', 'W210', 'X3:8'),
      R('10', 'Porta aperta', '623', 'NU', 'W210', 'X3:9'),
      R('11', 'Porta chiusa', '624', 'NU', 'W210', 'X3:10'),
      R('12', 'Barriera/costa', '625', 'NU', 'W210', 'X3:11'),
      R('13', 'Allarme (copia)', '626', 'NU', 'W210', 'X3:12'),
      R('14', 'Pesacarico 4–20 mA +', '641', 'NU', 'W211', 'X3:21 (coppia schermata)'),
      R('15', 'Pesacarico 4–20 mA −', '642', 'NU', 'W211', 'X3:22'),
      R('16', 'Porte: apri', '751', 'NU', 'W210', 'X4:1'),
      R('17', 'Porte: chiudi', '752', 'NU', 'W210', 'X4:2'),
      R('18', 'Luce cabina (comando)', '753', 'NU', 'W210', 'X4:3'),
      R('19', 'CAN1 H', '801', 'NU', 'W212', 'X5:1 (coppia twistata schermata)'),
      R('20', 'CAN1 L', '802', 'NU', 'W212', 'X5:2'),
      R('21', 'CAN1 schermo', '803', 'NU', 'W212', 'X5:3'),
      R('22', 'CAN1 +24 V', '804', 'NU', 'W212', 'X5:4'),
      R('23', 'CAN1 0 V', '805', 'NU', 'W212', 'X5:5'),
      R('24', 'Luce cabina L', '311', 'NU', 'W209', 'X6:1'),
      R('25', 'Luce cabina N', '312', 'NU', 'W209', 'X6:2'),
      R('26', 'Luce cabina PE', 'PE', 'NU', 'W209', 'X6:3'),
      R('27', 'Porte L', '315', 'NU', 'W210', 'X6:7'),
      R('28', 'Porte N', '316', 'NU', 'W210', 'X6:8'),
      R('29', 'Porte PE', 'PE', 'NU', 'W210', 'X6:9'),
      R('30', 'Citofono: fonia A', '1011', 'NU', 'W210', '-A6:A (comunicatore)'),
      R('31', 'Citofono: fonia B', '1012', 'NU', 'W210', '-A6:B'),
      R('32', 'Citofono: +24 V', '1013', 'NU', 'W210', '-A6:+'),
      R('33', 'Citofono: 0 V', '1014', 'NU', 'W210', '-A6:−'),
      R('34', 'Luce emergenza: carica +', '1021', 'NU', 'W210', '-EL1 (luce di emergenza)'),
      R('35', 'Luce emergenza: segnale', '1022', 'NU', 'W210', '-EL1'),
      R('36', 'Ispezione: SALITA (in serie con MARCIA)', '627', 'NU', 'W210', 'X3:23'),
      R('37', 'Ispezione: DISCESA (in serie con MARCIA)', '628', 'NU', 'W210', 'X3:24'),
      R('38', 'Ispezione: +24 V', '951', 'NU', 'W210', 'alimentazione pulsantiera tetto'),
      R('39', 'Ispezione: 0 V', '952', 'NU', 'W210', ''),
      R('40', 'Riserva', '—', 'NU', 'W210', ''),
      R('41', 'Zona porta: sensore 1', '961', 'NU', 'W210', '-BZ1 → modulo CE -A5'),
      R('42', 'Zona porta: sensore 2', '962', 'NU', 'W210', '-BZ2 → modulo CE -A5'),
      R('43', 'Zona porta: +24 V', '963', 'NU', 'W210', ''),
      R('44', 'Zona porta: 0 V', '964', 'NU', 'W210', ''),
      R('45', 'PE (terra di protezione)', 'PE', 'NU', 'W210', 'barra PE cabina'),
      R('46', 'Riserva', '—', 'NU', 'W210', ''),
      R('47', 'Riserva', '—', 'NU', 'W210', ''),
      R('48', 'Riserva', '—', 'NU', 'W210', ''),
    ],
  },
};

// Cavi. [sigla, tipo, da, a, percorso, nota]
const C = (id, tipo, da, a, nota = '') => ({ id, tipo, da, a, nota });
export const CABLES = [
  C('W101', 'FG16OR16 5G6 mm²', 'QGBT edificio', '-X1:1…5', 'alimentazione del quadro (sezione di esempio)'),
  C('W102', 'cavo motore schermato 4G6 mm²', '-X1:11…14', '-M1', 'schermo a terra a entrambi i capi (EMC)'),
  C('W103', 'FG16OR16 4×1,5 mm²', '-X1:15…18', '-YB1/-YB2', 'bobine freno, due circuiti'),
  C('W104', 'schermato 2×0,75 mm²', '-X1:19, 20', '-RT1', 'termistore motore'),
  C('W105', 'schermato 4×2×0,25 mm² (coppie twistate)', '-X3:13…20', '-B2', 'encoder di posizione (contatore veloce); schermo a terra lato quadro'),
  C('W106', 'schermato 4×2×0,25 mm² (coppie twistate)', '-U1 (ingresso encoder)', '-B1', 'encoder del motore per l\'anello chiuso; schermo a terra lato inverter'),
  C('W201', '2×0,75 mm²', '-X2:1, 2', '-SF1 (fossa)', 'catena, tratto A, vano'),
  C('W202', '2×0,75 mm²', '-X2:5, 6', '-SG1', 'catena, limitatore di velocità'),
  C('W203', '2×0,75 mm²', '-X2:9, 10', '-SQ1…-SQ3', 'catena, extracorsa e ammortizzatori'),
  C('W204', 'dorsale serrature 2×0,75 mm² per tratta', '-X2:11, 12', 'XP1…XPn', 'ingresso e ritorno della catena di piano'),
  C('W205', '2×0,5 mm²', '-X3:3, 4', '-SQ4/-SQ5', 'finecorsa di rallentamento'),
  C('W206', '2×0,75 mm²', '-X3:6, -X4:6', '-SK1/-HL1', 'chiave pompieri e spia fuori servizio (piano designato)'),
  C('W207', '2×0,75 mm²', '-X4:4, 5', '-M2/-HA1', 'ventola e avvisatore'),
  C('W208', 'dorsale CAN2: coppia 120 Ω schermata + coppia 24 V', '-X5:6…10', 'XP1…XPn', 'bus dei piani'),
  C('W209', 'FG16OR16 3G1,5 mm² (nel cavo mobile)', '-X6:1…3', 'XC:24…26', 'luce cabina 230 V'),
  C('W210', 'cavo mobile 48 conduttori numerati + schermi', 'quadro', 'XC (cabina)', 'cavo pendente EN 50214 o equivalente'),
  C('W211', 'coppia schermata nel cavo mobile', '-X3:21, 22', 'XC:14, 15', 'pesacarico 4–20 mA'),
  C('W212', 'coppia twistata schermata nel cavo mobile', '-X5:1…5', 'XC:19…23', 'CAN1'),
  C('W213', 'FG16OR16 3G1,5 mm²', '-X6:4…6', 'vano', 'luce vano e prese'),
  C('W214', 'FG16OR16 2×6 mm²', '-X6:10, 11', '-G4', 'batteria (sezione di esempio)'),
  C('W301', 'Ethernet Cat.6 schermato', '-A1', '-A3', 'rete OT'),
  C('W302', 'Ethernet Cat.6 schermato', '-A3', '-A4', 'verso il router'),
  C('W303', 'coassiale per antenna (2 pezzi 5G + 2 Wi-Fi)', '-A4', 'antenne', 'attacchi SMA, antenna esterna al quadro'),
];

// Alimentazioni e protezioni (E03)
export const SUPPLIES = [
  { id: '-QF2', desc: 'magnetotermico 1P+N, luce cabina e vano', rating: '10 A (esempio)', out: 'X6:1…6', note: 'a monte del generale; differenziale ≤ 30 mA (EN 81-20 5.10.1.2.3)' },
  { id: '-QF3', desc: 'magnetotermico 1P+N, alimentatore 48 V (-G1)', rating: '6 A (esempio)', out: '-G1', note: '' },
  { id: '-QF4', desc: 'magnetotermico 1P+N, alimentatore 24 V (-G2)', rating: '6 A (esempio)', out: '-G2', note: '' },
  { id: '-QF5', desc: 'magnetotermico 1P+N, caricabatterie (-G3)', rating: '6 A (esempio)', out: '-G3', note: 'a monte del generale' },
  { id: '-QF6', desc: 'magnetotermico 1P+N, router, gateway, access point', rating: '6 A (esempio)', out: 'UPS', note: '' },
  { id: '-G1', desc: 'alimentatore 48 V c.c. SELV, uscita protetta', rating: '48 V c.c., 2,5 A (esempio)', out: 'catena di sicurezza', note: 'separazione galvanica' },
  { id: '-G2', desc: 'alimentatore 24 V c.c. PELV', rating: '24 V c.c., 10 A (esempio)', out: 'logica, bus, sensori', note: '' },
  { id: '-G3', desc: 'caricabatterie 12 V con contatto di batteria ok', rating: '12 V, 3 A (esempio)', out: '-G4', note: '' },
  { id: '-G4', desc: 'batteria 12 V al piombo/AGM', rating: '12 V, 12 Ah (esempio)', out: 'ARD, luce emerg., allarme', note: 'vedi T11 (dimensionamento)' },
  { id: '-G5', desc: 'alimentatore freno con eccitazione rapida', rating: '110 V c.c. (esempio)', out: '-YB1, -YB2', note: '' },
  { id: '-G6', desc: 'UPS 24 V per router e gateway', rating: '24 V, autonomia ≥ 4 h (esempio)', out: '-A3, -A4, -A9', note: '' },
];

// Dispositivi principali (designazione, descrizione, foglio)
export const DEVICES = [
  ['-QS1', 'Sezionatore generale 3P+N, lucchettabile', 'E01'],
  ['-QF1', 'Magnetotermico 3P 32 A (esempio) per inverter', 'E01'],
  ['-QR1', 'Differenziale tipo B (esempio)', 'E01'],
  ['-Z1', 'Filtro EMC di linea', 'E01'],
  ['-L1', 'Reattanza di linea', 'E01'],
  ['-U1', 'Inverter VVVF anello chiuso, 11 kW / 24 A (esempio)', 'E01'],
  ['-R1', 'Resistenza di frenatura', 'E01'],
  ['-KM1', 'Contattore di potenza 3P, 25 A AC-3, bobina 24 V c.c., contatti a specchio', 'E01'],
  ['-KM2', 'Contattore di potenza 3P (indipendente da KM1), contatti a specchio', 'E01'],
  ['-KB1', 'Contattore/relè comando freno 1, contatti a specchio', 'E06'],
  ['-KB2', 'Contattore/relè comando freno 2, contatti a specchio', 'E06'],
  ['-M1', 'Motore asincrono su argano geared, 7,5 kW (esempio)', 'E01'],
  ['-YB1', 'Bobina freno 1', 'E01'],
  ['-YB2', 'Bobina freno 2', 'E01'],
  ['-B1', 'Encoder del motore verso l\'inverter (A, B, Z + inversi)', 'E01'],
  ['-B2', 'Encoder di posizione verso il contatore veloce del PLC', 'E08'],
  ['-RT1', 'Termistore PTC del motore', 'E01'],
  ['-KA1', 'Relè di controllo fasi', 'E03'],
  ['-KA2', 'Relè a termistori (PTC)', 'E01'],
  ['-K10', 'Relè di sicurezza, contatti a guida forzata (canale 1)', 'E06'],
  ['-K11', 'Relè di sicurezza, contatti a guida forzata (canale 2)', 'E06'],
  ['-A1', 'PLC: CPU standard, 2 porte CAN, Ethernet', 'E07'],
  ['-A2', 'Moduli I/O (32 DI, 18 DO relè, 2 AI, contatore veloce)', 'E07'],
  ['-A3', 'Gateway web (computer industriale)', 'E15'],
  ['-A4', 'Router industriale 5G', 'E15'],
  ['-A5', 'Modulo certificato CE (bypass porte, UCM)', 'E06'],
  ['-A6', 'Comunicatore EN 81-28 con SIM propria', 'E14'],
  ['-A7', 'Scheda di isolamento per la lettura della catena (4 canali)', 'E07'],
  ['-A9', 'Access point Wi-Fi locale', 'E15'],
  ['-SF1', 'STOP fossa (pulsante bistabile, apertura positiva)', 'E04'],
  ['-SF2', 'STOP tetto cabina', 'E04'],
  ['-SF3', 'Commutatore ispezione tetto (contatto NORMALE)', 'E04'],
  ['-SF4', 'STOP quadro / pannello prove', 'E04'],
  ['-SG1', 'Contatto del limitatore di velocità', 'E04'],
  ['-SP1', 'Contatto del paracadute', 'E04'],
  ['-SQ1', 'Extracorsa alto', 'E04'],
  ['-SQ2', 'Extracorsa basso', 'E04'],
  ['-SQ3', 'Contatto ammortizzatori', 'E04'],
  ['-SL1…', 'Contatti serratura di piano (uno per fermata)', 'E04'],
  ['-SD1', 'Contatto porta di cabina', 'E04'],
  ['-SQ4', 'Finecorsa rallentamento alto', 'E07'],
  ['-SQ5', 'Finecorsa rallentamento basso', 'E07'],
  ['-SK1', 'Chiave pompieri (piano designato)', 'E07'],
  ['-BZ1', 'Sensore zona porta 1', 'E10'],
  ['-BZ2', 'Sensore zona porta 2', 'E10'],
];

// Ingressi digitali (28) e uscite (18): assegnazione al campo. [canale, descrizione, origine, morsetto o collegamento interno]
const D = (ch, desc, src, ref) => ({ ch, desc, src, ref });
export const DI = [
  D('I00', 'Controllo fasi / rete presente', '-KA1 (NA)', 'interno'),
  D('I01', 'Catena tratto A (lettura)', '-A7 canale 1', 'interno'),
  D('I02', 'Catena tratto B (lettura)', '-A7 canale 2', 'interno'),
  D('I03', 'Catena tratto C (lettura)', '-A7 canale 3', 'interno'),
  D('I04', 'Catena tratto D (lettura)', '-A7 canale 4', 'interno'),
  D('I05', 'Retroazione KM1', '-KM1 (NC aux)', 'interno'),
  D('I06', 'Retroazione KM2', '-KM2 (NC aux)', 'interno'),
  D('I07', 'Retroazione freno 1', '-KB1 (NC aux)', 'interno'),
  D('I08', 'Retroazione freno 2', '-KB2 (NC aux)', 'interno'),
  D('I09', 'Zona porta, copia sensore 1', '-A5 uscita libera da potenziale', 'interno'),
  D('I10', 'Zona porta, copia sensore 2', '-A5 uscita libera da potenziale', 'interno'),
  D('I11', 'Rallentamento alto', '-SQ4', 'X3:3'),
  D('I12', 'Rallentamento basso', '-SQ5', 'X3:4'),
  D('I13', 'Ispezione attiva', 'aux commutatore ispezione', 'X3:5'),
  D('I14', 'Chiave pompieri', '-SK1 (anello fail-safe)', 'X3:6'),
  D('I15', 'Sovraccarico cabina', 'pesacarico', 'X3:7'),
  D('I16', 'Carico completo', 'pesacarico', 'X3:8'),
  D('I17', 'Inverter pronto', '-U1 relè uscita', 'interno'),
  D('I18', 'Inverter in guasto', '-U1 relè uscita', 'interno'),
  D('I19', 'PTC motore', '-KA2 (NA)', 'interno'),
  D('I20', 'Batteria ok / ARD attivo', '-G3 contatto', 'interno'),
  D('I21', 'Chiave SERVIZIO nel quadro', '-SS1 (sportello)', 'interno'),
  D('I22', 'Pulsante Wi-Fi locale', '-SS2 (sportello)', 'interno'),
  D('I23', 'Porta aperta', 'operatore porte', 'X3:9'),
  D('I24', 'Porta chiusa', 'operatore porte', 'X3:10'),
  D('I25', 'Barriera / costa', 'operatore porte', 'X3:11'),
  D('I26', 'Pulsante di allarme (copia)', '-A6 uscita', 'X3:12'),
  D('I27', 'Ispezione: SALITA (in serie con MARCIA)', 'pulsantiera tetto', 'X3:23'),
  D('I28', 'Ispezione: DISCESA (in serie con MARCIA)', 'pulsantiera tetto', 'X3:24'),
  D('I29', 'Emergenza elettrica: SALITA', 'pannello emergenza e prove', 'interno'),
  D('I30', 'Emergenza elettrica: DISCESA', 'pannello emergenza e prove', 'interno'),
  D('I31', 'Riserva', '—', '—'),
];
export const DO = [
  D('Q00', 'Consenso KM1 (attraverso la catena)', '-KM1 bobina', 'E06'),
  D('Q01', 'Consenso KM2 (attraverso la catena)', '-KM2 bobina', 'E06'),
  D('Q02', 'Consenso freno 1', '-KB1 bobina', 'E06'),
  D('Q03', 'Consenso freno 2', '-KB2 bobina', 'E06'),
  D('Q04', 'Inverter: marcia salita', '-U1 ingresso DI1', 'interno'),
  D('Q05', 'Inverter: marcia discesa', '-U1 ingresso DI2', 'interno'),
  D('Q06', 'Inverter: velocità 1 (alta)', '-U1 ingresso DI3', 'interno'),
  D('Q07', 'Inverter: velocità 2 (livello)', '-U1 ingresso DI4', 'interno'),
  D('Q08', 'Inverter: velocità 3 (ispezione/recupero)', '-U1 ingresso DI5', 'interno'),
  D('Q09', 'Inverter: reset', '-U1 ingresso DI6', 'interno'),
  D('Q10', 'Porte: apri', 'operatore porte', 'X4:1'),
  D('Q11', 'Porte: chiudi', 'operatore porte', 'X4:2'),
  D('Q12', 'Luce cabina (comando)', 'relè luce cabina', 'X4:3'),
  D('Q13', 'Ventola', '-M2', 'X4:4'),
  D('Q14', 'Alimentazione Wi-Fi locale', '-A9 (tramite relè)', 'interno'),
  D('Q15', 'Avvisatore fuori servizio', '-HA1', 'X4:5'),
  D('Q16', 'Spia fuori servizio al piano', '-HL1', 'X4:6'),
  D('Q17', 'Riserva', '—', '—'),
];

// Distinta materiali (generica, senza marche). [pos, qtà, descrizione, designazione, nota]
const B = (pos, qty, desc, ref, note = '') => ({ pos, qty, desc, ref, note });
export const BOM = [
  B(1, 1, 'Armadio 800×1000×300 mm, IP54, con piastra di fondo e sportello a chiave', '-', 'T15'),
  B(2, 1, 'Sezionatore generale 3P+N lucchettabile, 40 A', '-QS1', 'esempio'),
  B(3, 1, 'Magnetotermico 3P 32 A curva C', '-QF1', 'esempio'),
  B(4, 1, 'Differenziale tipo B', '-QR1', 'esempio'),
  B(5, 5, 'Magnetotermico 1P+N 6–10 A', '-QF2…-QF6', 'esempio'),
  B(6, 1, 'Filtro EMC + reattanza di linea', '-Z1, -L1'),
  B(7, 1, 'Inverter VVVF anello chiuso 11 kW/24 A con encoder', '-U1', 'da preventivo'),
  B(8, 1, 'Resistenza di frenatura con protezione termica', '-R1'),
  B(9, 2, 'Contattori di potenza 3P 25 A AC-3, bobina 24 V c.c., contatti a specchio', '-KM1, -KM2'),
  B(10, 2, 'Contattori/relè freno, contatti a specchio', '-KB1, -KB2'),
  B(11, 1, 'Alimentatore freno 110 V c.c. con eccitazione rapida', '-G5'),
  B(12, 1, 'Alimentatore 48 V c.c. SELV, 2,5 A', '-G1'),
  B(13, 1, 'Alimentatore 24 V c.c. PELV, 10 A', '-G2'),
  B(14, 1, 'Caricabatterie 12 V con contatto di batteria ok', '-G3'),
  B(15, 1, 'Batteria 12 V 12 Ah', '-G4'),
  B(16, 1, 'UPS 24 V per router e gateway', '-G6'),
  B(17, 2, 'Relè di sicurezza a guida forzata (due canali)', '-K10, -K11'),
  B(18, 1, 'Modulo certificato CE: bypass porte e UCM', '-A5', 'da preventivo'),
  B(19, 1, 'Scheda di isolamento lettura catena, 4 canali', '-A7'),
  B(20, 1, 'PLC: CPU con 2 porte CAN e Ethernet + moduli I/O (32 DI, 18 DO, 2 AI, contatore veloce)', '-A1, -A2'),
  B(21, 1, 'Gateway web (computer industriale)', '-A3'),
  B(22, 1, 'Router industriale 5G con antenne', '-A4'),
  B(23, 1, 'Access point Wi-Fi', '-A9'),
  B(24, 1, 'Comunicatore EN 81-28 con SIM propria', '-A6', 'da preventivo'),
  B(25, 12, 'Nodo di piano CAN con 2 tasti, LED e gong (+12 per 24 fermate)', 'XP1…XP12'),
  B(26, 1, 'Cavo mobile 48 conduttori numerati + schermi', 'W210'),
  B(27, 1, 'Morsettiere a vite con ponticelli di prova (X1…X6)', '-X1…-X6'),
  B(28, 1, 'Canalette, capicorda, targhette, collari, pressacavi', '-'),
  B(29, 1, 'Fusibili e portafusibili (48 V, 24 V, freno)', '-F1…'),
];

// Elenco dei fogli (titolo breve = titolo nel cartiglio)
export const SHEETS = [
  ['E00', 'Copertina, indice, legenda e convenzioni'],
  ['E01', 'Potenza — trazione (rete, inverter, contattori, motore, freno, encoder)'],
  ['E02', 'Potenza — idraulico (centralina, soft starter, valvole)'],
  ['E03', 'Ausiliari e alimentazioni (230 V, 48 V, 24 V, batteria)'],
  ['E04', 'Catena di sicurezza — trazione (collegamenti e morsetti)'],
  ['E05', 'Catena di sicurezza — idraulico (collegamenti e morsetti)'],
  ['E06', 'Interfaccia di sicurezza: consensi, contattori, freni e retroazioni'],
  ['E07', 'PLC — alimentazione e ingressi digitali (I00…I31)'],
  ['E08', 'PLC — uscite (Q00…Q17), ingressi analogici, encoder e CAN'],
  ['E09', 'Bus CAN, 24 V di bus, connettori e terminazioni'],
  ['E10', 'Nodo di piano (schema tipo) e dorsale del vano'],
  ['E11', 'Cabina e cavo mobile (morsettiera XC)'],
  ['E12', 'Porte (operatore, contatti, barriera)'],
  ['E13', 'Ispezione, pannello di emergenza e prove, bypass'],
  ['E14', 'Allarme EN 81-28, luce di emergenza e ARD'],
  ['E15', 'Rete: router 5G, gateway, access point, antenne'],
  ['E16', 'Elenco morsettiere X1…X6, XC'],
  ['E17', 'Lista cavi'],
  ['E18', 'Distinta materiali e dispositivi'],
];
